### ISSUE TITLE
v1.3.5邮件提醒问题

### ISSUE THREAD

**Issue by wasonchung** [cookieY/Yearning#100]
v1.3.5邮件提醒问题：
1. 收件人显示是空的；
2.地址是localhost，这里应该是工单的URL吧。

**Comment by wasonchung** [comment]
![image](https://user-images.githubusercontent.com/37434329/50478019-f8671780-0a09-11e9-963c-2c3269c08d11.png)

**Comment by cookieY** [comment]
@wasonchung 地址是你自己配置的 在docker-compose里面有个host字段

**Comment by wasonchung** [comment]
我想确认一下，这里面的地址，只是告知收件人要去yearning做审核吧。不是说，收件人可以直接点击地址后跳转至相应的工单审核界面？
![image](https://user-images.githubusercontent.com/37434329/50534605-e7d5af00-0b79-11e9-9c91-2c35ac4cb0b2.png)

**Comment by cookieY** [comment]
只是告诉你地址，并不能直接跳转到审核界面
