### ISSUE TITLE
[Question] 是否支持全部DDL走OSC

### ISSUE THREAD

**Issue by lhh-yeah** [cookieY/Yearning#1007]
**描述问题**
  是否支持全部DDL使用OSC？ 
  我做了一下尝试：将OscSize设置为0，但所有DDL都不使用OSC了。
  
**环境 (请填写环境信息):**
- 版本号 3.1.4

**Comment by cookieY** [comment]
目前只按照表体积作为判断标准 超过阈值后会走 osc 如果设置 为 0 则全部都不经过 osc
