### ISSUE TITLE
[Feature] 关于 cmd + e 执行 SQL 语句的快捷键合理性问题

### ISSUE THREAD

**Issue by hmlu** [cookieY/Yearning#1032]
**描述需求**
默认的执行 SQL 语句的快捷键是 CMD + E（Windows 下为 CTRL + E），但是这个 E 是在 W 跟 R 中间，CMD + W 为关闭浏览器标签页，CMD + R 为刷新页面，无论按到哪个都不是好事。

**你的思路**
更换执行 SQL 语句默认的 CMD + E 的快捷键

**截图**
如果可以，可以提供截图

**Comment by cookieY** [comment]
已新增实体按钮
