### ISSUE TITLE
[Question] 如果在工单界面，重复点击流转到下一步，会造成core_workflow_details表里面存入多条重复数据

### ISSUE THREAD

**Issue by zhumeichun** [cookieY/Yearning#1037]
如果在工单界面，重复点击流转到下一步，会造成core_workflow_details表里面存入多条重复数据：
| 279 | 20240408154148854 | ***| 2024-04-08 15:43 | 审核通过,并已转交至 ***|
| 280 | 20240408154148854 | ***| 2024-04-08 15:43 | 审核通过,并已转交至 ***|
| 281 | 20240408154148854 | ***| 2024-04-08 15:43 | 审核通过,并已转交至 ***|
当下一个环节点开该工单时，会报错：
Apr 08 16:01:00 Yearning[11905]:  [Error] 2024-04-08 16:01:00 (github.com/cookieY/yee@v0.5.1/context.go:153) /api/v2/fetch/timeline?source_id=127a4aed-bb25-4c0b-a43e-1dc8c0b75b64&work_id=20240408154148854 Internal Server Error
Apr 08 16:01:00 Yearning[11905]:  [Warn] 2024-04-08 16:01:00 "url":"/api/v2/fetch/timeline" "method":"GET" "status":500 "protocol":"HTTP/1.1" "remote_ip":"117.174.23.25" "bytes_in": "0 bytes" "bytes_out": "21 bytes"
手动删除后面两个步骤后能正常打开界面。
mysql> delete from core_workflow_details where Id=280;
Query OK, 1 row affected (0.01 sec)
mysql> delete from core_workflow_details where Id=281;
Query OK, 1 row affected (0.00 sec)

**Comment by laihaibing** [comment]
遇到了相同的问题

**Comment by cookieY** [comment]
resolved [https://github.com/cookieY/Yearning/releases/tag/v3.1.8](https://github.com/cookieY/Yearning/releases/tag/v3.1.8)
