### ISSUE TITLE
[Question] 带日期的更新 sql，检测sql 语法的时候报错

### ISSUE THREAD

**Issue by zz940522** [cookieY/Yearning#1039]
**Describe the question**
update table_name SET endTime='2024-04-09 17:30:00'
%!(EXTRA string=ms, string=endTime) appears

**Comment by cookieY** [comment]
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/6f6e3238-1903-487f-bf29-e501db0736d2">
似乎在 3.1.8 版本中没有复现
