### ISSUE TITLE
Yearning 1.4.0 更新内容

### ISSUE THREAD

**Issue by cookieY** [cookieY/Yearning#104]
Yearning开源一周年 star 1700+ 感谢大家一直以来的关注~

作为yearning  2019年将要推送的第一次发布

我很高兴给大家带来yearning 1.4.0 版本的更新内容

1.修改审核/我的工单 数据获取逻辑,大幅提高数据获取速度。
2.修复用户提交工单时更换连接后无法获取新连接名下数据库信息的问题。
3.修复工单执行失败的情况下无法获得执行成功的部分SQL语句回滚的问题。
4.修复多级审核模式下 无法获取OSC进度展示的问题
5.全面优化安全逻辑
6.精简功能, 去除ddl 及索引自动语句生成功能,去除数据库字典功能,重新设计DDL提交功能
7.新增表格搜索功能,
8.查询支持字段级别补全
9.新增页面缓存(从现在开始DDL,DML页面数据不再丢失)
10.在编辑或删除非第一页数据时实时刷新不再直接返回第一页而是停留在当前页提升管理员批量编辑效率
11.优化ldap逻辑,提升使用体验。参考git,svn,grafana配置,ldap用户只能使用ldap登陆。
12.修复了登陆异常报错不正确的问题
13.修复1.3.5查询limit失效的问题
14. 审核页面增加实时数据获取开关
15.依赖模块升级(ui库及django版本升级到最新)
16. 前端代码重构第二期
17.修复数据库大小写敏感时无法获取查询数据的问题
18.增加了对数据库连接密码加密的支持
19.重新设计首页
20.我的工单及审核工单页面在开启多级审核后会显示执行人信息
21.修复了当管理员用户角色变为使用者时 权限组没有及时删除对应用户信息的问题
22.修复查询导出数据精度丢失的问题
23.优化了钉钉推送消息模板消息个格式
24.统一了分页显示数据，修复查询审核分页问题
该版本将会适时发布，感谢大家~

**Comment by BetterKen** [comment]
我刚改完
>12.修复了登陆异常报错不正确的问题
这个bug。。。。。

**Comment by BetterKen** [comment]
请问什么时候更新啊？
