### ISSUE TITLE
[Question] 开启审核规则启用OSC,OSC进度sh: pt-online-schema-change: not found

### ISSUE THREAD

**Issue by so-easy** [cookieY/Yearning#1044]
**描述问题**
  开启审核规则启用OSC，执行sql成功 OSC进度sh: pt-online-schema-change: not found
  
**复现**
重现该行为的步骤:
  1. 开启osc
  2. sql：alter table pt_online_test add column xxxx varchar(255) NOT NULL DEFAULT '' COMMENT 'xxxx';
  3. 执行成功，OSC进度sh: pt-online-schema-change: not found
  
**期望的结果**
  开启审核规则启用OSC，执行sql成功 OSC进度正常
  
**截图**
  
<img width="974" alt="image" src="https://github.com/cookieY/Yearning/assets/7981458/415c1686-56c5-4aac-9208-96f4de7590a4">

  
**部署方式**
- [ ] Docker
- [ ] Manual
- [ ] 源码部署和docker
services:
juno:
image: yeelabs/juno:latest
container_name: yearning-juno
hostname: yearning-juno
  
**环境 (请填写环境信息):**
- 操作系统: [linux]
- 浏览器 [e.g. chrome, safari]
- 版本号 [3.1.7]
  
**额外的日志信息**
Yearning © 2018-2024 Created by HenryYee ver.3.1.7

**Comment by cookieY** [comment]
pt-osc需要自行安装在宿主机上
