### ISSUE TITLE
[Question] sql执行完成，工单状态还是执行中

### ISSUE THREAD

**Issue by Sakuragi27** [cookieY/Yearning#1077]
Please provide titles that are straightforward and concise. exp: [Question] How to use or [Feature] Add new feature

      请提供简单明了的标题。例如 [Question] 如何使用 or [Feature] 添加新功能

**Comment by JackloveJam** [comment]
我最近也遇到这个问题了。使用的最新版本。
我唯一可能做的有影响的地方 就是给yearning的数据库各表、字段增加了中文注释。
但是感觉这不应该是影响这个地方啊。百思不得其解。😅
