### ISSUE TITLE
[Question] v3.1.8 版本检测报错，v2.3.5 版本检测通过

### ISSUE THREAD

**Issue by ChengJiuSu** [cookieY/Yearning#1081]
**描述问题**
在v3.1.8 版本执行：（举例语句）
insert into test(`voided_time_millis`, `is_err`, `voided_reason`) VALUES ( NULL, 0, NULL);

提示报错如下：
Error info：%!(EXTRA string=voided_time _millis) %! (EXTRA string=voided_reas on)

但是在v2.3.5 版本执行则可以检测通过并执行成功
 
  
**期望的结果**
 v3.1.8 版本也能正常检测和执行
   
**截图**
  
<img width="860" alt="企业微信截图_74b4057d-9838-490a-9bfb-7bba279ed8db" src="https://github.com/user-attachments/assets/09d08c95-2ed3-48bb-8b0c-29a7d3c5e80d">
<img width="989" alt="企业微信截图_9c67ae91-ed12-4f51-b43a-75ad14b7824b" src="https://github.com/user-attachments/assets/d9dba850-3d02-43ff-8c85-85fe6fffaa26">

  
**部署方式**
- [ ] Docker
- [x] Manual
  
**环境 (请填写环境信息):**
- 操作系统: ubuntu 18/04
- 浏览器：chrome
- 版本号：v3.1.8
- 数据库：MySQL5.7

**Comment by cookieY** [comment]
是否可以提供一下建表语句呢 @ChengJiuSu
