### ISSUE TITLE
[Question] pattern chat/*: no matching files found

### ISSUE THREAD

**Issue by bpzhang** [cookieY/Yearning#1084]
在编译过程中提示pattern chat/*: no matching files found，
这个chat是哪里编译来的？

**Comment by zhongmax** [comment]
貌似是个前端的文件，可以把这个注释了，就能跑起来了

**Comment by bpzhang** [comment]
是的 但是这些文件是哪里来的

**Comment by cookieY** [comment]
https://github.com/cookieY/Ychat
