### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by duguaoxue** [cookieY/Yearning#1089]
**描述问题**
mysql版本：mysql8.0.28
表结构
id字段类型：bigint unsigned
sql语句
select * from mggt_cashier_statistics where statistics_no='537984'
Yearning执行结果
id返回值：1829782991634612200
真实值：1829782991634612225
  
**复现**
重现该行为的步骤:
  
**期望的结果**
 yearning执行结果
![图片](https://github.com/user-attachments/assets/dcdb9101-5f6c-4370-93eb-01f3891aa4f4)

  期待结果
![图片](https://github.com/user-attachments/assets/6e4f260e-45c1-4850-b008-1aa85bafd4e9)

  
**部署方式**
 Manual
  
**环境 (请填写环境信息):**
- 操作系统: Ubuntu：22.04
- 浏览器  chrome
- 版本号 3.1.8
  
**额外的日志信息**
在这里添加有关该问题的所有日志。

**Comment by cookieY** [comment]
精度问题已在 3.1.9 版本中修复

**Comment by ddl1228** [comment]
3.1.9还没完全修复，我们有两个数据库，其中一个库查询时精度没问题，另一个库查询时精度还是有问题
![image](https://github.com/user-attachments/assets/d5046999-9287-4865-a04a-bae10406d51d)
![image](https://github.com/user-attachments/assets/c7a8161a-19b4-4e3a-a0d2-d3f064fb3591)
