### ISSUE TITLE
查看回滚语句提示 （此工单没有备份或语句执行失败）

### ISSUE THREAD

**Issue by DavenAaron** [cookieY/Yearning#11]
1、工单提交的时候已经点选备份。
2、数据库连接正常
[mysql]
db = yearning
address = 127.0.0.1
port = 3306
username = yearning
password = 12312300

[host]
ipaddress = 10.170.195.166:8080

[Inception]
ip = 127.0.0.1
port = 6669
user = root
password  =
backupdb = 127.0.0.1
backupport = 3306
backupuser = admin
backuppassword = 12312300
......

**Comment by cookieY** [comment]
@DavenAaron 
1.inception是根据binlog生成回滚语句 请检查目标数据库是否开启binlog。

2. 该语句执行失败所以没有回滚语句 请查看执行记录找到对应工单的详细信息

如有其他疑问可进群探讨
