### ISSUE TITLE
[Question] 在审核也没重复点击审核会造成审核页面500

### ISSUE THREAD

**Issue by big-dollar** [cookieY/Yearning#1100]
**描述问题**
  清晰而简洁地描述你遇到的问题
  
**复现**
重现该行为的步骤:
版本：3.1.8
  1. 在审核也没重复点击检测并审核
  2. 退出也没再重新进入会报500
  3. 日志报：index out of range [3] with length 3
  4. 上个版本就有的问题，之前提过issue
  
**期望的结果**
  清晰而简洁地描述你希望得到的结果
  
**截图**
  
![image](https://github.com/user-attachments/assets/b76113bd-3f04-4fdd-aa59-735673e6d551)

  
**部署方式**
- [ ] Manual

**Comment by cookieY** [comment]
是普遍现象还是就这一个单子？   直接二进制部署还是源代码自编译部署？

**Comment by big-dollar** [comment]
二进制直接部署，只要单子需要同一个人同时审核两次，会复现。

**Comment by cookieY** [comment]
同时审核两次的意思是  连续 2 个阶段都是同一个审核人 还是快速点击审核了两次？  是否可以告知下具体的复现步骤

**Comment by big-dollar** [comment]
我这边设置的是两级审核，如果两级审核中都包含同一个审核人。
当这个审核人在同一个审核页面重复点击两次【同意】按钮时会复现这个问题，不需要快速点击，只要当前页面不关闭就会复现
![image](https://github.com/user-attachments/assets/79f92447-ee46-4052-8242-359756a56e41)

**Comment by cookieY** [comment]
最新版本已修复
