### ISSUE TITLE
[Question] MFA的开关找不到，官方文档也没说明

### ISSUE THREAD

**Issue by RHCE-2018** [cookieY/Yearning#1101]
**描述问题**
  安装最新版的v3.1.8后没有找到MFA的开关
  
**复现**
重现该行为的步骤:
  
**期望的结果**
  清晰而简洁地描述你希望得到的结果
  
**截图**
  
  
**部署方式**
- [ ] Docker

  
**环境 (请填写环境信息):**
- 操作系统: [CentOS7.9]
- 浏览器 [chrome]
- 版本号 [49]
  
**额外的日志信息**
在这里添加有关该问题的所有日志。

**Comment by cookieY** [comment]
mfa 为赞助版本功能，社区版本暂未支持
