### ISSUE TITLE
[Question] 二次开发改了代码后build的二进制需要使用rpc吗

### ISSUE THREAD

**Issue by showsmall** [cookieY/Yearning#1102]
**描述问题**
  二次开发改了代码后build的二进制需要使用rpc吗？我使用3.1.8的源代码改了一些东西，编译后执行查询sql，提示rpc调用失败，发现需要配置rpc，但是我用作者编译的包就不需要，2024/09/19 11:10:04 dial tcp: missing address ，求解答，然后还有就是
//go:embed chat/server/app/index.html
var chatindex string   这个资源在哪里呢？chat的静态资源，没有找到
  
**复现**
重现该行为的步骤:
  
**期望的结果**
  清晰而简洁地描述你希望得到的结果
  
**截图**
 
![image](https://github.com/user-attachments/assets/62c1dc7f-3eda-409c-a1db-7d9215f6a585)
 
  
**部署方式**
- [ ] Docker
- [x] Manual
  
**环境 (请填写环境信息):**
- 操作系统: [e.g. iOS]
- 浏览器 [e.g. chrome, safari]
- 版本号 [e.g. 22]
  
**额外的日志信息**
在这里添加有关该问题的所有日志。

**Comment by showsmall** [comment]
![image](https://github.com/user-attachments/assets/c84ce6da-bf7e-428e-9d05-b481ecc01dbd)
实在是不知道怎么弄的了，v3.1.8的二进制版本官方打包需要rpc，我自己编译打包的就需用rpc，不知道哪里没弄好

**Comment by showsmall** [comment]
@cookieY help

**Comment by showsmall** [comment]
v3.1.8的二进制版本官方打包不需要rpc，我自己编译打包的就需要rpc，不知道哪里没弄好

**Comment by cookieY** [comment]
https://next.yearning.io/dev/callback.html 自行开发需要启动 juno
