### ISSUE TITLE
[Question] 查询结果被四舍五入

### ISSUE THREAD

**Issue by iuwai** [cookieY/Yearning#1104]
**描述问题**
  清查询结果被四舍五入
  
**复现**
重现该行为的步骤:
  1. 执行查询操作
  2. sql示例：select * from table1 where record_id = 111111111149234033

**截图**
  
![image](https://github.com/user-attachments/assets/845b2c33-aa4b-4dec-b4ee-fc31ef27cdbb)

  
**部署方式**
Manual
  
**环境 (请填写环境信息):**
- 操作系统: all
- 浏览器 [chrome]

**Comment by ddl1228** [comment]
我也遇到这个问题，请问怎么解决？

**Comment by ddl1228** [comment]
I also encountered this problem, how to solve it?

**Comment by unslur** [comment]
如果只查询ID 很恼火的写法
SELECT concat(id,"") from qw_call_urge_payment_call_record WHERE urge_id IN(317,142,69,312,323,465)

**Comment by Piean** [comment]
V3.1.4 我也遇到这个问题，应该是和前端JS不支持bigint导致精度丢失，希望尽快修复

**Comment by cookieY** [comment]
<img width="1701" alt="image" src="https://github.com/user-attachments/assets/bdf9bd5c-70f0-4dd4-aa03-d64ea616aad8">
将会在接下来的 3.1.9 版本彻底解决

**Comment by cookieY** [comment]
3.1.9 版本已修复

**Comment by ddl1228** [comment]
3.1.9还没完全修复，我们有两个数据库，其中一个库查询时精度没问题，另一个库查询时精度还是有问题
![image](https://github.com/user-attachments/assets/28e8590e-3503-43ab-9226-c75677c6bfbb)
![image](https://github.com/user-attachments/assets/0688019f-eb15-47eb-8aab-cd875a63fabe)

**Comment by cookieY** [comment]
请给一份复现的数据 包括脱敏后的建表语句以及 插入值

**Comment by ddl1228** [comment]
CREATE TABLE `ecs_stockup_req_detail_test` (
  `scm_order_rec_id` bigint(20) unsigned NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `ecs_stockup_req_detail_test`(`scm_order_rec_id`) VALUES (1853760420422066178);

**Comment by ddl1228** [comment]
It's been fixed, thanks
