### ISSUE TITLE
飞书 webhook未收到消息通知

### ISSUE THREAD

**Issue by xiejie2438** [cookieY/Yearning#1105]
Please provide titles that are straightforward and concise. exp: [Question] How to use or [Feature] Add new feature

      请提供简单明了的标题。例如 [Question] 如何使用 or [Feature] 添加新功能

**Comment by sunnerdu** [comment]
v3.1.8 have same problem, Is Feishu's webhook push not supported now?

**Comment by rayne-arklab** [comment]
3.1.4 same issue ？ thanks for anybody help
