### ISSUE TITLE
[Question] 使用OIDC服务提供商无法登录到Yearning

### ISSUE THREAD

**Issue by potatoone** [cookieY/Yearning#1107]
**描述问题**
我使用了两个开源SSO授权服务，Authentik和Casdoor，两者均有实现标准OIDC登录协议，但是配置之后都无法跳转到个人用户界面
，仍然停留在登录页
  

**toml配置文件如下**
![image](https://github.com/user-attachments/assets/f433702f-87f3-497c-bb98-5fd77c9609d5)

**应用程序oidc返回状态，1200应该是正常吧**
![image](https://github.com/user-attachments/assets/89e6c7a8-3aa1-4796-a4e1-35e01677d9c4)

**一直停留在此处**
![image](https://github.com/user-attachments/assets/fb91c12c-9150-4fc9-af23-4e56ac6bc136)

  
**部署方式**
- [x] Docker Compose
  
**环境 (请填写环境信息):**
- 操作系统：Debian 12
- 浏览器：Edge
- 版本号：129.0.2792.52
  
**应用程序日志信息**
 `[Info] 2024-09-29 11:36:45 "url":"/lang" "method":"GET" "status":200 "protocol":"HTTP/1.1" "remote_ip":"x.x.x.x" "bytes_in": "0 bytes" "bytes_out": "42 bytes"`
 `[Info] 2024-09-29 11:36:45 "url":"/oidc/state" "method":"GET" "status":200 "protocol":"HTTP/1.1" "remote_ip":"x.x.x.x" "bytes_in": "0 bytes" "bytes_out": "252 bytes"`
 `[Info] 2024-09-29 11:36:45 "url":"/fetch" "method":"GET" "status":200 "protocol":"HTTP/1.1" "remote_ip":"x.x.x.x" "bytes_in": "0 bytes" "bytes_out": "48 bytes"`

**Comment by dellnoantechnp** [comment]
![image](https://github.com/user-attachments/assets/07c9cc56-58c4-4ad7-80ba-9ed45581e8f6)
keycloak 测试没问题，能跑通。

**Comment by potatoone** [comment]
@dellnoantechnp 
搞好了。Casdoor也可以用了，重定向url必须是这个/oidc/_token-login
