### ISSUE TITLE
提交工单查看osc进度的时候一直是0匹配无数据

### ISSUE THREAD

**Issue by qiaoyi968** [cookieY/Yearning#111]
![image](https://user-images.githubusercontent.com/48576399/54594670-1c1b8600-4a6c-11e9-9e60-f8d0c2e1953c.png)

**Comment by cookieY** [comment]
@qiaoyi968 inception无法获取到SHA1导致

**Comment by qiaoyi968** [comment]
> @ qiaoyi968 inception无法获取到SHA1导致

已经搞定了是版本的问题，我下了最新版的yearning的docker镜像启动起来已经可以了，现在遇到查看回滚数据报错，
![V%3OO8{HBP{_FQJWQO_{{H](https://user-images.githubusercontent.com/48576399/54652525-1d8f9180-4af2-11e9-9c0a-d68851b1a3e6.png)

**Comment by cookieY** [comment]
@qiaoyi968 看下yearning官方文档上注意事项一栏吧

**Comment by qiaoyi968** [comment]
> @ qiaoyi968看下向往官方文档上注意事项一栏吧
好的谢谢
