### ISSUE TITLE
[Question] CoreSqlOrder写入报错

### ISSUE THREAD

**Issue by showsmall** [cookieY/Yearning#1114]
**描述问题**
  审批工单写入报错，提示：
![image](https://github.com/user-attachments/assets/0a5a2867-0194-4818-ae90-128f5207ade3)

  
**复现**
重现该行为的步骤:
通过排查代码：
发现是启动的时候把字段删除了，代码如下：
	if model.DB().Migrator().HasColumn(&model.CoreSqlOrder{}, "time") {
		_ = model.DB().Migrator().DropColumn(&model.CoreSqlOrder{}, "time")
	}
不知道为何这样做
  
**期望的结果**
  清晰而简洁地描述你希望得到的结果
  
**截图**
  
  
**部署方式**
- [ ] Docker
- [x] Manual
  
**环境 (请填写环境信息):**
- 操作系统: [e.g. iOS]
- 浏览器 [e.g. chrome, safari]
- 版本号 [e.g. 22]
  
**额外的日志信息**
在这里添加有关该问题的所有日志。

**Comment by cookieY** [comment]
降级了？

**Comment by showsmall** [comment]
没有降级呀，一直是3.1.8

**Comment by cookieY** [comment]
结构体同步后该问题解决
