### ISSUE TITLE
[Question] 连接开启SSL协议的mysql库会主动终止进程

### ISSUE THREAD

**Issue by liubowyf** [cookieY/Yearning#1120]
**描述问题**
  连接测试可以通过，也可以查询，但是执行dml工单会报错并退出进程：time="2024-10-31T10:16:57+08:00" level=error msg="Error 3159 (HY000): Connections using insecure transport are prohibited while --require_secure_transport=ON." file="gitee.com/cookieYe/enginex@v0.0.3/parse/parse.go:232"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x138ec3a]

goroutine 1314 [running]:
Yearning-go/src/handler/order/audit.(*Review).Exec.func1()
        Yearning-go/src/handler/order/audit/executor.go:168 +0x1a
Yearning-go/src/handler/order/audit.(*Review).Exec(0xc00093cd20)
        Yearning-go/src/handler/order/audit/executor.go:172 +0x14d
Yearning-go/src/handler/order/audit.(*Review).Executor.func1()
        Yearning-go/src/handler/order/audit/executor.go:158 +0x1e5
created by Yearning-go/src/handler/order/audit.(*Review).Executor in goroutine 1143
        Yearning-go/src/handler/order/audit/executor.go:83 +0x56
  
**复现**
重现该行为的步骤:
  
**期望的结果**
  清晰而简洁地描述你希望得到的结果
  
**截图**
  
  
**部署方式**
- [ ] Manual
  
**环境 (请填写环境信息):**
- 操作系统: [ubuntu22.04]
- 浏览器 [chrome]
- 版本号 [e.g. 22]
  
**额外的日志信息**
在这里添加有关该问题的所有日志。

**Comment by liubowyf** [comment]
当前版本3.1.8

**Comment by cookieY** [comment]
3.1.9 版本已修复
