### ISSUE TITLE
[Question] 对开启SSL认证的mysql数据库执行查询时，无结果响应

### ISSUE THREAD

**Issue by liubowyf** [cookieY/Yearning#1124]
**Describe the question**
对开启SSL认证的mysql数据库执行查询时，无结果响应，执行ddl语句及dml语句可以正常执行，当前使用版本v3.1.9

**Deployment**
![image](https://github.com/user-attachments/assets/f5bd2563-ce50-48f4-b3bd-9ef3fcba71da)
<img width="1131" alt="image" src="https://github.com/user-attachments/assets/fd9de388-771c-417e-8fd1-e8eae4766a73">

- [ ] Manual

**Env (please complete the following information):**
- OS: [ubuntu 22.04]
- Browser [chrome]

**Additional Logs**
Add any logs about the problem here.

**Comment by cookieY** [comment]
最新版本已修复
