### ISSUE TITLE
[Question] 查询审核失效

### ISSUE THREAD

**Issue by linjicong** [cookieY/Yearning#1126]
**描述问题**
 开启查询审核功能后，只申请一个数据库的权限，通过更改url的方式可实现任意有权限的数据库查询
  
**复现**
重现该行为的步骤:
  1. 工单申请，查询，提交查询
![image](https://github.com/user-attachments/assets/5a402a32-bb9d-4c67-a55d-1a0845ba5a17)
  2. 工单申请，DML，进入任意一个数据库的工单填写界面，将url中的/#/apply/order?替换为/#/apply/query?，source参数切换即可实现不同数据库的查询

  
**期望的结果**
只能查询已申请的数据库
  
**截图**
  
  
**部署方式**
- [x] Docker
- [ ] Manual
  
**环境 (请填写环境信息):**
- 操作系统: [alpine]
- 浏览器 [ chrome,]
- 版本号 [3.1.7]
  
**额外的日志信息**
在这里添加有关该问题的所有日志。

**Comment by cookieY** [comment]
这个复现的条件应该是
1. 开启查询审核
2. 切换的 sourceId 属于用户查询范围?

**Comment by linjicong** [comment]
> 这个复现的条件应该是
> 
> 1. 开启查询审核
> 2. 切换的 sourceId 属于用户查询范围?

是的，切换的sourceId属于用户查询范围，但是不是申请的那个sourceId

**Comment by cookieY** [comment]
最新版本已修复
