### ISSUE TITLE
支持阿里云的MySQL RDS数据库吗

### ISSUE THREAD

**Issue by arjiangHe** [cookieY/Yearning#117]
阿里云的RDS 数据库链接比较长，这个支持吗？还有inception不开源了，这个影响比较大吧

**Comment by iKunpw** [comment]
支持RDS，和链接长有什么关系？？？（迷)x

**Comment by arjiangHe** [comment]
inception 会报 The backup dbname 'rm-xxx.mysql.rds.aliyuncs.com-3306-xxx' is too long. 这个错误啊，我看这个也是基于inception弄的，所以问一下

**Comment by cookieY** [comment]
@arjiangHe 支持RDS 你可以ping 域名拿到ip的方式 使用
