### ISSUE TITLE
子查询出现提示库错误的情况

### ISSUE THREAD

**Issue by yxnstart** [cookieY/Yearning#129]
SQL如下 
UPDATE tb_old_man_extend
SET linkman_phone = NULL
WHERE linkman_phone IN
    (SELECT linkman_phone
     FROM
       (SELECT linkman_phone
        FROM tb_old_man_extend
        GROUP BY linkman_phone
        HAVING count(1) > 1) TEMP);

这个SQL查询了该表又进行了修改 mysql不允许这种行为 所以添加了个temp的嵌套查询 但是这个查询加上后 就提示 Incorrect database name '' 数据库名错误 希望能给个解答

**Comment by cookieY** [comment]
不支持这种写法
