### ISSUE TITLE
No slaves found.

### ISSUE THREAD

**Issue by wasonchung** [cookieY/Yearning#130]
yearning version : yearning:v1.3.5

近期执行加索引脚本时报以下错误。但是直接在目标数据库或者是navicat工具上是可以执行的。

No slaves found. See --recursion-method if host SIT44 has slaves. Not checking slave lag because no slaves were found and --check-slave-lag was not specified. Cannot chunk the original table `shopnctest`.`coupon_record_2019_before`: There is no good index and the table is oversized. at /usr/bin/pt-online-schema-change line 5876.

**Comment by cookieY** [comment]
此为pt报错,建议查看Pt报错信息 或直接在inception内关闭osc

**Comment by wasonchung** [comment]
原来是要alter的那个表没有主键，所以pt报错了。
