### ISSUE TITLE
Yearning2.0 开发计划

### ISSUE THREAD

**Issue by cookieY** [cookieY/Yearning#134]
# 主要变动
1.全新的扁平化设计，全新的配色方案，更美观，更有少女心
2.后端使用go语言重构,速度更快
3.使用自主开发的审核引擎，与yearning深度融合。审核速度更快
4.语法级别的SQL控制
5.查询新增多查询窗口,让多库查询不再如此麻烦
6.重新设计的鉴权逻辑，大幅提高安全性
7.修复回滚工单的错误延迟性bug
8.增加撤销操作加幂性
9.新增移动端支持！审核人可以在手机上操作啦！
10.更友好的安装体验(二进制./执行)
11.细粒度权限更改为基于用户，不再基于权限组。
12.新增注册开关，关闭后登陆页面不在提供注册功能
13.注册用户不再强制要求mail后缀
14.新增查询导出数据开关，关闭后不再可以导出数据
15.查询新增快速提交按钮，实现同时查询并提交DML功能
16.动态审核设置
17.页面渲染速度增加50%
18.自带gzip压缩/xss攻击防范/http2 等功能，无需nginx前置代理
# 部分界面变更展示

![image](https://user-images.githubusercontent.com/22343354/60162195-9ad24d00-982b-11e9-90c8-dc5128b1fe1a.png)

![image](https://user-images.githubusercontent.com/22343354/60263859-52db2500-9914-11e9-82f6-84965b27f8a9.png)

**Comment by zi000** [comment]
可否考虑集成小米的soar进去？

**Comment by cookieY** [comment]
@zi000 后期会考虑

**Comment by sweetpotatoman** [comment]
什么时候会发布啊～

**Comment by etforshell** [comment]
查询多个库的表，每次都需要关闭当前的数据库查询，然后申请其他库的权限，查完了关掉其他库的权限，然后又重新申请当前库的权限，能否在多库查询的时候另外新开启一个页面

**Comment by cookieY** [comment]
@etforshell 很抱歉 这样的功能暂时不在考虑之列。
