### ISSUE TITLE
SQL查询， 选择数据库为空

### ISSUE THREAD

**Issue by lifeblood** [cookieY/Yearning#135]
Traceback (most recent call last):
Jun 28 20:03:18 localhost journal:  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
Jun 28 20:03:18 localhost journal:    response = get_response(request)
Jun 28 20:03:18 localhost journal:  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
Jun 28 20:03:18 localhost journal:    response = self.process_exception_by_middleware(e, request)
Jun 28 20:03:18 localhost journal:  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
Jun 28 20:03:18 localhost journal:    response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jun 28 20:03:18 localhost journal:  File "/usr/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Jun 28 20:03:18 localhost journal:    return view_func(*args, **kwargs)
Jun 28 20:03:18 localhost journal:  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
Jun 28 20:03:18 localhost journal:    return self.dispatch(request, *args, **kwargs)
Jun 28 20:03:18 localhost journal:  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
Jun 28 20:03:18 localhost journal:    response = self.handle_exception(exc)
Jun 28 20:03:18 localhost journal:  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception
Jun 28 20:03:18 localhost journal:    self.raise_uncaught_exception(exc)
Jun 28 20:03:18 localhost journal:  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch
Jun 28 20:03:18 localhost journal:    response = handler(request, *args, **kwargs)
Jun 28 20:03:18 localhost journal:  File "/mnt/src/core/api/serachsql.py", line 369, in put
Jun 28 20:03:18 localhost journal:    highlist.append({'vl': i['Database'], 'meta': '库名'})
Jun 28 20:03:18 localhost journal: KeyError: 'Database'

**Comment by cookieY** [comment]
是mysql查询么？  确定不是mycat这种？

**Comment by lifeblood** [comment]
被你猜中了，是mycat

**Comment by lifeblood** [comment]
怎么破，兄弟

**Comment by cookieY** [comment]
不支持
