### ISSUE TITLE
老哥你这字段规范检测没判断反引号``，以前不规范的表都炸了!

### ISSUE THREAD

**Issue by dsphper** [cookieY/Yearning#139]
老哥你这字段规范检测没判断反引号，就算是关键词保留词，执行的SQL中字段如果加了反引号mysql 语法检测是可以通过的，现在的话通过这个平台CRUD 以前不规范的表都炸了，执行不了SQL了。
像INSERT，UPDATE，DELETE 这种操作不应该再检测字段关键词了，从源头CREATE TABLE控制住就可以了。
我也不知道这是否算是特性？还是Bug，姑且先提个建议~
希望能增强这个项目对历史表的包容性。😁

**Comment by cookieY** [comment]
@dsphper 新的源码已经使用反引号规范 但是没打包成镜像发布 - -

**Comment by jin123456bat** [comment]
这个问题我也发现了，在inception中把inception_enable_identifer_keyword设置为1就可以了
