### ISSUE TITLE
docker 安装方式登录失败

### ISSUE THREAD

**Issue by KISSMonX** [cookieY/Yearning#14]
```
Failed to load http://1x8.2x.43.2x4:8000/api-token-auth/: Response to preflight 
request doesn't pass access control check: No 'Access-Control-Allow-Origin' header
 is present on the requested resource. Origin 'http://1x8.2x.4x.2x4:86' is therefore 
not allowed access.
```

![image](https://user-images.githubusercontent.com/2876745/37134649-6be77c04-22d4-11e8-8e2f-bb562ff5d7ad.png)

**Comment by cookieY** [comment]
docker run -it -d -p 80:80 -p 8000:8000 -e "HOST=宿主机ip" registry.cn-hangzhou.aliyuncs.com/cookie/yearning:v1.0.0  宿主机ip填什么 就用这个ip访问  需要了解下跨域问题
