### ISSUE TITLE
beta002版本一直无法连接到数据库，代码也看不到。没法弄

### ISSUE THREAD

**Issue by N0mansky** [cookieY/Yearning#140]
![image](https://user-images.githubusercontent.com/16576004/61358865-d651bb80-a8ad-11e9-9826-f1645355d466.png)

**Comment by N0mansky** [comment]
想加个群询问下吧，又满员了，真是服了。感觉没法继续下去了

**Comment by cookieY** [comment]
2.0 群号747364310
