### ISSUE TITLE
执行insert类型datetime值为0000-00-00 00:00:00的sql失败

### ISSUE THREAD

**Issue by jin123456bat** [cookieY/Yearning#141]

**Comment by jin123456bat** [comment]
Execute: Incorrect datetime value: '0000-00-00 00:00:00' for column 'deleted_at' at row 1
--

**Comment by gaotuan** [comment]
这个问题是后端mysql的sql_mode 控制的，和代码无关

**Comment by jin123456bat** [comment]
> 这个问题是后端mysql的sql_mode 控制的，和代码无关

SQL_MODE已经设置过了，在mysql中可以插入进去

**Comment by jin123456bat** [comment]
关了，搞错数据库了
