### ISSUE TITLE
请使用后续维护项目Yearning-Go

### ISSUE THREAD

**Issue by cookieY** [cookieY/Yearning#143]
Yearning python版本**已不再进行官方维护**, Yearning-go项目为**后续维护项目**。

我们强烈建议无二次开发需求的用户使用[Yearning-go项目](https://github.com/cookieY/Yearning-go)。

该项目上线后已迭代10个版本,目前已趋于稳定。

### 如仍使用python版本Yearning须知:

1. Yearning python版本不会闭源，仍可基于AGPL3.0许可进行二次开发。
2. 由于inception已闭源失去后续支持,python版本将失去对审核规则及审核逻辑的维护。(此问题即使Yearning项目也无法解决。go版本已实现相关审核逻辑，由Yearning自己维护,保证及后续维护。)
3. 已知python版本含有多个提权漏洞(用户 -> 管理员) golang版本通过token内嵌角色信息的方式避免了此类问题。

### 从yearning 迁移到 yearning-go

由于yearning-go 数据字段及加解密算法与Yearning的差异

**无法进行平滑升级**

### 前端
- 全新的扁平化设计，全新的配色方案，更美观，更有少女心
- 页面渲染速度增加50%

### 后端
- 后端使用go语言重构,速度更快
- 内置自主实现的审核引擎,不再依赖inception
- 重新设计的鉴权逻辑，大幅提高安全性
- 细粒度权限更改为基于用户，不再基于权限组。
- 语法级别的SQL控制
- 执行语句变更为一个事务,单个工单内所有SQL如一条错误则全部作废

### 功能性
- 查询新增多查询窗口,让多库查询不再如此麻烦
- 支持多数据源查询
- 动态审核规则设置
- 新增注册开关，关闭后登陆页面不在提供注册功能,注册用户不再强制要求mail后缀
- 新增使用人申请权限每日上限开关
- 新增全局查询时限设置
- 新增查询导出数据开关，关闭后不再可以导出数据
- 查询新增快速提交按钮，实现同时查询并提交DML功能
- 新增定时任务中止功能
- 新增审核查询一键关闭功能
- 新增alter语句合并功能
- 新增数据源分类
- 新增查询耗时展示

### 修复的bug
 - 修复回滚工单的错误延迟性bug
 - 修复某些情况下无法脱敏成功的问题
 - 修复撤销操作加幂性问题

### 其他
- 自带gzip压缩/xss攻击防范/http2 等功能，无需nginx前置代理
- 更友好的安装体验(二进制./执行)
- 兼容mysql 8.0

**Comment by ruoyi0531** [comment]
666

**Comment by hsiangbinhua** [comment]
666666

**Comment by zenpax** [comment]
大神，请问最新版本2.1.2里面为何找不到“可注册邮箱后缀”的设置了呢？

**Comment by cookieY** [comment]
> 大神，请问最新版本2.1.2里面为何找不到“可注册邮箱后缀”的设置了呢？

取消了
