### ISSUE TITLE
lost installer forlder

### ISSUE THREAD

**Issue by jxc222** [cookieY/Yearning#145]
Hi,  
the new update sounds lost installer folder,  so below previous cannot running, 
because now Yearning/install/ is disappeared.

[snip]
yum install -y git
mkdir -p /data/soft/
cd /data/soft/
git clone https://github.com/cookieY/Yearning
cd Yearning/install/yearning-docker-compose/
docker-compose up -d

**Comment by jxc222** [comment]
find reason,  user below cmd instead,
wget -c https://github.com/cookieY/Yearning/archive/python.zip

**Comment by cookieY** [comment]
u can checkout branch to python  And then you can see that forlds
