### ISSUE TITLE
读写操作建议能在同一个库上操作

### ISSUE THREAD

**Issue by changeflyhigh** [cookieY/Yearning#147]
在很多场景中，读写操作在同一个库上进行是很常见的需求。或者配置一个开关设置这一项内容，这样可以满足更多人的需求，谢谢。

**Comment by cookieY** [comment]
@changeflyhigh 强制读写分离初衷是为了线上主库的安全，避免因为查询慢SQL导致主库异常影响线上业务。所以并不建议读写都在一个数据源当中进行,应该尽力规避这样的使用方法。

**Comment by changeflyhigh** [comment]
确实对线上的业务系统，尤其是发展到中后期都会做读写分离的。但是单库的场景还是很多的，并且结合工作实际，还有其他考虑，列举如下：
1. 在业务初期基于成本考虑，通常都只有一台主库。
2. CDB对于业务系统来说就是“单库”的场景。
3. 线上应用对数据的访问是高频的，所以应该读写分离。但使用yearning是人，人登录数据库操作的频率是比较少的，所以读写都在主库上操作影响很小，所以人对数据库的访问就没必要做读写分离了
4.  就算人访问数据库需要读写分离，可以把这项作为默认配置而不是唯一配置
这就是我个人结合工作实际，提出的场景需求，希望可以采纳。

**Comment by cookieY** [comment]
1.对于成本考虑可以采用多主一从的方式汇集所有的数据到一台数据库上。
2.线上应用对数据是高频访问，虽然人的查询是低频，可一旦低频的查询发生了慢sql那对高频的应用访问就是致命的。
3.每个公司的场景虽然不同, 但是原则上以线上生产环境稳定为第一优先级。(如果只图方便拿直接线上查数据不是更舒服)
4.其实可以对一个数据建立两个数据源的方式绕过去。这是个非正规的方法，但是可以这么用。因为不推荐这么用。

**Comment by changeflyhigh** [comment]
1. 一个数据库实例是多个业务系统共用的，一个业务系统就有一个帐号，也就是说，一个数据库实例上就有多个帐号。原来每个帐号建立一个连接，现在需要翻倍，这个工作量是不小的，而且这只是一个数据库实例而已
2. 就算人访问数据库要主从分离有一万个理由，也并非把它作为唯一选项，不同的业务场景应该有不同的使用方式
3. 退一万步说，在使用yearning查询主库导致了致命问题，作为yearning作者也无需担当任何责任的，对吧。

**Comment by cookieY** [comment]
@changeflyhigh 开源只能满足大部分人需求。对于个性化需求可以自己改代码实现或找我定制。

**Comment by changeflyhigh** [comment]
好的，谢谢！
