### ISSUE TITLE
执行影响多条的sql，回滚语句只有一条

### ISSUE THREAD

**Issue by harvey-zang** [cookieY/Yearning#15]
我执行一个sql，类似 update set name='lalala' where id in (1,2) ，影响了两条。
但是在查看回滚语句时，只显示了一条。
我认为是这行代码的问题：（Yearning/src/core/api/auditorder.py 215行）
`_h = sorted([i[0][0] for i in sql])`

查看sql 执行时value为：
sql = [ (
1、                (update xxxxx),
2、                (update xxxxx),
         ),
        (
3、                (update xxxxx),
4、                (update xxxxx),
        )]
上面_h 应该是只取了1、和3、吧。

**Comment by cookieY** [comment]
最新版已解决这个问题
