### ISSUE TITLE
V2.0.8 创建索引时未判断表记录数

### ISSUE THREAD

**Issue by yuandajn578** [cookieY/Yearning#151]
V2.0.8 ，以语法 "create index <index_name> on <table_name> (columns)" 创建索引时，检测给出的影响条数为0，无法限制DDL影响条数。

**Comment by cookieY** [comment]
@yuandajn578 感谢提交bug,该问题将会在下个版本进行修复。 请将该issues 提交到yearning-go 项目中 感谢！

**Comment by yuandajn578** [comment]
@cookieY  已经提交到yearning-go 项目，辛苦。
