### ISSUE TITLE
查看回滚语句页面对显示的sql数量做限制

### ISSUE THREAD

**Issue by REN-I** [cookieY/Yearning#152]
之前update一条语句，影响了几百万条数据，并且选择了备份。在查看回滚语句页面那里，由于会显示所有的sql。如果备份的语句少，没有问题，可以查看所有的备份sql然后提交回滚工单。如果回滚语句多的话，在这个地方会要全部展示，会导致浏览器崩溃掉。所以需要在这个地方进行显示数量限制，不然点开就直接崩溃，根本就没有机会去点击创建回滚工单的

**Comment by cookieY** [comment]
@REN-I 该建议已加入2.1.0开发计划。

**Comment by cookieY** [comment]
@REN-I 该建议已加入2.1.0开发计划。
