### ISSUE TITLE
读写分离的新想法

### ISSUE THREAD

**Issue by huohuanhuan** [cookieY/Yearning#153]
连接名使用一个，但是在配置数据库的时候，配置2个地址，DDL,DDM使用一个，查询使用一个！

**Comment by cookieY** [comment]
@huohuanhuan 感谢提供建议。 v2.1.0版本将对该功能点进行调整,以满足不同用户的需求。

**Comment by cookieY** [comment]
@huohuanhuan 感谢提供建议。 v2.1.0版本将对该功能点进行调整,以满足不同用户的需求。
