### ISSUE TITLE
消息推送处的地址是什么东东显示127.0.0.1，怎么修改

### ISSUE THREAD

**Issue by jin544642965** [cookieY/Yearning#156]
![image](https://user-images.githubusercontent.com/18446221/64435538-3f5af000-d0f5-11e9-95bd-9b5f73e9e04b.png)

**Comment by cookieY** [comment]
@jin544642965 什么版本？

**Comment by jin544642965** [comment]
你好，是最新版2.1.1,前两天刚装

**Comment by cookieY** [comment]
> 你好，是最新版2.1.1,前两天刚装

启动Yearning是 -b 指定  详细可通过-h 查看

**Comment by jin544642965** [comment]
> > 你好，是最新版2.1.1,前两天刚装
> 
> 启动Yearning是 -b 指定 详细可通过-h 查看

嗯，我不是问启动，是问邮件推送信息中的地址如何修改，默认发送邮件中的地址是：127.0.0.1

**Comment by cookieY** [comment]
> > > 你好，是最新版2.1.1,前两天刚装
> > 
> > 
> > 启动Yearning是 -b 指定 详细可通过-h 查看
> 
> 嗯，我不是问启动，是问邮件推送信息中的地址如何修改，默认发送邮件中的地址是：127.0.0.1

启动时 -b 指定了 就会更改了呀

**Comment by jin544642965** [comment]
> > > > 你好，是最新版2.1.1,前两天刚装
> > > 
> > > 
> > > 启动Yearning是 -b 指定 详细可通过-h 查看
> > 
> > 
> > 嗯，我不是问启动，是问邮件推送信息中的地址如何修改，默认发送邮件中的地址是：127.0.0.1
> 
> 启动时 -b 指定了 就会更改了呀

好的！多谢
