### ISSUE TITLE
能否加个日志系统

### ISSUE THREAD

**Issue by jin544642965** [cookieY/Yearning#158]
Yearning没有日志系统？删除不掉数据库 没法看报错![QQ图片20190923112238](https://user-images.githubusercontent.com/18446221/65400384-78cd7400-ddf4-11e9-9976-c9cd017d3322.png)

**Comment by jin544642965** [comment]
问题已找到，名称中有“/”，就删除不了。。。这bug，也没报错

**Comment by cookieY** [comment]
日志仅在前台打印  启动时 使用nohup > xx.out 即可

**Comment by jin544642965** [comment]
用nohup起的，这种删除操作类报错并没有写入
nohup > xx.out，里面貌似只有启动日志



------------------ 原始邮件 ------------------
发件人: "Henry"<notifications@github.com>;
发送时间: 2019年9月23日(星期一) 下午4:07
收件人: "cookieY/Yearning"<Yearning@noreply.github.com>;
抄送: "544642965"<544642965@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cookieY/Yearning] 能否加个日志系统 (#158)




日志仅在前台打印  启动时 使用nohup > xx.out 即可

**Comment by cookieY** [comment]
日志等级为error 只有报错才会有日志 

刚才的那个问题是由于转义导致的，这个错误如果不是人为进行判断逻辑程序是无法捕捉到的。所以才会导致没有报错

**Comment by jin544642965** [comment]
好的 ，明白了。



------------------ 原始邮件 ------------------
发件人: "Henry"<notifications@github.com>;
发送时间: 2019年9月23日(星期一) 下午4:12
收件人: "cookieY/Yearning"<Yearning@noreply.github.com>;
抄送: "544642965"<544642965@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cookieY/Yearning] 能否加个日志系统 (#158)




日志等级为error 只有报错才会有日志
 
刚才的那个问题是由于转义导致的，这个错误如果不是人为进行判断逻辑程序是无法捕捉到的。所以才会导致没有报错
