### ISSUE TITLE
no backup

### ISSUE THREAD

**Issue by trockxi** [cookieY/Yearning#164]
like this
![image](https://user-images.githubusercontent.com/28647418/67362217-215e2780-f59d-11e9-96a4-d1118417ac70.png)
![image](https://user-images.githubusercontent.com/28647418/67362313-59656a80-f59d-11e9-9f28-7932df8bf9ed.png)
正常执行后数据删除了，但备份语句没有，请问是哪里没配置正确或理解不对？

**Comment by cookieY** [comment]
@trockxi https://guide.yearning.io/attention.html

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
