### ISSUE TITLE
GrpcAddr这个配置对应的是什么服务？

### ISSUE THREAD

**Issue by hetiansu5** [cookieY/Yearning#165]

**Comment by cookieY** [comment]
https://guide.yearning.io/args.html

**Comment by hetiansu5** [comment]
> https://guide.yearning.io/args.html

谢谢，不过我看了juno可执行文件好像只能支持linux平台，看了也是基于Go构建的，不知道哪里可以有源码。

**Comment by cookieY** [comment]
@hetiansu5 juno 不提供源码
