### ISSUE TITLE
FootPrint guide link is not working

### ISSUE THREAD

**Issue by jimmy-liao-gogoro** [cookieY/Yearning#166]
### Screenshot
1.  
<img width="1440" alt="Screen Shot 2019-10-24 at 9 33 21 AM" src="https://user-images.githubusercontent.com/52391190/67446011-a1d66400-f641-11e9-9e29-336eb9fca15d.png">
2.  
<img width="1440" alt="Screen Shot 2019-10-24 at 9 34 36 AM" src="https://user-images.githubusercontent.com/52391190/67446028-b0bd1680-f641-11e9-8a30-deba3ba1e92c.png">

### Link
http://www.guide.yearning.io/

**Comment by cookieY** [comment]
@jimmy-liao-gogoro  fixd,thanks
