### ISSUE TITLE
最希望Yearning 增加什么功能？

### ISSUE THREAD

**Issue by cookieY** [cookieY/Yearning#169]
非常感谢喜爱与支持Yearning  ~

对于Yearning 的后续版本有什么期待呢？

把你想要的功能评论至该issue下方。

Yearning下个版本的新增功能将会从点赞数高的需求中选择。

**Comment by yangyi358252535** [comment]
有定时执行SQL功能么？



---原始邮件---
发件人: "Henry Yee"<notifications@github.com&gt;
发送时间: 2019年10月25日(星期五) 下午4:02
收件人: "cookieY/Yearning"<Yearning@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [cookieY/Yearning] 最希望Yearning 增加什么功能？ (#169)



非常感谢喜爱与支持Yearning

**Comment by cookieY** [comment]
> 有定时执行SQL功能么？
> […](#)
> ---原始邮件--- 发件人: "Henry Yee"<notifications@github.com&gt; 发送时间: 2019年10月25日(星期五) 下午4:02 收件人: "cookieY/Yearning"<Yearning@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [cookieY/Yearning] 最希望Yearning 增加什么功能？ (#169) 非常感谢喜爱与支持Yearning — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

该功能当前版本已支持

**Comment by yangyi358252535** [comment]
OK，我看一下文档，thx



---原始邮件---
发件人: "Henry Yee"<notifications@github.com&gt;
发送时间: 2019年10月25日(星期五) 下午4:09
收件人: "cookieY/Yearning"<Yearning@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"yangyi358252535"<822566107@qq.com&gt;;
主题: Re: [cookieY/Yearning] 最希望Yearning 增加什么功能？ (#169)


 
有定时执行SQL功能么？
 …
 ---原始邮件--- 发件人: "Henry Yee"<notifications@github.com&gt; 发送时间: 2019年10月25日(星期五) 下午4:02 收件人: "cookieY/Yearning"<Yearning@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [cookieY/Yearning] 最希望Yearning 增加什么功能？ (#169) 非常感谢喜爱与支持Yearning — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
该功能当前版本已支持

**Comment by cookieY** [comment]
> 我看了一下是不是没有dump功能？自动从prod db 备份到对应的 uat 或者 dev DB
> […](#)
> ---原始邮件--- 发件人: "Henry Yee"<notifications@github.com&gt; 发送时间: 2019年10月25日(星期五) 下午4:02 收件人: "cookieY/Yearning"<Yearning@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [cookieY/Yearning] 最希望Yearning 增加什么功能？ (#169) 非常感谢喜爱与支持Yearning — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

备份功能指的是生成回滚语句 并不是指备份数据

**Comment by sh-hanson** [comment]
希望工单提交时加上钉钉@指定审核人的功能，减少人工沟通交流成本，详细请参考：[https://ding-doc.dingtalk.com/doc#/serverapi2/qf2nxq](url)

**Comment by lwg2001s** [comment]
后期会支持MS SQL Server吗？

**Comment by cookieY** [comment]
@lwg2001s 很抱歉，不会

**Comment by devinop** [comment]
最希望能支持oracle




------------------&nbsp;Original&nbsp;------------------

**Comment by mjwtc0722** [comment]
提交审批的时候，sql脚本从git直接导入

**Comment by uiwe** [comment]
小哥哥，我又来了，我们的运维小哥哥强烈要求支持ldaps ,保证安全。

**Comment by thomaslou** [comment]
希望增加 查询导出 数据格式为 sql

**Comment by xiongmingwu** [comment]
因内部安全团队要求，希望能支持ldaps功能，配置项可参照 GitLab、Jenkins等，拜谢....

**Comment by xiongmingwu** [comment]
另外建议作者提供官方的docker镜像，方便用户使用。

**Comment by cookieY** [comment]
> 另外建议作者提供官方的docker镜像，方便用户使用。

这个安装包自带了Dockerfile可以自己打镜像

**Comment by dingshijie** [comment]
添加用户时能填手机号，在发送钉钉消息时能够利用手机号来@相关人员

**Comment by mjwtc0722** [comment]
> 另外建议作者提供官方的docker镜像，方便用户使用。

FROM centos:7

EXPOSE 8000

COPY Yearning  /opt/Yearning
COPY dist /opt/dist

RUN yum install -y tzdata https://repo.percona.com/yum/percona-release-latest.noarch.rpm && yum clean all
RUN yum install -y percona-toolkit && yum clean all
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo "Asia/Shanghai" >> /etc/timezone
RUN echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

WORKDIR /opt

ENTRYPOINT  ["/opt/Yearning"]

CMD ["-m", "-s", "-p", "8000"]

这个Dockerfile集成了pt-osc，OscBinDir设置为/usr/bin/即可

**Comment by xiongmingwu** [comment]
> 添加用户时能填手机号，在发送钉钉消息时能够利用手机号来@相关人员

建议手机号码也能通过LDAP获取。

**Comment by wangrenqing** [comment]
希望可以支持，，dump  sql文件 下来。

**Comment by yingwu** [comment]
希望能支持按数据库查询已应用了哪些工单 , 然后导出 , 将这些工单应用到其他库中;
目前开发中会维护一套库版本 , 会使用Yearing管理结构变化, 和基础数据变化; 
这些变化体现在工单中 , 需要给客户发版时同步到客户库中

**Comment by deeper-yang** [comment]
希望能添加企业微信机器人的通知功能

**Comment by JetBrainZP** [comment]
希望能增加一个【SQL审核必读】的页面，可以把自己公司的数据库设计规范放上去，在遇到SQL审核有疑问时，可以及时查询规则。如下图类似：
![image](https://user-images.githubusercontent.com/10757257/69702660-aacbc100-112a-11ea-9a19-300d2926ffd5.png)

**Comment by FelixLiuSheng** [comment]
增加执行计划Explain的功能

**Comment by zy14** [comment]
使用源码build后，sql 执行成功/失败不会发送通知了

**Comment by tiddlerhxy** [comment]
希望在审核工单列表里显示 环境 和 库名， 用于区分不同环境和数据库

**Comment by yunweigo** [comment]
希望支持枚举类型

**Comment by charnet1019** [comment]
是否可以支持goInception    https://github.com/hanchuanchuan/goInception

**Comment by cookieY** [comment]
> 是否可以支持goInception https://github.com/hanchuanchuan/goInception
