### ISSUE TITLE
审核菜单下面的工单里面加字段

### ISSUE THREAD

**Issue by REN-I** [cookieY/Yearning#171]
记录里面的工单审计里面有环境和连接名称，库名挺好的。能否在审核菜单下面的工单里面，也添加这三列。

**Comment by REN-I** [comment]
我们多个环境都接入了这一个审核平台，同样一个sql审批后我去执行到不同的环境。一些sql我需要在上线的时候去执行，其他环境可以直接执行。我每次还得挨个点进去查看该行工单是哪个环境的，最好能在外层就显示出来

**Comment by cookieY** [comment]
@REN-I 这里主要是涉及到列数量过多会导致小分辨率用户的使用体验，会出现全部挤在一团的不良效果,所以暂时只把我认为主要的信息直观展示出来
