### ISSUE TITLE
每次查询都会超过20s

### ISSUE THREAD

**Issue by david576111775** [cookieY/Yearning#172]
连接了一个mysql 5.7.26 
每次查询操作都会超过二十秒

**Comment by cookieY** [comment]
需要考虑三个因素:

1.网络
2.sql本身
3.使用了脱敏功能

**Comment by david576111775** [comment]
应该是对mysql的读写网络连接问题，每次查询时间保持在20020ms左右。
发现是mysql首先选择域名解析，配置禁用域名解析即可。
禁止mysql做域名解析，在mysql配置中添加以下配置
[mysqld] 

skip-name-resolve
