### ISSUE TITLE
下载了release版本Yearning v2.1.5，发现这个版本初始化数据库报错

### ISSUE THREAD

**Issue by lwg2001s** [cookieY/Yearning#174]
[root@test Yearning-go]# ll
总用量 8676
-rw-r--r--. 1 root root     137 10月 29 11:52 conf.toml
drwxr-xr-x. 6 root root     116 10月 29 10:58 dist
-rw-r--r--. 1 root root     597 8月  21 17:19 Dockerfile
-rw-r--r--. 1 root root     177 8月  23 15:13 # README
-rwxr--r--. 1 root root 8870272 10月 29 10:57 Yearning

[root@test Yearning-go]# ./Yearning -m
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x598fc6]

goroutine 1 [running]:
github.com/jinzhu/gorm.(*DB).clone(0x0, 0x7fe8a923d6d0)
/var/jenkins_home/go/pkg/mod/github.com/jinzhu/gorm@v1.9.8/main.go:777 +0x26
github.com/jinzhu/gorm.(*DB).New(...)
/var/jenkins_home/go/pkg/mod/github.com/jinzhu/gorm@v1.9.8/main.go:102
Yearning-go/src/model.DB(...)
/var/jenkins_home/workspace/Yearning-go/src/model/db.go:105
Yearning-go/src/service.Migrate()
/var/jenkins_home/workspace/Yearning-go/src/service/migrate.go:53 +0x44
main.main()
/var/jenkins_home/workspace/Yearning-go/main.go:75 +0x10c

**Comment by cookieY** [comment]
@lwg2001s 请重新下载。已上传了修复好的版本
