### ISSUE TITLE
centos6.9使用supervisor 管理一直提示无法链接数据库

### ISSUE THREAD

**Issue by kukukafei** [cookieY/Yearning#175]
环境 centos6.9 
yum 安装supervisor 
配置：
[program:Yearnging]
command=/usr/local/aaa/yearning/Yearning -s -p 8000
directory=/usr/local/aaa/yearning/
autostart=true                                                                  
autorestart=true
redirect_stderr=True
startsecs=10
startretries=3
user=kevin
logfile=/usr/local/aaa/yearning/aaa.log
logfile_maxbytes=1MB
logfile_backups=10

启动以后一直报无法链接数据库，但在手动运行程序时，可以正常使用。

**Comment by mjwtc0722** [comment]
应该是配置文件没有正确读取，最新的2.1.5应该可以使用/usr/local/aaa/yearning/Yearning -s -p 8000 -c /path/to/conf.toml
或者尝试使用添加环境变量的方法（容器化传参的方法）：environment=MYSQL_USER=root,MYSQL_ADDR=10.0.0.3:3306,MYSQL_PASSWORD=123123,MYSQL_DB=Yearning

**Comment by kukukafei** [comment]
测试了下，已经ok 了。给个大大的赞👍👍👍👍👍

**Comment by mjwtc0722** [comment]
> 测试了下，配置文件已经ok 了，但是貌似页面文件找不到。

方便提供截图吗

**Comment by kukukafei** [comment]
supervisor配置
[program:yearning]
command=/usr/local/yearning/Yearning -s -p 4000 -c /usr/local/yearning/conf.toml 
directory=/usr/local/yearning/
autostart=true              
autorestart=true            
startsecs=10                
startretries=3             
user=root                 ; setuid to this UNIX account to run the program
log_stdout=true             ; if true, log program stdout (default true)
log_stderr=true             ; if true, log program stderr (def false)
logfile=/usr/local/yearning/yearning.log    ; child log path, use NONE for none; default AUTO
logfile_maxbytes=100MB        ; max # logfile bytes b4 rotation (default 50MB)
logfile_backups=10          ; # of logfile backups (default 10)


shell 执行curl结果
$ curl localhost:4000
{"message":"Not Found"}

**Comment by mjwtc0722** [comment]
> supervisor配置
> [program:yearning]
> command=/usr/local/yearning/Yearning -s -p 4000 -c /usr/local/yearning/conf.toml
> directory=/usr/local/yearning/
> autostart=true
> autorestart=true
> startsecs=10
> startretries=3
> user=root ; setuid to this UNIX account to run the program
> log_stdout=true ; if true, log program stdout (default true)
> log_stderr=true ; if true, log program stderr (def false)
> logfile=/usr/local/yearning/yearning.log ; child log path, use NONE for none; default AUTO
> logfile_maxbytes=100MB ; max # logfile bytes b4 rotation (default 50MB)
> logfile_backups=10 ; # of logfile backups (default 10)
> 
> shell 执行curl结果
> $ curl localhost:4000
> {"message":"Not Found"}

使用-m参数进行一下数据库初始化试试

**Comment by cookieY** [comment]
@kukukafei 静态文件夹dist 必须和 yearning 放在同级目录

**Comment by kukukafei** [comment]
> @kukukafei 静态文件夹dist 必须和 yearning 放在同级目录

dist 与yearning 是同级目录

drwxr-xr-x 2 4096 10月 30 14:02 cmd
-rw-r--r-- 1 148 10月 30 14:11 conf.toml
drwxr-xr-x 6 4096 10月 30 14:04 dist
-rw-r--r-- 1 597 8月  21 17:19 Dockerfile
-rw-r--r-- 1 177 8月  23 15:13 # README
-rwxr--r-- 1 8870280 10月 29 17:24 Yearning
-rw-r--r-- 1 1232 11月  4 17:24 yearning.log
