### ISSUE TITLE
juno

### ISSUE THREAD

**Issue by meishaoyong** [cookieY/Yearning#180]
hi, juno cannot start in windows environment, how to fix it? thanks.

**Comment by meishaoyong** [comment]
![image](https://user-images.githubusercontent.com/12692871/68356258-bee45a00-014c-11ea-80cc-e6af0836eb09.png)

**Comment by lyrl** [comment]
配置启动参数 -s

**Comment by cookieY** [comment]
juno目前仅支持linux系统
