### ISSUE TITLE
非项目底下and不指定配置文件，启动时报错信息有点怪

### ISSUE THREAD

**Issue by hjfeng1988** [cookieY/Yearning#184]
[root@XM-v101 ~]# /usr/local/Yearning-go/Yearning -s
    Yearning_error: 2019/11/09 14:40:51.931427 /var/jenkins_home/workspace/Yearning- 
    go/src/model/db.go:87: open conf.toml: no such file or directory
    无法连接数据库!
    [root@XM-v101 ~]# ls /var/jenkins_home
    ls: cannot access /var/jenkins_home: No such file or directory

我知道怎么启动，就是来反映报错信息怪异的问题

**Comment by cookieY** [comment]
这个只是编译前的路径 和实际错误无关
