### ISSUE TITLE
后端源码跟github发布好的包不一致?

### ISSUE THREAD

**Issue by thomas1984** [cookieY/Yearning#185]
您好!我出于一些个性化需求,现拉源码进行编译,发现源码跟发布好的包不一致,烦请解惑.v2.1.5
如:
1.源码使用grpc,做了grpc的client端的链接池.编译好的包确不需要.
2.general.go的GeneralTable方法返回l数组,发布包前端却是需要highlight跟table键值.
3.GeneralSQLTest调用了TsClient方法,目的是?发布包报文返回的有"审核完成",但整个项目源码没有这个值.

**Comment by cookieY** [comment]
1.由于审核引擎juno并不再开源范围内,所以源码中使用grpc与编译好的审核引擎进行通信。直接编译好的则是集成在一起。
2.源码的更新频率会低于版本包。会在几个小版本后集中一次性更新。
3.当前源码基于2.1.4 会在最近更新到最新的源码

**Comment by thomas1984** [comment]
但是我看发布包没有开GRPC 50001端口,juno这个产品的地址能提供一下么?我没能找到,感谢!

**Comment by cookieY** [comment]
源码包下 juno 二进制文件

**Comment by thomas1984** [comment]
找到了 关于这款juno产品的介绍地址能提供下么?

**Comment by cookieY** [comment]
https://guide.yearning.io/args.html
