### ISSUE TITLE
用户批量授权的问题

### ISSUE THREAD

**Issue by hryGithub** [cookieY/Yearning#190]
普通授权批量授权，我选择了相应的用户，但是还是覆盖了整页的用户权限，
另外是否加入权限组的future

**Comment by cookieY** [comment]
> 普通授权批量授权，我选择了相应的用户，但是还是覆盖了整页的用户权限，
> 另外是否加入权限组的future

后期会考虑新增权限组,个人权限与权限组权限并行。 类似于AWS的IAM机制

**Comment by cookieY** [comment]
下个版本新增权限组功能
