### ISSUE TITLE
钉钉工单提交通知，平台地址不正确

### ISSUE THREAD

**Issue by 203HAHA** [cookieY/Yearning#196]
![image](https://user-images.githubusercontent.com/48740082/69318180-8f1e7180-0c77-11ea-8839-16583d9ee840.png)

启动命令是： ./Yearning -s -b "172.16.224.211" -p "8000"

能否输出：  平台地址: http://172.16.224.211:8000 ,
这样可以通过鼠标点击直接进入网页查看，  目前只能调整端口为80 启动 。

**Comment by cookieY** [comment]
-b "172.16.224.211:8000"

**Comment by 203HAHA** [comment]
用-b "172.16.224.211:8000"  ， 平台地址正确了

**Comment by CxistHans** [comment]
不能通过环境变量注入嘛？最新版好像没有这个变量了,该怎么操作? 然后还希望跳到对应的工单详情页。
