### ISSUE TITLE
开启检查列的默认值问题

### ISSUE THREAD

**Issue by marionxue** [cookieY/Yearning#198]
在审核规则中开启了检查默认值，并且在创建表语句中添加了默认是，SQL检查时候没有问题，已经通过，但是在执行的时候报不能有默认值
![image](https://user-images.githubusercontent.com/20356700/69511803-921da880-0f7c-11ea-9a9f-5a67919d66f4.png)
![image](https://user-images.githubusercontent.com/20356700/69511829-a2358800-0f7c-11ea-85d1-ad5b91889350.png)

**Comment by cookieY** [comment]
该字段本身就不允许有默认值.打开检查默认值后依然是无法设置blob text json等字段为not null ,请给出具体的SQL语句,作为复现之用

**Comment by marionxue** [comment]
```sql
`content` text default '' comment 'json内容',
```

**Comment by cookieY** [comment]
![image](https://user-images.githubusercontent.com/22343354/70763404-e69f9100-1d8e-11ea-8b15-7ade29075f4c.png)
v.2.1.6 无问题
