### ISSUE TITLE
在多级审核中，是否就可以角色，可否为使用者，管理员，执行人，执行人/管理员，添加一个双重身份的角色，避免紧急事件的时候，工单在执行人和管理员之间来回传递

### ISSUE THREAD

**Issue by HUIHUIHUANG2018** [cookieY/Yearning#206]
在多级审核中，是否就可以角色，可否为使用者，管理员，执行人，执行人/管理员，添加一个双重身份的角色，避免紧急事件的时候，工单在执行人和管理员之间来回传递

_Originally posted by @HUIHUIHUANG2018 in https://github.com/cookieY/Yearning/issues/178#issuecomment-563159537_

**Comment by cookieY** [comment]
暂时无法支持这个功能。后续可能会跟进
