### ISSUE TITLE
字段还有逗号会导致导出的csv文件格式错误

### ISSUE THREAD

**Issue by feidududexigua** [cookieY/Yearning#209]
求解
版本：2.6.1
数据：
![image](https://user-images.githubusercontent.com/7575988/70876325-2d41f500-1ff4-11ea-8a12-e54ea8aaf03e.png)
导出的数据
![image](https://user-images.githubusercontent.com/7575988/70876349-49459680-1ff4-11ea-808b-14912f9b20cf.png)

excel显示问题
![image](https://user-images.githubusercontent.com/7575988/70876340-4185f200-1ff4-11ea-992c-5bc89766bb94.png)

**Comment by cookieY** [comment]
@feidududexigua csv格式默认以逗号作为分隔符。目前无法规避

**Comment by feidududexigua** [comment]
> @feidududexigua csv格式默认以逗号作为分隔符。目前无法规避
多谢回复

如果csv无法规避，那是否有打算扩展一些其他格式呢？例如https://github.com/360EntSecGroup-Skylar/excelize

**Comment by SnowOnion** [comment]
敬请考虑 https://github.com/cookieY/Yearning/issues/24#issuecomment-613900521 的 CSV 转义方案（有 https://datatracker.ietf.org/doc/html/rfc4180 做保证）。
