### ISSUE TITLE
权限申请/审核在启用了角色后失效

### ISSUE THREAD

**Issue by feidududexigua** [cookieY/Yearning#211]
Version 版本:
2.1.7

问题描述
在升级到2.1.7后用户在申请权限并通过审核后，由于没有角色设置，导致权限丢失
1、test1用户申请权限
![image](https://user-images.githubusercontent.com/7575988/70892288-d8b66e00-2023-11ea-8d23-0d5ccfb03052.png)
2、管理员审核通过
3、权限丢失
![image](https://user-images.githubusercontent.com/7575988/70892492-39de4180-2024-11ea-9a9c-781151594ad7.png)

可否在申请的时候采用角色方式申请呢

**Comment by cookieY** [comment]
@feidududexigua 感谢你的提醒。更改权限设计时没有考虑到这块

**Comment by feidududexigua** [comment]
> @feidududexigua 感谢你的提醒。更改权限设计时没有考虑到这块

另外如果某个角色的审核人是aaa，但是如果aaa这个账号在权限里未被设置成管理员的话，他是看不到待审核的单的

**Comment by cookieY** [comment]
这个需要自己去设计了权限组的合理性了。
