### ISSUE TITLE
在ddl语句中加入了dbname.可通过审核，但是在启用了osc后会导致osc.go报错

### ISSUE THREAD

**Issue by feidududexigua** [cookieY/Yearning#213]
Version 版本:
2.1.7

Describe 问题描述
在同一个表上提交两个ddl操作，一个使用alter table t1，一个使用alter table test.t1
![1](https://user-images.githubusercontent.com/7575988/70959916-722f5f80-20b8-11ea-9698-dbbb251ed971.png)
![2](https://user-images.githubusercontent.com/7575988/70959927-79566d80-20b8-11ea-947f-f3e15c04773a.png)
审核操作也是没有问题的
![3](https://user-images.githubusercontent.com/7575988/70959942-84a99900-20b8-11ea-9971-198e35cf4989.png)
![4](https://user-images.githubusercontent.com/7575988/70959946-870bf300-20b8-11ea-872d-ceb70156ce7f.png)
但带有test.这个库名的sql执行报错
![6](https://user-images.githubusercontent.com/7575988/70959981-a276fe00-20b8-11ea-9af5-bd14742e9500.png)
![5](https://user-images.githubusercontent.com/7575988/70959985-a440c180-20b8-11ea-9baf-a26db1428e06.png)
后台go错误：
![image](https://user-images.githubusercontent.com/7575988/70960004-b589ce00-20b8-11ea-89d8-e200e45cc0e0.png)

Expected 预期
在处理携带dbname.这样的ddl时，纠正在osc中的用法

**Comment by cookieY** [comment]
暂时请自行规避错误写法
