### ISSUE TITLE
密码中不得含有? @ ^ $

### ISSUE THREAD

**Issue by 203HAHA** [cookieY/Yearning#217]
Yearning升级到最新版本2.1.7 后， 添加数据库，密码不支持特殊符号， 希望可以支持。 
毕竟mysql 密码支持特殊符号，Yearning 校验的时候也支持一下吧。 
现在的处理办法是，手工插入拼装好的SQL 到core_data_sources 表，貌似可以使用。但是不知道是否有其它未知问题。 
![image](https://user-images.githubusercontent.com/48740082/71441827-288ce780-273e-11ea-8794-7494e0af392a.png)

**Comment by cookieY** [comment]
限制这些特殊字符是为了规避pt-osc对特殊字符的转义问题。
