### ISSUE TITLE
Alert 修改表结构不支持bit类型

### ISSUE THREAD

**Issue by busyboy-ws** [cookieY/Yearning#219]
## Alert 修改表结构不支持bit类型
执行DDL Alert语句时,sql语句正确，但是不能通过检测。
![image](https://user-images.githubusercontent.com/21153799/71513537-b4854780-28d5-11ea-9465-ee4e6ce7d4d0.png)

SQL语句在Navicat上执行正常！

**Comment by cookieY** [comment]
下个版本支持该类型
