### ISSUE TITLE
DML检测不通过

### ISSUE THREAD

**Issue by ldean1203** [cookieY/Yearning#22]
报错Invalid source infomation。用过上一个版本搭过完全没问题，配置没变，现在新版这个样子，测了insert，delete都会报这个错

1 | NONE | 2 | None | Invalid source infomation. | Global environment | 0
-- | -- | -- | -- | -- | -- | --

**Comment by cookieY** [comment]
检查inception配置

**Comment by ldean1203** [comment]
我走的一键安装啊～而且inception跟之前测试的一模一样

**Comment by cookieY** [comment]
@ldean1203 这个错是Inception那边报的 和yearning这边是没有关系的

**Comment by ldean1203** [comment]
嗯，我已经找到问题了，谢谢

**Comment by QiuMing** [comment]
@ldean1203  我也遇到类似的问题，请问你是怎么解决的？

**Comment by ldean1203** [comment]
@QiuMing 密码不允许用星号
