### ISSUE TITLE
数据审核条件有误

### ISSUE THREAD

**Issue by guojingyinan219** [cookieY/Yearning#220]
![Uploading 企业微信截图_15776777882913.png…]()

您好，我在删除数据的时候，判断条件，其实影响行数只有几十行，但是这里面获取到的影响行数是整个表的数据，所以数据审核老是会出现不通过的问题

**Comment by guojingyinan219** [comment]
![image](https://user-images.githubusercontent.com/13974995/71569017-e6c9bb80-2b06-11ea-826b-ddbb96e9f097.png)

**Comment by cookieY** [comment]
https://guide.yearning.io/attention.html
