### ISSUE TITLE
误点alter语句，导致创建表报错

### ISSUE THREAD

**Issue by 203HAHA** [cookieY/Yearning#221]
1. 测试DDL语句 (2个create语句一起复制到"填写SQL语句" 对应的填写框里)：
CREATE TABLE `test_bill` ( `bill_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID', `user_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '用户ID',PRIMARY KEY (`bill_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户账单表';	

CREATE TABLE `test_bill_detail` ( `detail_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID', `bill_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '用户账单ID', `user_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '用户ID',  PRIMARY KEY (`detail_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='详情表';	

2. 测试步骤
①点  "ALTER 语句合并"-->②点"检测语句"
该步骤会在每个语句的末尾再加一个';' ，且检测语句显示无错误，自动流转到审批人员。
审核人员接到工单后，点"检测sql" 没有问题， 但是点"执行" 报语法错误。 

3. 建议
“alter 语句合并” 对create 不做处理 ，防止误点

**Comment by 203HAHA** [comment]
截图没粘贴上，下面是测试的截图：
![image](https://user-images.githubusercontent.com/48740082/71658530-5fd34800-2d7f-11ea-9ad4-0159522c4776.png)

**Comment by cookieY** [comment]
@203HAHA Yearning v2.1.8版本
