### ISSUE TITLE
查询审计详细只能显示20条，不能翻页？

### ISSUE THREAD

**Issue by feidududexigua** [cookieY/Yearning#222]
Version 版本:
2.1.8

Describe 问题描述
记录->查询审计->详细信息 里：
数据库表中记录超过20条，而页面详细信息里只显示前20条且不能翻页
![image](https://user-images.githubusercontent.com/7575988/71713862-6ed0fd80-2e46-11ea-8782-541f6a5ddfef.png)

Expected 预期
希望能实现翻页查看所有的查询记录

**Comment by cookieY** [comment]
@feidududexigua 已定位改问题,将会在下个版本修复
