### ISSUE TITLE
LDAP配置时如何添加filter？？

### ISSUE THREAD

**Issue by GuanshengYang** [cookieY/Yearning#225]
2.1.7版本
目前filter是下拉框只有cn，uid，sANAccountName这三个选项
如果想加入使用memberof的filter该怎么配置？例如；
(&(objectClass=inetOrgPerson)(memberof=cn=yearning,ou=groups,dc=xxxxx,dc=com))

我看代码没有memberof选项，是不是现在不支持？https://github.com/cookieY/Yearning/blob/4e463bbf490823d8bedf6bc200ce39cfbf2bce06/src/lib/toolbox.go#L107

**Comment by cookieY** [comment]
目前不支持自定义
