### ISSUE TITLE
设置了环境和数据库，提交工单时加载不出来

### ISSUE THREAD

**Issue by vinartis** [cookieY/Yearning#226]
添加了环境、添加了数据库，提交工单时，环境加载出来了，但是连接没有，不清楚是有什么特别的设置？
![图片](https://user-images.githubusercontent.com/4651907/72057451-66c30300-3309-11ea-8ead-2ab141e852be.png)
![图片](https://user-images.githubusercontent.com/4651907/72057523-80fce100-3309-11ea-9090-b7a1aef2efff.png)

**Comment by cookieY** [comment]
https://guide.yearning.io/permission2.html
