### ISSUE TITLE
审核页面sql查看没有格式化

### ISSUE THREAD

**Issue by vinartis** [cookieY/Yearning#227]
作为审核人员看到的这个审核页面重点不突出，审核的重点是sql，而sql却显示为隐藏（默认），而且没有格式化，一团糟，
![图片](https://user-images.githubusercontent.com/4651907/72116482-4c2e6f80-3385-11ea-82a8-34a5786c488e.png)

**Comment by cookieY** [comment]
1.在大量sql提交时如果不对Sql进行隐藏会导致排版杂乱
2.在大量sql提交时如果对每条sql进行格式化会导致滚动条拉长很多。最终导致繁琐的滚轮操作。

综合以上因素，不会对其进行更改
