### ISSUE TITLE
不通权限组审核人之间跨环境审核异常

### ISSUE THREAD

**Issue by feidududexigua** [cookieY/Yearning#228]
Version 版本:
V2.1.9

Describe 问题描述
审核人有：U1、U2
数据库环境有：D1、D2
权限组有：G1，G2
G1下的数据库为D1环境的，审核人为U1
G2下的数据库为D2环境的，审核人为U2

用户U3是使用者、同属于G1、G2组，在提交查询是申请D1的查询权限，但是可以选择审批人为U2，U2审批通过后U3即可访问D1的数据

Expected 预期
审批权限由各自的审批管理员操作

**Comment by cookieY** [comment]
@feidududexigua 首先需要先明白权限目前是基于权限组来进行调整 并不是基于审核人/数据源等等。

你遇到的问题 完全可以通过新建不同的审核人权限组然后分配到不同的用户下就可以完成。

**Comment by feidududexigua** [comment]
> @feidududexigua 首先需要先明白权限目前是基于权限组来进行调整 并不是基于审核人/数据源等等。
> 
> 你遇到的问题 完全可以通过新建不同的审核人权限组然后分配到不同的用户下就可以完成。

我遇到的问题是现在关于权限组G1的审批操作可以由一个非G1权限组审批人里的人来操作：

权限组G1定义审核人为U1，查询权限是数据库环境D1；
权限组G2定义审核人为U2，查询权限是数据库环境D2；

用户U3是使用人角色，赋予G1，G2权限组权限，所以他的申请单审核人包括了U1跟U2，**当他想申请D1的查询权限时，可以选择U2来审批**，按权限组来说，需要访问D1的所有申请都应该由审核人U1来操作

**Comment by cookieY** [comment]
@feidududexigua 

G1下的数据库为D1环境的，
G2下的数据库为D2环境的，
G3审核人为U1
G4审核人为U2

用户U3  赋予G1 G3 

搞定

**Comment by feidududexigua** [comment]
> @feidududexigua
> 
> G1下的数据库为D1环境的，
> G2下的数据库为D2环境的，
> G3审核人为U1
> G4审核人为U2
> 
> 用户U3 赋予G1 G3
> 
> 搞定

现况是U3申请D1权限可以由U2来审批，在V2.1.9这个版本上是行得通的，但是实际上我认为必须由U1来审批这个单，在U3申请D1查询权限时审批人那一栏就不应该出现U2而只出现U1

**Comment by feidududexigua** [comment]
补充下：这里是不同组之间可以跨环境审核（查询权限是按环境申请的）
数据库有两个环境，分别是测试环境1跟测试环境2：
![1](https://user-images.githubusercontent.com/7575988/72153348-b298a980-33e8-11ea-96fb-dc5b88cf68ee.png)
然后建立两个组，分别用于管理两个环境数据库查询权限，审批人分别是管理员1跟管理员2，；
![2](https://user-images.githubusercontent.com/7575988/72153384-ce9c4b00-33e8-11ea-8202-9763d97ad592.png)
![3](https://user-images.githubusercontent.com/7575988/72153393-d2c86880-33e8-11ea-89f0-37a26a3fe932.png)
建立一个使用用户用户1，授予两个组的权限：
![4](https://user-images.githubusercontent.com/7575988/72153449-f55a8180-33e8-11ea-9cfe-0f06f1589779.png)
**但当用户1申请环境1的权限时可以把单提交给管理员2**
所以，当用户选择申请环境1时，审核人那一栏是不是应该只能出现管理员1这个选项，但实际上出现了多个管理员
![5](https://user-images.githubusercontent.com/7575988/72153518-305cb500-33e9-11ea-8965-7f76e3529eee.png)

**Comment by cookieY** [comment]
把审核人单独拎出来成立一个安全组啊 别一个权限组又是数据源权限又有审核人啊

这个很难理解么？

**Comment by cookieY** [comment]
@feidududexigua 你这样的赋权当然会有2个审核人 因为你给用户赋予了2个权限组 而这两个权限组的上级审核人又分别是管理员1和管理员2。


我的意思是把管理和数据源拆成2个权限组来做

**Comment by feidududexigua** [comment]
> @feidududexigua 你这样的赋权当然会有2个审核人 因为你给用户赋予了2个权限组 而这两个权限组的上级审核人又分别是管理员1和管理员2。
> 
> 我的意思是把管理和数据源拆成2个权限组来做
> 
> 你的大概意思是 希望审核人变成两个种类。 一个是审核的上级审核人 一个是查询的上级审核人。
> 
> 如果是这样的话 目前是没有这样的功能的

我的意思是不同的数据源应该由对应的审核人来审单，现在是审核人A不在权限组G里，但是他可以审核权限组G里相关数据源的单

**Comment by cookieY** [comment]
@feidududexigua 
![image](https://user-images.githubusercontent.com/22343354/72415933-8d24ea80-37b0-11ea-8a07-2dd57430b634.png)
![image](https://user-images.githubusercontent.com/22343354/72415947-957d2580-37b0-11ea-944a-f5a38deb91f6.png)

**Comment by feidududexigua** [comment]
> @feidududexigua
> ![image](https://user-images.githubusercontent.com/22343354/72415933-8d24ea80-37b0-11ea-8a07-2dd57430b634.png)
> ![image](https://user-images.githubusercontent.com/22343354/72415947-957d2580-37b0-11ea-944a-f5a38deb91f6.png)

我们有些工程师是负责多个项目，他需要向不同项目数据申请权限，但是这些项目的负责人（审核人）不是同一个，所以不能放到同一个权限组里

**Comment by cookieY** [comment]
@feidududexigua 你这是基于项目的权限划分了

应该把项目转化思维为基于权限组的权限划分

![image](https://user-images.githubusercontent.com/22343354/72418262-78972100-37b5-11ea-8cfe-8e81ccd8d963.png)
![image](https://user-images.githubusercontent.com/22343354/72418286-80ef5c00-37b5-11ea-8327-e671d54c26ed.png)

**Comment by feidududexigua** [comment]
> @feidududexigua 你这是基于项目的权限划分了
> 
> 应该把项目转化思维为基于权限组的权限划分
> 
> ![image](https://user-images.githubusercontent.com/22343354/72418262-78972100-37b5-11ea-8cfe-8e81ccd8d963.png)
> ![image](https://user-images.githubusercontent.com/22343354/72418286-80ef5c00-37b5-11ea-8327-e671d54c26ed.png)

那根据实际需求：多个项目要在同一个平台来管理，项目负责人不一样，开发需要访问到多个项目，这种情况该如何来建立权限组

**Comment by cookieY** [comment]
@feidududexigua 目前是不支持这种方式，因为上级审核人是DDL/DML/Query3方共用。

实际上也只是选择范围的问题。 

虽然可以其他的审核人 但是可以不通过。对整体影响不大。
