### ISSUE TITLE
Sql查询显示问题

### ISSUE THREAD

**Issue by GogoPei** [cookieY/Yearning#233]
Version 版本:
Yearning v2.1.9

Describe 问题描述
sql查询显示问题，bit类型无法显示，没法查看结果

Expected 预期
可以转换成布尔值类型显示在html上。不然要查这些内容看不到很尴尬。。。

**Comment by GogoPei** [comment]
我下午发现，布尔类型 查询也不显示，，，

**Comment by ytx1988320** [comment]
juno 程序启动不了， 连不上数据库 有遇到吗
