### ISSUE TITLE
权限组下拉列表不可筛选 并且没有排序 当全新数量超过30的时候 用起来很费劲

### ISSUE THREAD

**Issue by xqzt** [cookieY/Yearning#237]
![image](https://user-images.githubusercontent.com/5992144/72782665-48d99480-3c5f-11ea-8196-34b50097a9df.png)

**Comment by cookieY** [comment]
将提供搜索功能

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/edit/v2.2.0
