### ISSUE TITLE
查询结果导出格式错误

### ISSUE THREAD

**Issue by ChuckPerry** [cookieY/Yearning#24]
hi,各位大神：
首先感谢大家提供这样一个优美的平台。

SQL查询界面-导出数据，如下查询
![image](https://user-images.githubusercontent.com/10229398/38846163-8d6c7ee2-422d-11e8-93a2-86f943293d0f.png)

字段含有“,”时，导出结果如下
![image](https://user-images.githubusercontent.com/10229398/38846148-6d39c724-422d-11e8-87f2-2371e0be8755.png)

**Comment by cookieY** [comment]
由于导出格式为了csv格式 默认已 逗号作为分隔符。所以会导致此情况

**Comment by cookieY** [comment]
-

**Comment by luozikuan** [comment]
> @ChuckPerry 由于导出格式为了csv格式 默认已 逗号作为分隔符。所以会导致此情况

对于含有逗号的列，导出的时候转义一下，步骤如下：
1. 可以将此列中所有`"`改成`""`；
2. 把值开头和末尾用 `"` 包起来。

例如，某列原始内容 `{"name":"xxx",score:98}`，第一步之后变成`{""name"":""xxx"",score:98}`，第二步之后变成`"{""name"":""xxx"",score:98}"`

**Comment by SnowOnion** [comment]
> > [@ChuckPerry](https://github.com/ChuckPerry) 由于导出格式为了csv格式 默认已 逗号作为分隔符。所以会导致此情况
> 
> 对于含有逗号的列，导出的时候转义一下，步骤如下：
> 
> 1. 可以将此列中所有`"`改成`""`；
> 2. 把值开头和末尾用 `"` 包起来。
> 
> 例如，某列原始内容 `{"name":"xxx",score:98}`，第一步之后变成`{""name"":""xxx"",score:98}`，第二步之后变成`"{""name"":""xxx"",score:98}"`

赞 @luozikuan 。补充：对 CSV 中逗号和双引号的转义，是 https://datatracker.ietf.org/doc/html/rfc4180 约定好的，所以我相信 CSV 的编辑器基本都会支持。（也可以看 https://zhuanlan.zhihu.com/p/671064497 ）
