### ISSUE TITLE
多表关联查询，等待几秒后，界面无报错无结果

### ISSUE THREAD

**Issue by sh-hanson** [cookieY/Yearning#241]
Version 版本:
2.1.9

Describe 问题描述
多表关联查询，客户端执行需要近1分钟出结果。在审核平台上执行，界面等待几秒钟后，显示“暂无数据”，没有结果，也没有报错。mysql中show processlist看语句还在执行中
查看日志发现如下错误：（以下实际IP已替换为x.x.x.x）
packets.go:36: read tcp x.x.x.x:34912->x.x.x.x:3306: i/o timeout

Expected 预期
希望支持复杂sql查询，大表查询，就是语句执行时间在几分钟左右的能支持查询结果。因为正常查询都是走的独立从库，不影响生产。

**Comment by sh-hanson** [comment]
单表无索引查询，表记录4kw+，取一天内符合条件的记录，筛选后不到百条，客户端查询需要30几秒，审核平台查询现象跟上面一样，无结果无错误，mysql中看sql仍在执行中

**Comment by cookieY** [comment]
此问题主要是http超时时间导致，暂时无法进行更改
