### ISSUE TITLE
时间戳函数没有智能补全

### ISSUE THREAD

**Issue by sh-hanson** [cookieY/Yearning#242]
Version 版本:
2.1.9

Describe 问题描述
unix_timestamp，from_unixtime，这两个常用函数没有智能提示，没有补全功能
同时，工单中包含此函数的SQL，即使这两个函数单词拼写错误，也被审核通过了，然后到DBA这边执行报错，提示不存在这个函数

**Comment by cookieY** [comment]
暂时无法对函数进行补全以及检查函数名是否正确
