### ISSUE TITLE
如何设置才能实现禁止管理员删除“工单审核”记录？

### ISSUE THREAD

**Issue by ackfin** [cookieY/Yearning#246]
Version 版本:
版本号: v2.1.8 

Describe 问题描述:
我们的使用场景是这样的：
项目开发人员提交SQL变更请求（使用人）--> 项目开发负责人审核SQL变更请求（管理员）--> DBA审核执行SQL变更请求（执行人）
但是项目开发负责人（管理员）把工单审核记录删除了，DBA（执行人）的审核记录也没有了

Expected 预期:
只允许指定的管理员删除“工单审核”记录，
在我们的场景里，就是希望只有DBA才能删除“工单审核”记录，不希望项目开发负责人可以删除“工单审核”记录。

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/edit/v2.2.0
