### ISSUE TITLE
查询功能SQL语法有误导致Yearning奔溃down掉

### ISSUE THREAD

**Issue by opscolin** [cookieY/Yearning#247]
Version 版本:
2.1.9

Describe 问题描述
查询页面，如果写入的SQL语法有问题，直接执行查询，会导致Yearning奔溃服务down掉，报错如下：
![image](https://user-images.githubusercontent.com/11386088/75664046-cfe14a00-5cac-11ea-850b-db4e83b798ea.png)

Expected 预期
1、能否直接报错提示 SQL 语法有问题，而不是导致Yearning奔溃服务down掉 
2、能否添加SQL审核校验，如果不执行校验或者校验不通过，不能执行查询

如果能满足第一种就行

**Comment by cookieY** [comment]
@opscolin 可以使用已编译好的版本
