### ISSUE TITLE
chrome登录时页面无响应

### ISSUE THREAD

**Issue by ackfin** [cookieY/Yearning#248]
chrome 版本 80.0.3987.122（正式版本） （64 位）
yearning 版本号: V2.1.9
bug 截图：[chrome登录时页面无响应](https://upload-images.jianshu.io/upload_images/12475671-3f8593de3b165aed.png)

**Comment by cookieY** [comment]
个别情况下 前端框架会触发内存泄露问题。可关闭后重新尝试
