### ISSUE TITLE
是否支持自定义检查规则

### ISSUE THREAD

**Issue by shanyuxiyun** [cookieY/Yearning#25]
看inception已经将近3年没有维护了，在inception基础上开发是否底座有风险？
是否支持mysql自定义检查规则？

**Comment by cookieY** [comment]
@shanyuxiyun 只要Inception支持就支持

**Comment by anic** [comment]
如何修改inception的规则？例如inception中有支持外键的配置inception_enable_foreign_key，但是在yearning配置界面没有看到

**Comment by cookieY** [comment]
> 如何修改inception的规则？例如inception中有支持外键的配置inception_enable_foreign_key，但是在yearning配置界面没有看到

inception不支持外键的  而且2.0版本已经不用Inception了 自研的版本依然不开放外键。
