### ISSUE TITLE
如何配置OSC

### ISSUE THREAD

**Issue by zeroisme** [cookieY/Yearning#251]
Version 版本:
Yearning2.2.0

Describe 问题描述
![image](https://user-images.githubusercontent.com/9354439/76277294-51dffd00-62c3-11ea-955f-5bd7fb11334b.png)

管理界面配置打开OSC后， 审批Alter DDL。应该使用osc执行，使用navicat观察数据库进程。发现直接执行的alter
![image](https://user-images.githubusercontent.com/9354439/76277252-2f4de400-62c3-11ea-953d-0cd801102bbe.png)

配置如下
![image](https://user-images.githubusercontent.com/9354439/76288934-f58cd580-62e2-11ea-97d5-b08fd0daba22.png)

Yearning日志无输出

Expected 预期
使用pt-osc执行alter语句

**Comment by cookieY** [comment]
具体请参考pt-osc 文档

**Comment by zeroisme** [comment]
pt的路径配置都没问题，错误日志也没有错误信息。我目前是换到archery上了
