### ISSUE TITLE
SQL执行失败时, 无法查看SQL记录

### ISSUE THREAD

**Issue by Flyonsnow** [cookieY/Yearning#255]
提交SQL工单以后，DBA又去数据库内执行了sql，导致语句执行失败，此时审核员无法查看sql语句了

<img width="1118" alt="1" src="https://user-images.githubusercontent.com/10215557/76498594-26eada00-6478-11ea-9476-5b0f06c37558.png">

<img width="1189" alt="2" src="https://user-images.githubusercontent.com/10215557/76498599-28b49d80-6478-11ea-9c2c-867b33e40ec2.png">

**Comment by cookieY** [comment]
@Flyonsnow 请使用最新版本
