### ISSUE TITLE
【bug】SQL查询ERROR 1690 (22003) 精度溢出问题

### ISSUE THREAD

**Issue by yiwenshuo** [cookieY/Yearning#257]
通过mysql client查询情况
mysql> desc test12;
+-------+---------------------+------+-----+---------+-------+
| Field | Type                | Null | Key | Default | Extra |
+-------+---------------------+------+-----+---------+-------+
| id    | int(11)             | YES  |     | NULL    |       |
| a     | bigint(20) unsigned | YES  |     | NULL    |       |
| b     | bigint(20) unsigned | YES  |     | NULL    |       |
+-------+---------------------+------+-----+---------+-------+
3 rows in set (0.02 sec)

mysql> 
mysql> 
mysql> select * from test12;
+------+------+------+
| id   | a    | b    |
+------+------+------+
| 1    | 3    | 5    |
| 2    | 5    | 1    |
+------+------+------+
2 rows in set (0.03 sec)

mysql> select  * from test12 where a-b>1 ;
BIGINT UNSIGNED value is out of range in '(`ywsdb`.`test12`.`a` - `ywsdb`.`test12`.`b`)'
mysql> 

但是通过Yearning平台查询的时候返回结果集为空，不报错，导致结果误导

**Comment by cookieY** [comment]
这和精度溢出没什么关系。应该是错误信息没有正确反馈。 会关注这个问题
