### ISSUE TITLE
why error ? go 1.13.8  intellij idea

### ISSUE THREAD

**Issue by Brainhu** [cookieY/Yearning#259]
clone your code 
go run main.go 

then:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x8fba44]

goroutine 1 [running]:
sync.(*Mutex).Lock(...)
	D:/Dev/Go/src/sync/mutex.go:74
Yearning-go/src/pool.(*GRPCPool).Close(0x0)
	D:/workspace/go/src/yearning/src/pool/pool.go:195 +0x34
main.main()
	D:/workspace/go/src/yearning/main.go:106 +0xec

**Comment by cookieY** [comment]
https://guide.yearning.io/args.html

**Comment by JetBrainZP** [comment]
您好，我也碰到这个问题，这个开发使用文档可以写的更加详细一些吗？对我们这种小白来说，比较困难，
比如：juno 是什么，需要如何启动？

**Comment by JetBrainZP** [comment]
@CookieYe ,大佬能加你微信，聊一下吗？
