### ISSUE TITLE
Yearning v1.2.0 正式发布

### ISSUE THREAD

**Issue by cookieY** [cookieY/Yearning#26]
1.查询支持字段脱敏

2.支持多级审核

3.工单定时执行

4.新增设置页面,减少启动配置项

5.修复待办事项点击完成后显示的异常问题

6.修复横向导航标签 首页标签会变更坐标的异常问题

7.新增一键关闭所有横向导航标签按钮

8.修复一键生成字典下拉框样式异常的问题

9.优化翻页

10.添加执行失败显示

11.取消跨域限制

12.允许自定义机房

13.修复查询bigint字段精度丢失的问题

14.修复查询blob字段报错的问题

15.修改前端数据保存方式

16.修改查询时左侧表名过长的样式问题

17.优化查询及执行工单时错误提示语句

18.新增查询审核开关

19.修复ddl及索引提交空sql后审核检测时错误提示不清晰的问题

20.修复由于mysql 连接超时时间设置过短而导致查询时限失效的问题

21.修复sql过多导致的样式问题

22.新增执行结果自动刷新，不再需要手动刷新

23.修复ldap用户更改密码后登陆异常的问题

24.修复了其他影响用户体验的bug

**Comment by wuyanan1993** [comment]
赞

**Comment by ruoxiaojie** [comment]
赞

**Comment by ChuckPerry** [comment]
您好，这个多级审核是纵向的还是横向的？
是不是可以选择夺个审核人的那种？

**Comment by cookieY** [comment]
@ChuckPerry 上下级 不是选择多个

**Comment by 18611115400** [comment]
赞

**Comment by wuyanan1993** [comment]
啥时候发？

**Comment by cookieY** [comment]
@ChuckPerry 暂时不考虑

**Comment by cookieY** [comment]
@wuyanan1993 明天合并
