### ISSUE TITLE
添加数据库时提示“密码中不得含有? @ ^ $”

### ISSUE THREAD

**Issue by geq1fan** [cookieY/Yearning#261]
可是我的数据库密码就是有‘@’符号，导致无法保存，请问怎么解决？
![image](https://user-images.githubusercontent.com/29982379/77045847-f4ebf180-69fc-11ea-8e15-89c1eabf136e.png)

**Comment by cookieY** [comment]
禁用该特殊字符主要是由于存在转义及osc异常问题

**Comment by geq1fan** [comment]
也就是说如果我想用的话只能改数据库密码了？

**Comment by cookieY** [comment]
> 也就是说如果我想用的话只能改数据库密码了？

是的

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/edit/v2.2.0
