### ISSUE TITLE
 select 是 DML 语句吗？

### ISSUE THREAD

**Issue by taylorshrey** [cookieY/Yearning#263]
如何配置才能在dml中使用select *?

**Comment by cookieY** [comment]
这个问题 应该变成select 是DML语句吗？

**Comment by taylorshrey** [comment]
情况是：

升级到2.2.0版本之后，支持了create table like，但是dml中使用
INSERT INTO tablename SELECT * FROM tablename;

这里提示：请提供dml语句。

**Comment by cookieY** [comment]
目前强制不允许使用select *

**Comment by taylorshrey** [comment]
那有办法修改这个配置吗？因为没有这个操作的话，就没有办法备份整张表

**Comment by cookieY** [comment]
备份表的操作 我认为本身就不属于Yearning的使用范围。这种类型的SQL审核的意义也不大
