### ISSUE TITLE
创建表时增加INDEX提示过长

### ISSUE THREAD

**Issue by anic** [cookieY/Yearning#265]
建表语句
```
CREATE  TABLE  `my_table` (`pkid` bigint( 20) NOT  NULL  COMMENT  '主键', 
`name` varchar( 255) NOT  NULL  COMMENT  '姓名', 
PRIMARY  KEY  (
  `pkid`), 
  INDEX  `my_table_idx1` (
    `name`) USING  BTREE
  );
```
使用Yearning（juno）检测提示：索引 'my_table_idx1' 过长; 所有组成索引列的长度和不能大于767字节!

如果是先建表不建索引，再创建索引，则可以正常通过
```
ALTER TABLE `my_table` 
ADD INDEX `my_table_idx1`(`name`) USING BTREE;
```

为什么呢

**Comment by cookieY** [comment]
mysql 5.6版本索引长度限制是767,5.7及之后变为3072

**Comment by anic** [comment]
长度限制是知道的，但是为什么表没创建时候回提示，创建了就不提示？

难道是用的RDS的原因？

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/edit/v2.2.0

**Comment by corama** [comment]
这个问题要怎么解决？现在问题依然存在，yearning审核不通过，但是在数据库执行没有问题
