### ISSUE TITLE
alter ddl 执行失败

### ISSUE THREAD

**Issue by spiritman1990** [cookieY/Yearning#266]
**Version 版本:**
Yearning-2.1.9

**Describe 问题描述**
执行DDL SQL报错：
SQL语句：
ALTER TABLE `t_order_section_attach_test` ADD COLUMN `root_order_id` binary(16) DEFAULT NULL COMMENT '原始订单ID，链条上第一个订单' ;

检测通过后，最终执行报错：
exec: "pt-online-schema-change": executable file not found in $PATH 

打开OSC时执行失败
关闭OSC后，依旧失败

**Expected 预期**

求助，解决此问题

**Comment by cookieY** [comment]
exec: "pt-online-schema-change": executable file not found in $PATH

翻译:

执行文件 pt-online-schema-change 不在$PATH变量中。

说明你没有填写pt-online-schema-change的所在路径

**Comment by spiritman1990** [comment]
请教下在哪儿pt-online-schema-change的所在路径？我是下载的binary，不知道怎么改

**Comment by cookieY** [comment]
设置页面
