### ISSUE TITLE
通过修改cookie可随意更改角色与登陆人

### ISSUE THREAD

**Issue by kailang-dev** [cookieY/Yearning#267]
![企业微信截图_15850468354813](https://user-images.githubusercontent.com/54127034/77420784-9b713180-6e05-11ea-8ed9-5ecdeaf3d820.png)
![企业微信截图_15850472218552](https://user-images.githubusercontent.com/54127034/77420795-a1671280-6e05-11ea-8ad8-51a9edc5ae8f.png)
![企业微信截图_15850478265313](https://user-images.githubusercontent.com/54127034/77420805-a6c45d00-6e05-11ea-9269-bf391e59a959.png)
如图所示，只需要修改对应的username、admin、access即可登录查看他人的账号，并拥有他人账号的权限，甚至可以更改自己账号的权限。建议在接口校验时，同时校验username和jwt中包含的人物角色信息

**Comment by cookieY** [comment]
@kailang-dev 这是1.x的版本,确实存在这个问题。建议切换至2.0版本，1.0版本已不再维护
详情请查阅 https://guide.yearning.io/different.html
