### ISSUE TITLE
alter操作engine变更不会采用pt-osc

### ISSUE THREAD

**Issue by feidududexigua** [cookieY/Yearning#268]
Version 版本:
2.2.0

Describe 问题描述
使用yearning做表变更（打开osc设置为on），表数据在300万，表引擎为MyISAM
alter table t engine=innodb;
在数据库中发现yearning并没有采用pt-osc来进行表变更

同样的配置，我回退到2.1.9版本后就可以正常使用pt-osc来变更了

Expected 预期
希望2.2.0点表引擎变更也能通过pt-osc来变更

**Comment by cookieY** [comment]
@feidududexigua 该问题将在随后的版本修复~

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/edit/v2.2.0
