### ISSUE TITLE
在提交SQL时可否选择多个审批人

### ISSUE THREAD

**Issue by feidududexigua** [cookieY/Yearning#269]
目前2.2.0版本在权限设计里上级审核人是可以设置为多位，那工单提交时是否也可以选这些审核人中的一位或者多位，如果其中一位没时间审核，可以让另一位审核工单；

**Comment by cookieY** [comment]
非常感谢你的建议。yearning会在后续版本持续优化

**Comment by xdstack** [comment]
需要这个功能，期待更新。

**Comment by xdstack** [comment]
或者允许超级管理员可以查看所有待审核的。
