### ISSUE TITLE
数据库+环境都已配置完成，连接成功，但是提交工单处无法勾选

### ISSUE THREAD

**Issue by geekyouth** [cookieY/Yearning#270]
![image](https://user-images.githubusercontent.com/12899262/77824846-7bf94200-7140-11ea-93a1-9dfceeadce49.png)
![image](https://user-images.githubusercontent.com/12899262/77824847-7e5b9c00-7140-11ea-9ede-90b949dac835.png)

如上图，在步骤 1、2 都已经配置好数据库，但是步骤3处，提交工单 DDL 下拉框没有出现已配好的数据库。
我部署的版本号：Yearning-2.1.9.linux-amd64.zip Centos7-x64 系统

**Comment by feidududexigua** [comment]
角色建了吗？对角色授予这个数据库的ddl变更权限了吗？对当前用户授予了这个角色权限了吗？
