### ISSUE TITLE
希望增加SQL查询页面缓存

### ISSUE THREAD

**Issue by sh-hanson** [cookieY/Yearning#273]
**Version 版本:**
2.1.9

**Describe 问题描述**
目前的场景是，开发主管角色，有两种操作很频繁：
1、审核下属提的SQL工单  
2、自己提SQL工单

这样就会在审核页面，与SQL查询页面之间频繁切换，然后SQL查询界面的语句，切换后就没有了。每次切回SQL界面，语句都要重新写一遍

**Expected 预期**
希望SQL查询页面增加缓存，或者通过多标签的方式打开

**Comment by cookieY** [comment]
SQL查询页面由于需要在挂载时检查当前用户状态信息 所以无法进行缓存
