### ISSUE TITLE
密码校验逻辑不合理

### ISSUE THREAD

**Issue by dzhyw** [cookieY/Yearning#274]
![image](https://user-images.githubusercontent.com/7122097/78095686-28ba1480-740a-11ea-9f19-15fcf60bc999.png)
这个有点不合理吧，密码还不让有@？

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/edit/v2.2.0

**Comment by shenshihala** [comment]
这个问题在最新的2.3.1中还没有修复吧，请问是后续版本也不会修改吗

**Comment by cookieY** [comment]
#416
