### ISSUE TITLE
查询结果能导出成xls文件吗，csv遇到问题

### ISSUE THREAD

**Issue by hubeixulu** [cookieY/Yearning#275]
问题是mysql查询出来的结果实际上只有2个字段，但是其中一个字段很长是用{ }括起来的字段，{ }里面又有逗号，所以导致导出来的csv文件被分割成6个字段

**Comment by hubeixulu** [comment]
问题是mysql查询出来的结果实际上只有2个字段，但是其中一个字段很长是用{ }括起来的字段，{ }里面又有逗号，所以导致导出来的csv文件被分割成6个字段

**Comment by cookieY** [comment]
目前暂时不支持导出成xls文件.
