### ISSUE TITLE
Cookie里有明文用户名和密码

### ISSUE THREAD

**Issue by falleafe** [cookieY/Yearning#278]
路径：/api/v2/dash/userinfo， /api/v2/fetch/test
version: Yearning/2.2.0 author: HenryYee
Cookie: session=eyJvcGVuLWZhbGNvbi1jayI6Imtlbm55OmJlNDIxOWQ4NWUwNDExZWE5ZGJlZmVmY2ZlMDcyZmNlIn0.Xl-F8Q.XMdhCsmyKKV8RWRPT8ZyARFJm8I; csrftoken=OBHyoYpbtL0L06e1iZQu5kfyjjT715RTxshxLmyVR31DCdQDMzzmTdZD9gq3O8F6; token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMDEsInVzZXJuYW1lIjoia2VubnkiLCJleHAiOjE1ODU5MDQxMzQsImVtYWlsIjoia2VubnlAc2luYS5jbiJ9.HnA5OoHAntiXRYc0Hwe5Eb-ybw2BRbgJo-ObFwruE8k; user=xxxx; password=xxxxx

**Comment by cookieY** [comment]
Yearning2.0 只在sessionStorage当中保存用户非敏感信息，并不会保存密码。 请告知详细实现步骤

**Comment by falleafe** [comment]
用的edge浏览器的问题，chrome没有问题
