### ISSUE TITLE
报数据库连接不上

### ISSUE THREAD

**Issue by nick2550123097** [cookieY/Yearning#279]
[root@izuf63os69edbeuwug1z3az Yearning-go]# netstat -pan|grep :3306
tcp6       0      0 :::3306                 :::*                    LISTEN      8754/mysqld
tcp6       0      0 127.0.0.1:3306          127.0.0.1:45178         TIME_WAIT   -
tcp6       0      0 127.0.0.1:3306          127.0.0.1:45180         TIME_WAIT   -
[root@izuf63os69edbeuwug1z3az Yearning-go]# ./Yearning -s -p 8000
无法连接数据库!

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/edit/v2.2.0
