### ISSUE TITLE
我吐槽一下，

### ISSUE THREAD

**Issue by qingduyu** [cookieY/Yearning#28]
代码审核，就返回1.或者2， 别人怎么知道错在哪里，这显然不人性化啊，好比你去政府办事，就和你说证件不够，缺啥都不告诉你，这用户体验简直了。
![_20180517091148](https://user-images.githubusercontent.com/10934057/40151408-60a98390-59b2-11e8-860c-bb07858968e4.png)

**Comment by cookieY** [comment]
为个例情况，升级UI库解决
