### ISSUE TITLE
Yearning -m 数据库初始化，提示数据库链接不了

### ISSUE THREAD

**Issue by tiandong19860806** [cookieY/Yearning#280]
OS环境: CentOS 7.4 X64
Yearning版本：Yearning/2.1.9

执行步骤，如下：
root >> ls -al ${YEARNING_HOME}
root >> cat ${YEARNING_HOME}/conf.toml
root >> ${YEARNING_HOME}/Yearning -m -c ${YEARNING_HOME}/conf.toml

错误提示，如下：
![图片](https://user-images.githubusercontent.com/12596666/78515022-d9e3f480-77e6-11ea-9cd0-5a2f19778720.png)

期望结果，如下：
希望执行-m初始化命令后，能够成功初始化数据库，并且通过如下命令可以启动Yearning
root >> ${YEARNING_HOME}/Yearning -s -c ${YEARNING_HOME}/conf.toml

**Comment by tiandong19860806** [comment]
尝试修改链接字符串中的账号/密码/HOST等都不包含特殊字符“-”或“."，测试发现，Yearning -m命令还是报错：提示无法连接数据库；但是实际上我在外面客户端是可以访问数据库的。

1. Yearning报错截图，如下
![图片](https://user-images.githubusercontent.com/12596666/78516138-1c0f3500-77eb-11ea-9713-e39751840fe6.png)

2. 相同数据库连接信息，使用客户端navicat 工具，却可以成功链接和访问，如下图：
![图片](https://user-images.githubusercontent.com/12596666/78516204-57a9ff00-77eb-11ea-9172-875461cf67e5.png)

**Comment by tiandong19860806** [comment]
Hi @cookieY，

         Could you kindly to check this issue.

Thanks.

**Comment by cookieY** [comment]
请不要使用中文标点

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/edit/v2.2.0

**Comment by tiandong19860806** [comment]
Hi @cookieY ,

      找到原因了，就是你的教材中没有说清楚，误以为数据库Yearning可以先创建。以下是本地调试的代码。建议更新一下教材文档，如下：

本地调试，截图
vscode 配置环境变量，如下
![图片](https://user-images.githubusercontent.com/12596666/79036854-d5f90d80-7bfe-11ea-9eea-3999e223f5c0.png)

代码调试报错，如下：
![图片](https://user-images.githubusercontent.com/12596666/79036860-e27d6600-7bfe-11ea-83e2-45c848537ca0.png)


**备注：**
https://guide.yearning.io/install.html 
章节“2.初始化数据结构”，

**更新内容，如下：**
**-m命令初始化，使用的yearning数据库一定不要创建，否则程序会错误判断为DB重复初始化**
请务必在-s启动前首先执行-m 初始化操作！
如要再次初始化，请先把yearning库下所有表删除，否则重复执行无效

**从而导致，使用-s命令启动程序，程序报错：targets server is empty**

**改善建议：**
Yearning代码，对于无表的数据，可以尝试直接使用空的DB，或者完善输出信息：
当Yearning数据库已经存在时候，判断是否有表，如果没有表则提示不要手动创建Yearning DB。

**Comment by tiandong19860806** [comment]
Hi @cookieY ，

      我上面检查有错误，刚才我重新删掉yearning数据库后，在重新创建一个同样配置和账号的yearning数据库，然后使用-m -c 命令初始化yearning系统。这次初始化成功了，没有提示任何错误。

谢谢

![图片](https://user-images.githubusercontent.com/12596666/79038941-26c53200-7c10-11ea-9944-71e25f31144e.png)
