### ISSUE TITLE
页面打不开报错

### ISSUE THREAD

**Issue by xiaodi8704** [cookieY/Yearning#283]
refused to execute script from http://ip:8000/js/chunk-vendors. d8accf9e because its MIME type ('text/x-js') is not executable, and strict MIME type checking is enabled
2.1.9版本
chrome 版本35

**Comment by cookieY** [comment]
现在chrome版本都80了

**Comment by xiaodi8704** [comment]
要求是要80版本么？我刚刚使用73版本仍然同一个错误

**Comment by xiaodi8704** [comment]
![15863952867630 6749873395694541](https://user-images.githubusercontent.com/63328761/78848184-a071db80-79d6-11ea-853e-9ae2c52ff1d2.jpg)

**Comment by xiaodi8704** [comment]
已经使用最新版本浏览器。仍然报上上述错误

**Comment by cookieY** [comment]
是否是使用nginx等其他web服务做了代理转发 

如果是  请检查MIME类型是否允许 text/x-js
