### ISSUE TITLE
Yearning -s 启动程序失败，数据库有初始化称成功，错误提示targets server is empty

### ISSUE THREAD

**Issue by tiandong19860806** [cookieY/Yearning#286]
Hi @cookieY ,

     我重新删掉yearning数据库后，在重新创建一个同样配置和账号的yearning数据库。
然后使用-m -c 命令初始化yearning系统。这次初始化成功了，没有提示任何错误，
但是为何使用-s -c命令，却无法正常启动？

**1. 检查，如下：**
![图片](https://user-images.githubusercontent.com/12596666/79039155-e49cf000-7c11-11ea-9efb-2603d7ea9a08.png)

数据库表，里面有表了，如下图
![图片](https://user-images.githubusercontent.com/12596666/79039159-ec5c9480-7c11-11ea-84f1-856ca77ee6ec.png)

**2.问题，如下：**
启动yearning系统命令，也报错：targets server is empty
![图片](https://user-images.githubusercontent.com/12596666/79039164-f8485680-7c11-11ea-9a31-71e5af2f7fe1.png)

**Comment by tiandong19860806** [comment]
Hi @cookieY ,
    是否是你教材中提到的conf.toml文件，配置参数不完整？

cat conf.toml
[Mysql]
Db = "Yearning"
Host = "127.0.0.1"
Port = "3306"
Password = "xxxx"
User = "root"

[General]   #数据库加解密key，只可更改一次。
SecretKey = "dbcjqheupqjsuwsm"

**Comment by cookieY** [comment]
文档都指的是使用编译好的二进制文件的使用教程。

错误仅返回信息 没有返回错误栈的调用链 无法定位错误
