### ISSUE TITLE
执行DML  juno返回参数无法匹配!

### ISSUE THREAD

**Issue by OhBonsai** [cookieY/Yearning#287]
感谢您做了这么棒的工具，最近准备将yearning1.0升级到2.0+。 我在使用期间遇到一些问题

## 版本
- Yearning版本为: 2.2.0 `commit 7e64e9e3bfdf772854a619f8f8c6447b16c1fb13 (tag: v2.2.0)`
- 系统版本为: `CentOS Linux release 7.5.1804 (Core) `

### 详细描述问题
**执行DML JUNO回格式错误**

#### 审核一个工单

![image](https://user-images.githubusercontent.com/18596879/79041501-fdfa6800-7c22-11ea-93a9-dffe7f0f6aa6.png)

#### 打印出执行的pb

```src/handle/audit.go:L219``` 增加日志```	fmt.Println("LibraAuditOrder pb: ", s.String())```

#### 返回参数无法匹配
```
LibraAuditOrder pb:  SQL:"INSERT  into  runoob_tbl  (runoob_title, runoob_author, submission_date) \nVALUES  \n  (\n    \"hello\", \"xx\", now()\n  )" DataBase:"spotmanager" Execute:true Backup:true source:<Addr:"127.0.0.1" User:"spot_audit" Password:"123456" Port:3306 > WorkId:"20200411103222230" 
参数无法匹配!
```

## 期待结果

我对比了[文档](https://guide.yearning.io/args.html)并没有发现格式不对的地方...

**Comment by cookieY** [comment]
@OhBonsai 少了一个传参IsDML   https://guide.yearning.io/args.html 可以在这里查看具体的调用必须传参。   建议使用编译好的二进制。

**Comment by OhBonsai** [comment]
因为公司内部用户管理有一套独立的体系， 没办法用ldap。需要修改登陆的逻辑。 
@cookieY  我改用了`proto.MarshalTextString()`来打印`IsDML`是存在的

```
grpc call is finish
staring call grpc!
==========================
SQL: "INSERT into runoob_tbl (runoob_title, runoob_author, submission_date) VALUES ( \"hello\", \"xx\", now() )\n"
DataBase: "spotmanager"
Execute: true
IsDML: true
Backup: true
source: <
  Addr: "127.0.0.1"
  User: "spot_audit"
  Password: "123456"
  Port: 3306
>
WorkId: "20200413033204815"
```

另外还有一个疑问： 当juno处理完order之后，是会直接修改数据库中的数据吗？

**Comment by cookieY** [comment]
很抱歉 最近一直没有时间处理相关的issues 这个问题我会在查看相关代码并定位后给予你答复
