### ISSUE TITLE
juno是什么

### ISSUE THREAD

**Issue by gmailzj** [cookieY/Yearning#288]
编译运行了Yearning , 页面跑起来了，但是查询时接口报错，transport: Error while dialing dial tcp 127.0.0.1:50001: connect: connection refused

看文档里面，安装，写的不依赖第三方， 迷惑了，

安装
注意事项
Yearning 不依赖于任何第三方SQL审核工具作为审核引擎,内部已自己实现审核/回滚相关逻辑。

仅依赖Mysql数据库。

注意
juno与Yearning 必须共用同一个数据库且共用同一份配置文件(如juno与Yearning不在同一台主机，则需拷贝一份cofnig.toml文件与juno放在同级目录。且Yearning项目内的config.toml文件中GrpcAddr配置项填写为juno所在主机的ip及端口)

由于当前juno仅只有linux版本,建议基于mac/windows平台开发的开发者使用docker启动juno。

**Comment by cookieY** [comment]
文档安装教程指的是使用已编译好的 二进制文件

请直接用二进制文件即可

如果要二开 请看文档二次开发页面

**Comment by SnowOnion** [comment]
我从 https://guide.yearning.io/developer.html 和 https://guide.yearning.io/args.html 确实也没找到 juno 是什么。

根据 https://github.com/cookieY/Yearning/issues/793#issuecomment-1519289285 ，我认为 juno 指的是：
https://hub.docker.com/r/yeelabs/juno/tags

**Comment by SnowOnion** [comment]
好的，在新文档里可以通过命令看出 juno 是啥了 https://next.yearning.io/zh/development/16e5vp2y/

建议在 GitBook 版旧文档，提示读者去新文档……
