### ISSUE TITLE
登录超时时间是否可以设置？

### ISSUE THREAD

**Issue by sh-hanson** [cookieY/Yearning#290]
Version 版本:
2.1.9

Describe 问题描述
目前登录超时时间具体不清楚是多少，就是登录空闲时间超过1个小时或者两个小时候，再次进入时又需要输入账号密码。正常开发上班时间早九~晚九，设置12小时超时，一天只需登录一次即可

Expected 预期
希望可以设置登录超时时间（比如空闲12小时后再进入则需要输入账号密码），或者直接加长超时时间

**Comment by lzw-steve** [comment]
老哥，这个可以设置吗？
