### ISSUE TITLE
DML工单检测有错误，仍然可以提交工单

### ISSUE THREAD

**Issue by sh-hanson** [cookieY/Yearning#292]
**Describe the bug**
**描述Bug**
DML工单中，update a set addr='xxx',name='xxx' where id=1;，如果这个语句name写成name1，就是字段不存在的情况下，提示：无法获得影响行数,字段不存在或该版本数据库不支持explain
然后“提交”按钮仍然可以点击，最后DBA执行时也是报错

**To Reproduce**
**如何复现**

**Expected behavior**
**期望的结果**
语句检测时有错误时，“提交”按钮置灰不可用，防止提交错误语句

**Screenshots**
**截图**

**Desktop (please complete the following information):**
**环境**

**Additional context**
**其他**

**Comment by cookieY** [comment]
2.2.1已修复
