### ISSUE TITLE
下载最新 release (2.2.0) 包会无法启动

### ISSUE THREAD

**Issue by frank780117** [cookieY/Yearning#293]
已经填写了 conf.toml (ip 帐号密码都有改), 但是怎么执行 Yearning 都会报错

Error 1045: Access denied for user ''@'localhost' (using password: NO)

![image](https://user-images.githubusercontent.com/7590449/79741743-54a72680-8334-11ea-89e2-70422c0ca12e.png)

**Comment by Yebolin** [comment]
情况一样，我上周测试的，排查了一下没发现问题，只好换到2.1.9就正常了。我是全新环境

**Comment by zhhx** [comment]
创建yearning数据库，然后执行 ./Yearning -m，就可以了

**Comment by cookieY** [comment]
报错很明显了  库都没创建 怎么初始化？
