### ISSUE TITLE
Yearning 配置文件配置了数据库端口之后，无法生效

### ISSUE THREAD

**Issue by skymoou** [cookieY/Yearning#296]
**Describe the bug**
**描述Bug**
            在conf.toml里面配置了非3306端口后，无法初始化数据库
**To Reproduce**
**如何复现**
1. 修改conf.toml 里面的端口，改为非3306
2. 初始化数据库
3. See error

**Expected behavior**
**期望的结果**
  conf.toml 能够支持非3306端口

**Screenshots**
**截图**

**Desktop (please complete the following information):**
**环境**
 - OS: [e.g. Linux]

**Additional context**
**其他**

**Comment by cookieY** [comment]
没有此类Bug 请仔细检查自己的配置是否正确
