### ISSUE TITLE
修改了conf.toml Host 无法连接到数据库

### ISSUE THREAD

**Issue by CrasOu** [cookieY/Yearning#297]
**Describe the bug**
修改了conf.toml里的mysql host，使用./Yearning -m 提示dial tcp 127.0.0.1:3306: connect: connection refused

**To Reproduce**
**如何复现**
1、vi conf.toml
2、修改 mysql host
[Mysql]
Db = "Yearning"
Host = "172.16.100.62"
Port = "3306"
Password = "root!1"
User = "root"
3、./Yearning -m
提示dial tcp 127.0.0.1:3306: connect: connection refused

**Expected behavior**
**期望的结果**
进行数据库初始化

**Screenshots**
**截图**

**Desktop (please complete the following information):**
**环境**

**Additional context**
**其他**

**Comment by cookieY** [comment]
建数据库了么？
