### ISSUE TITLE
Bug Report：DML和DDL中无法匹配连接名，数据源已经创建

### ISSUE THREAD

**Issue by 1029649360** [cookieY/Yearning#301]
DML和DDL中无法匹配连接名，数据源已经创建
![image](https://user-images.githubusercontent.com/45092668/81164946-b7025700-8fc3-11ea-8191-a02374bbf58d.png)

![image](https://user-images.githubusercontent.com/45092668/81164967-bff32880-8fc3-11ea-8e86-c3c6a6527a31.png)

**Comment by cookieY** [comment]
https://guide.yearning.io/permission2.html

**Comment by 1029649360** [comment]
![image](https://user-images.githubusercontent.com/45092668/81165314-5de6f300-8fc4-11ea-8079-ea48ebaac9da.png)
