### ISSUE TITLE
前端有没有老哥优化一下。。。。

### ISSUE THREAD

**Issue by KU4NG** [cookieY/Yearning#302]
**截图**

![QQ截图20200508180552](https://user-images.githubusercontent.com/32036696/81396132-6a4f8500-9157-11ea-99da-404c83c38ea6.jpg)
![QQ截图20200508180505](https://user-images.githubusercontent.com/32036696/81396136-6b80b200-9157-11ea-8064-220c38e48231.jpg)

**Comment by cookieY** [comment]
只支持1080p以上分辨率
