### ISSUE TITLE
无法查找数据源，如图

### ISSUE THREAD

**Issue by techtqmall** [cookieY/Yearning#303]
无法查找数据源，如图
版本：Yearning/2.2.0
![image](https://hz-imile-static.oss-cn-hangzhou.aliyuncs.com/imile/111.png)

**Comment by techtqmall** [comment]
http://hz-imile-static.oss-cn-hangzhou.aliyuncs.com/imile/111.png

**Comment by cookieY** [comment]
https://guide.yearning.io/problem.html
