### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by DBA-Ray** [cookieY/Yearning#304]
**Describe the bug**
字符型数据中包含“'”导致生成的回滚语句无法执行。

**To Reproduce**
提交dml工单（表中字符型数据中包含“'”）；
生成的回滚语句中字符型数据中包含“'”导致生成的回滚语句无法执行。

**Expected behavior**
可以转义“'”,或者直接改成基于主键回滚。

**Screenshots**
回滚语句截图
![image](https://user-images.githubusercontent.com/42759187/81470724-eeb90b00-921e-11ea-9941-90ab031bd71a.png)

![image](https://user-images.githubusercontent.com/42759187/81470741-06908f00-921f-11ea-9bfd-e7fa3213e778.png)

**Desktop (please complete the following information):**
**环境**
 - OS: [centos7]
 - Browser [chrome]
 - Version [v2.2.1]

**Additional context**
**其他**

**Comment by cookieY** [comment]
@DBA-Ray 请给出测试 表结构语句及测试语句 谢谢

**Comment by cookieY** [comment]
新版增加以主键回滚开关
