### ISSUE TITLE
yearning2.0执行SQL是会锁表而1.0不会 请问是哪里设置的问题吗

### ISSUE THREAD

**Issue by why2mf** [cookieY/Yearning#305]
yearning2.0执行SQL是会锁表而1.0不会 请问是哪里设置的问题吗

**Comment by cookieY** [comment]
DDL 走OSC

**Comment by why2mf** [comment]
就是配置了OSC才会出现这样的

**Comment by cookieY** [comment]
检查 是否打开osc开关  是否表体积大于最低osc启用大小

Yearning只是通过exec调用 osc,锁不锁表与Yearning自身是无关的。
