### ISSUE TITLE
可不可以加一个中止sql的功能

### ISSUE THREAD

**Issue by geercode** [cookieY/Yearning#306]
有时候一些查询语句写错了，或者优化得不太好，执行了会影响到生产数据库，能否添加一个中止sql的功能，防止误操作无法停止，影响到生产数据库，比如加索引，比如虚表过大，临时文件撑爆之类的事情

**Comment by cookieY** [comment]
生产环境的数据应读写分离。  开发查询的读库应该与生产环境隔离。
