### ISSUE TITLE
添加sql必须刷新页面才可以再次添加和命令模式下版本没变

### ISSUE THREAD

**Issue by stevenliuit** [cookieY/Yearning#310]
**Describe the bug**
**描述Bug**
![image](https://user-images.githubusercontent.com/4044994/82316227-11a5a500-99ff-11ea-8ef9-d143819fb9ed.png)
升级了2.2.1还是显示2.2.0
**To Reproduce**
**如何复现**

**Expected behavior**
**期望的结果**

**Screenshots**
**截图**

**Desktop (please complete the following information):**
**环境**

**Additional context**
**其他**

**Comment by cookieY** [comment]
没有描述清楚的问题
