### ISSUE TITLE
点击全选按钮无效

### ISSUE THREAD

**Issue by dongqianzheng** [cookieY/Yearning#314]
**描述Bug**
权限组-数据库查询权限-连接名-全选，这个全选按钮点击没有反应，没有选择所有的连接名。

**如何复现**
点击截图的全选按钮。

**期望的结果**
全选所有的连接名。

**Screenshots**
**截图**
![image](https://user-images.githubusercontent.com/26294657/83390192-02bdea00-a424-11ea-9c6c-28245dc6e8c1.png)

**环境**
 - Version ：v2.2.1

**Comment by cookieY** [comment]
这个要多按一下才行 - -
