### ISSUE TITLE
本应脱敏的字段可以被绕过实现明文查寻

### ISSUE THREAD

**Issue by lougon** [cookieY/Yearning#315]
**本应脱敏的字段可以被绕过实现明文查寻**

**如何复现**
1. 添加脱密字段id_card_number
2. 查寻,语法为select CONCAT('',id_card_number) AS test_id_card_number from *****

**Comment by cookieY** [comment]
暂时脱敏无法避免通过函数逃避监测的方式

**Comment by wzshuang** [comment]
2022年8月9日 19:39:06
有办法修复吗

**Comment by cookieY** [comment]
现在已经可以规避了

**Comment by wzshuang** [comment]
`select concat(pwd) as abc from user limit 10;`
刚试了这种写法可以绕过

**Comment by wzshuang** [comment]
版本：3.0.5
字段名：pwd
脱敏字段：pwd、Pwd
`select pwd from user` 可以脱敏
`select Pwd from user` 可以脱敏
`select pwd as abc from user` 可以脱敏
`select Pwd as abc from user` 可以脱敏
`select concat(pwd) from user` 可以脱敏
`select concat(Pwd) from user` 可以脱敏
`select concat(pwd) as abc from user` 脱敏失败
`select concat(Pwd) as abc from user` 脱敏失败

**Comment by cookieY** [comment]
3.0.6 将会修复 as 逃逸问题
