### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by kebyn** [cookieY/Yearning#317]
Yearning v2.2.1版本
表名为`config`时无法直接查询
```
select * from config
```
需要加上库名才可以查询
```
select * from database.config
```
测试的错误日志是
```
Yearning_error: 2020/06/05 14:05:45.874185 /go/Yearning/src/lib/fetchJuno.go:81: could not connect: rpc error: code = Unknown desc = line 1 column 20 near "config"
```

**Comment by cookieY** [comment]
没有选择库名无法获得库名自然必须要加库名了。

查询时点击旁边的库名 展开后才能获得库名

**Comment by kebyn** [comment]
已经选择库名了

**Comment by kebyn** [comment]
换其它表名是可以直接查询的

**Comment by kebyn** [comment]
@cookieY 在浏览器Request里可以看到库名已经选择了的，换其它表名是可以正常查询的
![image](https://user-images.githubusercontent.com/9145323/84459019-fc880300-ac98-11ea-8d58-568d51b5dd59.png)
