### ISSUE TITLE
可否考虑放宽dml数量限制，目前单次提交上限10行，无法应对批量场景需求

### ISSUE THREAD

**Issue by zerostarfro** [cookieY/Yearning#320]
如图
![image](https://user-images.githubusercontent.com/6415275/84135989-409ebc00-aa7d-11ea-833a-bb9ae72f3bbc.png)

**Comment by cookieY** [comment]
审核规则自行设置

**Comment by zerostarfro** [comment]
请问是哪个设置项呢~ 貌似并没看到dml上限行数设置项
![image](https://user-images.githubusercontent.com/6415275/84136791-5cef2880-aa7e-11ea-9fb3-4e5d3f6dcef3.png)

**Comment by cookieY** [comment]
@zerostarfro Insert语句字段上限
