### ISSUE TITLE
Juno服务调用报错

### ISSUE THREAD

**Issue by hetiansu5** [cookieY/Yearning#322]
版本：Yearning v2.2.1
docker image:golang:1.13-buster

部署的juno服务，GRPC调用会如下报错：

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x8ab9a6]

goroutine 26 [running]:
github.com/jinzhu/gorm.(*DB).Close(0x0, 0x40, 0x149aa88)
	/var/jenkins_home/go/pkg/mod/github.com/jinzhu/gorm@v1.9.12/main.go:118 +0x26
Juno/libraGrpc/server.(*Ser).OrderDeal.func1(0xc00022f540)
	/var/jenkins_home/workspace/Juno/libraGrpc/server/server.go:182 +0x33
Juno/libraGrpc/server.(*Ser).OrderDeal(0x2651bb0, 0x1622940, 0xc0003af7d0, 0xc000286a20, 0xc0001e10c0, 0x0, 0x0)
	/var/jenkins_home/workspace/Juno/libraGrpc/server/server.go:203 +0x35b
Juno/libraGrpc/proto._Juno_OrderDeal_Handler(0x12e38e0, 0x2651bb0, 0x1622940, 0xc0003af7d0, 0xc000083da0, 0x0, 0x1622940, 0xc0003af7d0, 0xc000288780, 0x4c)
	/var/jenkins_home/workspace/Juno/libraGrpc/proto/detection.pb.go:618 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001980, 0x1635060, 0xc000001b00, 0xc0001dee00, 0xc0003af500, 0x25eece0, 0x0, 0x0, 0x0)
	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1007 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc000001980, 0x1635060, 0xc000001b00, 0xc0001dee00, 0x0)
	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1287 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000041e90, 0xc000001980, 0x1635060, 0xc000001b00, 0xc0001dee00)
	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:722 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:720 +0xa1

**Comment by cookieY** [comment]
https://guide.yearning.io/args.html
