### ISSUE TITLE
Yearning 不支持 nginx反向代理设置访问路径吗？

### ISSUE THREAD

**Issue by ericheroster** [cookieY/Yearning#325]
因服务器只对外开放了80端口,故nginx里面配置了反向代理到Yearning

 location /Yearning/ {
                proxy_pass http://127.0.0.1:8000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header X-Real-IP $remote_addr;
        }

启动也无错误，但是打开首页 http://192.168.XX.XX/Yearning/，浏览器显示 {"message":"Not Found"}

**Comment by cookieY** [comment]
动静分离会导致这样的情况  建议使用虚拟主机进行配置
