### ISSUE TITLE
SQL查询界面，点击选择数据库时，点击数据源名称也会被当作数据库

### ISSUE THREAD

**Issue by amnesia01** [cookieY/Yearning#326]
SQL查询界面，点击选择数据库时，点击数据源名称也会被当作数据库，希望可以去掉
<img width="873" alt="img" src="https://user-images.githubusercontent.com/26243454/84984186-ed0f2b00-b16c-11ea-90c4-06e819ccd5b1.png">

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v2.2.2
