### ISSUE TITLE
Yearning可否考虑增加会话过期时间设置

### ISSUE THREAD

**Issue by zerostarfro** [cookieY/Yearning#327]
Yearning可否考虑增加会话过期时间设置，现在好像是默认一个小时就失效了，每次都要强制输入新密码，在具体的使用场景下有点严苛且缺乏灵活性了，建议做成可调整的，希望作者可以看到。

**Comment by cookieY** [comment]
现在默认是4个小时.个人感觉是够用的哈. sponsor版本已经可配置啦

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v2.2.2
