### ISSUE TITLE
hello，我想请教下Yearning编译脚本

### ISSUE THREAD

**Issue by haoxz11** [cookieY/Yearning#328]
hello，我git clone下源代码发现go build，编译后的应用与您打包出来的并不一样？比如应用日志是YEE 0.0.1 标记，而使用release的版本为YEARNING,并且编译出来的应用好像启动服务并不可用T_T，请问编译脚本有特殊配置么？

**Comment by haoxz11** [comment]
没看到前面的issue，不好意思

**Comment by zhenglin305** [comment]
求问一下你的编译脚本，现在需要把推送钉钉消息改为推送企微消息，编译后查询数据会报rpc错误
