### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by 20has** [cookieY/Yearning#332]
**Describe the bug** **描述Bug**
下载Yearning-2.2.0.linux-amd64.zip后 ./Yearning -s可以正常启动
但是页面端老是提示 验证码不对

**To Reproduce** **如何复现**
操作步骤：
#安装yum源
wget http://repo.mysql.com/mysql57-community-release-el7.rpm
rpm -ivh mysql57-community-release-el7.rpm

#安装最新版本mysql5.7 
yum -y install  mysql-server  mysql-devel mysql
##安装mysql，一直输入y回车即可，最后出现Complete! 说明安装完成了

#开机启动服务
systemctl enable --now mysqld

#获取初始密码
[root@lxc-centos7 ~]# grep 'password' /var/log/mysqld.log
2020-06-03T13:15:33.887644Z 1 [Note] A temporary password is generated for root@localhost: >x-u&r/sm6Mh

#登录
mysql -uroot -p'>x-u&r/sm6Mh'

#降低密码安全强度检查
set global validate_password_policy=0;
set global validate_password_length=4;

#设置本地密码为简单数字 123456
set password=password('123456');

#下载Yearning v2.2.0 release
wget https://github.com/cookieY/Yearning/releases/download/v2.2.0/Yearning-2.2.0.linux-amd64.zip
unzip Yearning-2.2.0.linux-amd64.zip
cd Yearning-go

#修改配置文件
[root@lxc-centos7 Yearning-go]# cat conf.toml
[Mysql]
Db = "Yearning"
Host = "localhost"
Port = "3306"
User = "root"
Password = "123456"
[General]
SecretKey = "TesTqheupqjsuwqq"

#创建依赖的数据库
mysql> create database Yearning default character set utf8mb4 collate utf8mb4_unicode_ci;
Query OK, 1 row affected (0.00 sec)

#初始化数据结构
[root@lxc-centos7 Yearning-go]# ./Yearning -m
......
初始化成功!
用户名: admin
密码:Yearning_admi

#启动服务
./Yearning -s

然后火狐\谷歌浏览器登录
**Expected behavior** **期望的结果**
**Screenshots** **截图**
https://sm.ms/image/H9NzK1qjRyi7pGw

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
2.2.0版本验证码 大小写敏感
