### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by 101github** [cookieY/Yearning#333]
**Describe the bug** **描述Bug**
当使用yearning启动服务时错误,使用的是v2.2.1版本，具体操作如下
```
$#./Yearning -b 10.50.133.168 -p 80 -c ./conf.toml 
dial tcp 127.0.0.1:3306: connect: connection refused
```
我看我的数据库是可以对外提供访问的，而且我的配置文件如下
```
#$:/tmp/tmp#cat conf.toml 
[Mysql]
Db = "Yearning"
Host = "10.50.133.169"
Port = "3306"
Password = "123456"
User = "yearning"

[General]
SecretKey = "dbcjqheupqjsuwsv"
```

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
1.数据库建了么？
2.配置填对了么？

**Comment by leesonwei** [comment]
我按照你的文档一步步来的. 启动要指定配置文件吗?可以自动获取吗?配置文件已经设置成root/root. 提示的user名是空的.这个我要怎么处理?
