### ISSUE TITLE
Error 1045: Access denied for user ''@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by leesonwei** [cookieY/Yearning#335]
**Describe the bug** **描述Bug**

配置好mysql配置后,执行./Yearning -m/-s都会出现Error 1045: Access denied for user ''@'localhost' (using password: NO)

**To Reproduce** **如何复现**

配置好mysql配置后,执行./Yearning -m/-s都会出现Error 1045: Access denied for user ''@'localhost' (using password: NO)

**Expected behavior** **期望的结果**

正确获取配置文件中的User配置

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
@leesonwei #333
