### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ColaTasty** [cookieY/Yearning#337]
**描述Bug**
- 添加数据库错误（图片右上角提示）
![image](https://user-images.githubusercontent.com/31401450/86102834-9996c880-baee-11ea-852d-4c3bebdc58c5.png)

- 开发者工具截图
![image](https://user-images.githubusercontent.com/31401450/86103066-e11d5480-baee-11ea-94e4-fcf1b069ea6d.png)

**如何复现**
2.2.2beta中添加数据库的bug

**期望的结果**
希望成功添加数据库

**环境**
- 系统 windows10
- 浏览器 chrome
- 运行环境 ubuntu18
- 虚拟机 vbox

**Comment by cookieY** [comment]
@ColaTasty 提供后台日志

**Comment by ColaTasty** [comment]
> @ColaTasty 提供后台日志

打扰了，AES的长度不够，现已解决
