### ISSUE TITLE
2.2.1版本驳回的工单不能修改

### ISSUE THREAD

**Issue by 203HAHA** [cookieY/Yearning#338]
![image](https://user-images.githubusercontent.com/48740082/86193094-aca4a980-bb7d-11ea-85f7-e7bcb198e71b.png)
点击工单信息,
![image](https://user-images.githubusercontent.com/48740082/86193313-2dfc3c00-bb7e-11ea-9d52-3bf364dfd2dd.png)
无法修改驳回的工单.

**Comment by cookieY** [comment]
@203HAHA 已发现这个问题,重新开放在驳回状态下的 显示执行信息按钮 点击后可以重新提交
