### ISSUE TITLE
依照文档进行Yearning初始化时，并没有读取conf.toml文件

### ISSUE THREAD

**Issue by Mxinhu** [cookieY/Yearning#339]
**Describe the bug** **描述Bug**

版本：Yearning-2.2.2-4kstars.linux-amd64.zip

依照文档修改配置文件后，进行下一步启动，并没有加载到配置文件

[root@yearning Yearning-go]# ./Yearning -m
dial tcp 127.0.0.1:3306: connect: connection refused
[root@yearning Yearning-go]# ls
conf.toml  dist  # README  Yearning

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/50960351/86217526-2d7d9880-bbb2-11ea-8e5a-92b9445570ae.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
不建数据库？

**Comment by Mxinhu** [comment]
配置文件内的数据库链接并没有读到，数据库和服务器是分离的，当启动程序的时候，默认找127.0.0.1了，使用参数指定配置文件也不行

**Comment by cookieY** [comment]
不建数据库？

**Comment by Mxinhu** [comment]
在本地创建数据库吗

**Comment by Mxinhu** [comment]
就是在服务器上部署MySQL

**Comment by cookieY** [comment]
我说的是database 不是source

**Comment by Mxinhu** [comment]
![image](https://user-images.githubusercontent.com/50960351/86223709-76d1e600-bbba-11ea-9cd8-7ff5dd779967.png)

**Comment by cookieY** [comment]
请仔细检查 配置是否有误

**Comment by Mxinhu** [comment]
![image](https://user-images.githubusercontent.com/50960351/86223960-cf08e800-bbba-11ea-88f2-dfacc4bf6f79.png)

**Comment by Mxinhu** [comment]
没有使用docker进行部署
