### ISSUE TITLE
审核时查看工单的SQL语句的换行问题

### ISSUE THREAD

**Issue by Ethan30k** [cookieY/Yearning#340]
**Describe the bug** **描述Bug**
1、管理员审核工单时，包括看自己的工单信息SQL语句时，工单里的SQL是没有换行的，如果是一个建表语句或很长的SQL，就很杂乱

**To Reproduce** **如何复现**
1、提交一个很长的SQL的工单，查看工单SQL详情就能看到

**Expected behavior** **期望的结果**
1、能够创建工单时SQL什么格式，审核时看到的就是什么格式

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**
 - OS: win7
 - Browser chrome
 - Version 2.2.1

**Additional context** **其他**

**Comment by cookieY** [comment]
此优化为赞助版本优化内容 普通版本并没有设置
