### ISSUE TITLE
工单审核的地方可否加一列,显示库名?

### ISSUE THREAD

**Issue by gs80140** [cookieY/Yearning#341]
**Describe the bug** **描述Bug**
工单审核的地方可否加一列,显示库名?
多个库同时加字段不方便统一操作
每个库要加一遍, 另外审核也看不出来库名,容易弄错

**To Reproduce** **如何复现**

工单审核的地方可否加一列,显示库名?

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
#210
