### ISSUE TITLE
Juno不实时读取数据库中的yearning配置

### ISSUE THREAD

**Issue by SgtDaJim** [cookieY/Yearning#344]
在操作`脱敏字段`时，修改保存后，下次查询时依然没有更新脱敏的字段。在重启Juno后，更新的配置才有效。因为Juno的不开源，所以大致猜测是Juno不会实时读取数据库所造成的。

**Comment by colynn** [comment]
你使用的最新版本的 juno 吗，维护者不是增加实时加载的配置的功能吗？ [->代码链接](https://github.com/cookieY/Yearning/blob/2af94a9cea4e05a325cddf7e019d4a544cec0fc0/src/lib/fetchJuno.go#L174)
