### ISSUE TITLE
[bug] 添加数据库异常

### ISSUE THREAD

**Issue by qianggetaba** [cookieY/Yearning#350]
【环境】
一台vmware虚拟机，nat网络，安装mysql与yearning
从物理机host访问虚拟机web
添加了一个自定义环境名称，保存了
添加数据库，测试连接成功，点击确定，500，Internal Server Error

![image](https://user-images.githubusercontent.com/15232892/88157327-31df2380-cc3d-11ea-8399-a94d64404e5c.png)
![image](https://user-images.githubusercontent.com/15232892/88157384-47ece400-cc3d-11ea-8ed3-026b9302ae90.png)

**Comment by xfengfeng** [comment]
我也遇到同样的问题，mysql 8.0
Yearning版本：Yearning-2.2.2-4kstars.linux-amd64-patch-1.zip
非docker运行

报错信息：
`yee v0.1.2 [Warn] 2020-07-28 10:02:14 "url":"/api/v2/management_db" "method":"POST" "status":500 "protocol":"HTTP/1.1" "remote_ip":"xxxxxx" "bytes_in": "125 bytes" "bytes_out": "5 bytes"`

**Comment by xfengfeng** [comment]
> 我也遇到同样的问题，mysql 8.0
> Yearning版本：Yearning-2.2.2-4kstars.linux-amd64-patch-1.zip
> 非docker运行
> 
> 报错信息：
> `yee v0.1.2 [Warn] 2020-07-28 10:02:14 "url":"/api/v2/management_db" "method":"POST" "status":500 "protocol":"HTTP/1.1" "remote_ip":"xxxxxx" "bytes_in": "125 bytes" "bytes_out": "5 bytes"`

已经解决：
安装了一个旧版本(2.2.0)就能看到明显报错：AES秘钥必须为16位！
2.2.2版本只报500，没有出现明显报错信息。

conf.toml配置文件里的SecretKey值要有16位。
