### ISSUE TITLE
构建镜像提示 “No such file or directory”

### ISSUE THREAD

**Issue by Megatron7-code** [cookieY/Yearning#351]
在构建镜像的时候提示：
WARNING: Ignoring http://mirrors.ustc.edu.cn/alpine/v3.1.2/main/x86_64/APKINDEX.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  libc6-compat (missing):
    required by: world[libc6-compat]
  tzdata (missing):
    required by: world[tzdata]
ERROR: Service 'yearning' failed to build: The command '/bin/sh -c echo "http://mirrors.ustc.edu.cn/alpine/v3.1.2/main/" > /etc/apk/repositories &&       apk add --no-cache tzdata libc6-compat &&       ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&       echo "Asia/Shanghai" >> /etc/timezone &&       echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf' returned a non-zero code: 2

顺着地址去到镜像站点，发现没有v3.1.2这个版本，改成v3.12完美跑起来了

不知道是这个版本被撤了，还是Dockerfile里写错了~

**Comment by cookieY** [comment]
新的2.2.2版本已经将3.1.2改成3.12了

**Comment by Megatron7-code** [comment]
我下的是 Yearning-2.2.2-4kstars.linux-amd64-patch-1.zip

里面的 Dockerfile 应该还是忘改了，

![image](https://user-images.githubusercontent.com/10461791/89365076-78855100-d706-11ea-95f2-04b07c703aa6.png)
@cookieY

**Comment by cookieY** [comment]
好的 感谢提醒 跟随下个版本修复

**Comment by Megatron7-code** [comment]
还有个疑惑在，为什么 Docker 相关的文件不放在 git master 分支上，放在了 releases 里的 zip 包里。

**Comment by Megatron7-code** [comment]
@cookieY 

docker-compose.yml 中的 yearning 服务中最好加一句

```yml
depends_on:
      - mysql
```

不然很有可能 yearning 率先启动，导致找不到数据库直接挂掉。

由 'yearning_1  | mysql连接失败! 亲 数据库建了没？ 配置填对了没？' 报错带来的思考
