### ISSUE TITLE
Yearning v2.2.2版本新增数据库报500错误

### ISSUE THREAD

**Issue by hzmiaoda** [cookieY/Yearning#353]
登录Yearning--"管理"--“数据库”，测试成功后，点击新增，报500错误
浏览器错误信息
vue-router.esm.js:2089 Uncaught (in promise) tmessage: "Navigating to current location ("/my_order") is not allowed"name: "NavigationDuplicated"_name: "NavigationDuplicated"stack: "Error↵    at new t (http://flysql.fuliaoyi.com/front/assets/js/chunk-vendors.d82201d8.js:17:17390)↵    at t.He.confirmTransition (http://flysql.fuliaoyi.com/front/assets/js/chunk-vendors.d82201d8.js:17:19699)↵    at t.He.transitionTo (http://flysql.fuliaoyi.com/front/assets/js/chunk-vendors.d82201d8.js:17:19156)↵    at t.push (http://flysql.fuliaoyi.com/front/assets/js/chunk-vendors.d82201d8.js:17:22219)↵    at http://flysql.fuliaoyi.com/front/assets/js/chunk-vendors.d82201d8.js:17:25801↵    at new Promise (<anonymous>)↵    at ft.push (http://flysql.fuliaoyi.com/front/assets/js/chunk-vendors.d82201d8.js:17:25764)↵    at Object.openPage (http://flysql.fuliaoyi.com/front/assets/js/app.6346c43f.js:1:23880)↵    at a.currentPageTab (http://flysql.fuliaoyi.com/front/assets/js/app.6346c43f.js:1:25794)↵    at it (http://flysql.fuliaoyi.com/front/assets/js/chunk-vendors.d82201d8.js:23:11780)"__proto__: Error
2/api/v2/management_db:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
3xhr.js:178 POST http://flysql.fuliaoyi.com/api/v2/management_db 500 (Internal Server Error)

**Comment by cookieY** [comment]
#350
