### ISSUE TITLE
执行DDL报错“exec: "pt-online-schema-change": executable file not found in $PATH”

### ISSUE THREAD

**Issue by byronjxb** [cookieY/Yearning#356]
执行DDL sql（ALTER TABLE `aaa` modify column cover_name varchar(1000) DEFAULT NULL COMMENT 'aaa' ;）
报错：“exec: "pt-online-schema-change": executable file not found in $PATH”，请教下如何处理？
通过二进制按照yearning。

**Comment by byronjxb** [comment]
在审核设置里修改了路径，再次执行提示“osc执行失败 请检查相关设置是否正确/该表之前如进行过osc kill操作 请清除该表相关触发器及临时表等遗留数据”

**Comment by cookieY** [comment]
请根据实际情况填写相关pt-osc的设置。设置参数填写不正确将无法使用pt-osc

**Comment by byronjxb** [comment]
![image](https://user-images.githubusercontent.com/21222280/90462842-226bd100-e13c-11ea-9369-8b3808ad9f55.png)
这是目前的配置

**Comment by cookieY** [comment]
路径必须精确到 程序本身

**Comment by byronjxb** [comment]
![image](https://user-images.githubusercontent.com/21222280/90462990-82fb0e00-e13c-11ea-80bb-532803bb1bc5.png)
![image](https://user-images.githubusercontent.com/21222280/90462999-8a221c00-e13c-11ea-9195-6d6d5a984405.png)
这样吗？
