### ISSUE TITLE
项目组名称包含  /  则删除的时候提示Not Found

### ISSUE THREAD

**Issue by guoxiaod** [cookieY/Yearning#357]
**描述Bug**

删除同名的已经删除过的权限组失败，提示 Not Found

**如何复现**

1. 创建 项目组 “AB/C”
2. 删除项目组 “AB/C”
3. 提示Not Found

**期望的结果**
可以正常删除

**截图**

**Desktop (please complete the following information):** **环境**
 - OS: Mac
 - Browser: chrome
 - Version : 84

**Additional context** **其他**

删除项目组接口是按照名称来删除的，然后URL解析的时候把 / 当作分隔符了，建议按照 ID 来删除

**Comment by cookieY** [comment]
由于逻辑实现 无法使用ID进行删除。建议不要采取类似命名规则
