### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by jinyuxiaoqiang** [cookieY/Yearning#359]
前端页面显示问题：
管理员登录后，管理，设置，进阶设置中，  多级审核，查询审核，注册，查询导致，这些按钮无法点击。

**To Reproduce** **如何复现**
登录后就可以复现

**Expected behavior** **期望的结果**
能否操作

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/34361941/90627627-c34ab100-e24e-11ea-9cf6-16e8d3988372.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
分辨率必须为1080p 及以上哦
