### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ColinZou** [cookieY/Yearning#360]
**Describe the bug** **描述Bug**
工单审核通过时，报一个网关错误（一闪而过），然后工单一直处于“执行中”

**To Reproduce** **如何复现**
NGINX配置：
location / {
        if ($scheme != "https") {
            return 301 https://$host$request_uri;
        }
        root /opt/pkg/yearning/dist;
    }
    location /front/ {
      alias /opt/pkg/yearning/dist/;
    }
    location ~ ^(/api|/login|/fetch|/ldap) {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8100;
        proxy_pass_request_headers on;
    }

Yearning 2.2.2

数据库MariaDB 10.3

**Expected behavior** **期望的结果**

执行不报错

**Screenshots** **截图**
![yearning报错](https://user-images.githubusercontent.com/6029079/90960415-ecc83e80-e4d3-11ea-8d52-a16266750459.png)

**Desktop (please complete the following information):** **环境**
 - OS: Manjaro (Xfce 4.14)
 - Browser: Chromium
 - Version 84.0.4147.125

**Additional context** **其他**

**Comment by cookieY** [comment]
请提供后台日志信息

**Comment by ColinZou** [comment]
你好，我能够拿到的日志见附件。还有其它更详细的日志记录吗？
[yearning.log.gz](https://github.com/cookieY/Yearning/files/5122003/yearning.log.gz)

**Comment by cookieY** [comment]
请提供出问题时的日志信息。删除多余无用信息

**Comment by ColinZou** [comment]
日志里面并没有其它的输出，这个已经是完整的日志。我有没有办法输出更为详细的DEBUG日志。我后面通过更改帐号的办法解决了。
