### ISSUE TITLE
Bug Report: 导出csv格式，数据错位

### ISSUE THREAD

**Issue by loveyang2012** [cookieY/Yearning#361]
![image](https://user-images.githubusercontent.com/24237714/91001491-6b20ff80-e5fe-11ea-89af-02b931d5a1c8.png)
这应该是1列的，
正常的应该是这样：
![image](https://user-images.githubusercontent.com/24237714/91001523-84c24700-e5fe-11ea-97a5-263bb6b2fe54.png)

**Comment by cookieY** [comment]
csv 以逗号为分隔符

**Comment by loveyang2012** [comment]
> csv 以逗号为分隔符

能否提个需求，导出的时候，可以选择分割符逗号或者空格
