### ISSUE TITLE
建表时不能指定字符集

### ISSUE THREAD

**Issue by hzmiaoda** [cookieY/Yearning#362]
**Describe the bug** **描述Bug**
提交建表语句时，检查语句时提示如下：表 'core_test1' 禁止设置字符集!，为什么不能指定字符集

**Comment by cookieY** [comment]
请查看审核规则

**Comment by hzmiaoda** [comment]
好的，谢啦

**Comment by hzmiaoda** [comment]
你好，还有一个没找到，”设置“--“进阶设置”， 查询导出，这个在页面上没找到
