### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by jinyuxiaoqiang** [cookieY/Yearning#363]
**Describe the bug** **描述Bug**
查询中的快速提交，工单提交失败。

**To Reproduce** **如何复现**
查询后执行快速递交出现 Internal error

**Expected behavior** **期望的结果**
可以再查询页面进行快速提交。

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/34361941/91248106-71da7e80-e786-11ea-9981-301eaa834aae.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**
报错内容如下：
2020-08-26 10:25:13.717578 I | Yearning_error: 2020/08/26 10:25:13.717534 /var/jenkins_home/workspace/Yearning-go/src/lib/encrypt.go:104: 无法获得传入密码
^[[31myee v0.1.2 [Critical] 2020-08-26 10:25:13 (/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/runtime/panic.go:969) [PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference Traceback:
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/runtime/panic.go:212
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/runtime/panic.go:211
        /var/jenkins_home/go/pkg/mod/github.com/jinzhu/gorm@v1.9.12/main.go:848
        /var/jenkins_home/go/pkg/mod/github.com/jinzhu/gorm@v1.9.12/main.go:495
        /var/jenkins_home/workspace/Yearning-go/src/parser/fetchRemote.go:130
        /var/jenkins_home/workspace/Yearning-go/src/parser/lib.go:551
        /var/jenkins_home/workspace/Yearning-go/src/parser/ast.go:140
        /var/jenkins_home/workspace/Yearning-go/src/parser/parser.go:77
        /var/jenkins_home/workspace/Yearning-go/src/parser/parser.go:186
        /var/jenkins_home/workspace/Yearning-go/src/handle/sqlrefer.go:97
        /var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.2/context.go:101
        /var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.2/middleware/gzip.go:63
        /var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.2/context.go:101
        /var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.2/middleware/recovery.go:38
        /var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.2/context.go:101
        /var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.2/middleware/logger.go:57
        /var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.2/context.go:101
        /var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.2/yee.go:192
        /var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.2/yee.go:124
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/net/http/server.go:2808
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/net/http/server.go:1896
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/runtime/asm_amd64.s:1374

**Comment by cookieY** [comment]
#350

**Comment by jinyuxiaoqiang** [comment]
我遇到的报错跟上边的不是一个问题。
1.我的conf.toml 设置是16位。
2.我是可以正常添加保存数据库的。这是再执行快速提交的时候提示 /var/jenkins_home/workspace/Yearning-go/src/lib/encrypt.go:104: 无法获得传入密码
