### ISSUE TITLE
release包中的Dockerfile文件路径错误

### ISSUE THREAD

**Issue by terrellhu** [cookieY/Yearning#364]
RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.1.2/main/" > /etc/apk/repositories && \
      apk add --no-cache tzdata libc6-compat && \
      ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
      echo "Asia/Shanghai" >> /etc/timezone && \
      echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

http://mirrors.ustc.edu.cn/alpine/v3.1.2/这里应该是v3.12多了个点点

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v2.3.0
