### ISSUE TITLE
多条 ALTER 语句，相同表会被合并成一行执行，会重复执行

### ISSUE THREAD

**Issue by Best1s** [cookieY/Yearning#365]
**Describe the bug** **描述Bug**

多条 ALTER 语句，相同表会被合并成一行执行，重复执行

**To Reproduce** **如何复现**
ALTER 语句 修改相同表的不同字段，不使用 ALTER 语句合并 提交工单

**Expected behavior** **期望的结果**
必须要合并吗？

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/35737228/91706242-b3b55b80-ebb0-11ea-92e1-df05d093c511.png)
![image](https://user-images.githubusercontent.com/35737228/91706417-f24b1600-ebb0-11ea-98f9-615068a4d2d9.png)
![image](https://user-images.githubusercontent.com/35737228/91706697-4e159f00-ebb1-11ea-8625-b38308f42bff.png)
![image](https://user-images.githubusercontent.com/35737228/91706723-5a016100-ebb1-11ea-8dd9-cef194491ed3.png)

**Desktop (please complete the following information):** **环境**
 - OS:   CentOS Linux release 7.6.1810 (Core)
 - Browser chrome

**Additional context** **其他**

**Comment by cookieY** [comment]
此问题会在下个版本修复

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v2.3.0
