### ISSUE TITLE
Dockerfile  bug

### ISSUE THREAD

**Issue by montery8** [cookieY/Yearning#366]
WARNING: Ignoring http://mirrors.ustc.edu.cn/alpine/v3.1.2/main/x86_64/APKINDEX.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:

http://mirrors.ustc.edu.cn/alpine/v3.1.2/main/x86_64/APKINDEX.tar.gz   
404 Not Found

RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.1.2/main/
->change into
RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.12/main/

**Comment by bestseantt** [comment]
RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.12/main/" > /etc/apk/repositories

**Comment by liang2025** [comment]
@bestseantt The same problem!

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v2.3.0
