### ISSUE TITLE
查询页面进行快速提交，错误500 检查sql可以正常获取source，提交工单时source参数为空

### ISSUE THREAD

**Issue by jinyuxiaoqiang** [cookieY/Yearning#367]
**Describe the bug** **描述Bug**

https://github.com/cookieY/Yearning/issues/363#issue-685955071

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
很抱歉给你带来的困扰 该问题会在下个版本中修复

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v2.3.0
