### ISSUE TITLE
Inception的问题是否有修复计划

### ISSUE THREAD

**Issue by peterxiemin** [cookieY/Yearning#37]
在使用过程中遇到如：
inception中如TEXT/BLOB类型的列不支持NOT NULL、备份语句长度超过限制、变更字段类型时的默认值问题等问题，网上提供修改sql/sql_parse.cc的方案（没试是否有效），担心稳定性。请问官方是否有修复计划

**Comment by cookieY** [comment]
@peterxiemin Yearning 不负责任何inception相关的工作。 如有inception问题请到inception repo下提交
