### ISSUE TITLE
企业微信webhook机器人 无法发送消息

### ISSUE THREAD

**Issue by qq290070744** [cookieY/Yearning#370]
**Describe the bug** **描述Bug**
企业微信webhook 无法发送消息

![image](https://user-images.githubusercontent.com/18340634/92296163-3b5dea00-ef64-11ea-83f5-7b2f9864b3aa.png)
看了企业微信机器人的配置文档，把上图这行代码截图里面的 text 修改成 content 就可以正常发消息

![image](https://user-images.githubusercontent.com/18340634/92296280-abb93b00-ef65-11ea-9326-0e227931368f.png)

**Comment by zhenglin305** [comment]
请问是在哪个文件改？我现在也需要从钉钉报警切换到企业微信

**Comment by qq290070744** [comment]
src\lib\sendMail.go
