### ISSUE TITLE
2.2.2升级2.3.0后admin管理员的管理模块丢失

### ISSUE THREAD

**Issue by carlden** [cookieY/Yearning#371]
版本：2.3.0-rc2
![image](https://user-images.githubusercontent.com/22387976/92697505-ff6cbf80-f37d-11ea-9a97-e0be7faf40c0.png)

**Comment by cookieY** [comment]
启动前使用-k 命令修复下

**Comment by carlden** [comment]
> 启动前使用-k 命令修复下

按照这个个操作之后出现了另一个问题，在提交工单下，当在选择连接名时后台有报错
![image](https://user-images.githubusercontent.com/22387976/92883601-9b143380-f443-11ea-8942-3586e6669d89.png)
报错信息：
![image](https://user-images.githubusercontent.com/22387976/92883890-e595b000-f443-11ea-99b9-d2adecc1aed5.png)

**Comment by cookieY** [comment]
#350

**Comment by carlden** [comment]
> #350

找到问题所在了，在2.2.2中，core_accounts表里，admin的rule字段为admin，但是在2.3.0中，这个字段的值必须要是super
