### ISSUE TITLE
工单详情里，只有当前操作人才能看到 SQL 内容，是设计如此还是 BUG？

### ISSUE THREAD

**Issue by Vinnk-Frozen** [cookieY/Yearning#373]
举例：
用户 A 发起的工单，最后用户 B 执行了工单，但用户 A 却看不到工单详情里的 SQL 信息了，只有 B 能看到。

期望：
在“工单记录”模块里，任何人都应该能看到 SQL 的详情。

**Comment by cookieY** [comment]
请提供版本号信息 以及截图描述信息

**Comment by xuexue1208** [comment]
> 请提供版本号信息以及截图描述信息
Yearning版本信息2.3.0 ，提交人 提交 DDL 工单后，在本账号的我的工单中，就看不到对应的 sql 详情啦
![image](https://user-images.githubusercontent.com/45139245/93567105-b7bee700-f9c0-11ea-9eac-0a41bcb98394.png)

执行人可以看到对应的详情，如下图
![image](https://user-images.githubusercontent.com/45139245/93567277-fce31900-f9c0-11ea-98b2-c0b6c1a5a465.png)

**Comment by Vinnk-Frozen** [comment]
**版本号：**v2.3.0-RC2
**截图：**
![image](https://user-images.githubusercontent.com/71375554/93570880-408c5180-f9c6-11ea-8259-ae592b9be022.png)
![image](https://user-images.githubusercontent.com/71375554/93570893-44b86f00-f9c6-11ea-8fb9-20b959c5546d.png)

**Comment by cookieY** [comment]
下载使用rc3试试

**Comment by xuexue1208** [comment]
这个问题我解决啦，如果是自行编译运行的，修改 profile.vue的 <template v-if="order.assigned ===user">即可
![image](https://user-images.githubusercontent.com/45139245/93587019-cbc41200-f9db-11ea-9024-0b686cc0e693.png)

**Comment by Vinnk-Frozen** [comment]
谢谢楼上，但我不是自行编译运行的，Yearning-2.3.0-RC3-path1-linux-amd64 这个版本也不行。
