### ISSUE TITLE
在Windows上通过源码运行前后端，部分菜单获取失败

### ISSUE THREAD

**Issue by chimisu** [cookieY/Yearning#374]
**Describe the bug** **描述Bug**

在Windows上通过源码运行前后端，部分菜单获取失败

**To Reproduce** **如何复现**

在Windows上克隆前后端源码，运行。

**Expected behavior** **期望的结果**

页面菜单正常显示

**Screenshots** **截图**

![image](https://user-images.githubusercontent.com/12495369/93428797-a909fe80-f8f2-11ea-87ff-9547fa1bc454.png)
![image](https://user-images.githubusercontent.com/12495369/93428823-b6bf8400-f8f2-11ea-86b9-18ecfb6f9c38.png)

**Desktop (please complete the following information):** **环境**
 - OS: Windows
 - Browser chrome

**Additional context** **其他**

**Comment by chimisu** [comment]
我搜了后端的源码，找不到initMenu相关的代码

**Comment by cookieY** [comment]
Yearning-gemini请使用dev分支
