### ISSUE TITLE
版本 2.3.0 管理员更改用户的 role 不生效

### ISSUE THREAD

**Issue by xuexue1208** [cookieY/Yearning#375]
详情： Yearning 2.3.0 ，手动编译。 登录管理员后台后， 点击 管理 --用户--详细信息 ， 修改角色不生效 。 修改其它信息（邮箱，部门，真实姓名）没有问题。 

![image](https://user-images.githubusercontent.com/45139245/93565309-bb9d3a00-f9bd-11ea-8b12-257eff2e1b9c.png)

**Comment by cookieY** [comment]
前端请用dev分支。请先使用编译好的包进行功能体验。

**Comment by xuexue1208** [comment]
> 前端请用dev分支。请先使用编译好的包进行功能体验。

前端是使用的 dev 分支，讲 dev 分支编译后的代码  放到到 release2.3.0 的 yearning 二进制目录下运行，是可以更改 rule 的，说明前端代码没有问题。  但是我下载 yearning 代码后，切换到 tag 2.3.0 后，自己编译就不可以更改 rule  ， 其他功能正常

**Comment by cookieY** [comment]
Yearning master分支
前端 dev分支

**Comment by xuexue1208** [comment]
> Yearning master分支
> 前端 dev分支

重新 git clone yearning ， 使用 master分支 进行 go build ， 运行 ./Yearning-go  -c  conf.toml -s ， 使用管理员登录， rule 还是不可以进行修改，但是对应的 rule 有传递过去，之前 rule 的值为 guest，下图为请求 http://127.0.0.1:8000/api/v2/manage_user 的截图 


![image](https://user-images.githubusercontent.com/45139245/93581025-2b69ef80-f9d3-11ea-9707-145af24bbd7c.png)

**Comment by xuexue1208** [comment]
文件解决啦，sql 进行信息修改的时候，没有添加 rule 信息 

![image](https://user-images.githubusercontent.com/45139245/93661322-6d556d00-fa89-11ea-97ee-bb26c5e5dbf6.png)
