### ISSUE TITLE
提交工单时无法选择库名

### ISSUE THREAD

**Issue by chimisu** [cookieY/Yearning#376]
**Describe the bug** **描述Bug**

前端使用dev分支最新代码，后端使用master最新代码，在mac上运行。提交工单时，无法选择库名。

**To Reproduce** **如何复现**

前端使用dev分支最新代码，后端使用master最新代码，在mac上运行。提交工单时，库名下拉框为空。

**Expected behavior** **期望的结果**

能够选择库名

**Screenshots** **截图**

![image](https://user-images.githubusercontent.com/12495369/93569727-87794780-f9c4-11ea-882e-fa72e10641a6.png)

**Desktop (please complete the following information):** **环境**
 - OS: macos
 - Browser chrome

**Additional context** **其他**

**Comment by chimisu** [comment]
跟踪后端代码：
![image](https://user-images.githubusercontent.com/12495369/93569918-d1622d80-f9c4-11ea-8653-f699ce00d946.png)
发现在此处直接返回：
```
if model.DB().Where("source =?", unescape).First(&tpl).RecordNotFound() {
		return c.JSON(http.StatusOK, map[string]interface{}{"results": nil, "highlight": nil, "admin": nil})
}
```

**Comment by Vinnk-Frozen** [comment]
我之前也遇到这个问题，把流程模板设置一下就可以有库名下拉了。

**Comment by jwangkun** [comment]
我也遇到这个bug，希望下个版本修复一下，或者增加一下提醒
