### ISSUE TITLE
Bug Report使用osc执行失败

### ISSUE THREAD

**Issue by zhituanchen** [cookieY/Yearning#377]
**Describe the bug** **描述Bug**
使用执行时候报错：
osc执行失败 请检查相关设置是否正确/该表之前如进行过osc kill操作 请清除该表相关触发器及临时表等遗留数据

**To Reproduce** **如何复现**
配置pt-ost开启，用户提交工单，审核后执行

**Expected behavior** **期望的结果**
使用osc正常添加字段

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/71009460/93581304-8dc2f000-f9d3-11ea-95e7-adb72214cbe9.png)

**Desktop (please complete the following information):** **环境**
 - OS CentOS Linux release 7.6.1810 (Core)
 - Browser 版本 85.0.4183.102（正式版本） （64 位）
 - Version Yearning v2.3.0-RC3

**Additional context** **其他**

**Comment by cookieY** [comment]
请设置正确的osc参数

**Comment by zhituanchen** [comment]
您好：
   感谢你的回复，手工测试PT，提示用户需要PROCESS privilege权限即可;

**Comment by ZXW-ZZ** [comment]
![image](https://user-images.githubusercontent.com/73461479/132783977-c73e80ac-0c9a-41c5-89fc-096a512371b7.png)
