### ISSUE TITLE
osc进度无法终止 版本2.2.2

### ISSUE THREAD

**Issue by snake0126** [cookieY/Yearning#378]
**Describe the bug** **描述Bug**
执行的sql有问题，导致sql卡死，osc进程无法终止

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**
如何强行终止执行，或设置超时时间？

**Screenshots** **截图**
![1600763196895](https://user-images.githubusercontent.com/6120407/93859594-67ad9080-fcf0-11ea-9fcf-efe458526ba0.jpg)

**Desktop (please complete the following information):** **环境**
 - OS: MACOS [e.g. iOS]
 - Browser chrome  [e.g. chrome, safari]
 - Version 85.0.4183.102 [e.g. 22]

**Additional context** **其他**

**Comment by cookieY** [comment]
请使用最新版本
