### ISSUE TITLE
工单执行错误时，页面仅显示"执行失败"，未显示具体错误原因

### ISSUE THREAD

**Issue by babay550** [cookieY/Yearning#380]
**Describe the bug** **描述Bug**
工单执行错误时，页面仅显示"执行失败"，未显示具体错误原因

**To Reproduce** **如何复现**
工单执行错误时

**Expected behavior** **期望的结果**
显示具体错误原因

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
工单详情
