### ISSUE TITLE
验证码如何去掉，2.2.2版本

### ISSUE THREAD

**Issue by hazz78** [cookieY/Yearning#381]
**Describe the bug** **描述Bug**
验证码如何去掉，2.2.2版本

**To Reproduce** **如何复现**

验证码如何去掉，2.2.2版本

**Expected behavior** **期望的结果**

验证码去掉

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
无法去除
