### ISSUE TITLE
脱敏字段，稍微在前面加个函数就能读取其中内容，版本：v2.2.2

### ISSUE THREAD

**Issue by ZhangAiRen** [cookieY/Yearning#384]
如图，以concat为例：
![1](https://user-images.githubusercontent.com/34363408/95562298-8d57cb00-0a4e-11eb-8656-bbf94caaa85f.jpg)
![2](https://user-images.githubusercontent.com/34363408/95562419-b8421f00-0a4e-11eb-9996-03d66fb18025.jpg)
![3](https://user-images.githubusercontent.com/34363408/95562563-e6276380-0a4e-11eb-8bfb-9c77db5f33dd.jpg)

**Comment by cookieY** [comment]
无法规避函数类型的脱敏
