### ISSUE TITLE
批量插入数据，执行到中间失败时，整体判定为失败，但是部分已经执行成功了

### ISSUE THREAD

**Issue by zengyongjie** [cookieY/Yearning#387]
**Describe the bug** **描述Bug**
譬如执行10条插入语句，第5条和第6条主键冲突，插入第六条失败，则整个工单判定为失败，在详细信息里面也是判定所有语句为失败，其实前面1-5条已经成功的插入到数据库了。

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

中间失败时，自动批量回滚本次工单中已经发生影响的部分，在本例中，自动撤销前面1-5的插入结果。

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
基于会自动生成回滚语句的机制，在工单中如遇到错误直接回滚的就不存在必要性。如果实现这样的功能如遇大批量SQL语句的工单回滚操作将会持续非常多的时间
