### ISSUE TITLE
脱敏的字段做个函数运算就能读取其中内容，版本：v2.3.0

### ISSUE THREAD

**Issue by chow-q** [cookieY/Yearning#389]
**Describe the bug** **描述Bug**

脱敏的字段+1后脱敏就失效了。

**To Reproduce** **如何复现**

> select phone_mob+1 from admin limit 1;
再拿电话号码减1就是正确电话号码

**Expected behavior** **期望的结果**

**Screenshots** **截图**

![图片](https://user-images.githubusercontent.com/73530205/97294723-545e8980-1889-11eb-8b9f-2345b6b44241.png)

**Desktop (please complete the following information):** **环境**
 - Version [e.g. 2.3.0]

**Additional context** **其他**

**Comment by cookieY** [comment]
![image](https://user-images.githubusercontent.com/22343354/97383762-4b150180-1909-11eb-8fc3-1f91a27f740e.png)

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v2.3.1
