### ISSUE TITLE
查看回滚语句功能异常

### ISSUE THREAD

**Issue by whithen** [cookieY/Yearning#391]
**Describe the bug** **描述Bug**
工单执行后，查看回滚语句功能异常

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**
![图片](https://user-images.githubusercontent.com/33741400/97845985-4ba60180-1d28-11eb-837d-f768db8333cc.png)

**Desktop (please complete the following information):** **环境**
 - Browser [all]
 - Version [2.3.0]

**Additional context** **其他**

**Comment by cookieY** [comment]
https://guide.yearning.io/attention.html

**Comment by whithen** [comment]
已开启binglog，并使用root账户链接测试，还是一样
![图片](https://user-images.githubusercontent.com/33741400/97853021-7f862480-1d32-11eb-8025-95d5efb0c7fb.png)

**Comment by whithen** [comment]
同样的帐号配置和DML在2.1.4版本上面正常

**Comment by cookieY** [comment]
暂时无法复现此问题

**Comment by umena337** [comment]
2.3.0回滚有异常

**Comment by umena337** [comment]
生成回滚语句
Yearning 采用解析binlog方式的方式获得回滚语句。由于Mysql replication协议限制,必须拥有SUPER/REPLICATION SLAVE, REPLICATION CLIENT ,ALL PRIVILEGES 权限的账号才可以获得binlog流。所以，如想体验生成回滚语句备份功能，请确保对应填写的数据源账号拥有相应权限，同时对应数据源应开启binlog功能。

**Comment by umena337** [comment]
版本v2.3.0  操作数据库mysql5.6 root用户 开启了binlog 语句Update ....replace...
