### ISSUE TITLE
无法解析版本号5.5.18.1-log

### ISSUE THREAD

**Issue by SgtDaJim** [cookieY/Yearning#392]
版本： 2.2.2

![image](https://user-images.githubusercontent.com/10288044/98351973-680faa00-2058-11eb-983e-81f0d12202e0.png)

**Comment by cookieY** [comment]
不支持mysql5.5

**Comment by SgtDaJim** [comment]
所以这个问题是mysql5.5的问题，而不是版本号带-log的问题？

**Comment by cookieY** [comment]
是的
