### ISSUE TITLE
使用谷歌浏览器登录时卡死

### ISSUE THREAD

**Issue by liufeng6582** [cookieY/Yearning#395]
使用docker-compose部署，后台报错信息如下
2020-11-11 15:54:54.940607 I | Yearning_error: 2020/11/11 15:54:54.940596 /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/net/http/server.go:3061: http: panic serving 172.27.0.1:57774: runtime error: index out of range [0] with length 0
goroutine 2048 [running]:
net/http.(*conn).serve.func1(0xc000176320)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/net/http/server.go:1772 +0x139
panic(0x1455280, 0xc000143b80)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/runtime/panic.go:975 +0x3e3
github.com/cookieY/yee.(*context).Next(0xc000344380)
	/var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.4/context.go:104 +0x1b1
github.com/cookieY/yee.(*Core).handleHTTPRequest(0xc0005ae410, 0xc000344380)
	/var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.4/yee.go:191 +0x23e
github.com/cookieY/yee.(*Core).ServeHTTP(0xc0005ae410, 0x177cf00, 0xc0003442a0, 0xc0000b2400)
	/var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.4/yee.go:123 +0x142
net/http.serverHandler.ServeHTTP(0xc000344000, 0x177cf00, 0xc0003442a0, 0xc0000b2400)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc000176320, 0x1784380, 0xc000216140)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/net/http/server.go:2933 +0x35c
2020-11-11 15:54:54.944872 I | Yearning_error: 2020/11/11 15:54:54.944864 /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/net/http/server.go:3061: http: panic serving 172.27.0.1:57778: runtime error: index out of range [0] with length 0
goroutine 2098 [running]:
net/http.(*conn).serve.func1(0xc000176460)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/net/http/server.go:1772 +0x139
panic(0x1455280, 0xc0005d00e0)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/runtime/panic.go:975 +0x3e3
github.com/cookieY/yee.(*context).Next(0xc000344620)
	/var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.4/context.go:104 +0x1b1
github.com/cookieY/yee.(*Core).handleHTTPRequest(0xc0005ae410, 0xc000344620)
	/var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.4/yee.go:191 +0x23e
github.com/cookieY/yee.(*Core).ServeHTTP(0xc0005ae410, 0x177cf00, 0xc000344540, 0xc0000b2500)
	/var/jenkins_home/go/pkg/mod/github.com/cookie!y/yee@v0.1.4/yee.go:123 +0x142
net/http.serverHandler.ServeHTTP(0xc000344000, 0x177cf00, 0xc000344540, 0xc0000b2500)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc000176460, 0x1784380, 0xc000216240)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go_1.14.4/src/net/http/server.go:2933 +0x35c

**Comment by cookieY** [comment]
报错信息中没有 有效信息
