### ISSUE TITLE
juno无法执行ddl工单

### ISSUE THREAD

**Issue by sh-hanson** [cookieY/Yearning#396]
**Describe the bug** **描述Bug**
基于2.3.0版本的二开，在提交ddl时，进度一直提示1%，无法继续执行。也没有报错，也不结束
一个工单提交一个ddl与多个ddl情况一样，都是提示1%后无法继续

**To Reproduce** **如何复现**
除了ddl无法执行外，其它功能都正常

pt-osc配置截图如下
![image](https://user-images.githubusercontent.com/41986080/98911427-887bb080-24ff-11eb-8b42-4d91b6661c22.png)

ddl执行时，juno中正常打印pt-online-schema-change命令信息，没有错误输出
![image](https://user-images.githubusercontent.com/41986080/98911766-1ce61300-2500-11eb-937a-5e6993ed7d9f.png)

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v2.3.1
