### ISSUE TITLE
回滚功能 操作数据库mysql5.6执行update语句后，点击回滚，生成的回滚语句是空的

### ISSUE THREAD

**Issue by umena337** [cookieY/Yearning#399]
**Describe the bug** **描述Bug**
回滚功能 操作数据库mysql5.6执行update语句后，点击回滚，生成的回滚语句是空的
Yearning 2.3.1
操作的数据库 Mysql 5.6  开启了binlog
执行语句 Update ....replace
执行成功后 点击查看回滚语句
生成的回滚语句是空的

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/44667665/99472838-6614e780-2984-11eb-8e70-88ff708feadd.png)
![image](https://user-images.githubusercontent.com/44667665/99472849-6ad99b80-2984-11eb-8f65-1481972f20da.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by umena337** [comment]
Yearning2.3.0也同样 才升级2.3.1的

**Comment by umena337** [comment]
Update 表名 Set 字段名 = replace(字段名,被替换的字符,要替换的字符);

**Comment by umena337** [comment]
操作数据库用户是root

**Comment by umena337** [comment]
开启binlog
vi /etc/my.conf
log-bin=/home/mysql_data/binlogs
保存退出
systemctl restart mysqld

**Comment by umena337** [comment]
Yearning 2.3.1
操作的数据库 Mysql 5.6 root用户开启了binlog
执行语句 Update 表名 Set 字段名 = replace(字段名,被替换的字符,要替换的字符)
执行成功后 点击查看回滚语句
生成的回滚语句是空的

**Comment by umena337** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
5.7 测试没啥问题
5.6不支持json
必须5.7或者以上版本才能正常用yearning

**Comment by cookieY** [comment]
已在Q群回复
