### ISSUE TITLE
Yearning v1.3.0 正式发布

### ISSUE THREAD

**Issue by cookieY** [cookieY/Yearning#40]
功能更新如下：

1.修改了报错提示

2.新增细粒化权限组，废除之前的个人权限划分

3.连接名webook合并至配置页面webhook

4.删除查询时限,新增管理员结束用户查询权限

4.查询页面支持自动补全库名及表名

5.新增版本号接口 (登陆后/#/version)

6.修复权限审核页面,数据库管理页面低版本chrome或其他浏览器401报错的问题

7.修复查询审核时查询工单提交没有消息推送的问题

**Comment by jaat89** [comment]
docker化安装的时候，能否把inception也集成到docker里面去？

**Comment by cookieY** [comment]
@jaat89 后面会考虑

**Comment by ztorin** [comment]
采用v1.3.0安装完后，ddl，dml，索引这些都没问题。但是sql查询的时候会报错sql1064语法错误，但是肯定sql本身语法是没问题了？有遇到一样问题了吗?

**Comment by cookieY** [comment]
@ztorin 没有设置limit

**Comment by ztorin** [comment]
加上limit 1,10 这样的条件后，又报错invalid literal for int() with base 10: ''了？非常感谢你的回复

**Comment by ztorin** [comment]
找到原因了。设置里面没有设置limit值。新手上路，打扰了

**Comment by ztorin** [comment]
现在v1.3.0里面遇到两个问题：1.在审核工单里面查看执行成功的DML语句的回滚语句时，docker日志里面报[ERROR]- AttributeError: 'SQLgo' object has no attribute 'execute' ，确认我的设置inception设置里面配置的备份用户是all privileges   2.admin用户能正常执行dml ddl dcl语句，但是创建的普通用户授予了必要的权限，但是普通用户就dml ddl dcl都不能执行，docker容器里面报错为：[ERROR]- AttributeError: 'NoneType' object has no attribute 'permissions'

**Comment by cookieY** [comment]
@ztorin 请下载新的docker镜像，老的有这个问题

**Comment by ztorin** [comment]
我是今天早上才拉的最新的代码搭建的。

**Comment by cookieY** [comment]
@ztorin 更新过啦

**Comment by ztorin** [comment]
刚刚拉取了最新代码测试，发现还是存在上面提到的2个问题；1.无法查看回滚语句，只是现在docker容器里面的报错提示不一样了，现在是 [ERROR]- KeyError: 0        2.就是关于普通用户无法执行任何DML DDL DCL语句的问题，可以解决吗？我排查觉得是创建的普通用户的有些信息没有写到Yearning库里面的相关表里面了？

**Comment by cookieY** [comment]
@ztorin 已修复

**Comment by wfwfjdhy** [comment]
ddl审计提交中，选择了审核人，但是没有显示，导致无法提交工单。

**Comment by xjdai1** [comment]
能增加一个语句，一次提交执行多个实例

**Comment by sky1006** [comment]
1.inception 审核太严格，手动模式，警告无法提交，生成模式，可以提交，但无法执行成功。
2.提交步骤太复杂，开发要疯掉了

**Comment by cookieY** [comment]
@sky1006 inception有对应的参数可以进行设置。

**Comment by cookieY** [comment]
@sky1006 
1.inception一些审核限制可以通过对应参数关闭。具体请查看inception文档
2.yearning 面向的是需要流程化，规范化的，审核平台的用户

**Comment by bravewind** [comment]
select，dml，ddl 语句都ok，但是回滚报错。。。docker ip连接不上我的备份服务器

**Comment by cookieY** [comment]
@bravewind 错误提示已经很明显了 检查自己的配置。特别注意 网段是否与docker的虚拟网段重名

**Comment by bravewind** [comment]
@cookieY  谢谢你的回复，
备份的部分配置如下：
#备份服务器信息
inception_remote_system_password=123456
inception_remote_system_user=test
inception_remote_backup_port=3306
inception_remote_backup_host=192.168.201.49
inception_support_charset=utf8

结果还是报错：
Backup: Access denied for user 'test'@'192.168.201.49' (using password: YES) Backup: Access denied for user 'test'@'192.168.201.49' (using password: YES)

mysql 已经授权给了test用户，docker 和宿主机应该是互通的吧？大佬请指点

**Comment by bravewind** [comment]
@cookieY  你好，我们使用场景都是有从库的，并且是过滤表了，做的主从同步，现在报错如下：
Found 1 slaves: fba-script -> 172.30.14.112:3306 Will check slave lag on: fba-script -> 172.30.14.112:3306 Replication filters are set on these hosts: fba-script replicate_ignore_table = valsun_fba.fba_iorecords_extend,valsun_fba.fba_checkcost_info,valsun_fba.fba_test_info_06,valsun_fba.fba_prompt_msg,valsun_fba.fba_from_open_config,valsun_fba.fba_exception_info,valsun_fba.fba_white_sku_info,valsun_fba.fba_alert_log,valsun_fba.fba_goods_category Please read the --check-replication-filters documentation to learn how to solve this problem. at /data/temp/percona/bin/pt-online-schema-change line 8693.

查看文档没发现可设置的参数？请问怎么解决呢？

**Comment by bravewind** [comment]
@cookieY   在进行alter 操作的时候可以忽略从库吗？
因为我从库的端口可能不是3306

**Comment by bravewind** [comment]
@cookieY  你好，我使用的1.2 版本，在更改表时（添加字段，添加索引等），如果表数据比较多，百万以上，就会一直处于 执行中 的 状态，请问怎么解决？谢谢！

**Comment by cookieY** [comment]
@snailAlice 请具体描述下问题
