### ISSUE TITLE
DML工单提交多条Delete语句报“Not Allowed”

### ISSUE THREAD

**Issue by macpherson0625** [cookieY/Yearning#400]
**Describe the bug** **描述Bug**
DML工单提交多条Delete语句报“Not Allowed”

**To Reproduce** **如何复现**
提交DML工单输入多条Delete语句点击“检测语句”

**Expected behavior** **期望的结果**
望能尽快修复此问题

**Screenshots** **截图**
 
![微信截图_20201118161602](https://user-images.githubusercontent.com/5416086/99503806-9a56cb00-29b9-11eb-8abc-bea0007567f2.png)

**Desktop (please complete the following information):** **环境**
 - OS: Ubuntu 16.04
 - Browser: Chrome
 - Version: V2.3.1

**Additional context** **其他**

**Comment by macpherson0625** [comment]
补充下，我是用Docker容器部署的，Yearning版本 V2.3.1，单条Delete语句可以检测通过。

**Comment by cookieY** [comment]
![image](https://user-images.githubusercontent.com/22343354/99506809-8f9e3500-29bd-11eb-8fb1-c0bce0fc4926.png)

无法复现

**Comment by macpherson0625** [comment]
@cookieY   感谢回复，问题我已经解决了，是被Nginx代理过滤了。
