### ISSUE TITLE
图标和浏览器宽度问题

### ISSUE THREAD

**Issue by byronjxb** [cookieY/Yearning#401]
![image](https://user-images.githubusercontent.com/21222280/99643032-2daa0200-2a87-11eb-8a4b-27fedd5f0f2b.png)

字体排版不行呀~

**Comment by cookieY** [comment]
![image](https://user-images.githubusercontent.com/22343354/99654008-b67b6a80-2a94-11eb-9e25-b9a4ff9a355f.png)

啊？

**Comment by byronjxb** [comment]
win10 chrome最新版 87.0.4280.66（正式版本） （64 位）依旧如此

**Comment by cookieY** [comment]
你分辨率多少呀

**Comment by byronjxb** [comment]
1920 x 1080
