### ISSUE TITLE
DDL、DML饼图统计问题  Bug Report

### ISSUE THREAD

**Issue by macpherson0625** [cookieY/Yearning#407]
**Describe the bug** **描述Bug**
首页饼图统计DDL、DML工单类型数量是不是反了？从列表里来看DDL只有1条，DML14条，但饼图里显示DML数量1条，DDL数量14条。

![DDL](https://user-images.githubusercontent.com/5416086/100704304-41872980-33e0-11eb-9df9-2c852635c606.png)
![List](https://user-images.githubusercontent.com/5416086/100704315-46e47400-33e0-11eb-91d8-87ab03995674.png)

另外，我也一直在使用Archery工单系统，虽然功能比较多，但添加用户和修改权限等配置需要进入Django后台，在朋友的推荐下体验了Yearning，从添加流程配置和使用确实方便了不少，同时也有几点建议看下可否满足：
1. 在首页上栏的统计方框里可否加入URL链接，可以跳转到相应的列表里，也便捷维护可操作性。
![Index](https://user-images.githubusercontent.com/5416086/100705664-8dd36900-33e2-11eb-94bb-f4e58131e0b1.png)

![Archery](https://user-images.githubusercontent.com/5416086/100705791-cecb7d80-33e2-11eb-83a0-96aa5034da83.png)
[参考Archery DashBoard首页]

2. 建议在工单里添加SQL文件上传，有些[*.sql]备份集文件恢复操作确实很不方便，需要把SQL备份集文件打开，再复制粘贴到工单系统
![SQL_Submit](https://user-images.githubusercontent.com/5416086/100705636-83b16a80-33e2-11eb-9c7f-f2c2c596271f.png)

**Comment by cookieY** [comment]
饼图问题已在2.3以上版本修复
