### ISSUE TITLE
Yearing后端连接TiDB时：DML操作勾选备份时SQL执行失败

### ISSUE THREAD

**Issue by liuhuanHappyStudy** [cookieY/Yearning#409]
提交DML操作：UPDATE stu SET age=5 WHERE id=4;
勾选：备份

审核后执行结果：
![image](https://user-images.githubusercontent.com/43037963/100979941-77aedf80-357f-11eb-9f01-80d20a8fcaeb.png)

点击执行结果：
![image](https://user-images.githubusercontent.com/43037963/100980266-f0ae3700-357f-11eb-8592-4b70dfadf548.png)

Yearing报错日志：
Yearning_error: 2020/12/03 15:47:41.179087 /var/jenkins_home/workspace/Yearning-go/src/parser/roll.go:590: Binlog没有开启无法备份!

TiDB集群是开启binlog的。是否tidb和mysql生产binlog的形式不一样，Yearing在tidb上不支持备份呢？

如果提交DML操作时，不勾选备份，可在tidb集群上正常执行。

**Comment by liuhuanHappyStudy** [comment]
Yearning版本：version: Yearning/2.1.5
tidb集群版本：v4.0.2

**Comment by cookieY** [comment]
暂不支持tidb 回滚
