### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by guofushan** [cookieY/Yearning#410]
**Describe the bug** **描述Bug**
如下ddl sq在工单提交时失败，sql审核机制因该有问题。
CREATE TABLE `test` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `test` VARCHAR(200) NOT NULL COMMENT 'test',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB COMMENT='test'

**To Reproduce** **如何复现**
提交ddl工单就会报错。

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v2.3.1
