### ISSUE TITLE
添加不存在的mysql数据库后不能删除 

### ISSUE THREAD

**Issue by liwei225** [cookieY/Yearning#42]
先添加了一个不存在的mysql实例，之后要删除此实例，显示如下图：
![image](https://user-images.githubusercontent.com/22341888/43698176-34643e20-997b-11e8-90b9-dda439f22101.png)

**Comment by liwei225** [comment]
如果从docker上看，并没有error log报出来，如下：
![image](https://user-images.githubusercontent.com/22341888/43701612-67a707d2-9989-11e8-9320-a3f106e7f887.png)

**Comment by cookieY** [comment]
@liwei225 下载最新镜像

**Comment by liwei225** [comment]
@cookieY 抱歉没有及时反馈，已经是最新的镜像了，问题依然存在
