### ISSUE TITLE
用户管理界面无响应是什么情况

### ISSUE THREAD

**Issue by Yongci** [cookieY/Yearning#424]
**Describe the bug** **描述Bug**

点击用户管理界面，页面卡死，一直无响应

**To Reproduce** **如何复现**

我这边接入的LDAP认证，容器部署形式，我做了些改造，将其放入了Kubernetes运行；并使用Ingress-nginx做代理，用了将近1年多了，查询、插入啥的也都没啥问题，最近突然出现用户管理界面无响应的情况

尝试修改代理超时时间没解决，日志里也没有看到报错

**Expected behavior** **期望的结果**

可以正常进行用户管理

**Screenshots** **截图**

![image](https://user-images.githubusercontent.com/5220897/101712202-f9e35a80-3acf-11eb-90f9-f5740d548f09.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
1.请检查浏览器是否存在插件冲突
2.更换浏览器

**Comment by Yongci** [comment]
已解决
