### ISSUE TITLE
Yearing平台，提交的 定时执行的sql，在一周之后的定时任务失效了，请问是什么原因？

### ISSUE THREAD

**Issue by hanxiwang** [cookieY/Yearning#434]
![image](https://user-images.githubusercontent.com/57393501/104979487-5c206b00-5a3f-11eb-818c-bfca50aa2373.png)
2021-01-05 09:39 提交的定时执行的工单，在执行时间再 2021-01-12 01:00之后的 定时工单就失败了，请问是什么原因呢？

**Comment by cookieY** [comment]
中间重启过了吧
