### ISSUE TITLE
有审核权限的用户在sql查询页面能提交DDL语句

### ISSUE THREAD

**Issue by yangjunPrivate** [cookieY/Yearning#437]
**Describe the bug** **描述Bug**
有审核权限的用户，在使用sql查询的时候，输入ddl语句，然后点击查询，页面提示返回500错误，但实际上对应语句是执行成功的。我用alter语句测试的增加表字段

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
请给出具体使用过程及截图
