### ISSUE TITLE
建议：审核人列表显示“姓名”字段信息

### ISSUE THREAD

**Issue by eagleos** [cookieY/Yearning#446]
您好，yearning很好用，感谢无私开源！这里提个小建议，希望能采纳，谢谢！
就是：
审核人列表目前显示的是username这个字段，这个有2方面原因建议修改成“姓名”字段信息：
（1）安全风险：显示username字段就是登录用户名，容易被利用于黑客攻击，有一定安全风险。
（2）开设时，username一般填写的是英文之类的信息，“姓名”才是写中文员工名字，因此这里改为显示姓名，才方便快速选择对应的审核人员进行审核。
谢谢！

**Comment by cookieY** [comment]
由于真实姓名并非强制性获取。 无法保证每一个用户都会填写真实姓名，为了保证工单的非歧义性。只能采取username+真实姓名的方式展示
