### ISSUE TITLE
连接到juno服务报错

### ISSUE THREAD

**Issue by regend** [cookieY/Yearning#448]
在同一台机器上使用同一份conf.toml文件正常. 但是将juno单独部署在docker容器内,使用同一份配置文件的时候,并且yearning中的grpc地址改成了docker的地址端口,使用中报错:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x8a4976]

goroutine 15 [running]:
github.com/jinzhu/gorm.(*DB).Close(0x0, 0x40, 0x12c7b40)
	/var/jenkins_home/go/pkg/mod/github.com/jinzhu/gorm@v1.9.12/main.go:118 +0x26
Juno/libraGrpc/server.(*Ser).OrderDeal.func1(0xc0001035c0)
	/var/jenkins_home/workspace/juno/libraGrpc/server/server.go:180 +0x33
Juno/libraGrpc/server.(*Ser).OrderDeal(0x2609970, 0x15d64c0, 0xc0001e7ad0, 0xc0000f8630, 0xc0001c7000, 0x0, 0x0)
	/var/jenkins_home/workspace/juno/libraGrpc/server/server.go:201 +0x362
Juno/libraGrpc/proto._Juno_OrderDeal_Handler(0x12c3dc0, 0x2609970, 0x15d64c0, 0xc0001e7ad0, 0xc00017d980, 0x0, 0x15d64c0, 0xc0001e7ad0, 0xc0000ed0c0, 0x3d)
	/var/jenkins_home/workspace/juno/libraGrpc/proto/detection.pb.go:559 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000362600, 0x15e7ca0, 0xc00015a900, 0xc0001c4e00, 0xc000381b00, 0x2598b60, 0x0, 0x0, 0x0)
	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0x501
google.golang.org/grpc.(*Server).handleStream(0xc000362600, 0x15e7ca0, 0xc00015a900, 0xc0001c4e00, 0x0)
	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000209de4, 0xc000362600, 0x15e7ca0, 0xc00015a900, 0xc0001c4e00)
	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xa1

**Comment by cookieY** [comment]
docker的地址和本机的地址 能是一个地址么？

**Comment by regend** [comment]
> docker的地址和本机的地址 能是一个地址么？

都是宿主机的地址

**Comment by olderwang** [comment]
请问问题解决了吗？
