### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by whitefirer** [cookieY/Yearning#452]
**Describe the bug** **描述Bug**
所有页面报500，除非重新登录

**To Reproduce** **如何复现**
管理员在用户列表搜索用户后，不点重置按钮

**Expected behavior** **期望的结果**
正常显示

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/12084604/112264678-2f413c00-8cac-11eb-802e-512e54562b77.png)

**Desktop (please complete the following information):** **环境**
 - OS: win10，mac
 - Browser  chrome, safari

**Additional context** **其他**

**Comment by cookieY** [comment]
已定位此问题,感谢反馈
