### ISSUE TITLE
源码./Yearning run启动报错

### ISSUE THREAD

**Issue by whl-2020-Hunan** [cookieY/Yearning#453]
提示报 stat /data/Yearning/src/service/dist/index.html: no such file or directory 错误，但我从官方git拉代码下来，是没有看到有dist这个文件夹的，还请告知怎么处理，谢谢！
![image](https://user-images.githubusercontent.com/69785008/112966341-ba26a880-917c-11eb-9df6-c5806a393592.png)

**Comment by danfengcao** [comment]
遇到同样的问题

**Comment by spotaku** [comment]
遇到同样的问题

**Comment by cookieY** [comment]
注释相关行代码

**Comment by nbaiguo** [comment]
请问怎么解决的？

**Comment by spotaku** [comment]
> 请问怎么解决的？

先编译 Yearning-gemini 这个前端项目，放到报错的路径下，再编译Yearning
