### ISSUE TITLE
Bug Report ldap connection error

### ISSUE THREAD

**Issue by terryshi96** [cookieY/Yearning#458]
v2.3.2版本
ldap url配置 636端口，勾选ldaps并保存配置
登陆时未使用ldaps连接，报错unable to read LDAP response packet: unexpected EOF

ldap url配置 389端口，取消勾选ldaps并保存配置，能正常登陆
在grafana验证同样的配置 使用ldaps能正常登陆

**Comment by terryshi96** [comment]
https://github.com/go-ldap/ldap/blob/v3.3.0/examples_test.go
ldap包中DialTLS函数已经废弃 是否能更新为新方法DiaURL
// DialTLS connects to the given address on the given network using tls.Dial
// and then returns a new Conn for the connection.
// @deprecated Use DialURL instead.

**Comment by cookieY** [comment]
新版本已修复此问题
