### ISSUE TITLE
工单记录详情页，登录人审核的工单点开详情空白

### ISSUE THREAD

**Issue by Keanhua** [cookieY/Yearning#459]
**Describe the bug** **描述Bug**
工单记录详情页，登录人审核的工单点开详情空白，其他人审核的工单可以正常打开

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**
非空白

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/31396902/114161964-34b0ae80-995b-11eb-959e-a4623f31fb28.png)
![image](https://user-images.githubusercontent.com/31396902/114161974-37ab9f00-995b-11eb-9bec-0638b35476b6.png)

**Desktop (please complete the following information):** **环境**
版本 v2.3.2.2

**Additional context** **其他**

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/2.3.2.1
