### ISSUE TITLE
工单查询数据异常Post请求/api/v2/query/results

### ISSUE THREAD

**Issue by Mxinhu** [cookieY/Yearning#460]
**Describe the bug** **描述Bug**
1、使用当前最新的代码构建后，Post请求/api/v2/query/results接口异常，返回内容如下
`{
	"payload": null,
	"code": 5555,
	"text": "rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: missing address\""
}`
2、src/handler/personal/query.go内FetchQueryResults函数，异常地方在红框内
![image](https://user-images.githubusercontent.com/50960351/114278313-cefb1a00-9a61-11eb-858d-b612bc8fee5c.png)
3、使用已经打包好的 2.3.2tar包，可以正常使用

可以帮忙看下什么原因吗

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**
 - OS: win10
 - Browser: Google Chrome
 - Version: 2.3.2

**Additional context** **其他**

**Comment by Mxinhu** [comment]
body里的内容可以正常读取
`fmt.Println(string(ioutil.ReadAll(c.Request().Body)))`
输出内容：
{"sql":"select * from t_dns_records","data_base":"bind9","source":"123456"}

**Comment by cookieY** [comment]
https://guide.yearning.io/args.html

**Comment by Mxinhu** [comment]
Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cookieY/Yearning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月12日(星期一) 上午9:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cookieY/Yearning] 工单查询数据异常Post请求/api/v2/query/results (#460)





 
Closed #460.
