### ISSUE TITLE
Yearning 2.3.2提交SQL工单，查看回滚语句空白。

### ISSUE THREAD

**Issue by macpherson0625** [cookieY/Yearning#461]
MySQL 5.7.25 已开启binlog，执行Yearning工单后查看回滚语句显示空白，查了下Yearning日志也没报错。

![微信截图_20210413144213](https://user-images.githubusercontent.com/5416086/114508040-82ccf700-9c66-11eb-9a5a-851eecd3b9ec.png)

![微信截图_20210413143547](https://user-images.githubusercontent.com/5416086/114507610-ed316780-9c65-11eb-9b39-c02a8eb59a04.png)

**Comment by cookieY** [comment]
请提供具体回滚时的日志信息

**Comment by macpherson0625** [comment]
1. 当天执行的SQL如下

**Comment by thomasdongcn** [comment]
![微信图片_20210505151936](https://user-images.githubusercontent.com/16532193/117108179-67609200-adb5-11eb-8a4d-f5e2d4e7e7fb.png)

**Comment by macpherson0625** [comment]
感谢，问题已经解决了。我看了下是数据库用户没有REPLICATION CLIENT、REPLICATION SLAVE这两个权限。
