### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Myshiner** [cookieY/Yearning#462]
**Describe the bug** **描述Bug**
版本是v2.2.2的，有一天管理菜单中的数据源管理菜单就不见了，重启服务和升级到v2.3也不行。

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/48242833/115340658-aef1f600-a1d9-11eb-8434-3fd7d450ec93.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
请检查浏览器是否开启无痕 更换浏览器后重试
