### ISSUE TITLE
大写用户名，用小写登陆后看不到审核记录

### ISSUE THREAD

**Issue by rexlibing** [cookieY/Yearning#464]
**Describe the bug** **描述Bug**
用户名在工单流程中部分字段区分大小写。
用户来自LDAP,默认获取到的用户首字母为大写，登陆时若使用小写登陆，审核栏目下看不到自己的提交或待审记录。
在查询对应数据库审核人，确实有权限。***但留意到这里审核人采用的也是首字母大写的默认用户名。
使用大写首字母的用户名登陆，就可以查看自己的审核工单了。
**To Reproduce** **如何复现**
创建用户时使用大写首字母用户名，对应数据库流程模板和审核人选择该用户。登陆使用小写用户名创建工单，复现问题

**Expected behavior** **期望的结果**
工单流程中用户关联字段忽略其大小写，温馨提示~

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/16685466/116659817-bf1d8880-a9c4-11eb-8b9a-70dae590155c.png)
![image](https://user-images.githubusercontent.com/16685466/116659928-e411fb80-a9c4-11eb-9635-e912cfd24014.png)

**Desktop (please complete the following information):** **环境**
 - 客服端环境 win7
 - chrome
 - 90.0.4430

**Additional context** **其他**

**Comment by cookieY** [comment]
请将Yearning所在的数据库开启大小写敏感

**Comment by rexlibing** [comment]
OK,了解了
