### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by wensenz** [cookieY/Yearning#465]
**Describe the bug** **描述Bug**

2021/05/06 18:40:24 stat /Users/zhongzhengwen/go/src/yearning/src/service/dist/index.html: no such file or directory

**To Reproduce** **如何复现**

go version go1.15.6 darwin/amd64
./yearning run，毕现， 是我打开的方式不对吗？

**Expected behavior** **期望的结果**
正常启动

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
自行修改代码时应该先编译好前端文件在进行打包
