### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by yidazhi** [cookieY/Yearning#468]
**Describe the bug** **描述Bug**
执行了一个加字段的DDL语句，查看回滚，然后执行提交工单，报如下错误

流程信息缺失,请检查该数据源流程配置!

我的流程配置是提交-->审核-->执行，如果需要回滚，我应该如何配置

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**
回滚成功

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/35521643/117939676-e49e8080-b33a-11eb-84e4-5a911e0ae869.png)
![image](https://user-images.githubusercontent.com/35521643/117939771-fed85e80-b33a-11eb-9a6a-aafc532ecad0.png)

**Desktop (please complete the following information):** **环境**
 - OS: CentOS Linux release 7.7.1908 (Core)
 - Browser 谷歌

**Comment by cookieY** [comment]
请检查对应流程上是否存在对应审核人

**Comment by zhenglin305** [comment]
兄弟搞好了吗？我也碰到这个问题了，不知道怎么搞
