### ISSUE TITLE
如何配置pt-osc参数，更改表结构的时候使用pt-osc

### ISSUE THREAD

**Issue by wwwwwwchun** [cookieY/Yearning#470]
如何配置pt-osc工具，发现文档上没有提供pt-osc参数的配置信息，这个能给提供一下吗？

**Comment by cookieY** [comment]
https://www.percona.com/doc/percona-toolkit/3.0/pt-online-schema-change.html

**Comment by wwwwwwchun** [comment]
是想问一下，这个yearing有没有类似
inception_osc_bin_dir
inception_osc_check_interval
这种参数？就是调用pt-osc工具的参数，制订pt-osc的目录位置，表数据量多大后才用pt-osc工具执行alter语句，是这个意思

**Comment by cookieY** [comment]
审核规则内有 并且有相关参数的详细解释 请自行仔细查看
