### ISSUE TITLE
ldap配置正确但登陆失败 User does not exist or too many entries returned

### ISSUE THREAD

**Issue by fency12** [cookieY/Yearning#471]
**Describe the bug** **描述Bug**
ldap登陆报错：User does not exist or too many entries returned

**To Reproduce** **如何复现**
ldap目录如

![image](https://user-images.githubusercontent.com/19307432/120761489-d3b2ea80-c547-11eb-8f9c-e817464aa042.png)
配置如：
![image](https://user-images.githubusercontent.com/19307432/120761613-f80ec700-c547-11eb-9b08-d52c1690852e.png)

ldap配置测试正确，但页面登陆提示 User does not exist or too many entries returned

**Expected behavior** **期望的结果**

因为通过ldap的日志发现如下：可能是因为默认添加了(objectClass=organizationalPerson)这个过滤器，请问这个怎么去掉？
60b9d2fa conn=4477 op=1 SRCH base="dc=xxx,dc=com" scope=2 deref=0 filter="(&(objectClass=organizationalPerson)(cn=xxx))"

**Comment by fency12** [comment]
已正常接入dap的验证有jira、wiki、yapi、jumpserver等都没问题，验证正常ldap日志如下
60c07739 conn=5899 op=1 SRCH base="dc=xxx,dc=com" scope=2 deref=3 filter="(&(objectClass=organizationalRole)(cn=xxx))"

**Comment by cookieY** [comment]
https://blog.csdn.net/qq_33997198/article/details/104607102

**Comment by fency12** [comment]
> https://blog.csdn.net/qq_33997198/article/details/104607102

原因已经找到：是因为yearning默认的过滤规则为filter="(&(objectClass=organizationalPerson)(cn=xxx))"，自带了(objectClass=organizationalPerson)这个过滤属性，而我们在做ldap时如果不用这个就没法用ldap，我通过实验已经验证了。
建议将(objectClass=organizationalPerson)默认过滤属性去掉，改为objectClass=top过滤，虽大但全。或者借鉴jira、wiki、yapi、jumpserver等方法

**Comment by cookieY** [comment]
后面会开放自定义搜索规则
