### ISSUE TITLE
从2.3.2版本升级到2.3.3最新版后提交工单审批流程，审批人无法看到该工单编号

### ISSUE THREAD

**Issue by macpherson0625** [cookieY/Yearning#473]
我是docker部署的，查了下容器的访问日志出现这个报错（如截图），以下是Dockerfile文件（除了改过启动参数，其它没改）

Dockerfile:
----------------------------------------------------------------------------------------------------------------------------------------------

FROM alpine:3.12

LABEL maintainer="HenryYee-2020/11/16"

EXPOSE 8000

COPY Yearning  /opt/Yearning
COPY conf.toml /opt/conf.toml

RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.12/main/" > /etc/apk/repositories && \
      apk add --no-cache tzdata libc6-compat && \
      ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
      echo "Asia/Shanghai" >> /etc/timezone && \
      echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

WORKDIR /opt

CMD /opt/Yearning install && /opt/Yearning run -b xxx.xxx.com

----------------------------------------------------------------------------------------------------------------------------------------------

![yearning](https://user-images.githubusercontent.com/5416086/120987756-7cfc1980-c7b0-11eb-85da-1cf9216c712d.png)

**Comment by cookieY** [comment]
把这个字段删了

**Comment by macpherson0625** [comment]
> 把这个字段删了

请问在那张表里面？

**Comment by cookieY** [comment]
core_sql_orders
