### ISSUE TITLE
是否可以支持DRDS

### ISSUE THREAD

**Issue by 007akuan** [cookieY/Yearning#475]
**Describe the bug** **描述Bug**

连接阿里云DRDS时获取不到数据库列表

**To Reproduce** **如何复现**
如图：
![image](https://user-images.githubusercontent.com/74766271/121638719-0451d180-cabe-11eb-93dd-2ffe1d6de90e.png)

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
权限不足 无法获得元数据

**Comment by 007akuan** [comment]
> 权限不足 无法获得元数据

权限是有的，好像是drds获取元数据的方式和普通rds的方式不同
