### ISSUE TITLE
update delete sql 语法检测总是提示 an error in your SQL syntax

### ISSUE THREAD

**Issue by king-of-pigs** [cookieY/Yearning#477]
浏览器: 
![image](https://user-images.githubusercontent.com/41321823/122504538-1509c680-d02d-11eb-96bb-3123ce0a832e.png)

操作系统: docker

Yearning版本: 2.3.3

问题描述:
 我用最新版，遇到个问题，我提交dml工单，update  和delete  相关sql 在语法检测过程中总是提示
 Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UPDATE runoob_tbl SET runoob_title='学习 C++' WHERE runoob_id=1' at line 1

实际sql在命令行执行是没有问题，也是最基础的sql；

截图信息:
![image](https://user-images.githubusercontent.com/41321823/122508051-ea6f3c00-d033-11eb-83c0-870e29017752.png)
![image](https://user-images.githubusercontent.com/41321823/122508289-52be1d80-d034-11eb-8142-4980478d2333.png)

日志截图:
![image](https://user-images.githubusercontent.com/41321823/122508246-3a4e0300-d034-11eb-9e7c-49341f1f0b0e.png)

**Comment by king-of-pigs** [comment]
我尝试更换了数据库，发现执行sql的数据库为5.5.60 版本的mysql时候会有问题，用5.6.42 的库就问题；
yeraning的数据库为5.7.24

**Comment by cookieY** [comment]
Yearning 无法支持5.6以下的数据库
