### ISSUE TITLE
设置了审核流程在提交工单时还是没办法看到库名

### ISSUE THREAD

**Issue by 12gameRensheng** [cookieY/Yearning#478]
**Describe the bug** **描述Bug**
设置了审核流程在提交工单时还是没办法看到库名

**To Reproduce** **如何复现**
![image](https://user-images.githubusercontent.com/45571957/122554241-528d4480-d06b-11eb-847c-492cc365eee9.png)
![image](https://user-images.githubusercontent.com/45571957/122554303-646ee780-d06b-11eb-89c8-f1fa67d56fb4.png)

**Expected behavior** **期望的结果**
如何设置库名 
并且可以进行选择出来

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**
 - linux
 -  chrome,
 - 2.3.3

**Additional context** **其他**

**Comment by cookieY** [comment]
检查数据源账户权限

**Comment by 12gameRensheng** [comment]
感谢 已解决
