### ISSUE TITLE
如何定制化验证规则 或者在哪里可以进行配置验证规则

### ISSUE THREAD

**Issue by 12gameRensheng** [cookieY/Yearning#480]
**Describe the bug** **描述Bug**
如何自定义验证规则
表名长度不得超过10
![image](https://user-images.githubusercontent.com/45571957/122750691-6af69c80-d2c1-11eb-8615-251d16fdab1e.png)

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
审核规则页面 自行打开或关闭 规则

**Comment by 12gameRensheng** [comment]
你好 很高兴 数据表长度的问题已经解决了
但是创建表时 字符集 和 长度也不允许 我找了一圈管理=》 审核规则里面的开关 没有看到对应的信息
![image](https://user-images.githubusercontent.com/45571957/123099221-92399f00-d464-11eb-9175-1ab9da394280.png)

![image](https://user-images.githubusercontent.com/45571957/123099366-b39a8b00-d464-11eb-8fef-acfb087f927f.png)
