### ISSUE TITLE
是否集成了 inception or gh-ost

### ISSUE THREAD

**Issue by hahait** [cookieY/Yearning#481]
### 想咨询如下问题：
1. 目前 yearning 的 db 操作，是集成了 inception 还是 gh-ost，或者完全是自定义的？
2. 使用 pt-osc，是需要自己安装这个工具吗 ？

谢谢

**Comment by cookieY** [comment]
1.审核与inception无关, gh-ost未集成
2.自己安装

**Comment by hahait** [comment]
> 1.审核与inception无关, gh-ost未集成
> 2.自己安装

好的，非常感谢
