### ISSUE TITLE
insert 失败，但页面扔提示”已执行“，而不是 ”执行失败“

### ISSUE THREAD

**Issue by hahait** [cookieY/Yearning#483]
**描述Bug: 页面显示问题，insert 执行失败，页面上显示"已执行"**

**如何复现: 提交一个工单，insert 语句中对唯一索引列的设置个重复值，并且执行**

**期望的结果: 页面能正常显示实际的执行结果**

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/20253863/123250891-2d8e4b00-d51d-11eb-96fa-39935ae1cb01.png)

![image](https://user-images.githubusercontent.com/20253863/123251545-e8b6e400-d51d-11eb-8e56-01fcb3c8bd21.png)

**Desktop (please complete the following information):** **环境**
 - OS: debain 10
 - Browser: chrom
 - Version: 2.3.3
 - 部署方式: docker 镜像，k8s 部署

**Comment by cookieY** [comment]
最新的2.3.3.1 无此问题

**Comment by hahait** [comment]
> 最新的2.3.3.1 无此问题

刚升级了 2.3.3.2，可是此问题还是存在的；2.3.3.1 找不到相关的 releases 了

**Comment by cookieY** [comment]
> > 最新的2.3.3.1 无此问题
> 
> 刚升级了 2.3.3.2，可是此问题还是存在的；2.3.3.1 找不到相关的 releases 了

自行编译的？

**Comment by hahait** [comment]
> > > 最新的2.3.3.1 无此问题
> > 
> > 
> > 刚升级了 2.3.3.2，可是此问题还是存在的；2.3.3.1 找不到相关的 releases 了
> 
> 自行编译的？

不是的，使用 release 中的；然后 docker build；
