### ISSUE TITLE
MySQL插入datetime类型的数值会无法通过自动审核，报错错误的datetime值:'2021-06-30 11:12:12'(字段 'dataexchange_01.test.create_at') 错误的datetime值:'2021-06-30 11:12:12'(字段 'dataexchange_01.test.updated_at')

### ISSUE THREAD

**Issue by xinge-1** [cookieY/Yearning#486]
报错信息：
错误的datetime值:'2021-06-30 11:12:12'(字段 'dataexchange_01.test.create_at')
错误的datetime值:'2021-06-30 11:12:12'(字段 'dataexchange_01.test.updated_at')

表结构：
![image](https://user-images.githubusercontent.com/76768331/123895365-4de15e00-d992-11eb-87d0-57d8ac376417.png)

帮忙看下是啥问题导致的

**Comment by xinge-1** [comment]
CREATE TABLE `test`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `create_at` datetime(0) NULL DEFAULT NULL,
  `updated_at` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

**Comment by cookieY** [comment]
版本号

**Comment by xinge-1** [comment]
![image](https://user-images.githubusercontent.com/76768331/124056436-4c7a6900-da58-11eb-889d-79fd77d5738b.png)

**Comment by cookieY** [comment]
升级到最新版本

**Comment by xinge-1** [comment]
升级到最新版本Yearning-2.3.3.2启动之后 也发生了报错
![image](https://user-images.githubusercontent.com/76768331/124059051-0a075b00-da5d-11eb-82e2-b68441c45e36.png)

插入sql
insert into
  test(name, create_at, updated_at)
values(
    '小米',
    '2021-07-01 11:08:01',
    '2021-07-01 11:08:01'
  );

**Comment by xinge-1** [comment]
date数据类型不再要求默认值必须为现在日期,仅需符合日期格式规范
你好 这次更新是否没包括datetime字段类型呢？

**Comment by cookieY** [comment]
> date数据类型不再要求默认值必须为现在日期,仅需符合日期格式规范
> 你好 这次更新是否没包括datetime字段类型呢？

已定位
