### ISSUE TITLE
工单审核转交失败

### ISSUE THREAD

**Issue by zhoufuke** [cookieY/Yearning#491]
**Describe the bug** **描述Bug**
Aa用户提交工单，Ab用户审核，Ac用户执行。
Aa提交工单到Ab为成功，Ab审核通过后转交Ac提示成功，但是实际为失败。
打印日志报错为：
```
(/Users/henryyee/Yearning-go/src/handler/order/audit/impl.go:25) 
[2021-07-14 15:52:00]  Error 3141: Invalid JSON text in argument 1 to function cast_as_json: "Invalid value." at position 0. 
```

**Screenshots** **截图**
用户权限：
![image](https://user-images.githubusercontent.com/30163846/125589544-e99faa97-b0f5-4779-8f4d-eee705c672ed.png)

流程模板：
![image](https://user-images.githubusercontent.com/30163846/125589623-27f5421f-6dee-453f-9b81-2c3435c36023.png)

流程转交记录：
![image](https://user-images.githubusercontent.com/30163846/125589771-5564d816-a1c4-4dfa-9ff3-e0465b0e8848.png)

在Ab向Ac转交后报错：
![image](https://user-images.githubusercontent.com/30163846/125589946-7a7343ce-f42f-45f1-9840-d778d39c8f44.png)

版本为：
![image](https://user-images.githubusercontent.com/30163846/125590381-21f312d1-5f9d-4959-9b8f-e820b2176eeb.png)

**Comment by cookieY** [comment]
![image](https://user-images.githubusercontent.com/22343354/125721740-7553c2d7-bbf5-498e-b2f9-bb78185266e9.png)

**Comment by zhoufuke** [comment]
mysql换成5.7.25版本可以了。

当撤销工单时可否不做删除操作？只做标记来终止流转。

**Comment by cookieY** [comment]
> mysql换成5.7.25版本可以了。
> 
> 当撤销工单时可否不做删除操作？只做标记来终止流转。

后面会持续优化

**Comment by zhoufuke** [comment]
感谢回复
