### ISSUE TITLE
自动任务配置了不生效

### ISSUE THREAD

**Issue by otjoy** [cookieY/Yearning#492]
自动任务配置了不生效

配置了自动任务以后，提工单，还是不能自动审批delete语句

![image](https://user-images.githubusercontent.com/39723623/125659580-43760092-981d-4515-9fcd-e0902f64b615.png)

**Comment by cookieY** [comment]
请告知 具体版本

**Comment by otjoy** [comment]
Yearning 2.3.4

**Comment by cookieY** [comment]
如图可见你这边影响行数为0 导致任何语句都无法通过。0目前在autoTask中暂时无法表示为无限制

**Comment by otjoy** [comment]
> 如图可见你这边影响行数为0 导致任何语句都无法通过。0目前在autoTask中暂时无法表示为无限制

我配置的时候是设置了行数的，但是保存后，就自动变回0了 。
