### ISSUE TITLE
rpc error: code = Unknown desc = 仅支持Query语句!

### ISSUE THREAD

**Issue by kuun993** [cookieY/Yearning#493]
**描述**
使用Yearning-2.3.4-linux-amd64.zip安装的能正常使用show命令
使用juno调试的报错 “rpc error: code = Unknown desc = 仅支持Query语句!”

**如何复现**
使用juno调试，查询 show databases

**截图**
正常
![image](https://user-images.githubusercontent.com/21998194/126252177-74557d60-db8a-44b5-8a6f-2a5a7d83c7f4.png)

juno调试报错
![image](https://user-images.githubusercontent.com/21998194/126252493-32a69bcc-c38f-4f8d-8935-109d2525dcd4.png)

 **环境**
 - OS:  juno: Linux, other: windows
 - Browser:  Google Chrome v91.0.4472.164

希望有时间能帮忙看下，谢谢

**Comment by cookieY** [comment]
由于show 命令可以查看到系统参数 所以暂时禁用 后续版本将会细分show命令的检测
