### ISSUE TITLE
两台笔记本，chrome和edge都是，一登陆页面无响应，啥情况？

### ISSUE THREAD

**Issue by ShisanXing** [cookieY/Yearning#498]
**Describe the bug** **描述Bug**

卡死在登陆页面

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by ShisanXing** [comment]
复现方式：用笔记本自带的屏幕登录卡死；外接大号显示器就可以登陆，麻烦查一下你界面上哪里写死循环了

**Comment by cookieY** [comment]
可更换火狐浏览器使用
