### ISSUE TITLE
unicode is an undefined name in Python 3

### ISSUE THREAD

**Issue by cclauss** [cookieY/Yearning#5]
__unicode__ was removed from Python 3 because all strs are Unicode.

flake8 testing of https://github.com/cookieY/Yearning on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./install/cursors.py:354:36: F821 undefined name 'unicode'
                if isinstance(msg, unicode):
                                   ^
1     F821 undefined name 'unicode'
```

**Comment by cookieY** [comment]
@cclauss  thanks for your reminder. the cursors.py is part of the pymysql package.  I think it was written for compatibility with python2 and python3。
