### ISSUE TITLE
v2.3.5包里实际是v2.3.4的可执行文件

### ISSUE THREAD

**Issue by wangxu31** [cookieY/Yearning#506]
大佬！https://github.com/cookieY/Yearning/releases/download/2.3.5/Yearning-2.3.5-linux-amd64.zip
v2.3.5的包，下载下来，版本是v2.3.4啊
@fixed: 开启允许select子句时 DML包含子查询时仍无法通过审核的问题 这个问题还是存在

**Comment by wangxu31** [comment]
为什么把bug标签移除掉啊，这个问题还在呢 @CookieYe ，我又重新下了zip包，解出来，Yearning -V，显示Version: 2.3.4 Neptune，进到网页里进行select语句的工单提交，提示不支持的DML。

**Comment by wangxu31** [comment]
麻烦check下，换个最近的2.3.5的包到链接里呗，摆脱大佬了🙏

**Comment by cookieY** [comment]
你可以给一份测试用例出来
