### ISSUE TITLE
勾选启用ldap 时测试连接失败，不勾选时测试连接成功

### ISSUE THREAD

**Issue by zdwork** [cookieY/Yearning#507]
**Describe the bug** **描述Bug**

勾选启用ldap 时测试连接失败，不勾选时测试连接成功

**To Reproduce** **如何复现**

勾选启用ldap 时测试连接失败，不勾选时测试连接成功

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by 344310362** [comment]
还没解决怎么就关了，最新版本 3.0.1 还有这个问题呢
