### ISSUE TITLE
网络卡顿时，开发人员多次点击提交按钮会造成工单多次提交

### ISSUE THREAD

**Issue by otjoy** [cookieY/Yearning#508]
**Describe the bug** **描述Bug**
当有网络延迟，提交工单页面出现卡顿，提交人员会不自觉地多点几次提交按钮，等过了几秒，网络恢复时，就出现提交了多个相同的工单。一不注意，审核人员就可能重复执行。

**To Reproduce** **如何复现**
提交工单时有网络延迟，出现卡顿，多点几次提交按钮。

**Expected behavior** **期望的结果**
仅收到一个工单

**Screenshots** **截图**
![1629439859(1)](https://user-images.githubusercontent.com/39723623/130188427-bc662cef-32f0-4fc2-bd7e-8379545977ce.png)

**Comment by cookieY** [comment]
v2.3.6 done

**Comment by otjoy** [comment]
AWSL
