### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by drscrewdriver** [cookieY/Yearning#509]
**Describe the bug** **描述Bug**
建表失败500
CREATE TABLE `widget_user_bank_institution_relation` (
  `id` bigint(20) NOT NULL,
  `channel_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '渠道id',
  `username` varchar(255) NOT NULL DEFAULT '' COMMENT '用户唯一标识',
  `nickname` varchar(255) NOT NULL DEFAULT '' COMMENT '昵称',
  `bank_institution_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '银行机构id',
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `creator` varchar(45) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `modifier` varchar(45) NOT NULL DEFAULT 'system' COMMENT '修改人',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '版本号，用于乐观锁处理',
  `is_deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标识。1：此记录已经删除',
  PRIMARY KEY (`id`),
  KEY `username` (`username`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户银行机构关系';

相关错误代码
yee v0.2.1 [Critical] 2021-08-25 06:32:44 (/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.2/middleware/recovery.go:33) [PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference Traceback:
	/usr/local/go/src/runtime/panic.go:212
	/usr/local/go/src/runtime/signal_unix.go:737
	/Users/henryyee/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20210601035937-ccaefa2a3ddf/types/datum.go:96
	/Users/henryyee/Yearning-go/src/parser/check.go:885
	/Users/henryyee/Yearning-go/src/parser/ddl.go:259
	/Users/henryyee/Yearning-go/src/parser/parser.go:96
	/Users/henryyee/Yearning-go/src/parser/parser.go:187
	/Users/henryyee/Yearning-go/src/parser/parser.go:249
	/Users/henryyee/Yearning-go/src/handler/fetch/fetch.go:191
	/Users/henryyee/Yearning-go/src/apis/fetch.go:45
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.2/context.go:106
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.2/middleware/gzip.go:66
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.2/context.go:106
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.2/middleware/recovery.go:38
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.2/context.go:106
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.2/middleware/logger.go:57
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.2/context.go:106
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.2/middleware/cors.go:96
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.2/context.go:106
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.2/yee.go:196
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.2/yee.go:128
	/usr/local/go/src/net/http/server.go:2888
	/usr/local/go/src/net/http/server.go:1953
	/usr/local/go/src/runtime/asm_amd64.s:1372
yee v0.2.1 [Error] 2021-08-25 06:32:44 (/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.2/context.go:123) /api/v2/fetch/test Internal Server Error
yee v0.2.1 [Warn] 2021-08-25 06:32:44 "url":"/api/v2/fetch/test" "method":"PUT" "status":500 "protocol":"HTTP/1.0" "remote_ip":"192.168.0.1" "bytes_in": "1161 bytes" "bytes_out": "21 bytes"

**To Reproduce** **如何复现**

操作建表

**Expected behavior** **期望的结果**

正常建立表格的返回

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
请先告知版本号是否为最新版本
