### ISSUE TITLE
最新的2.3.5 镜像版本运行环境问题

### ISSUE THREAD

**Issue by fanqinghui** [cookieY/Yearning#513]
容器化运行一下语句，报错了
运行语句
docker run  -it -p8000:8000 -e MYSQL_USER=root -e MYSQL_ADDR=localhost:3306 -e MYSQL_PASSWORD=root-e MYSQL_DB=yearning zhangsean/yearning:2.3.5
报错信息：
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./Yearning": stat ./Yearning: no such file or directory: unknown.
我的docker版本是20.10.7
另外在k8s里运行也出OCI问题，k8s版本是V18.4

**Comment by cookieY** [comment]
Yearning 并没有官方的镜像,请自行根据dockefile进行镜像构建
