### ISSUE TITLE
数据源编辑保存信息时，密码保存了******

### ISSUE THREAD

**Issue by wangxu31** [cookieY/Yearning#519]
数据源已经配置好，点击编辑，什么都不改直接保存信息，密码实际入库保存了******

**Comment by wangxu31** [comment]
<img width="722" alt="截屏2021-09-16 09 42 13" src="https://user-images.githubusercontent.com/21062113/133535803-c9d1c6a2-ca7a-4c8a-a2d1-f0ea746d911a.png">
<img width="1081" alt="30C367CB-D220-4D1E-94FB-4D2526EEDE17" src="https://user-images.githubusercontent.com/21062113/133535802-4c51dc82-55ae-44a7-8884-3d72835bfd39.png">

**Comment by cookieY** [comment]
v2.3.6 done
