### ISSUE TITLE
禁止改变列顺序

### ISSUE THREAD

**Issue by GarrettQi** [cookieY/Yearning#520]
**Describe the bug** **描述Bug**
禁止改变列顺序(列'test1.namea').

**To Reproduce** **如何复现**
修改表结构-添加字段：alter table test1 add namea varchar(20) after name;
错误信息：禁止改变列顺序(列'test1.namea').

**Expected behavior** **期望的结果**

**Screenshots** **截图**

![image](https://user-images.githubusercontent.com/18721697/133562527-75a137b8-329e-4f7b-a541-719ee2898b9f.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
审核规则内打开对应审核限制

**Comment by apollo-user** [comment]
Version: 3.0.6 Uranus
请问下如上版本是否没有这个规则呢？在审核规则里面没有找到有关列顺序的关键字 @cookieY 
![image](https://github.com/cookieY/Yearning/assets/19165162/d00df84d-d30c-4cd3-9665-281c369a8467)
