### ISSUE TITLE
SELECT INTO @variable报错

### ISSUE THREAD

**Issue by kuangzhilu** [cookieY/Yearning#523]
**Describe the bug** **描述Bug**
SELECT INTO @variable;语句检测报错

**To Reproduce** **如何复现**
SELECT 5 INTO @verifycodeserverid;

**Expected behavior** **期望的结果**
期望能支持SELECT INTO @variable

**Screenshots** **截图**
![图片](https://user-images.githubusercontent.com/45584744/135271240-11571ea7-a218-410b-ab60-bb4087407da7.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
不支持变量
