### ISSUE TITLE
DDL创建表时，检测时弹窗报状态码500错误

### ISSUE THREAD

**Issue by a429390237z** [cookieY/Yearning#524]
**Describe the bug** **描述Bug**
DDL创建表时，表中时间字段默认值为 CURRENT_TIMESTAMP，检测语句时弹窗报状态码500错误。同时日志中有报错：
yee v0.2.3 [Critical] 2021-10-18 17:03:25 (/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.3/middleware/recovery.go:33) [PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference Traceback:
	/usr/local/go/src/runtime/panic.go:212
	/usr/local/go/src/runtime/signal_unix.go:737
	/Users/henryyee/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20210601035937-ccaefa2a3ddf/types/datum.go:96
	/Users/henryyee/Yearning-go/src/parser/check.go:885
	/Users/henryyee/Yearning-go/src/parser/ddl.go:259
	/Users/henryyee/Yearning-go/src/parser/parser.go:96
	/Users/henryyee/Yearning-go/src/parser/parser.go:187
	/Users/henryyee/Yearning-go/src/parser/parser.go:249
	/Users/henryyee/Yearning-go/src/handler/fetch/fetch.go:191
	/Users/henryyee/Yearning-go/src/apis/fetch.go:45
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.3/context.go:106
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.3/middleware/gzip.go:66
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.3/context.go:106
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.3/middleware/recovery.go:38
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.3/context.go:106
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.3/middleware/logger.go:57
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.3/context.go:106
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.3/middleware/cors.go:96
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.3/context.go:106
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.3/yee.go:196
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.3/yee.go:128
	/usr/local/go/src/net/http/server.go:2888
	/usr/local/go/src/net/http/server.go:1953
	/usr/local/go/src/runtime/asm_amd64.s:1372
yee v0.2.3 [Error] 2021-10-18 17:03:25 (/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.2.3/context.go:123) /api/v2/fetch/test Internal Server Error

尝试从源码编译安装yearning，发现此错误来自：juno

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1306ab4]

goroutine 16 [running]:
github.com/pingcap/tidb/types.(*Datum).Kind(...)
        /Users/henryyee/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20210601035937-ccaefa2a3ddf/types/datum.go:96
Juno/parser.(*YerningAuditOrder).mysqlCheckField(0xc000122630, 0xc00010e240, 0xc0001de3c0, 0x1)
        /Users/henryyee/Juno/parser/check.go:885 +0x7f4
Juno/parser.(*YerningAuditOrder).checkCreateTableResult(0xc000122630, 0xc0000ca8f0)
        /Users/henryyee/Juno/parser/ddl.go:257 +0x2950
Juno/parser.YerningAuditOrder.checkDDLRole(0xc000436700, 0x6df, 0x0, 0xc00019c458, 0x8, 0x0, 0x0, 0xc0000b2090, 0x2b, 0xc00019c5e0, ...)
        /Users/henryyee/Juno/parser/parser.go:104 +0x735
Juno/parser.(*YerningAuditOrder).Parser(0xc000123788, 0x1851758, 0xc0000ca8f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/henryyee/Juno/parser/parser.go:187 +0x1e8
Juno/parser.(*YerningAuditOrder).New(0xc000123788, 0x2, 0x0, 0x203000, 0xc0004707b0, 0x40da3b)
        /Users/henryyee/Juno/parser/parser.go:249 +0x3cd
Juno/libraGrpc/server.(*Ser).OrderDeal(0x28df078, 0x18459c0, 0xc00040c750, 0xc00010e000, 0x0, 0x0, 0x0)
        /Users/henryyee/Juno/libraGrpc/server/server.go:190 +0x413
Juno/libraGrpc/proto._Juno_OrderDeal_Handler(0x14f7f40, 0x28df078, 0x18459c0, 0xc00040c750, 0xc00019a360, 0x0, 0x18459c0, 0xc00040c750, 0xc00008f000, 0x742)
        /Users/henryyee/Juno/libraGrpc/proto/detection.pb.go:559 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001c80, 0x1856478, 0xc000001080, 0xc00026c100, 0xc00040c9f0, 0x2844520, 0x0, 0x0, 0x0)
        /Users/henryyee/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc000001c80, 0x1856478, 0xc000001080, 0xc00026c100, 0x0)
        /Users/henryyee/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00019c040, 0xc000001c80, 0x1856478, 0xc000001080, 0xc00026c100)
        /Users/henryyee/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/henryyee/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xa5

**To Reproduce** **如何复现**
DDL创建表时，带有包含“CURRENT_TIMESTAMP”字段时：
`created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
检测语句时报错500。

**Expected behavior** **期望的结果**
检测正常，无错误发生。

**Screenshots** **截图**

![err1](https://user-images.githubusercontent.com/20034836/137703394-33810536-8c3c-4384-8ccc-ccf0ff58fe1c.png)
![err2](https://user-images.githubusercontent.com/20034836/137703395-a27392d5-56e7-4167-a208-b1100cb73732.png)

**Desktop (please complete the following information):** **环境**
 - OS: Centos7.4
 - Browser: chrome
 - Version: 94.0.4606.61

**Additional context** **其他**

**Comment by cookieY** [comment]
v2.3.6 done
