### ISSUE TITLE
arm架构的机器能编译这个程序吗，我编译报错

### ISSUE THREAD

**Issue by whoami-z** [cookieY/Yearning#536]
![image](https://user-images.githubusercontent.com/85213985/143208515-a2bcfd1f-bd68-4389-9818-2d83fe160648.png)

# github.com/golang-jwt/jwt
../go/pkg/mod/github.com/golang-jwt/jwt@v3.2.2+incompatible/ecdsa.go:135:4: r.FillBytes undefined (type *big.Int has no field or method FillBytes)
../go/pkg/mod/github.com/golang-jwt/jwt@v3.2.2+incompatible/ecdsa.go:136:4: s.FillBytes undefined (type *big.Int has no field or method FillBytes)

x86的机子都能编译，但是arm架构编译始终报错，看看能解决吗

**Comment by cookieY** [comment]
@whoami-z  https://github.com/golang-jwt/jwt/issues/90

**Comment by whoami-z** [comment]
谢谢
