### ISSUE TITLE
能否增加工单导出或转提环境的功能（sql版本控制）

### ISSUE THREAD

**Issue by FE-wangjb** [cookieY/Yearning#537]
能否增加这样一个功能：根据历史工单，复选框选择之后将工单中执行过的sql依据执行顺序导出一个sql文件，用于数据库sql版本控制？
或者已执行的工单可以直接切环境执行：比如测试环境执行了这个工单的sql，后转生产的时候可以直接继承这个工单的内容直接提交审核和执行？

**Comment by LockiJiang** [comment]
> 能否增加这样一个功能：根据历史工单，复选框选择之后将工单中执行过的sql依据执行顺序导出一个sql文件，用于数据库sql版本控制？ 或者已执行的工单可以直接切环境执行：比如测试环境执行了这个工单的sql，后转生产的时候可以直接继承这个工单的内容直接提交审核和执行？

我也觉这个需求会比较有用
