### ISSUE TITLE
密码输入框有限制但实际测试链接都成功了

### ISSUE THREAD

**Issue by Alceatraz** [cookieY/Yearning#538]
**Describe the bug** **描述Bug**

1：密码包含不允许的字符，但是测试链接都已经成功了
2：改个密码以后，测试链接成功，可以点击确认，但是报错

**To Reproduce** **如何复现**

非16位，包含^的密码

**Expected behavior** **期望的结果**

如同测试链接按钮一样，正确保存数据源

**Screenshots** **截图**

![QQ截图20211130093711](https://user-images.githubusercontent.com/8266702/143969912-a8b8d9bd-b0b8-458f-a2bd-828d9769f6e8.png)

![QQ截图20211130093846](https://user-images.githubusercontent.com/8266702/143970011-d1145a8f-ed60-4870-b95f-a2f75adc4df9.png)

**Desktop (please complete the following information):** **环境**
 - OS: [e.g. iOS] Win10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 96.0.4664.45

**Additional context** **其他**

**Comment by cookieY** [comment]
测试连接暂时没有做规则校验的
