### ISSUE TITLE
Docker compose build error 

### ISSUE THREAD

**Issue by 631068264** [cookieY/Yearning#539]
**Describe the bug** **描述Bug**
 => [2/5] COPY Yearning  /opt/Yearning                                                                                                                                 0.4s
 => [3/5] COPY conf.toml /opt/conf.toml                                                                                                                                0.3s
 => ERROR [4/5] RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.12/main/" > /etc/apk/repositories &&       apk add --no-cache tzdata libc6-compat &&       ln -sf /us  75.7s
------                                                                                                                                                                      
 > [4/5] RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.12/main/" > /etc/apk/repositories &&       apk add --no-cache tzdata libc6-compat &&       ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&       echo "Asia/Shanghai" >> /etc/timezone &&       echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf:
#8 0.589 fetch http://mirrors.ustc.edu.cn/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
#8 75.61 WARNING: Ignoring http://mirrors.ustc.edu.cn/alpine/v3.12/main/: network error (check Internet connection and firewall)
#8 75.61 ERROR: unable to select packages:
#8 75.61   libc6-compat (no such package):
#8 75.61     required by: world[libc6-compat]
#8 75.61   tzdata (no such package):
#8 75.61     required by: world[tzdata]
------
executor failed running [/bin/sh -c echo "http://mirrors.ustc.edu.cn/alpine/v3.12/main/" > /etc/apk/repositories &&       apk add --no-cache tzdata libc6-compat &&       ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&       echo "Asia/Shanghai" >> /etc/timezone &&       echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf]: exit code: 2

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**
 - OS:  osx
 - Version Yearning-2.3.5-linux-amd64

**Additional context** **其他**

**Comment by chaiyd** [comment]
https://github.com/chaiyd/docker/tree/master/yearning

**Comment by cookieY** [comment]
#540
