### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ErousZ** [cookieY/Yearning#541]
**Describe the bug** **描述Bug**
DDL建表语句 int类型默认值为负数时候检测出现500错误

**To Reproduce** **如何复现**
CREATE TABLE `test` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data int(11) NULL default -1 COMMENT '层级',
  PRIMARY KEY (`id`) USING BTREE USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 COMMENT = 'test' ROW_FORMAT = Dynamic;

**Expected behavior** **期望的结果**
500 ERROR

**Screenshots** **截图**
![图片](https://user-images.githubusercontent.com/96157081/146110608-2b8ea0a9-bc65-4540-adf3-02f81a93ad2a.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
@ErousZ 正在开发的新版审核引擎测试中不存在该问题此问题将随Yearning 3.0版本同步修复

**Comment by caijianhui** [comment]
> @ErousZ 正在开发的新版审核引擎测试中不存在该问题此问题将随Yearning 3.0版本同步修复

感谢。大概什么时候会发布

**Comment by cookieY** [comment]
> > @ErousZ 正在开发的新版审核引擎测试中不存在该问题此问题将随Yearning 3.0版本同步修复
> 
> 感谢。大概什么时候会发布

年后
