### ISSUE TITLE
部署完，测试sql语句就报错

### ISSUE THREAD

**Issue by linsihao7788** [cookieY/Yearning#545]
**Describe the bug** **描述Bug**
执行select * from cmdn_host;
报错不支持DML语句

**Expected behavior** **期望的结果**
能正常执行sql语句

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/46431972/148527652-4e322be3-0721-49a8-89a0-b6756f78a93c.png)

**Desktop (please complete the following information):** **环境**
 - OS: centos7
 - Browser：chrome
 - Version：2.3.5

**Comment by ErousZ** [comment]
界面上都写了dml工单 当然只能填写dml语句，查询语句去查询菜单执行

**Comment by linsihao7788** [comment]
好的，谢谢
