### ISSUE TITLE
Bug Report:  赋予用户超级管理员,用户不能修改任何人的权限

### ISSUE THREAD

**Issue by XzBuleSky** [cookieY/Yearning#547]
**Describe the bug** **描述Bug**
我已是超级管理员角色, 但无法修改任何用户的权限,包括自己. 
报错: 非法传参.  而 admin用户却没该问题出现.
**Expected behavior** **期望的结果**

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/33563050/148911669-d52c5dd8-3abf-426e-9544-400d1661e734.png)

![image](https://user-images.githubusercontent.com/33563050/148911023-44af9cc5-81bd-4f45-a502-9485368bb61a.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
超级管理员强制为admin用户无法通过修改其他用户获得超级管理员权限
