### ISSUE TITLE
left join 查询左表有数据字段不显示

### ISSUE THREAD

**Issue by Mrs-Cui** [cookieY/Yearning#551]
select a.*, b.* from a left join b 
on a.id = b.id and a.id1 = b.id1 
where a.id3 >= 1000

当 on 包含两个以上条件时左表数据就会有数据字段值不显示。

**Comment by cookieY** [comment]
你好 请问有具体的复现案例嘛

**Comment by cookieY** [comment]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/22343354/171355700-6985bc40-d207-4d27-8fb9-4f49d8544b4a.png">
