### ISSUE TITLE
UI交互对服务器带宽消耗太高

### ISSUE THREAD

**Issue by qaz4042** [cookieY/Yearning#552]
**Describe the bug** **描述Bug**
![image](https://user-images.githubusercontent.com/29392228/150073853-50ed00a2-205f-4cc1-9ad0-1c53a493f9c8.png)

**To Reproduce** **如何复现**
1.页面很多页面/按钮的切换都自动刷新页面,
2.刷新js和css都重新加载(浏览器开启缓存的情况下)
3.部署在带宽低的主机,,刷新经常等一分钟以上

**Expected behavior** **期望的结果**
1.页面除非按F5,不自动刷新
2.刷新默认走浏览器缓存,不重新下载
3.前端包可以尽可能精简,或者CDN一下

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
1.vue走的是虚拟dom只有在打开页面初始化的时候才会加载js与css文件,所以不存在每点一个页面就加载js和css文件的问题
2.浏览器只要不是古董级版本都支持disk cache。只要js文件没有变化就不会重新下载
3.前端工程化编辑后的文件才可以被放进CDN,这应该是使用者根据自己的情况自己去走CDN的事情。
tips：跟Jquery不一样

**Comment by qaz4042** [comment]
http://101.34.71.206:8000/&nbsp; &nbsp;
 用户名: admin 
密码:Yearning_admin 


你可以试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Henry ***@***.***&gt;; 
发送时间: 2022年1月20日(星期四) 中午11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cookieY/Yearning] UI交互对服务器带宽消耗太高 (Issue #552)





 
1.vue走的是虚拟dom只有在打开页面初始化的时候才会加载js与css文件,所以不存在每点一个页面就加载js和css文件的问题
 2.浏览器只要不是古董级版本都支持disk cache。只要js文件没有变化就不会重新下载
 3.前端工程化编辑后的文件才可以被放进CDN,这应该是使用者根据自己的情况自己去走CDN的事情。
 tips：跟Jquery不一样
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mr-hiddenaire** [comment]
在1MB/s 机器上，页面加载确实太慢了，大概得需要一分钟左右的时间，这个真是让人头疼。

**Comment by cookieY** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/22343354/157634021-d13b1ace-de37-4d76-b27a-43e21b4a2ec7.png">

**Comment by gundamff** [comment]
登陆页有个
front/assets/media/groud.38664d3a.mp4  5.9M
没这个必要吧。。 
我们部署到云平台上，用堡垒机访问首页能把堡垒机直接卡死
