### ISSUE TITLE
数据库密码不允许使用 ? @ ^ $ 等特殊字符 然而AWS-AuroraDB 是允许使用的

### ISSUE THREAD

**Issue by Dr-Shiki** [cookieY/Yearning#555]
**Describe the bug** **描述Bug**

在添加AWS AuroraDB（mysql的aws saas服务）时 因为我们的密码带有 ? @ ^ $ 特殊字符 无法添加
但是测试连接可以成功

**To Reproduce** **如何复现**
添加数据库时使用带有  ? @ ^ $ 特殊字符 的用户密码登录

**Expected behavior** **期望的结果**
成功添加

**Screenshots** **截图**
<img width="317" alt="image" src="https://user-images.githubusercontent.com/29034114/155477281-f2d24d53-8388-4192-9509-5bcaf94287bc.png">

**Desktop (please complete the following information):** **环境**
 - OS: [Amazon Linux 2]
 - Browser [firefox]
 - Version [lastest]

**Additional context** **其他**

**Comment by cookieY** [comment]
1.限制的主要目的是pt-osc的问题，这个于数据库支不支持没直接关系
2.完全可以创建一个单独的没有@符号的账号用来做更改
