### ISSUE TITLE
注册时已填邮箱，登录后邮箱字段是空的，需要再填一次

### ISSUE THREAD

**Issue by EchoWht** [cookieY/Yearning#559]
**Describe the bug** **描述Bug**
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/10495380/157014615-2e55909e-9e6a-4e07-a935-068423617507.png">
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/10495380/157014652-da60dbca-4efe-48c4-ad0f-8669f22a6693.png">

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by MemoryF** [comment]
我也出现了。
