### ISSUE TITLE
查询-数据库字典中数据库连接下拉框没有数据

### ISSUE THREAD

**Issue by eason0420** [cookieY/Yearning#56]
我是用docker运行的1.3.1
DDL和DML中都可以先选择机房后会有数据库连接，但在查询-数据库字典中，没有机房选择，数据库连接下拉框也没有值，权限组中 这里连接名也没有值可选择。DDL和DML那里是有连接名选择的

数据字典导出权限:   是  否
 连接名:
   全选

**Comment by cookieY** [comment]
没有生成数据库字典

**Comment by eason0420** [comment]
你是指哪里，我的DML和DDL下都是可以看到我创建的几个数据库连接的

**Comment by jimforit** [comment]
数据库连接管理最好可以进行编辑。目前发现如果添加数据库时出错，删除之后再添加，在下拉框无法识别对应机房的数据连接。版本v1.3.4
