### ISSUE TITLE
jwt用户认证的方式有漏洞

### ISSUE THREAD

**Issue by kevin-zhangwen** [cookieY/Yearning#57]
通过修改用户名的方式，即可切换到别的用户上。
当前版本是1.3.0，不过看最新的changelog，并没发现修复该漏洞。
![image](https://user-images.githubusercontent.com/8315913/47140614-487e7b00-d2f1-11e8-8b1c-e19f8e60addd.png)

**Comment by cookieY** [comment]
@kevin-zhangwen 已发现该问题。此问题与token无关和后端取数据有关，虽然可以修改用户名切换别的有用户但只能访问相同角色组的用户数据。还不能进行角色提权操作。后续会进行相关处理

**Comment by kevin-zhangwen** [comment]
这个有修复计划吗？
