### ISSUE TITLE
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

### ISSUE THREAD

**Issue by toxmc** [cookieY/Yearning#570]
**Describe the bug** **描述Bug**

$ docker-compose up                                                        
Pulling yearning-web (chaiyd/yearning:v2.3.5)...
v2.3.5: Pulling from chaiyd/yearning
8572bc8fb8a3: Pull complete
ff00a113193e: Pull complete
5a35aff6307c: Pull complete
4d0ea813af26: Pull complete
Digest: sha256:b0f6ed21a0d8c8efcad5993bc8e661e1c15cc0551e02383ddf7d72f12394f83c
Status: Downloaded newer image for chaiyd/yearning:v2.3.5
Creating yearning ... done
Attaching to yearning
yearning        | qemu: uncaught target signal 11 (Segmentation fault) - core dumped

**To Reproduce** **如何复现**
 
docker-compose.yml 内容如下

version: '3'

services:
  yearning-web:
    image: chaiyd/yearning:v2.3.5
    container_name: yearning
    ports:
      - 8000:8000
    environment:
      - MYSQL_ADDR=172.20.121.82:3306
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_DB=yearning
    restart: unless-stopped

**Expected behavior** **期望的结果**

正常运行

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**
 - OS: 
![image](https://user-images.githubusercontent.com/3990846/163096492-6d0202c4-a095-4a25-8519-f3269ea52d07.png)

$ docker-compose -v     
docker-compose version 1.29.2, build 5becea4c

$ docker -v                  
Docker version 20.10.11, build dea9396

**Comment by cookieY** [comment]
m1 ARM   Image X86
