### ISSUE TITLE
V3.0.0-RC7运行报错

### ISSUE THREAD

**Issue by wuweichi** [cookieY/Yearning#573]
**Describe the bug** **描述Bug**
 [Critical] 2022-04-27 11:04:01 (/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.3.0/middleware/recovery.go:33) [PANIC RECOVER] interface conversion: interface {} is nil, not string Traceback:
	/usr/local/go/src/runtime/iface.go:261
	/Users/henryyee/Yearning-go/src/lib/jwtAuth.go:47
	/Users/henryyee/Yearning-go/src/handler/order/audit/audit.go:53
	/Users/henryyee/Yearning-go/src/handler/order/audit/audit.go:103
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.3.0/context.go:115
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.3.0/middleware/gzip.go:66
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.3.0/context.go:115
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.3.0/middleware/recovery.go:38
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.3.0/context.go:115
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.3.0/middleware/logger.go:58
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.3.0/context.go:115
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.3.0/middleware/cors.go:96
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.3.0/context.go:115
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.3.0/yee.go:207
	/Users/henryyee/go/pkg/mod/github.com/cookie!y/yee@v0.3.0/yee.go:133
	/usr/local/go/src/net/http/server.go:2880
	/usr/local/go/src/net/http/server.go:1931
	/usr/local/go/src/runtime/asm_amd64.s:1582

**To Reproduce** **如何复现**
./Yearning install
./Yearning run

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**
 -Go版本
go version go1.18 linux/amd64

**Additional context** **其他**

**Comment by cookieY** [comment]
当前无法直接复现这个问题 请告知具体复现步骤 谢谢

**Comment by wuweichi** [comment]
> 当前无法直接复现这个问题 请告知具体复现步骤 谢谢

早上从2.3.4升级到3.0.0，晚上重新导入2.3.4的数据库备份后./migrate   然后run起来了
