### ISSUE TITLE
2.3.5版本前端SQL显示bug

### ISSUE THREAD

**Issue by yangjiahui417** [cookieY/Yearning#575]
**Describe the bug** **描述Bug**
DML Insert statement，when paste SQL from file into yearning，the column sequence changed，but i think it is a bug for the front-end display，when i click beautify button，the column is right

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**
the column sequence is same as sql in file

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/63395417/166862501-bb1b5564-a431-4a58-8a51-8dca6e395e3c.png)
![image](https://user-images.githubusercontent.com/63395417/166862179-fd6c04d1-153a-45ef-997f-3b2ec50b4cef.png)
![image](https://user-images.githubusercontent.com/63395417/166862270-a8ce2735-6d26-44cf-85c5-1923c842afd1.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
麻烦把这个符号 发一份 复现一下

**Comment by yangjiahui417** [comment]
```
CREATE TABLE `t1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `a` char(5) DEFAULT NULL,
  `b` int(11) DEFAULT NULL,
  `c` char(5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
INSERT INTO t1 (id,a,b,c) VALUES(NULL,"د",1,"a");
INSERT INTO t1 (id,a,b,c) VALUES(NULL,"﷼",2,"b");
```

**Comment by yangjiahui417** [comment]
> 麻烦把这个符号 发一份 复现一下

![image](https://user-images.githubusercontent.com/63395417/167235146-e706180e-6642-41e9-9bef-72f6fc29565a.png)
![image](https://user-images.githubusercontent.com/63395417/167235163-69ed1a26-07e9-4de7-aded-66e90b629e1b.png)
