### ISSUE TITLE
Yearning3.0.0 R11 ddl语句默认值空字符串，不能通过校验检查

### ISSUE THREAD

**Issue by reacar** [cookieY/Yearning#583]
**Describe** **描述**

ddl语句默认值空字符串，不能通过校验检查

**To Reproduce** **如何复现**
ALTER TABLE `store_apply`.`apply_address` 
ADD COLUMN `receiver_lon_lat` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '收货地址经纬度' AFTER `receiver_address`,
ADD COLUMN `deliver_lon_lat` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '配送地址的经纬度' AFTER `deliver_address`;

过不了检查

**Expected behavior** **期望的结果**
能通过检查

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/22343354/168508096-c1b8dd87-d96a-4fa3-b9b6-52962da51f48.png">
@reacar   我仅开启DDLCheckColumnNullable DDLCheckColumnDefault 两个审核选项

**Comment by cookieY** [comment]
rc12版本已解决
