### ISSUE TITLE
Yearning3.0.0 R11 执行dml，影响行数，不生效

### ISSUE THREAD

**Issue by reacar** [cookieY/Yearning#584]
**Describe** **描述**

执行dml，影响行数，不生效

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**
可以看到影响行数

**Screenshots** **截图**

![image](https://user-images.githubusercontent.com/74039707/168207326-f1b5ddce-418f-4b21-bd72-b9b63c0ed832.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
rc12版本已解决
