### ISSUE TITLE
SQL检测时，varchar类型字段检测有问题

### ISSUE THREAD

**Issue by Tanchusheng** [cookieY/Yearning#585]
**Describe** **描述**
一个字段 字符串长度是17，字段类型varchar(50) ，sql检测时，提示【数据长度'51'大于当前数据类型'varchar(50)】，
数据库的编码是UTF-8

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**
字符串长度是17，字段类型varchar(50) ，可以正常提交，没有提示错误

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/51952562/168299764-acc40e21-1ffe-4b54-9082-f9decc1f1933.png)
![image](https://user-images.githubusercontent.com/51952562/168297576-dcd2c139-7970-40be-84d9-a5a91ca3077a.png)

**Desktop (please complete the following information):** **环境**
 - OS: [e.g. iOS] linux
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] [Yearning-v3.0.0-rc11]

**Additional context** **其他**

**Comment by cookieY** [comment]
rc12版本已解决
