### ISSUE TITLE
查询功能，单个输入框短时间不用，再次执行sql时，整个页面转圈

### ISSUE THREAD

**Issue by zw1987213** [cookieY/Yearning#587]
<img width="675" alt="image" src="https://user-images.githubusercontent.com/3184274/168567519-608806d8-d531-4707-bf9d-a1f4d3f01084.png">

这个是输入框和服务器断开连接了吗？要重新刷新整个页面才可以执行。
设置的会话时间是180分钟。

**Comment by cookieY** [comment]
查询走的是websocket连接 请确保连通

**Comment by zw1987213** [comment]
> 

怎么确保连通，没有关闭，只是切换到其他开发工具，就不能保持连接了吗

**Comment by cookieY** [comment]
rc12版本已解决
