### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by yanghuii** [cookieY/Yearning#589]
**Describe** **描述**

Postgre 数据库可以支持一下吗？Postgre 特有空间处理能力，我们做GIS的选择不是很多。

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**
支持 Postgre SQL

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
Postgre的支持已经在进行开发 暂时还未有上线计划
