### ISSUE TITLE
有同时查询多个数据源的需要要怎么办

### ISSUE THREAD

**Issue by dfdf10086** [cookieY/Yearning#591]
查询审核开启后需要在查询前提交查询申请经由数据源负责人审批通过后方可查询，且同一时间只能申请一个数据源进行查询操作(可申请的数据源为用户其所拥有的query权限数据源)。

现在想同时查询多个数据源有什么办法么？

**Comment by cookieY** [comment]
目前如果开始查询审核则只能查询审核通过的数据源 无法同时查询多个

**Comment by cookieY** [comment]
3.0.1版本后已支持

**Comment by lifang218c** [comment]
我也需要这个功能， 请问啥时候可以支持一下
