### ISSUE TITLE
v3.0.0版本不会初始化数据库数据以及设置项出问题

### ISSUE THREAD

**Issue by jianxuanbing** [cookieY/Yearning#593]
**Describe** **描述**
1、迁移数据库后，LDAP 测试以及保存 一直错误。
2、获取最新镜像安装，不会初始化数据信息，连系统账号都没创建

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/7100363/173325119-0a621a4d-c80f-4243-bd21-41196483c46c.png)
![image](https://user-images.githubusercontent.com/7100363/173325234-3337fd52-021c-46cc-ae2a-705fc2fed6e7.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
请给下后端日志
