### ISSUE TITLE
建表语句回滚执行失败

### ISSUE THREAD

**Issue by likedan130** [cookieY/Yearning#596]
数据库：MySQL
建表语句执行成功后生成的回滚语句包含两个部分，一个删除主键的语句和删表语句，由于建表时主键设置为自增类型，所以执行删除主键语句时报错
![image](https://user-images.githubusercontent.com/11495550/173761535-ac2f4e3c-ed23-4646-a869-9d6319a3151b.png)
问题原因：MySQL主键列中有auto_increment(递增)类型选项。如要删除表中的主键，需要先删除auto_increment类型。
所以回滚语句的生成逻辑中是否需要过滤主键索引，或者为主键索引的drop语句增加alter语句去除主键的自增属性？

**Comment by cookieY** [comment]
数据库版本
