### ISSUE TITLE
npm 和nginx不成功

### ISSUE THREAD

**Issue by ntuwang** [cookieY/Yearning#6]
(yearning) wangchao@wangchao-lyan:~/PycharmProjects/Yearning/webpage$ npm run dev

> deploy@1.0.0 dev /home/wangchao/PycharmProjects/Yearning/webpage
> node build/dev-server.js

module.js:540
    throw err;
    ^

Error: Cannot find module '/home/wangchao/PycharmProjects/Yearning/webpage/build/dev-server.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deploy@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deploy@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wangchao/.npm/_logs/2018-01-08T05_41_27_716Z-debug.log

# 1，npm启动静态资源服务器时候一直报错（node 6.10和node 8.9版本都试了）
# 2，for nginx，webpage/dist/没有这个文件夹啊

**Comment by cookieY** [comment]
@ntuwang npm run dev 之前 npm install 了吗？  dist文件夹被git忽略跟踪了很抱歉。 稍晚我会补上去

**Comment by cookieY** [comment]
@ntuwang dist已添加哦
