### ISSUE TITLE
SQL检测优化

### ISSUE THREAD

**Issue by blylei** [cookieY/Yearning#600]
**Describe** **描述**
在3.0.1版本，SQL编辑窗口写完以后，需要右键检查SQL，可以做一个“SQL检测”的按钮吗

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by codesverve** [comment]
跟我这个问题一样，就是按钮不明显，我之前也以为是个bug

https://github.com/cookieY/Yearning/issues/609

**Comment by cookieY** [comment]
以增加相关提醒文案

**Comment by RainElohim** [comment]
确实需要，太不明显了 ，不知道需要检查 或者流程修改下 自动检测
