### ISSUE TITLE
The number of rows affected by SQL detection is incorrect

### ISSUE THREAD

**Issue by jessekk1** [cookieY/Yearning#606]
**Describe** **描述**
SQL检测的影响行数计算不准确，除id外计算到的值为全表数据量，影响到DML行数的限制规则无法通过。
（最后执行行数是正确的）

**To Reproduce** **如何复现**

where 条件使用除 id 外的其他字段过滤

**Expected behavior** **期望的结果**

正确计算影响行数

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**
 - OS: Windows10
 - Browser: Chrome
 - Version: v3.0.1

**Additional context** **其他**

**Comment by cookieY** [comment]
https://next.yearning.io/feeback.html
