### ISSUE TITLE
日期类型默认值检查报错

### ISSUE THREAD

**Issue by xiaobing2017** [cookieY/Yearning#607]
![image](https://user-images.githubusercontent.com/32701623/176634220-82e917e9-2a1a-4ace-a8d3-df142c6fe2ce.png)
如果所示，目前测试的结果是字段default值必须要加单引号，否则检查不通过，但是对于时间类型的默认值，如果设置为default 'current_timestamp'可以检测通过，但是会执行失败

**Comment by xiaobing2017** [comment]
提示信息是500，缺少明确的错误信息

**Comment by xiaobing2017** [comment]
发现一个现象，应该是3.0.1版本加了字段默认值的限制，默认值必须加引号？如果是日期类型，默认值DEFAULT 'CURRENT_TIMESTAMP'，检测可以通过，但是数据库执行会报错

**Comment by cookieY** [comment]
2.0版本已经不维护了，实测3.0.1没有这个问题

**Comment by cookieY** [comment]
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/22343354/177117260-b9bd1e05-dff7-42f2-9de6-99841d4d5762.png">

**Comment by xiaobing2017** [comment]
![image](https://user-images.githubusercontent.com/32701623/177505962-2360c337-fc5f-4b1f-a7e6-18c4a126b2b1.png)

**Comment by xiaobing2017** [comment]
![image](https://user-images.githubusercontent.com/32701623/177507762-be0bdd70-b6da-46a0-91ba-6390bd77a08b.png)

**Comment by xiaobing2017** [comment]
我相信是没有这个问题的，但是我这报错就很诡异了，是不是配置的不对？

**Comment by cookieY** [comment]
@xiaobing2017 可以下载3.0版本看看
