### ISSUE TITLE
docker-compose up -d 报错

### ISSUE THREAD

**Issue by wasonchung** [cookieY/Yearning#610]
**Describe** **描述**
执行docker-compose up -d 后，yearning容器不断重启，报错如下：
goroutine 1 [running]:
github.com/gookit/gcli/v2/interact.AnswerIsYes({0x0, 0x0, 0xc0007abbc0})
        /Users/henryyee/go/pkg/mod/github.com/gookit/gcli/v2@v2.3.4/interact/read.go:76 +0x16c
github.com/gookit/gcli/v2/interact.Confirm({0x13bf7d8, 0x116f400}, {0x0, 0x0, 0x0})
        /Users/henryyee/go/pkg/mod/github.com/gookit/gcli/v2@v2.3.4/interact/interact.go:25 +0x79
Yearning-go/src/service.Migrate()
        /Users/henryyee/Yearning-go/src/service/migrate.go:59 +0xfd
Yearning-go/cmd.glob..func2(0x305f2a0, {0xc00003a050, 0x0, 0x0})
        /Users/henryyee/Yearning-go/cmd/cmd.go:29 +0x2c
github.com/gookit/gcli/v2.(*Command).execute(0x305f1e0, {0xc00003a050, 0x0, 0x0})
        /Users/henryyee/go/pkg/mod/github.com/gookit/gcli/v2@v2.3.4/cmd.go:243 +0x104
github.com/gookit/gcli/v2.(*App).doRun(0xc00017cf20, {0x7ffdbda7ff10, 0x7}, {0xc00003a050, 0x0, 0x0})
        /Users/henryyee/go/pkg/mod/github.com/gookit/gcli/v2@v2.3.4/app_run.go:173 +0x434
github.com/gookit/gcli/v2.(*App).Run(0xc00017cf20)
        /Users/henryyee/go/pkg/mod/github.com/gookit/gcli/v2@v2.3.4/app_run.go:126 +0x2f8
Yearning-go/cmd.Command()
        /Users/henryyee/Yearning-go/cmd/cmd.go:90 +0x188
main.main()
        /Users/henryyee/Yearning-go/main.go:21 +0x17
是否已将数据库字符集设置为UTF8/UTF8MB4? [yes|no]:

**To Reproduce** **如何复现**
version: '3'

services:
    yearning:
        image: chaiyd/yearning:v3.0.1
        environment:
            MYSQL_USER: yearning
            MYSQL_PASSWORD: ukC2ZkcG_ZTeb
            MYSQL_ADDR: mysql
            MYSQL_DB: yearning
        ports:
            - 8000:8000
        #首次使用请先初始化
        command: /bin/bash -c "./Yearning install"
        volumes:
          - ./conf.toml:/opt/conf.toml
        depends_on:
            - mysql
        restart: always

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ukC2ZkcG_ZTeb
            MYSQL_DATABASE: yearning
            MYSQL_USER: yearning
            MYSQL_PASSWORD: ukC2ZkcG_ZTeb
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
           - ./data/mysql:/var/lib/mysql

**Comment by wasonchung** [comment]
这个问题，我是通过以下方式来解决了：
1. docker compose run yearning bash  进入交互模式，
输入./Yearning install
在出现 是否已将数据库字符集设置为UTF8/UTF8MB4? [yes|no]:
后，输入yes。
等待初始化成功后，输入exit退出容器

2. docker-compose down 将mysql容器关掉
3. docker-compose up -d

**Comment by chaiyd** [comment]
可以告知下，docker 版本，以及使用的Linux发行版吗？

**Comment by wasonchung** [comment]
本机用的是MAC 10.15.4。 docker destop Version4.6.1 (76265)
<img width="648" alt="image" src="https://user-images.githubusercontent.com/37434329/177240146-2b03552a-9b1b-4125-893e-ef92be58ff71.png">

**Comment by chaiyd** [comment]
> 本机用的是MAC 10.15.4。 docker destop Version4.6.1 (76265) <img alt="image" width="648" src="https://user-images.githubusercontent.com/37434329/177240146-2b03552a-9b1b-4125-893e-ef92be58ff71.png">

ok

**Comment by chaiyd** [comment]
执行下以下两条命令
- docker version
- docker-compose version

**Comment by wasonchung** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/37434329/177241147-5d4b8d25-fbfd-419b-8d06-60d8d5ae362b.png">

**Comment by chaiyd** [comment]
@cookieY  你看下这个问题？目前测试结果是mac 上面会有这个问题

**Comment by MiracleWong** [comment]
@chaiyd @cookieY 也遇到的相同的问题。通过 @wasonchung 的方法解决了。
我的系统：CentOS Linux release 7.9.2009 (Core)  和 CentOS Linux release 7.6.1810 (Core)  都试过，都不行，不知是否和系统有关

```
docker version
docker-compose version
```

结果：
```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:49 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:54:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

和 

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by chaiyd** [comment]
> @chaiyd @cookieY 也遇到的相同的问题。通过 @wasonchung 的方法解决了。 我的系统：CentOS Linux release 7.9.2009 (Core) 和 CentOS Linux release 7.6.1810 (Core) 都试过，都不行，不知是否和系统有关
> 
> ```
> docker version
> docker-compose version
> ```
> 
> 结果：
> 
> ```
> Client: Docker Engine - Community
>  Version:           20.10.8
>  API version:       1.41
>  Go version:        go1.16.6
>  Git commit:        3967b7d
>  Built:             Fri Jul 30 19:55:49 2021
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.8
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.16.6
>   Git commit:       75249d8
>   Built:            Fri Jul 30 19:54:13 2021
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.4.9
>   GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
>  runc:
>   Version:          1.0.1
>   GitCommit:        v1.0.1-0-g4144b63
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> ```
> 
> 和
> 
> ```
> docker-compose version 1.29.2, build 5becea4c
> docker-py version: 5.0.0
> CPython version: 3.7.10
> OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
> ```

v3.0.3 之后版本会修复

**Comment by cookieY** [comment]
3.0.3已修复
