### ISSUE TITLE
SQL检测时，不能drop联合索引，自增列主键不得删除

### ISSUE THREAD

**Issue by ethan-lau** [cookieY/Yearning#612]
SQL检测时，不能drop联合索引，会出现2级错误，“自增列主键不得删除!”

此类问题应该如何解决？

<img width="970" alt="image" src="https://user-images.githubusercontent.com/6011697/177447988-e83d4b36-a13c-4da3-b988-4645b6ea91cc.png">

**Comment by cookieY** [comment]
3.0.3已修复
