### ISSUE TITLE
DML插入语句，不能允许字段为空

### ISSUE THREAD

**Issue by BossKing-newbie** [cookieY/Yearning#614]
**Describe** **描述**
![B9GUXF1~Q( YLK9S4 LEGYX](https://user-images.githubusercontent.com/54852330/177957304-118ad4fb-6607-4ff5-b337-0009d646686b.png)

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**
希望SQL检测能校验字段类型是否为空

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
DMLAllowInsertNull | DML | 允许insert语句插入Null值  打开这条审核规则
