### ISSUE TITLE
升级后工单点击详情报5555，数据源没有添加流程，无法查看详情

### ISSUE THREAD

**Issue by otjoy** [cookieY/Yearning#615]
**Describe** **描述**
升级后工单点击详情报5555，数据源没有添加流程，无法查看详情

**To Reproduce** **如何复现**
原来的2的版本升级为3.0.1，然后点击工单详情。

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/22343354/178211940-00f6e87c-bdd7-48d8-abaa-02a18f054589.png">
