### ISSUE TITLE
无法注册用户

### ISSUE THREAD

**Issue by sunzqe** [cookieY/Yearning#619]
**Describe** **描述**
使用admin账户用户管理页面注册用户的时候提示:”用户已存在，请重新注册“，无法正常注册

**Screenshots** **截图**
![1657874174283](https://user-images.githubusercontent.com/20399909/179186287-80cbb096-d528-4a64-88f3-5040fe3673cc.jpg)
![1657874178625](https://user-images.githubusercontent.com/20399909/179186341-bfc24810-b2ba-429d-95b5-36895af8c1d3.jpg)

**Desktop (please complete the following information):** **环境**
 - OS: macos monterey
 - Browser chrome
 - Version 3.0.2

**Comment by cookieY** [comment]
3.0.3已修复
