### ISSUE TITLE
 pattern dist/*: no matching files found

### ISSUE THREAD

**Issue by karlhuang95** [cookieY/Yearning#620]
**Describe** **描述**

 pattern dist/*: no matching files found
clone 代码下来，在执行 go mod vendor 的时候总是报错
go: pattern dist/*: no matching files found
这个前端的dist 需要放到什么位置下

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
请将前端代码编译后 存放在指定目录进行编译

**Comment by YazaiHu** [comment]
> 请将前端代码编译后 存放在指定目录进行编译

应该放在那个目录下面？

**Comment by yangkang-ola** [comment]
编译后的dist文件放到/src/service/dist 下，执行 go mod vendor 还是报错？ 提示：go: pattern dist/*: no matching files found， 这个怎么解决？
