### ISSUE TITLE
Juno arm64 架构无法运行

### ISSUE THREAD

**Issue by sowen1023** [cookieY/Yearning#621]
**Describe** **描述**
juno 只是一个二进制文件，arm64 架构下如何获取相对应的可执行文件

**Comment by cookieY** [comment]
后续会增加arm的支持

**Comment by blylei** [comment]
可以提供juno的源码吗

**Comment by longting** [comment]
> 

不用思考，肯定用的https://github.com/hanchuanchuan/goInception， 就是基于这个上层做了一个壳
