### ISSUE TITLE
同一张表的多个DDL能不能不强制合并？

### ISSUE THREAD

**Issue by otjoy** [cookieY/Yearning#622]
同一张表的多个DDL一定要合并为一条才能提交，TIDB不能对一张表同时变更一个以上的字段。这个能不强制吗

**Comment by cookieY** [comment]
审核规则内有相关开关

**Comment by otjoy** [comment]
“允许单个工单提交多条DDL语句” ，您说的是这个规则吧，这个如果是不同表的话到时可以的。但是同表的话，多个字段是不行的。

**Comment by cookieY** [comment]
DDLAllowMultiAlter DDL单个工单允许多alter语句提交
