### ISSUE TITLE
k8s部署3.0.1版本，数据库初始化一直有几张表无法创建

### ISSUE THREAD

**Issue by carl-chang** [cookieY/Yearning#625]
多次尝试初始化仍然无法把表建全，第一次是无法写入  core_accounts表提示表不存在，不能登录，第二次是提示 Error 1146: Table 'yearning.core_order_comments' doesn't exist ，提交评论无法正常显示

建议能不能把初始化数据库的sql单独写一个文件？
(如属个人操作问题请忽略，不懂go，小白一个，我自己在研究一下)

**Comment by carl-chang** [comment]
查阅文件 modal.go  已经将漏掉的表手动添加了，目前评论功能正常

**Comment by cookieY** [comment]
v3.0.4 fixed
