### ISSUE TITLE
申请工单之后点击撤消工单，显示撤销成功，工单依然在在审核流程中

### ISSUE THREAD

**Issue by JensenZz** [cookieY/Yearning#626]
**Describe** **描述**

申请工单之后点击撤消工单，显示撤销成功，工单依然在在审核流程中

**To Reproduce** **如何复现**

step1  申请dml工单  提交审核
step2  点击自己工单的详情 点击右上角的撤销
step3  查看工单依然在审核状态中，并且右上角撤销依然可以点击

**Expected behavior** **期望的结果**

撤销后直接进入非审核状态

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/16555820/179889794-cf7fee5a-e98a-4fa3-94a7-28ba7ea702d0.png)
![image](https://user-images.githubusercontent.com/16555820/179889837-13ce3e49-c79f-42dc-8b2d-3f0073fbbaa2.png)

**Desktop (please complete the following information):** **环境**
 - Version [e.g. 3.0.3]

**Additional context** **其他**

**Comment by cookieY** [comment]
v3.0.4 fixed
