### ISSUE TITLE
SQL提交卡死

### ISSUE THREAD

**Issue by 786951355** [cookieY/Yearning#630]
**Describe** **描述**

提交DDL语句，超过10条一起提交就会卡死。

**To Reproduce** **如何复现**

使用下面的模拟表创建，试试复现。

CREATE TABLE `aliyun_log6` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datasource_instance_id` int(11) NOT NULL COMMENT '数据源实例ID',
  `project` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `logstore` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `config` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `comments` varchar(256) DEFAULT NULL COMMENT '数据源实例ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_account_uid` (
    `datasource_instance_id`,
    `project`,
    `logstore`,
    `config`
  ) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '阿里云日志服务';
CREATE TABLE `aliyun_log7` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datasource_instance_id` int(11) NOT NULL COMMENT '数据源实例ID',
  `project` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `logstore` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `config` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `comments` varchar(256) DEFAULT NULL COMMENT '数据源实例ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_account_uid` (
    `datasource_instance_id`,
    `project`,
    `logstore`,
    `config`
  ) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '阿里云日志服务';
CREATE TABLE `aliyun_log9` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datasource_instance_id` int(11) NOT NULL COMMENT '数据源实例ID',
  `project` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `logstore` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `config` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `comments` varchar(256) DEFAULT NULL COMMENT '数据源实例ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_account_uid` (
    `datasource_instance_id`,
    `project`,
    `logstore`,
    `config`
  ) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '阿里云日志服务';
CREATE TABLE `aliyun_log10` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datasource_instance_id` int(11) NOT NULL COMMENT '数据源实例ID',
  `project` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `logstore` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `config` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `comments` varchar(256) DEFAULT NULL COMMENT '数据源实例ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_account_uid` (
    `datasource_instance_id`,
    `project`,
    `logstore`,
    `config`
  ) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '阿里云日志服务';
CREATE TABLE `aliyun_log11` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datasource_instance_id` int(11) NOT NULL COMMENT '数据源实例ID',
  `project` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `logstore` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `config` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `comments` varchar(256) DEFAULT NULL COMMENT '数据源实例ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_account_uid` (
    `datasource_instance_id`,
    `project`,
    `logstore`,
    `config`
  ) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '阿里云日志服务';

CREATE TABLE `aliyun_log8` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datasource_instance_id` int(11) NOT NULL COMMENT '数据源实例ID',
  `project` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `logstore` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `config` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `comments` varchar(256) DEFAULT NULL COMMENT '数据源实例ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_account_uid` (
    `datasource_instance_id`,
    `project`,
    `logstore`,
    `config`
  ) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '阿里云日志服务';

CREATE TABLE `aliyun_log12` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datasource_instance_id` int(11) NOT NULL COMMENT '数据源实例ID',
  `project` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `logstore` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `config` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `comments` varchar(256) DEFAULT NULL COMMENT '数据源实例ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_account_uid` (
    `datasource_instance_id`,
    `project`,
    `logstore`,
    `config`
  ) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '阿里云日志服务';

CREATE TABLE `aliyun_log13` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datasource_instance_id` int(11) NOT NULL COMMENT '数据源实例ID',
  `project` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `logstore` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `config` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `comments` varchar(256) DEFAULT NULL COMMENT '数据源实例ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_account_uid` (
    `datasource_instance_id`,
    `project`,
    `logstore`,
    `config`
  ) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '阿里云日志服务';

CREATE TABLE `aliyun_log14` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datasource_instance_id` int(11) NOT NULL COMMENT '数据源实例ID',
  `project` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `logstore` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `config` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `comments` varchar(256) DEFAULT NULL COMMENT '数据源实例ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_account_uid` (
    `datasource_instance_id`,
    `project`,
    `logstore`,
    `config`
  ) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '阿里云日志服务';

CREATE TABLE `aliyun_log15` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datasource_instance_id` int(11) NOT NULL COMMENT '数据源实例ID',
  `project` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `logstore` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `config` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `comments` varchar(256) DEFAULT NULL COMMENT '数据源实例ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_account_uid` (
    `datasource_instance_id`,
    `project`,
    `logstore`,
    `config`
  ) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '阿里云日志服务';

CREATE TABLE `aliyun_log16` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datasource_instance_id` int(11) NOT NULL COMMENT '数据源实例ID',
  `project` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `logstore` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `config` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `comments` varchar(256) DEFAULT NULL COMMENT '数据源实例ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_account_uid` (
    `datasource_instance_id`,
    `project`,
    `logstore`,
    `config`
  ) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '阿里云日志服务';

CREATE TABLE `aliyun_log17` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datasource_instance_id` int(11) NOT NULL COMMENT '数据源实例ID',
  `project` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `logstore` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `config` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `comments` varchar(256) DEFAULT NULL COMMENT '数据源实例ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_account_uid` (
    `datasource_instance_id`,
    `project`,
    `logstore`,
    `config`
  ) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '阿里云日志服务';

CREATE TABLE `aliyun_log18` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datasource_instance_id` int(11) NOT NULL COMMENT '数据源实例ID',
  `project` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `logstore` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `config` varchar(128) NOT NULL DEFAULT '' COMMENT '数据源实例ID',
  `comments` varchar(256) DEFAULT NULL COMMENT '数据源实例ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据源实例ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_account_uid` (
    `datasource_instance_id`,
    `project`,
    `logstore`,
    `config`
  ) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '阿里云日志服务';

**Expected behavior** **期望的结果**

**Screenshots** **截图**
提交就卡死，然后直到超时

![image](https://user-images.githubusercontent.com/8830332/180718009-9d3b47ea-b19a-485a-a3c1-5339b190f8a6.png)

**Desktop (please complete the following information):** **环境**
 - OS: [centos 7 64bit]
 - Browser [chrome]
 - Version [v3.0.4]

**Additional context** **其他**

**Comment by cookieY** [comment]
已修复
