### ISSUE TITLE
优化查询结果展示

### ISSUE THREAD

**Issue by fangw1** [cookieY/Yearning#631]
**Describe** **描述**
优化sql查询展示

**To Reproduce** **如何复现**
工单申请->查询->选择数据库并输入sql->右击“查询” ->结果列表

**Expected behavior** **期望的结果**
列值过长时建议省略显示 而非换行。 同时查询结果和查询框可以拉动大小。

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/20739640/180723108-8c14ebe3-126e-45c8-a2c1-55244b907c4a.png)

**Desktop (please complete the following information):** **环境**
 - OS: Mac OS
 - Browser: Chrome
 - Version： 3.0.1

**Additional context** **其他**

**Comment by cookieY** [comment]
resize 功能本身已支持 需要在页头处进行拉动，省略显示会进行评估

**Comment by fangw1** [comment]
使用过自研审计系统 省略效果会更好点。
