### ISSUE TITLE
网络有延迟时，提交工单，有一定概率会生成重复工单，审核人不小心会重复执行

### ISSUE THREAD

**Issue by otjoy** [cookieY/Yearning#633]

**Comment by cookieY** [comment]
请告知详细版本号

**Comment by otjoy** [comment]
版本 3.0.4。复现的方式是多次右键点击SQL检查，然后提交，就能出现两个重复的工单，开发人员提工单是不会注意这些细节的。网络延迟的或者不注意的时候就会重复点。

**Comment by cookieY** [comment]
3.0.4版本中 提交按钮有做loading功能并且增加了防抖。应该不会出现两次重复的问题
<img width="708" alt="image" src="https://user-images.githubusercontent.com/22343354/180963948-32260f50-6c25-4a93-ad43-7945ab5fdf3e.png">

**Comment by otjoy** [comment]
提交工单的时候，反复点击SQL检查，然后提交，就会出现重复的工单。

**Comment by cookieY** [comment]
反复点击SQL检查只会使提交按钮解除禁用。并不会触发提交操作。且两个按钮并无其他关联性。网络延迟从目前代码层面看应该不会出现重复，但是人为的重复这个无法规避(比如检测提交动作进行了多次)
