### ISSUE TITLE
权限及流程配置不生效

### ISSUE THREAD

**Issue by im050** [cookieY/Yearning#634]
**Describe** **描述**

配置了审核的流程，但是查询好像依然不需要审核，是不是只有开启查询审核才行。另外赋予了数据源权限后再取消，用户只要不结束会话仍然可以一直查询。

**To Reproduce** **如何复现**

记录有权限时的数据源访问地址
```
http://domain.com/apply/query?type=110&idc=Aliyun&source=测试数据库&source_id=5c3b819d-7851-4afe-b1d4-cdb2f5ff0bab
```
后续关闭权限，该地址依然可以手动输入访问使用，即便开启过审核也可以直接查询

重启后才恢复

**Expected behavior** **期望的结果**

期望移除权限后也能够自动结束用户的查询工单

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
已修复
