### ISSUE TITLE
SQL较长情况下，sql检测非常慢。

### ISSUE THREAD

**Issue by kami0314** [cookieY/Yearning#635]
**Describe** **描述**

sql比较长的时候，SQL检测会卡住

**To Reproduce** **如何复现**

SQL长度大于 17635，情况下检测非常慢。

**Expected behavior** **期望的结果**

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/25736811/181475741-5a7c42f0-ad8f-43a8-b4fc-9d45b537deb7.png)

![B3781DF399E083E8ECDF8D8CEC66D7A1](https://user-images.githubusercontent.com/25736811/181475536-908e2838-bd2d-4959-a0a8-dd66a9483b04.jpg)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
大量SQL检测会消耗大量的计算资源
