### ISSUE TITLE
火狐浏览器头部样式遮挡问题

### ISSUE THREAD

**Issue by 786951355** [cookieY/Yearning#637]
**Describe** **描述**

火狐浏览器的头部栏会遮住子菜单的显示，这个样式能优化一下吗？

![image](https://user-images.githubusercontent.com/8830332/182534074-5ba6f48c-46a7-46ab-8e3a-9fd4d8912e27.png)

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**
 - OS: [windows 10]
 - Browser [firefox 103]
 - Version [3.0.4]

**Additional context** **其他**

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v3.1.2.2

**Comment by Horus-K** [comment]
![image](https://user-images.githubusercontent.com/48319268/218665232-d3283990-9b05-4785-93bc-fed80312abc0.png)
样式异常，我退回上一版就好了
