### ISSUE TITLE
查询页面多tab页面sql自动提示语句重复的问题

### ISSUE THREAD

**Issue by 786951355** [cookieY/Yearning#638]
**Describe** **描述**

在查询系统中，如果有多个tab页面，则下面自动提示就会有多个重复的提示，不知道就是这样设计的呢还是需要优化

![image](https://user-images.githubusercontent.com/8830332/182536898-371da857-10a4-445c-bfd9-2b1bcdc8c5a4.png)

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
已修复
