### ISSUE TITLE
不支持的语法/请提交DML语句！

### ISSUE THREAD

**Issue by maincooss** [cookieY/Yearning#639]
**Describe** **描述**
执行select * from sc;
提示：
执行失败 | 2 | 不支持的语法/请提交DML语句！ | select * from sc; | 0

**Screenshots** **截图**

![Clip_20220804_130118](https://user-images.githubusercontent.com/55976796/182766757-fff5f31b-65bc-4c9c-aa52-3ea6896906d3.png)

**Comment by cookieY** [comment]
https://next.yearning.io/guide/get/query.html

**Comment by maincooss** [comment]
收到，我的没仔细看；

**Comment by vamxiaomi** [comment]
> https://next.yearning.io/guide/get/query.html

这个页面404了
