### ISSUE TITLE
chaiyd/yearning:v3.0.5 run error

### ISSUE THREAD

**Issue by RainElohim** [cookieY/Yearning#640]
**Describe** **描述**

Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /opt/Yearning)

Error relocating /opt/Yearning: __isnan: symbol not found

Error relocating /opt/Yearning: __isinf: symbol not found

Error relocating /opt/Yearning: __strdup: symbol not found

**To Reproduce** **如何复现**

docker run

**Comment by cookieY** [comment]
请删除本地3.0.5镜像后重新pull
