### ISSUE TITLE
SQL detects an exception but no prompt

### ISSUE THREAD

**Issue by jessekk1** [cookieY/Yearning#641]
**Describe** **描述**
SQL检测后无法提交，存在异常但是没有提示（v3.0.4 正常）

**To Reproduce** **如何复现**
DDL提交
create table t1 (
    id int not null comment 'id',
    name char(10) not null comment 'name',
    is_deleted tinyint(2) default 0 not null comment 'del' after name,
    primary key(id)
) ;

**Expected behavior** **期望的结果**
异常提示

**Desktop (please complete the following information):** **环境**
 - OS: Windows10
 - Browser: Chrome
 - Version: v3.0.5

**Comment by cookieY** [comment]
请删除本地3.0.5镜像后重新pull
