### ISSUE TITLE
容器版本系统没有库文件

### ISSUE THREAD

**Issue by sunzqe** [cookieY/Yearning#642]
**Describe** **描述**
使用kubernetes运行容器版本时提示:
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/20399909/183344491-8d26ebc7-7ed4-4ad1-bcee-a354329c07fc.png">

**Desktop (please complete the following information):** **环境**
 - Version 3.0.5

**Comment by cookieY** [comment]
请删除本地3.0.5镜像后重新pull
