### ISSUE TITLE
DQL 语句每次查询都会生成一个新的结果框，且不能自动跳转最新结果框

### ISSUE THREAD

**Issue by 992270017** [cookieY/Yearning#644]
**Describe** **描述**
3.0.5 版本有BUG
每次sql查询都会生成一个结果框，且不能自动跳转最新的结果框

**To Reproduce** **如何复现**

直接sql多次查询

**Expected behavior** **期望的结果**

只显示最新的结果即可

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/71716035/183614570-0067d150-1969-4b86-b2ee-82f72964a339.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
3.0.6 已修复
