### ISSUE TITLE
单个数据源，多个数据库的情况下，切换所选数据库失败

### ISSUE THREAD

**Issue by chow-q** [cookieY/Yearning#645]
**Describe** **描述**
版本3.0.5
工单申请》查询》
单个数据源，多个数据库的情况下，切换所选数据库失败。
第一次查询是正常的，切换所选数据库后，显示是新的库了，但是查询时会报错，实际查的还是上一次选择的库。

**To Reproduce** **如何复现**

Untitled 1 切换所选数据库查询就能复现

**Expected behavior** **期望的结果**

修复

**Screenshots** **截图**

无

**Desktop (please complete the following information):** **环境**
 - Version [3.0.5]

**Additional context** **其他**

**Comment by cookieY** [comment]
报错信息是什么？

**Comment by chow-q** [comment]
报表不存在，我切了新库以后，去查询新库里面的表，它会报  表不存在。（你背后的逻辑实际上还是去前一个库查询了）

**Comment by cookieY** [comment]
你可以尝试 使用3.0.6
