### ISSUE TITLE
3.0.5 审核DDL工单，右键sql检测，报状态码500

### ISSUE THREAD

**Issue by DamonJason** [cookieY/Yearning#646]
**Describe** **描述**
提交一个工单后，审核人在窗口右键点击sql检测，报状态码500
数据源测试连接是正常的，这个解密的密码指的是什么？
后台日志报panic
2022/08/10 14:22:10 /Yearning/src/handler/fetch/fetch.go:206 record not found
[0.484ms] [rows:0] SELECT * FROM `core_data_sources` WHERE source_id ='' ORDER BY `core_data_sources`.`id` LIMIT 1
 [Error] 2022-08-10 14:22:10 (/Yearning/src/lib/encrypt.go:108) 秘钥解析失败,无法解密当前密码！
time="2022-08-10T14:22:10+08:00" level=error msg="dial tcp :0: connect: connection refused" file="/enginex/parse/parse.go:232"
 [Critical] 2022-08-10 14:22:10 (/root/go/pkg/mod/github.com/cookie!y/yee@v0.3.4/middleware/recovery.go:33) [PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference Traceback:
	/usr/local/go/src/runtime/panic.go:220
	/usr/local/go/src/runtime/panic.go:219
	/Yearning/src/handler/fetch/fetch.go:222
	/Yearning/src/apis/fetch.go:59
	/root/go/pkg/mod/github.com/cookie!y/yee@v0.3.4/context.go:122
	/root/go/pkg/mod/github.com/cookie!y/yee@v0.3.4/middleware/gzip.go:66
	/root/go/pkg/mod/github.com/cookie!y/yee@v0.3.4/context.go:122
	/root/go/pkg/mod/github.com/cookie!y/yee@v0.3.4/middleware/recovery.go:38
	/root/go/pkg/mod/github.com/cookie!y/yee@v0.3.4/context.go:122
	/root/go/pkg/mod/github.com/cookie!y/yee@v0.3.4/middleware/logger.go:58
	/root/go/pkg/mod/github.com/cookie!y/yee@v0.3.4/context.go:122
	/root/go/pkg/mod/github.com/cookie!y/yee@v0.3.4/middleware/cors.go:96
	/root/go/pkg/mod/github.com/cookie!y/yee@v0.3.4/context.go:122
	/root/go/pkg/mod/github.com/cookie!y/yee@v0.3.4/yee.go:207
	/root/go/pkg/mod/github.com/cookie!y/yee@v0.3.4/yee.go:133
	/usr/local/go/src/net/http/server.go:2917
	/usr/local/go/src/net/http/server.go:1967
	/usr/local/go/src/runtime/asm_amd64.s:1572

 [Error] 2022-08-10 14:22:10 (/root/go/pkg/mod/github.com/cookie!y/yee@v0.3.4/context.go:140) /api/v2/fetch/test Internal Server Error

**Comment by cookieY** [comment]
https://next.yearning.io/guide/install.html
