### ISSUE TITLE
消息通知好像在3.0.5中不生效了

### ISSUE THREAD

**Issue by 786951355** [cookieY/Yearning#648]
**Describe** **描述**

3.0.4中点击测试还能发出消息，在3.0.5中已经变成no value了。

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/8830332/183881198-f23d29a0-dd61-4bd8-960a-622c7917e295.png)

**Desktop (please complete the following information):** **环境**
 - Version [3.0.5]

**Additional context** **其他**

**Comment by wzshuang** [comment]
3.0.5版本，我点击hook测试，页面提示成功但是收不到消息，不知道是咋回事
![b2微信截图_20220810202201](https://user-images.githubusercontent.com/8585771/183899929-95433d79-e380-4e1e-8983-5a9f4bc66064.png)

**Comment by cookieY** [comment]
3.0.6 已修复
