### ISSUE TITLE
钉钉webhook通知的都是占位符

### ISSUE THREAD

**Issue by RainElohim** [cookieY/Yearning#650]
Yearning工单提交通知#
 工单编号: $WORKID
 数据源: $SOURCE
 提交人员: $USER 
 下一步操作人: $AUDITOR 
 平台地址: $HOST 
 :** $STATE

占位符没有被替换 v3.0.6

**Comment by 786951355** [comment]
+1

**Comment by cookieY** [comment]
重新下载3.0.6 即可
