### ISSUE TITLE
老大bug太多了啊...

### ISSUE THREAD

**Issue by wang-xiaowu** [cookieY/Yearning#651]
**Describe** **描述**
1. 按文档描述创建完用户,组,数据源和审核流程后, 在sql审核处不展示我刚添加的数据源
2. 添加完用户后,在权限组查看不到我刚刚创建的用户

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/44340137/184314699-f08a9ce2-9ef6-410a-a36c-c3cfe238f173.png)
![image](https://user-images.githubusercontent.com/44340137/184314826-046366e5-8662-4afc-8002-505e3cea3385.png)
![image](https://user-images.githubusercontent.com/44340137/184314851-df411cb6-1d9d-4661-b95b-3357c9cb637e.png)

**Desktop (please complete the following information):** **环境**
 - OS: [e.g. iOS] centos7
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] latest

**Additional context** **其他**

**Comment by cookieY** [comment]
1.确认你的数据源是否在这个环境里
2.请查看后台日志
3. 2系列版本已经不维护了，可以适用3系列

**Comment by wang-xiaowu** [comment]
> 1.确认你的数据源是否在这个环境里 2.请查看后台日志 3. 2系列版本已经不维护了，可以适用3系列

3系列能给个地址么

**Comment by wang-xiaowu** [comment]
我安装了3系列,提交工单后报错, 一致在recording

![image](https://user-images.githubusercontent.com/44340137/184338993-3db42101-ac49-47aa-9b30-2f4a02fab570.png)


![image](https://user-images.githubusercontent.com/44340137/184338879-d695d792-2019-4c39-96bb-66cb5cef38fc.png)
