### ISSUE TITLE
3.0.6版本, 提交工单后报错, 一致在recording

### ISSUE THREAD

**Issue by wang-xiaowu** [cookieY/Yearning#652]
**Describe** **描述**
3.0.6版本,提交工单后报错, 一致在recording

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

![image](https://user-images.githubusercontent.com/44340137/184464878-b5fdfa86-67b1-4769-a300-77d425919171.png)
![image](https://user-images.githubusercontent.com/44340137/184464845-9d2949b0-c378-4c54-b324-aaa32a5d0a76.png)

还有这样的warn日志
```
yearning-yearning-1  |  [Warn] 2022-08-13 10:49:18 "url":"/api/v2/fetch/comment" "method":"GET" "status":400 "protocol":"HTTP/1.0" "remote_ip":"223.102.16.209" "bytes_in": "0 bytes" "bytes_out": "27 bytes"
yearning-yearning-1  |  [Warn] 2022-08-13 10:49:18 "url":"/api/v2/fetch/order_state" "method":"GET" "status":400 "protocol":"HTTP/1.0" "remote_ip":"223.102.16.209" "bytes_in": "0 bytes" "bytes_out": "27 bytes"
```

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
recording 是样式问题
