### ISSUE TITLE
工单详情里的状态是“完成”，列表里的状态是“审核中”

### ISSUE THREAD

**Issue by wzshuang** [cookieY/Yearning#658]
**Describe** **描述**
已经审核通过并且执行的工单，工单详情里的状态是“完成”，列表里的状态是“审核中”。

**To Reproduce** **如何复现**
不记得了

**Expected behavior** **期望的结果**
列表和详情里的状态保持一致，列表里的状态应该为“完成”

**Screenshots** **截图**
![2微信截图_20220816100955](https://user-images.githubusercontent.com/8585771/184784875-b74f2a00-3385-4aca-a6ca-32e4fdd066d7.png)
![3微信截图_20220816102346](https://user-images.githubusercontent.com/8585771/184784958-525cf3ce-3788-448a-b2fc-1894394468bc.png)

**Desktop (please complete the following information):** **环境**
 - OS: win10
 - Browser chrome 104
 - Version 3.0.6

**Additional context** **其他**

**Comment by cookieY** [comment]
请先查看sql_order表中是否有两条一样的工单

**Comment by wzshuang** [comment]
> 请先查看sql_order表中是否有两条一样的工单

有。提交人、数据源、脚本都一样，时间和单号不一样

**Comment by cookieY** [comment]
> > 请先查看sql_order表中是否有两条一样的工单
> 
> 有。提交人、数据源、脚本都一样，时间和单号不一样

请提供更多的复现条件 暂时无法定位这个问题产生的原因
