### ISSUE TITLE
容器化的站内信是被关掉了吗？

### ISSUE THREAD

**Issue by feidududexigua** [cookieY/Yearning#66]
Yearning功能很强大，初次使用交互做的很不错，但测试过程中出现了一些问题

版本：1.3.3
1、提交的ddl审核在审核人这没有收到站内信息或邮件；
2、主页右上角的站内信息提示标志不存在：

![_20181106194418](https://user-images.githubusercontent.com/7575988/48062226-69edcb00-e1fc-11e8-8b06-745e5f42e693.jpg)

**Comment by feidududexigua** [comment]
正常的是这样吧

![2](https://user-images.githubusercontent.com/7575988/48062310-9ace0000-e1fc-11e8-8dcb-33c2a1f45456.jpg)

**Comment by cookieY** [comment]
@feidududexigua 站内信功能已经删除， 没有收到邮件 请查看你的邮箱设置是否正确 是否开启了邮件推送，是否发送的邮件被认定为垃圾邮件

**Comment by feidududexigua** [comment]
@cookieY 邮件推送的问题已经找到，容器里src/util/send_mail.py send_mail对象的ssl没有初始化，
![3](https://user-images.githubusercontent.com/7575988/48105478-b8d64780-e272-11e8-95fa-6d3c91dca3de.jpg)
