### ISSUE TITLE
如何更改默认主题为浅色

### ISSUE THREAD

**Issue by aosolao** [cookieY/Yearning#663]
版本 [3.0.5]

默认登录主题为深色。
如何修改为浅色主题呢？
后续是否有计划添加全局设置？

不过我测试，在一个用户个人设置里设置为浅色主题后，登录第二个用户（默认设置）看到的依然是浅色。
但其他用户在其他电脑登录依然是深色。感觉不大符合逻辑。

**Comment by cookieY** [comment]
使用什么主题色由用户自己控制

**Comment by aosolao** [comment]
是否有办法将默认颜色改为浅色呢

**Comment by no-serve-people** [comment]
> 
在哪里设置
