### ISSUE TITLE
sql审核并且执行成功，但是状态显示失败

### ISSUE THREAD

**Issue by wzshuang** [cookieY/Yearning#664]
**Describe** **描述**
sql审核并且执行成功，但是列表里和详情里的状态显示失败

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**
状态显示为“完成”

**Screenshots** **截图**

![474C5A78-2F2B-44ca-801D-471C7969B42F](https://user-images.githubusercontent.com/8585771/185879594-3f4d061f-3bf7-45e3-8edb-322865faec91.png)

**Desktop (please complete the following information):** **环境**
 - OS: win11
 - Browser chrome
 - Version 3.0.6

**Additional context** **其他**

**Comment by cookieY** [comment]
查看你的结果信息

**Comment by wzshuang** [comment]
抱歉，结果信息里确实报错了
