### ISSUE TITLE
yearning运行日志输出到文件的方法不生效

### ISSUE THREAD

**Issue by blylei** [cookieY/Yearning#674]
@cookieY 在src/service/StartYearning方法中，设置日志输出到文件时，没有生效。代码调整如下：
![image](https://user-images.githubusercontent.com/38288045/187114969-d94df084-ed32-4768-aa4e-166f6dc52c0c.png)

排查后发现，是yee框架的日志中间件没有调用设置输出的方法，代码块如下图：
![image](https://user-images.githubusercontent.com/38288045/187115299-2f61a19d-3e08-4e30-9d1b-59ed3646d679.png)

**Comment by cookieY** [comment]
默认情况下 nohup > txt 即可
如果你想改造 https://github.com/cookieY/yee 这里有输出到对应文件的样例
