### ISSUE TITLE
提交数据量太多，导致卡死

### ISSUE THREAD

**Issue by sunzqe** [cookieY/Yearning#676]
**Describe** **描述**
提交了9个工单，每个工单大概有2w条记录，一共有10多w数据，现在页面卡死，点详情出现网页崩溃的情况，目前无法使用了

**Expected behavior** **期望的结果**
能否通过更给数据库表，把相关审核订单关闭，目前页面很卡

**Desktop (please complete the following information):** **环境**
 - Browser chrome
 - Version v3.0.8

**Comment by sunzqe** [comment]
![1](https://user-images.githubusercontent.com/20399909/187122227-557ecbbf-d69
![2](https://user-images.githubusercontent.com/20399909/187122240-0fec9830-4e8b-46c9-8ec5-e964d4aed633.jpg)
2-4502-af67-defc78dec39f.jpg)

**Comment by sunzqe** [comment]
![3](https://user-images.githubusercontent.com/20399909/187122422-fff18462-814f-4a02-b030-451ded893e26.jpg)

**Comment by sunzqe** [comment]
![1](https://user-images.githubusercontent.com/20399909/187122432-5d417f7e-b7cc-465d-a218-19f6cab7e2fe.jpg)

**Comment by sunzqe** [comment]
前端有报
![4](https://user-images.githubusercontent.com/20399909/187122617-bec98636-ca8c-446f-93f7-17c830808237.jpg)
错

**Comment by sunzqe** [comment]
发现有审核中的页面在不停的请求一个list的接口
![5](https://user-images.githubusercontent.com/20399909/187125722-aa90a9a4-e1fe-457b-8ff0-510f1f2997ba.jpg)

**Comment by sunzqe** [comment]
发现有审核中的页面在不停的请求一个list的接口
![5](https://user-images.githubusercontent.com/20399909/187125722-aa90a9a4-e1fe-457b-8ff0-510f1f2997ba.jpg)

**Comment by DamonJason** [comment]
+1 我也是相同情况 望管理员重视

**Comment by JerryGreenLuan** [comment]
审核页面，循环请求“api/v2/audit/order/list”接口的问题很严重，现在只要多人同时使用，就会非常卡顿！希望开发大佬能够修复！

**Comment by cookieY** [comment]
@sunzqe 3.0.9 fixed

**Comment by cookieY** [comment]
> 审核页面，循环请求“api/v2/audit/order/list”接口的问题很严重，现在只要多人同时使用，就会非常卡顿！希望开发大佬能够修复！

循环调用是为了定时刷新工单状态,单次查询20条 理论上对性能的影响较小。

**Comment by nandy33up** [comment]
> > 审核页面，循环请求“api/v2/audit/order/list”接口的问题很严重，现在只要多人同时使用，就会非常卡顿！希望开发大佬能够修复！
> 
> 循环调用是为了定时刷新工单状态,单次查询20条 理论上对性能的影响较小。

作为DBA，我建议页面工单查询，尽可能采用有索引的等值查询，后端查询代码中LIKE太多了。如果工单比较多，且使用了模糊查询（比如备注），查询1次都费力，更别说每5s定时查询了，会把整个数据库都拖垮的。
