### ISSUE TITLE
从2.3.6升级到3.0.5容器版本之后页面有报错。

### ISSUE THREAD

**Issue by macpherson0625** [cookieY/Yearning#677]
Hi，我从2.3.6版本更新到3.0.5容器版本之后，在配置邮件和钉钉通知页面无法保存，提示如下“传参错误”

![image](https://user-images.githubusercontent.com/5416086/187399262-1e53aa29-9498-4a3b-bf2b-ef3e4e65ce8e.png)

这是容器里的错误日志截图
![image](https://user-images.githubusercontent.com/5416086/187399171-25c21049-460c-4608-a79a-f45f0bc9f1bf.png)

**Comment by macpherson0625** [comment]
@cookieY  尝试初始化数据库后（core_global_configurations这张表）只有表结构，没有原始数据。麻烦指点下~🙏

**Comment by cookieY** [comment]
是否使用./migrate 进行迁移操作？

**Comment by macpherson0625** [comment]
@cookieY  我这里是容器更新的，在更新之前我用的是3.0.5二进制包解压之后执行了./migrate操作。最后再用docker启动3.0.5镜像的。

另外，近期又将3.0.5升级到3.0.8版本镜像后还发现在管理 --> 数据源 页面里新增数据源之后点击创建报了“500错误”，查看容器日志中出现了如下错误的截图。
![image](https://user-images.githubusercontent.com/5416086/188105909-05fec998-1568-4a58-a81c-fcd1c9fea54a.png)

最后，我提一个小建议，版本升级可否由应用自动去更新表结构，让用户手动去执行migrate操作体验不佳。

**Comment by cookieY** [comment]
@macpherson0625  一般的变更是自动更新表结构的 但是对于一些特殊的破坏性变更需要手动去做 因为重复的自动变更导致的无意义报错 会导致用户产生误解
