### ISSUE TITLE
建议能够自定义推送模板

### ISSUE THREAD

**Issue by wzshuang** [cookieY/Yearning#679]
**Describe** **描述**
提供一些内置变量，把模板内容开放出来，给个输入框，让用户可以根据自己的需要进行编辑。

```
Yearning工单提交通知#
工单编号: $WORKID
数据源: $SOURCE
提交人员: $USER
下一步操作人: $AUDITOR
平台地址: $HOST
```

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**
可以参考微信公众号的模板消息
![image](https://user-images.githubusercontent.com/8585771/187575221-bacb8785-17c2-4d56-ab0a-40473d72225b.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
该功能在赞助版中已实现，也可自行实现
