### ISSUE TITLE
#bug 回滚语句sql为空

### ISSUE THREAD

**Issue by ChengJieping** [cookieY/Yearning#680]
**Describe** **描述**

回滚语句sql为空，执行错误sql未回滚

**To Reproduce** **如何复现**

设置数据库开启binlog，分配账号权限
DML工单提交sql，2条插入语句，一条成功一条失败，未进行回滚处理，回滚语句sql为空

**Expected behavior** **期望的结果**

进行回滚处理，有回滚语句

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/34883841/188251655-addb2768-fe42-455e-af2b-beed610ec44d.png)
![image](https://user-images.githubusercontent.com/34883841/188251667-ec34e1bd-2a32-4e10-acda-3a75ac5674aa.png)
![image](https://user-images.githubusercontent.com/34883841/188252110-a889f7c5-bf45-4304-b227-58e39401d861.png)
![image](https://user-images.githubusercontent.com/34883841/188252134-119e1dd4-b35d-471a-ada6-959070abcf98.png)
![image](https://user-images.githubusercontent.com/34883841/188252154-f2ac5cf6-3920-4b75-9dda-eb37655564f0.png)

**Desktop (please complete the following information):** **环境**
 - OS:  虚拟机centos7
 - Browser  谷歌浏览器
 - Version 3.0.8

**Additional context** **其他**

**Comment by ChengJieping** [comment]
补充操作过程中日志截图

![image](https://user-images.githubusercontent.com/34883841/188252688-e3789d5f-805e-4498-8ed9-b93fdd01c0c4.png)

![image](https://user-images.githubusercontent.com/34883841/188252744-a9ec9222-7c0c-4706-b2f2-1321c4064e5f.png)

**Comment by cookieY** [comment]
建议先使用root用户进行回滚测试，另外如使用云数据库 如RDS 需要拿到super权限

**Comment by ChengJieping** [comment]
您好，您的邮件已收到，谢谢！

**Comment by ChengJieping** [comment]
非RDS，本地电脑安装的mysql服务进行的测试

root账号测试仍然没有回滚语句

![image](https://user-images.githubusercontent.com/34883841/188395032-99277515-31f2-431a-9b72-43d8219e9067.png)

**Comment by cookieY** [comment]
> 

一个失败的工单 怎么会有回滚语句呢？

**Comment by ChengJieping** [comment]
失败的工单包含一条插入成功的语句，一条插入失败的语句，我理解的回滚功能应该是能回滚第一条插入的数据
![image](https://user-images.githubusercontent.com/34883841/188815769-26eaf38f-40be-475f-b7b2-0c1119f50a19.png)

正常的工单也没有产生回滚语句
![image](https://user-images.githubusercontent.com/34883841/188815430-80efe37c-aa1d-4a34-89e8-4e5c1c3c67df.png)

都是通过root账号测试的

**Comment by cookieY** [comment]
目前无法复现你的问题，SQL执行正常且配置正常的binlog 可以获得正确的回滚语句

**Comment by feiyue2022** [comment]
问个问题  aws 的RDS没有super权限的 是否代表无法生成回滚语句了

**Comment by ChengJieping** [comment]
您好，您的邮件已收到，谢谢！
