### ISSUE TITLE
页面排版显示错误

### ISSUE THREAD

**Issue by aosolao** [cookieY/Yearning#681]
**Describe** **描述**

在firefox浏览器中页面菜单标题会被遮挡，请见截图

**To Reproduce** **如何复现**

浏览器与操作系统版本：Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0
![图片](https://user-images.githubusercontent.com/30789071/189027312-5f2222cb-e62e-45a4-b67e-3d21354acceb.png)

**Expected behavior** **期望的结果**

**Screenshots** **截图**

![Snipaste_2022-09-08_11-24-14](https://user-images.githubusercontent.com/30789071/189027449-a74963d9-8921-460c-a569-2dd8e182ca5a.jpg)
![Snipaste_2022-09-08_11-24-01](https://user-images.githubusercontent.com/30789071/189027464-a3afe5c7-988f-4d37-bb2e-dbbf16d06670.jpg)

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v3.1.2.2
