### ISSUE TITLE
通过工单自动备份后进行rollback数据不一致

### ISSUE THREAD

**Issue by zj5220924** [cookieY/Yearning#687]
1、这是通过手动方式在一个事务中包含两条sql执行前后表test01的数据状态
![9J~R8U{{SGEJF$PO`KSI6XF](https://user-images.githubusercontent.com/54430024/190967719-019099aa-8f73-4f5e-86f0-c59009bfeb33.jpg)
2、现在通过yearning 3.0.9进行如上两个sql的工单提交后，然后再进行回滚后的数据状态，uidpk=5那行数据的is_del应该为0，而不是为1，说明工单生成的回滚数据有问题，会导致执行工单前的数据和回滚后不一致。
![)UQD{~S~{_M5X$Q BL2R@WM](https://user-images.githubusercontent.com/54430024/190968266-74bb4641-d89d-4bf2-9399-b36d271c800f.jpg)

**Comment by cookieY** [comment]
请提供回滚生成的SQL语句

**Comment by zj5220924** [comment]
> 

![%Y$%U {HD(@7 P%}6@2T$M9](https://user-images.githubusercontent.com/54430024/191150530-f7437e33-cadf-4c15-bf91-01cfe0fd9d60.jpg)

**Comment by cookieY** [comment]
将通过 orderby 更改为降序 规避该问题  3.1.1版本修复
