### ISSUE TITLE
sql检测提示错误  数据长度'16'大于当前数据类型   但实际上是正常的sql

### ISSUE THREAD

**Issue by raozhileee** [cookieY/Yearning#689]
数据长度'16'大于当前数据类型'enum

**Comment by cookieY** [comment]
请提供建表语句
插入语句

**Comment by raozhileee** [comment]
我估计是把 enum的 种类 当成了长度进行限制   
update `oryx_user`.`user`
set platform    = 'external_work_wx',
    external_id = 'woNPDqBgAAxxx'
  where user_id = 23669999;

报错信息：
数据长度'16'大于当前数据类型'enum('wx_mini','wx_app','wx_official','sql_import','backstage_opening','new_import','external_work_wx')'，列'platform'

**Comment by danielvsdevops** [comment]
我们也碰到了这个问题了，请问是如何解决的？
