### ISSUE TITLE
自动任务

### ISSUE THREAD

**Issue by G-Akiraka** [cookieY/Yearning#702]
**Describe** **描述**
自动任务是否可以设置全部表或者多选表，只能选一个太麻烦了，一个数据库可能有几十上百个表，然后是否可以选择dml或者ddl来控制自动任务

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
自动任务不建议大规模使用，当前审核规则仅能对语法层进行相关检测 但包含业务逻辑错误是无法通过工具测试的。大规模的使用很有可能导致这样的情况发生 所以自动任务应该是小范围，固定化的场景使用

**Comment by G-Akiraka** [comment]
有没有一种用户需求，不在乎提交了什么，只需要dml自动审核执行就可以了
a、一种简单的，满足自动化即可
b、一种颗粒度极高的满足更高需求

**Comment by cookieY** [comment]
如果是这样 那也就不需要审核平台了

**Comment by G-Akiraka** [comment]
如何不给研发数据库权限，又可以保证一定安全性，sql审计平台还是很有必要的，只是没有那么的安全。
