### ISSUE TITLE
对于定时任务，是否可以支持 在审核后修改定时时间，或者撤回该工单

### ISSUE THREAD

**Issue by jessekk1** [cookieY/Yearning#703]
**Describe** **描述**

对于定时任务，是否可以支持 在审核后修改定时时间，或者撤回该工单。

在还没到时间前，尝试过在数据库修改，但定时器没生效，还是按最开始的时间执行。

**Expected behavior** **期望的结果**

还没执行前，能有一个开关可以再控制该流程，修改定时时间，或者撤回、驳回等。

**Desktop (please complete the following information):** **环境**
 - OS: Win10
 - Browser: Chorme
 - Version: 3.0.8

**Comment by RaiToKU** [comment]
同求，在2.x的版本支持直接执行定时任务，我同样也是希望可以驳回、撤销或者修改定时器时间
另外：有一个情况想集思益广的
Describe
该业务开发人员某需求需要先DDL新增字段，然后再填充数据（数据不能采用默认值），且DDL跟DML工单都需要定时执行，但是这种情况下DML的工单会提示字段不存在
步骤：
1、提交DDL工单，定时器执行
2、提交DML工单提示字段不存在
Expected behavior
我的方案：DML工单增加关联工单功能，匹配字段是否存在、类型是否符合等，然后允许提交工单，该工单需要在关联工单后执行且为关联工单已完成的情况
暂时想到这么多，类DAG的设计

**Comment by jianyang1982** [comment]
支持，因为计划赶不上变化。
