### ISSUE TITLE
sql校验报错

### ISSUE THREAD

**Issue by lingyuntao** [cookieY/Yearning#705]
sql校验，字段可以为空，但是校验结果不可以为空

![lQLPJxbD0KZzH4LMrs0EP7CDXMYOlRZAvANB48C_gBAA_1087_174 png_620x10000q90](https://user-images.githubusercontent.com/115465083/194845915-a007e195-a39d-4aab-aaf1-355e356844a5.jpg)
![lQLPJxbD0KZzH1HNAWTNA8qwM-pHW1eIp5cDQePAtgCRAA_970_356 png_620x10000q90](https://user-images.githubusercontent.com/115465083/194845931-def7dc8c-1ecd-4dea-8ebe-486ebd9a0ee4.jpg)

**Comment by cookieY** [comment]
检测条件主要是根据你的审核规则来进行判断的，检测的目的更多的是为了通过审核规则来规范化SQL语句，而不是单纯的语法检测。

**Comment by lingyuntao** [comment]
> 
所以这需要我们自己修改审核规则嘛
