### ISSUE TITLE
工单审批页面查询修改

### ISSUE THREAD

**Issue by pcstx** [cookieY/Yearning#706]
1、目前的工单审批页面太难用了，搜索条件在点击一条详情以后，再点击返回就丢失了，我有很多SQL需要审批，已经分页了，通过搜索条件查询后，一条条去审批，结果操作了一条以后点击返回，又要重新输入一遍之前的搜索条件，并且分页是从第一页开始。
可以使用keepalive来保持之前的记录。或者点击详情操作的时候弹开一个新的标签页面。

2、列表展示是否可以增加环境列，可以快速区分是测试环境的还是正式环境的SQL。

3、搜索条件增加工单编号这个条件，方便快速搜索。

**Comment by cookieY** [comment]
3.1.1 正式版本 已对审核页面添加前端缓存
