### ISSUE TITLE
偶尔出现查询卡死，界面一直转圈,查询的单个字段过长不会显示

### ISSUE THREAD

**Issue by Horus-K** [cookieY/Yearning#708]
**Describe** **描述**
偶尔出现查询卡死，界面一直转圈，必须刷新才能解决
![image](https://user-images.githubusercontent.com/48319268/196843861-5346bb50-ade4-4788-b8c8-e53220469297.png)
![image](https://user-images.githubusercontent.com/48319268/196843820-70c95652-5423-40a8-add1-d965bdf0b655.png)
查询的单个字段过长不会显示，2.3.5版本就能正确显示
![image](https://user-images.githubusercontent.com/48319268/196844591-cc8ede42-c803-4cda-88de-e15b5922ae64.png)
![image](https://user-images.githubusercontent.com/48319268/196844483-797e7ea1-9bb9-4cf5-84f0-17977b780978.png)

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**
 - Version [e.g. 22]  3.1.0

**Additional context** **其他**

**Comment by cookieY** [comment]
鼠标移动到省略字段内 会显示全部内容

**Comment by Horus-K** [comment]
@cookieY 会显示但没法复制，确实不方便

**Comment by cookieY** [comment]
> @cookieY 会显示但没法复制，确实不方便

这种很难调和 有人觉得全部显示 字段过长表格拉的很长 影响查看 有的人觉得我要复制就要全显示 - -

**Comment by Horus-K** [comment]
可以过长的点击复制？
