### ISSUE TITLE
数据长度'7'大于当前数据类型'enum('open','process','success','fail','cancel','ready')'，列'capital_notify_status't

### ISSUE THREAD

**Issue by chen642636047** [cookieY/Yearning#714]
**Describe** **描述**
枚举类型报错在3.1.1版本中未被修复

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
该问题将在3.1.1 正式版中解决
