### ISSUE TITLE
邮件服务需要支持用户名与发件人分开

### ISSUE THREAD

**Issue by TophillZK** [cookieY/Yearning#716]
**Desktop (please complete the following information):** **环境**
主机环境：
操作系统版本：CentOS Linux release 7.6.1810
内核版本：5.4.158-1.el7.elrepo.x86_64
Yearing版本：3.1.0

**Describe** **描述**
在进行邮件测试时，日志报出如下错误信息：
EXTRA *textproto.Error=535 5.7.3 Authentication unsuccessful

问题根因：有些邮件服务器进行用户验证时，使用的是用户名，不带@xxxx.com
目前的程序是把UserName与From都使用了mail.User这个变量，导致我使用我们公司邮件服务器的时候，在“邮件推送用户名”中填写yearning还是yearning@xxxx.com时，邮件都发送不成功。

**Expected behavior** **期望的结果**
希望把sendMail.go的122行进行如下修改：
Username: mail.User,   ->    Username: strings.Split(mail.User,"@")[0],

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/35677454/199457611-3a978c4d-ff0b-4bd3-8eff-131734d43a0e.png)

**Comment by cookieY** [comment]
这是一个很尴尬的问题有些邮件服务器只传用户名无法发送对应邮件
