### ISSUE TITLE
OSC进度显示空白

### ISSUE THREAD

**Issue by sh-hanson** [cookieY/Yearning#717]
你好，我使用pt-osc方式执行DDL，配置参数如下：pt-online-schema-change --host=$ADDR --port=$PORT --user=$USER --password=$PASSWORD --alter $SQL D=$SCHEMA,t=$TABLE --execute

DDL工单执行是成功的，但是OSC进度显示是空白的，无法看到OSC执行时的情况，请问这是什么原因呢？
版本3.1.0
![image](https://user-images.githubusercontent.com/41986080/199867418-e2847e75-22ae-4eea-9374-31a320b32a3f.png)
![image](https://user-images.githubusercontent.com/41986080/199867439-f1602524-0456-4555-afae-4a759d16abb9.png)

**Comment by sh-hanson** [comment]
还有DML工单，执行成功后，执行时间是空的，以前老版本还是有显示执行时间的
![image](https://user-images.githubusercontent.com/41986080/199866760-6e6731b5-9f6d-4410-bea3-4f0d69080316.png)

**Comment by kafenut** [comment]
我这边也遇到了类似的问题

**Comment by kafenut** [comment]
我这边也遇到了类似的问题, 我是从2.2.2升到3.1.0的, 我检查了数据库, 里面是有pt-osc进度信息的, 但前端没有显示, 后端报400错误
![image](https://user-images.githubusercontent.com/45032762/199914405-c821ba15-3a6c-4d28-a52d-7eb18807209e.png)

**Comment by kafenut** [comment]
破案了, nginx配置里没设置websocket

**Comment by kafenut** [comment]
破案了, nginx里没配置websocket

**Comment by kafenut** [comment]
破案了, nginx没配置websocket的问题, 3.0开始部分数据使用websocket获取了, proxy_set_header Connection upgrade;

**Comment by sh-hanson** [comment]
> 破案了, nginx没配置websocket的问题, 3.0开始部分数据使用websocket获取了, proxy_set_header Connection upgrade;

我这边不是版本升级，是全新安装的，而且也没有使用ngnix。所以应该就没有配置websocket的问题。不知道我这情况是什么原因

**Comment by kafenut** [comment]
> 

你看看数据库里有没有记录, 执行时间什么的在core_sql_records里; pt-osc在core_sql_orders里; 我这边是core_sql_orders有pt-osc的记录, 但core_sql_records里没有执行时间

**Comment by sh-hanson** [comment]
我看了core_sql_orders表中osc_info字段都是空的，没有值。core_sql_records里也没有执行时间

**Comment by cookieY** [comment]
@sh-hanson  执行时间将在正式版3.1.1中修复
