### ISSUE TITLE
2.3.3升级到3.1.1版本后 原来的账号无法登陆

### ISSUE THREAD

**Issue by yisirman** [cookieY/Yearning#718]
错误截图：
![image](https://user-images.githubusercontent.com/15642586/199689465-cb14c4f9-2a39-45ac-8a06-7b6f8c0630a0.png)

日志信息：
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/15642586/199689550-a38ea1f4-a8e4-4663-b7c7-c5bb9cb9e76d.png">

**Comment by yisirman** [comment]
配置ldap总是连接失败
<img width="718" alt="image" src="https://user-images.githubusercontent.com/15642586/199864266-fc87b4da-7227-4b7d-99e3-d746007e9197.png">

错误信息：
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/15642586/199864571-b54c204d-5a78-49a2-bd82-ca1811f29021.png">

**Comment by cookieY** [comment]
请检查LDAP配置
