### ISSUE TITLE
iptables和firewalld的问题

### ISSUE THREAD

**Issue by kachikoo** [cookieY/Yearning#72]
您好！
1、请问启动容器的时候是会对操作系统内存中的ipatbles规则进行覆写吗？启动容器之后，原来内存中加载的规则都没有了。
2、我把firewalld服务disable和mask掉了，容器重启就不成功了，是有依赖关系吗？

谢谢~

**Comment by cookieY** [comment]
docker 依赖iptables 进行nat转发
