### ISSUE TITLE
开启查询审核获取不到下一步操作人

### ISSUE THREAD

**Issue by yisirman** [cookieY/Yearning#723]
3.1.1版本开启查询审核 提交审核后没有获取到下一步操作人

数据源负责人也配置了，但是提交审核还是没有获取到
<img width="683" alt="image" src="https://user-images.githubusercontent.com/15642586/202141211-a1a95932-89a8-4002-a7f4-5a933375e868.png">

负责人账号下也没有该审批记录
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/15642586/202141701-c4914fbc-438b-4bd4-9240-fbfb6e616580.png">

**Comment by cookieY** [comment]
v3.1.2 closed
