### ISSUE TITLE
Report 编辑公告后不显示。

### ISSUE THREAD

**Issue by lizonggang** [cookieY/Yearning#727]
**Describe** **描述**
管理 -> 公告 编辑器中输入相应的文字，点 **保存** 按钮。
回首页查看公告还是空白。

**To Reproduce** **如何复现**
一直没有成功过。

**Expected behavior** **期望的结果**
编辑公告后可正常显示。

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/4124582/204092234-5a28f137-a451-4b1f-9562-1b8ae8d0ad35.png)
![image](https://user-images.githubusercontent.com/4124582/204092247-342c861c-aeb2-413a-be12-0fbf7dfc1cb2.png)

**Desktop (please complete the following information):** **环境**
服务器操作系统: CentOS Linux release 7.9.2009 (Core)
客户端：macOS 10.15.7
浏览器：版本 107.0.5304.110（正式版本） (x86_64)
软件版本：Yearning-v3.1.1-linux-amd64.zip

**Additional context** **其他**
1.接口信息。
{
    "payload": null,
    "code": 1200,
    "text": "公告已保存"
}

2.返回公告后编辑器内容为空。

**Comment by oslo254804746** [comment]
同楼上，保存后无法生效

**Comment by cookieY** [comment]
v3.1.2 closed
