### ISSUE TITLE
工单审核并执行，但数据库中实际没执行，前端页面一直处于执行中状态

### ISSUE THREAD

**Issue by nandy33up** [cookieY/Yearning#728]
**Describe** **描述**
如题，偶现前端页面显示执行中，但数据库实际未执行的情况

**To Reproduce** **如何复现**
给表添加索引，预计执行5min。页面审核并执行后，在数据库中show processlist，不存在加索引的sql执行

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**
 - OS: centos7
 - Browser chrome
 - Version v3.1.0

**Additional context** **其他**
未设置定时运行

**Comment by cookieY** [comment]
请给出具体的日志信息
