### ISSUE TITLE
Report 工单执行中调用juno的Engine.Exec会更改工单记录的状态？

### ISSUE THREAD

**Issue by mintrumpet** [cookieY/Yearning#729]
**Describe** **描述**

本人在二开过程中，发现审核执行后，调用Engine.Exec之后，工单的status会变更为1（已完成），在yarning的源码上没看到具体的UPDATE执行，请问是juno上更改了ORDER记录信息吗？

如果是的话，想咨询下怎么解决

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by mintrumpet** [comment]
希望能解答下~

**Comment by cookieY** [comment]
是的

**Comment by mintrumpet** [comment]
> 是的

想咨询下可以将对工单的处理交由给yearning本身么？

由于本人在二次开发中，涉及到多个执行步骤，现在的处理会导致工单没走完可能就已经完成关闭了。

**Comment by cookieY** [comment]
你可以更改已完成的状态为其他的状态 把已完成的状态更改为其他标识符
