### ISSUE TITLE
枚举类型检测长度异常

### ISSUE THREAD

**Issue by chen642636047** [cookieY/Yearning#731]
**Describe** **描述**
版本3.1.1
数据长度'8'大于当前数据类型'enum('unfinished','finished')'，列'capital_transaction_status'
目前只支持长度为2

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**
去除枚举类型检测，或者可以进行配置

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
请提供具体SQL语句

**Comment by chen642636047** [comment]
> 请提供具体SQL语句

update
  capital_transaction
set
  capital_transaction_expect_operate_at = capital_transaction_expect_finished_at,
  capital_transaction_actual_operate_at = capital_transaction_expect_finished_at,
  capital_transaction_user_repay_at = '2022-12-11 06:09:48',
  capital_transaction_status = 'finished',
  capital_transaction_withhold_result_channel = 'kkkkkkk',
  capital_transaction_process_status = 'aaaaaaa',
  capital_transaction_operation_type = 'noaaaaaaa'
where
  capital_transaction_asset_item_no = '111111111111111111'
  and capital_transaction_period = 9;

**Comment by chen642636047** [comment]
> 请提供具体SQL语句

数据长度'8'大于当前数据类型'enum('unfinished','finished')'，列'capital_transaction_status'

**Comment by cookieY** [comment]
最好也提供下 建表语句

**Comment by chen642636047** [comment]
> 最好也提供下 建表语句

CREATE TABLE `capital_transaction` (
  `capital_transaction_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `capital_transaction_asset_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'capital_asset表主键ID',
  `capital_transaction_channel` varchar(64) NOT NULL DEFAULT '' COMMENT ‘aaa’,
  `capital_transaction_grant_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT ‘sss’,
  `capital_transaction_grant_type` enum('cp_sell','direct') DEFAULT 'cp_sell' COMMENT ‘sss’,
  `capital_transaction_type` varchar(50) NOT NULL DEFAULT 'principal' COMMENT ‘sss’,
  `capital_transaction_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT ‘sss’,
  `capital_transaction_repaid_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT ‘sss’,
  `capital_transaction_rate` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT ‘sss’,
  `capital_transaction_holding_days` int(11) NOT NULL DEFAULT '0' COMMENT ‘sss’,
  `capital_transaction_year_days` int(11) NOT NULL DEFAULT '0' COMMENT ‘sss’,
  `capital_transaction_expect_finished_at` date NOT NULL DEFAULT '1000-01-01' COMMENT '时间',
  `capital_transaction_expect_operate_at` datetime NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '时间',
  `capital_transaction_user_repay_at` datetime NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '时间',
  `capital_transaction_actual_operate_at` datetime NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '时间',
  `capital_transaction_status` enum('unfinished','finished') NOT NULL DEFAULT 'unfinished' COMMENT 'unfinished 未完成,finished 完成',
  `capital_transaction_is_advance` enum('Y','N') NOT NULL DEFAULT 'N' COMMENT ‘sss’,
  `capital_transaction_advance_at` datetime NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '时间',
  `capital_transaction_order_id` int(11) NOT NULL DEFAULT '0' COMMENT 'id',
  `capital_transaction_operation_type` varchar(50) DEFAULT 'grant' COMMENT ‘kkk’,
  `capital_transaction_period` tinyint(2) DEFAULT '0' COMMENT ‘rg’,
  `capital_transaction_withhold_result_channel` varchar(50) NOT NULL DEFAULT '' COMMENT ‘yt’,
  `capital_transaction_create_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  `capital_transaction_update_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `capital_transaction_process_status` varchar(32) DEFAULT 'ready' COMMENT '状态：ready,process,fail,success',
  `capital_transaction_origin_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT ‘mm’,
  `capital_transaction_asset_item_no` varchar(64) NOT NULL DEFAULT '',
  `capital_transaction_push_success_at` datetime DEFAULT '1000-01-01 00:00:00' COMMENT '时间',
  PRIMARY KEY (`capital_transaction_id`),
  KEY `idx_ct_order_id` (`capital_transaction_order_id`),
  KEY `idx_capital_transaction_advance_at` (`capital_transaction_advance_at`),
  KEY `idx_capital_tran_asset_id` (`capital_transaction_asset_id`),
  KEY `idx_capital_tran_channel_type_finish_at` (`capital_transaction_channel`,`capital_transaction_type`,`capital_transaction_expect_finished_at`),
  KEY `idx_capital_tran_finish_at` (`capital_transaction_expect_finished_at`),
  KEY `idx_capital_transaction_actual_operate_at` (`capital_transaction_actual_operate_at`),
  KEY `idx_capital_transaction_expect_operate_at` (`capital_transaction_expect_operate_at`),
  KEY `idx_capital_transaction_user_repay_at` (`capital_transaction_user_repay_at`),
  KEY `idx_capital_transaction_item_no_period` (`capital_transaction_asset_item_no`,`capital_transaction_period`),
  KEY `idx_capital_transaction_push_success_at` (`capital_transaction_push_success_at`)
) ENGINE=InnoDB AUTO_INCREMENT=190801032 DEFAULT CHARSET=utf8 COMMENT='计划表'

**Comment by cookieY** [comment]
v3.1.2 closed
