### ISSUE TITLE
Report 无法发送邮件，测试邮件发不出.

### ISSUE THREAD

**Issue by fubotao** [cookieY/Yearning#732]
**Describe** **描述**
v3.1.0版本
无法发送邮件，测试邮件发不出.

日志报错：
[Error] 2022-12-07 23:44:55 (/Users/henryyee/PersonalProjects/Yearning-go/src/lib/sendMail.go:113) send mail%!(EXTRA *errors.errorString=gomail: unexpected server challenge: username:)

同样的相关邮件信息验证机器上命令行是可以发出邮件的。，所以肯定不是网络、配置之类的错了。是哪里有特殊注意事项遗漏了？

*

**Comment by cookieY** [comment]
可以正常收发邮件  请提供具体的邮件配置信息
