### ISSUE TITLE
update 语句显示受影响行数错误

### ISSUE THREAD

**Issue by FrancisAston** [cookieY/Yearning#733]
版本：yearning 3.1.1
update 语句显示受影响行数不准确。
只更新一条，但是显示后影响行数4条。
![image](https://user-images.githubusercontent.com/34341863/207491070-2c4e3ad0-ac3a-45ca-bbc0-8f421a4f53cd.png)

**Comment by FrancisAston** [comment]
看了问题，好像已经说了不准确了

**Comment by cookieY** [comment]
https://next.yearning.io/feeback.html
