### ISSUE TITLE
查询时最多只显示1000条，不知道这是bug还是只支持显示1000条

### ISSUE THREAD

**Issue by zzyork** [cookieY/Yearning#734]
这是yearning的查询数量截图![image](https://user-images.githubusercontent.com/45233837/207522325-cac75d97-7065-4c98-a913-840c2847b900.png)
这是navicat的查询数量截图
![image](https://user-images.githubusercontent.com/45233837/207522529-36ea83e6-1c2e-4280-9b99-f20f998b4415.png)

**Comment by cookieY** [comment]
设置里面可以设置查询最大条数

**Comment by zzyork** [comment]
> 设置里面可以设置查询最大条数

好的，找到这个设置了，感谢
