### ISSUE TITLE
查询页面500后卡住

### ISSUE THREAD

**Issue by kafenut** [cookieY/Yearning#736]
如果在查询里面选中了一个无法连接的数据库(一般是删除了的数据库), 查询页面会报500. 之后就没法切换数据源了, 需要重新进入查询系统.

**Comment by kafenut** [comment]
还有一个bug, Yearning3.1.1公告无法修改, 显示保存成功但主页公告并没有修改

**Comment by cookieY** [comment]
已在3.1.2.1版本中修复
