### ISSUE TITLE
alter语句，但是报dml错误

### ISSUE THREAD

**Issue by wang-xiaowu** [cookieY/Yearning#744]
**Describe** **描述**
alter语句，但是报dml错误，而非ddl

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/44340137/210925168-5585a47a-da37-48eb-af15-dd156184289d.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by nandy33up** [comment]
建议先搞清楚DML和DDL的区别再提问

**Comment by wang-xiaowu** [comment]
> 建议先搞清楚DML和DDL的区别再提问

要不您先查一下alter是ddl还是dml？
然后再看看是我需要搞清楚还是您需要搞清楚

**Comment by cookieY** [comment]
ddl语句应在 DDL审核申请处提交

**Comment by wang-xiaowu** [comment]
> ddl语句应在 DDL审核申请处提交

好的
