### ISSUE TITLE
不支持企业微信的webhook吗？

### ISSUE THREAD

**Issue by 80999625** [cookieY/Yearning#747]
**Describe** **描述**

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
社区版暂不支持哦

**Comment by mintrumpet** [comment]
可以自己实现，实际也是往hook地址发送，我这边已经更改了

**Comment by pgaowei** [comment]
> 

请问有具体实现步骤吗，我将ding.go里text改为content重新编译后会报“dial tcp: missing address”
