### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by mintrumpet** [cookieY/Yearning#749]
**Describe** **描述**

对于二次开发中，存在单个工单多个执行步骤的情况，在 yearning 的数据库设计上是否可以满足多个执行步骤的需求？

譬如以下情况：

- 回滚记录 core_rollbacks 中，是针对单个工单，里面记录 work_id
- 当存在多个执行步骤的时候，每个步骤的回滚语句会出现混淆
- 记录是 juno 产生的，work_id 应该是根据传的order的 work_id 生成，无法对其做额外的处理

希望可以支持多执行步骤的情况

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
流程基于串行逻辑，不支持并发执行的需求
