### ISSUE TITLE
无法注册用户？

### ISSUE THREAD

**Issue by clevertension** [cookieY/Yearning#751]
![image](https://user-images.githubusercontent.com/346723/215320889-1c37bfd7-d544-461d-8dea-5087f842b947.png)
user.vue里面，tp传的是create

可是
![image](https://user-images.githubusercontent.com/346723/215320917-c6851fac-1736-488b-9197-b13ddd12bc9b.png)
user.go文件里，switch没有create这个东西

难道我代码下错了??

**Comment by cookieY** [comment]
嗯 是的 代码下错了  https://github.com/cookieY/gemini-next
