### ISSUE TITLE
自增主键不指定时，SQL检测提示列数不匹配

### ISSUE THREAD

**Issue by hanzoi** [cookieY/Yearning#752]
**Describe** **描述**
提交DML SQL语句时，不指定自增主键(id)，SQL检测时会出现 列数不匹配的报错 

**To Reproduce** **如何复现**
执行DML语句时，key 和 value 不指定自增主键即可

**Expected behavior** **期望的结果**
如何可以确保自增主键自动递增，无需手动指定

**Comment by hanzoi** [comment]
语句是 insert into , 尝试加 set 语句可以实现自增，但是 set 的话不能同时插入多条，写起来也有点麻烦，不知道是否有办法 insert into 不加 set 实现自动自增

**Comment by cookieY** [comment]
@hanzoi 该问题将会在3.1.2版本中修复

**Comment by hanzoi** [comment]
> @hanzoi 该问题将会在3.1.2版本中修复

谢谢。我看已经有预发布版了，我可以自己先编译使用吗

**Comment by hanzoi** [comment]
我尝试下载 3.1.2 版本的源码，自行进行了编译，运行起来后发现仍然存在这个报错，是否是目前该版本仍然存在这个问题呢
