### ISSUE TITLE
SQL提交审批的时候，通过直接改包中的assigned可以指定任何人为审批人或执行人

### ISSUE THREAD

**Issue by reY2ox** [cookieY/Yearning#754]
我也是初次接触到yearning这个项目，
我公司用的是2.3.5
我在SQL提交审批的时候发现，通过直接改包中的assigned可以指定任何人为审批人或执行人
可能这个问题在后续版本中已经修复。想确认一下该问题还存在不，在哪个版本修复的？

**Comment by cookieY** [comment]
3.x版本已修复该问
