### ISSUE TITLE
v3.1.2.1 版本执行 Insert ，SQL 检测出现莫名其妙的错误提示

### ISSUE THREAD

**Issue by hanzoi** [cookieY/Yearning#755]
**Describe** **描述**
容器部署，使用 v3.1.2.1 镜像，执行 insert 语句，进行SQL检测时出现异常错误提示

**To Reproduce** **如何复现**
如上

**Expected behavior** **期望的结果**

**Screenshots** **截图**
<img width="855" alt="image" src="https://user-images.githubusercontent.com/61114924/216860377-0385009e-ccdb-4146-b79e-006d619e35e3.png">

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v3.1.2.2
