### ISSUE TITLE
YearningV2升级到V3版本以后，操作数据源保存提示出错

### ISSUE THREAD

**Issue by fanqinghui** [cookieY/Yearning#757]
mysql数据库，是5.7版本，UTF8mb4字符格式
使用了./Yearning migrate 命令进行了更新

对数据源进行保存操作的时候提示如下错误：
状态码:1200
config.toml文件中SecretKey值必须为16位！

经过检查，config.toml文件里的SecretKey 是默认的"dbcjqheupqjsuwsm"
请各位协作解决一下升级问题~

**Comment by cookieY** [comment]
你可以看下你的这个sk 是否是16个字符
