### ISSUE TITLE
v3.1.2.1版本sql检测错误，将varchar类型检测为了datetime类型。

### ISSUE THREAD

**Issue by as11144410** [cookieY/Yearning#759]
**Describe** **描述**
v3.1.2.1版本sql检测错误，将varchar类型检测为了datetime类型。

**To Reproduce** **如何复现**
创建表，表中字段类型为varchar，检测，报错。

**Expected behavior** **期望的结果**

不报错

**Screenshots** **截图**

![image](https://user-images.githubusercontent.com/28433464/217137867-2aea5326-3049-454b-a017-89bdffcdd27b.png)

**Desktop (please complete the following information):** **环境**
 - OS: mac
 - Browser: chrome
 - Version :v3.1.2.1

**Additional context** **其他**

**Comment by cookieY** [comment]
请把 完整建表语句发一下

**Comment by as11144410** [comment]
CREATE TABLE `cloud`.`gateway_model` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '网关型号id',
  `gateway_brand` tinyint(4) unsigned NOT NULL DEFAULT 0 COMMENT '1.飞凌，2.卡诺普',
  `gateway_model` varchar(100) NOT NULL DEFAULT '' COMMENT '网关型号',
  `model_explain` varchar(500) NOT NULL DEFAULT '' COMMENT '型号说明',
  `is_delete` tinyint(2) unsigned NOT NULL DEFAULT 0 COMMENT '0未删除，1已删除',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_Idx` (`gateway_brand`,`gateway_model`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网关型号表';

**Comment by as11144410** [comment]
@cookieY

**Comment by as11144410** [comment]
CREATE TABLE `cloud`.`gateway_model` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '型号id',
  `gateway_brand` tinyint(4) unsigned NOT NULL DEFAULT 0 COMMENT '1.fl，2.crp',
  `gateway_model` varchar(100) NOT NULL DEFAULT '' COMMENT '型号',
  `model_explain` varchar(500) NOT NULL DEFAULT '' COMMENT '型号说明',
  `is_delete` tinyint(2) unsigned NOT NULL DEFAULT 0 COMMENT '0未删除，1已删除',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_Idx` (`gateway_brand`,`gateway_model`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='型号表';

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v3.1.2.2
