### ISSUE TITLE
v3.1.2.1版本sql检测错误，DML语句insert 第二个值都是datatime类型

### ISSUE THREAD

**Issue by chen642636047** [cookieY/Yearning#760]
**Describe** **描述**
检测DML语句insert 第二个值都是datatime类型

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

![image](https://user-images.githubusercontent.com/11851326/217770423-6e8402b3-2028-4362-81b6-060ec33bfc16.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
https://github.com/cookieY/Yearning/releases/tag/v3.1.2.2
