### ISSUE TITLE
bug反馈，未审核的订单检测SQL不审核退出后就刷不出来此未审核订单了

### ISSUE THREAD

**Issue by sakufo** [cookieY/Yearning#766]
**Describe** **描述**
版本：yearning:v3.1.2.2
DML工单审核查看工单详细后不审核，点其它菜单（例如我的工单），再返回之前的审核-工单后会看不到之前待审核的工单

**To Reproduce** **如何复现**
A提交一个DML工单，流程B进行审核
当B点审核--进入工单--再点检测SQL后退出
再点我的工单会看到之前待审核的工作（只有撤销选项）
之后再点审核-工单会看不到之前待审核的那份工单，反复刷新页面都看不到，测试多个浏览器问题一样
只有注销B的账号再次登录才能在审核-工单菜单内看到

**Expected behavior** **期望的结果**
消除如上bug

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/9942967/222064936-d4b780aa-60c0-47f0-8052-06e640408ce6.png)
![image](https://user-images.githubusercontent.com/9942967/222064978-2167e524-d84b-4da5-a2e0-2a3bff904415.png)

**Desktop (please complete the following information):** **环境**
 - OS: WIN7
 - Version [[e.g. 22]](yearning:v3.1.2.2)

**Additional context** **其他**

**Comment by sakufo** [comment]
![image](https://user-images.githubusercontent.com/9942967/222066655-29d19df0-3f89-45a7-bb3f-d60adcabbb89.png)
这是在我的工单--工单详细里的信息。此时这条工单状态未审核，返回审核--工单菜单看不到这条工单。只有注销重新登录后才能看到

**Comment by fanqinghui** [comment]
我也测试发现了这个问题，麻烦尽快修复。。。

**Comment by cookieY** [comment]
将会在3.1.3版本中修复
