### ISSUE TITLE
Yearning在工单提交DDL的时候失败

### ISSUE THREAD

**Issue by zxy860320** [cookieY/Yearning#77]
DDL工单提交不了，
1.DDL工单指定审核人下拉菜单没有可供选择的人员，但是DML有
2.即使手动填写后提交工单的时候也报错，报的是工单缺失，请确定该工单是否缺失。
![image](https://user-images.githubusercontent.com/45409926/49123146-7e504f80-f2f2-11e8-9a33-c98acd61caa4.png)
![image](https://user-images.githubusercontent.com/45409926/49123160-90ca8900-f2f2-11e8-90d9-567d02190a1a.png)
不知道还需要做什么设置，请有知道的告诉我，谢谢！

**Comment by zxy860320** [comment]
使用谷歌浏览器有时候人员可以出来有时候出不来，没有明确的错误信息，目前测了两个版本1.3.3和1.3.4都会这样

**Comment by cookieY** [comment]
更新最新版chrome 不要开无痕 不要一机多开
