### ISSUE TITLE
DML语句INSERT在3.0之后不支持新增值为NULL，2.x是支持的

### ISSUE THREAD

**Issue by 815090488** [cookieY/Yearning#771]
DML语句INSERT在3.0之后不支持新增值为NULL，2.x是支持的
![image](https://user-images.githubusercontent.com/44593750/222874011-c0e1a216-1791-463a-afb0-efdf91be8261.png)

link_show 字段INSERT 数据库需要NULL值

**Comment by 815090488** [comment]
2.3.1版本
![image](https://user-images.githubusercontent.com/44593750/222877978-a7bdc77e-d195-4297-b0ba-f9ef7f64375e.png)

**Comment by cookieY** [comment]
该问题属于2.x系列的规则逃逸bug 3.0已修复 对于必须设置default的字段 使用Null进行规避这是不合理的
