### ISSUE TITLE
查询数据库的某几个表是会出现一直加载中，已排除数据库表问题

### ISSUE THREAD

**Issue by wisemeng** [cookieY/Yearning#774]
**Describe** **描述**
查询数据库的某几个表是会出现一直加载，查看F12已经报错，其他大部分数据库和表正常。
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/94349523/223600476-9b52b72a-b9f9-4c14-8dd0-5c54032d5e5e.png">

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
请查看后端相关信息
