### ISSUE TITLE
工单中检验语句时，影响函数显示错误

### ISSUE THREAD

**Issue by aosolao** [cookieY/Yearning#786]
**Describe** **描述**

在mysql客户端工具查询出结果为0行，也就是没有符合的结果。
但是在平台工单中将语句改为delete，SQL检测的时候，影响行会显示错误的行数。
实际执行下去，并不会对数据造成影响。所以应该是显示不正确的问题。
测试了不同的库与表，都存在相同的问题。

参考语句:
`SELECT * FROM cms.cms_content WHERE `code` IN ('123123','2345234','2312311');`

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**
![lQLPJxUUyj3iJ1jNA33NBqGwOD9_dps5sJkEEoQIawD-AA_1697_893](https://user-images.githubusercontent.com/30789071/226575513-82067737-4343-4b77-a829-47b39a5c541e.png)

![lQLPJxWdNtaZh1jNA9PNByiwU5BXADsvgmUEEoQIbUCDAA_1832_979](https://user-images.githubusercontent.com/30789071/226575835-52a67920-d7cd-494f-ad56-c2c8dcf1349c.png)

**Desktop (please complete the following information):** **环境**

docker部署
image: chaiyd/yearning:v3.1.2.2

**Additional context** **其他**

**Comment by cookieY** [comment]
https://next.yearning.io/feeback.html
