### ISSUE TITLE
用google浏览器执行查询语句语句时，如果查询结果的列过多，会导致整个浏览器被撑大。

### ISSUE THREAD

**Issue by chow-q** [cookieY/Yearning#789]
**Describe** **描述**

用google浏览器执行查询语句语句时，如果查询结果的列过多，会导致整个浏览器被撑大。

**To Reproduce** **如何复现**

用google浏览器执行查询语句语句时，如果查询结果的列过多

**Expected behavior** **期望的结果**

样式不变

**Screenshots** **截图**

![f29f075ea846408c02b9419bc82158de](https://user-images.githubusercontent.com/73530205/228115487-8f0a5fdb-e59a-47bb-992b-4f713898acce.png)

**Desktop (please complete the following information):** **环境**
 - OS: [windows]
 - Browser [chrome]
 - Version [3.1.3]

**Additional context** **其他**

**Comment by zhenglin305** [comment]
应该是3.1.2.2修复firefox浏览器出的bug，我直接回退到3.1.1了

**Comment by cookieY** [comment]
#784
