### ISSUE TITLE
查询导出功能希望能加到权限组，单独设置

### ISSUE THREAD

**Issue by sh-hanson** [cookieY/Yearning#79]
现在有需求就是提供查询权限，但是不想把导出结果开放给用户。
如果用目前的方式，就只能用户申请查询，审核的时候看有没有选择导出功能，如果选择就拒绝。这样感觉不太好。
正常的用户是不需要导出查询结果的，况且导出生产数据是有风险的。如果导出功能单独列出，那普通的查询用户就不需要提交审核，直接开通就好了。

**Comment by cookieY** [comment]
@sh-hanson 

本身用户查看到查询结果就意味着导出的风险，因为就算用户没有导出权限也可以通过以下方式导出数据。

例如：

1.一页一页的结果复制
2.截取返回数据快速获取所有数据

增加导出权限无非是增加了获取成本，但是这样的提升十分有限。

因为管理员不开启查询审核实际上就意味着用户可以随意的导出数据，因为用户看到的数据就是从数据库中导出来的。

因此如果真的是从数据泄露风险的角度考虑，那必然是开始查询审核来最大限度的规避风险。

此外，不管是否开启查询审核。该用户的所有操作行为都是有审计的。包括他提交查询申请时是否选择了导出数据(因为默认是否)。 这在一定程度上其实也增加了犯罪的成本。

综合以上，我个人认为这样的功能没有多大的实际意义。

**Comment by sh-hanson** [comment]
我是坚持有必要把查询权限一直开放出来，而且将导出功能单独设置权限，原因如下：
1、其实现在数据安全这块没有比较好的解决方法，大多数公司其实在做就是**增加获取数据的成本**，让数据不易获取（最大限度控制数据外流），这也是提升数据安全的一种措施。
2、我了解到的公司（互联网创业公司，本来就是迭代很快，线上问题几乎每天都有），给开发人员开生产数据库查询权限是很正常的事情，而且是要一直开着的。如果加了审核必然带来开发人员的反感，体验也不好。再如作者所说，因为有审计功能，所以即使一直开放查询权限，所做的操作都有记录，问题也不大。
3、导出功能还是需要的，但是要单独再审核。因为确实有些线上BUG需要大量数据来支持，这时只要有流程审核控制就可以。比如要CTO审核后才能导出

**Comment by cookieY** [comment]
@sh-hanson 嗯，每个公司的需求是不一样的。可以根据自身的需求进行对应的定制化开发。
