### ISSUE TITLE
查询无响应

### ISSUE THREAD

**Issue by axzsd** [cookieY/Yearning#796]
**Describe** **描述**
点击查询无响应，一直显示加载中

**Screenshots** **截图**
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/30335866/232951867-b56b7f26-b70f-4738-8486-50080a376a77.png">

navicat可以查询出来
<img width="352" alt="image" src="https://user-images.githubusercontent.com/30335866/232952024-d151aae2-e90f-49f3-ba1b-f95034b8c773.png">

**Desktop (please complete the following information):** **环境**
 - OS: mac
 - Browser chrome

yearning版本：3.1.3

**Comment by shiyindaxiaojie** [comment]
升级到 3.1.4 也是有这个问题

**Comment by cookieY** [comment]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/22343354/233884957-8abdfab1-e9bd-459e-ab50-aaf9966763d0.png">

**Comment by axzsd** [comment]
ok，确实是ws没有做反向代理，希望这种前端给一个提示
