### ISSUE TITLE
docker方式运行，有跨域问题

### ISSUE THREAD

**Issue by yangjiandong** [cookieY/Yearning#8]
run `docker run -it -d -p 80:80 -p 8000:8000 -e 192.168.1.109 registry.cn-hangzhou.aliyuncs.com/cookie/yearning:v0.0.3`

登录点击后，控制台报: 
`Failed to load http://192.168.1.109:8000/api-token-auth/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.109' is therefore not allowed access.`

**Comment by cookieY** [comment]
-e  "HOST=192.168.1.109"  应该是这样      docker版本已经更新到0.0.4 建议使用此版本 0.0.3有些问题
