### ISSUE TITLE
关于Yearning设定limit的问题

### ISSUE THREAD

**Issue by zhiqiang-xu** [cookieY/Yearning#800]
**Describe** **描述**
我们在yearing上执行SQL语句的时候，如果设置过了limit，就会爆出`limit数大于全局最大数`下面的错误。

→执行的SQL：
`SELECT * FROM table_0000 ORDER BY id DESC limit 1;`

→报错内容L：

`rpc error code=unknow desc=limit数大于全局最大数，请缩小查询范围`

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

现在我们生产环境一直使用Yearning这款OSS，但是这个问题一直不知道怎么解决。
希望给予support

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
在管理->设置页面可以设置查询limit限制大小

**Comment by zhiqiang-xu** [comment]
@cookieY 你好！感谢你的回复

我们也设置过了，现在设置了1000，但是还是不行。

我在细致的描述一下我们的问题
1 ： 我们的生产环境中有RDS的数据库，也安装了Yearning，也设置了limit，Yearning使用没有问题
2： 我们的容灾环境是生产环境库的replica，是个读写的replica，也设置了limit为10000，到那时执行sql的时候就会爆出我上面描述的错误。

**Comment by cookieY** [comment]
我有注意到你的报错是基于RPC调用Juno的报错，不知道是否在调用参数中的Limit 赋予了正确规则值

**Comment by zhiqiang-xu** [comment]
@cookieY  你好
我们就是在Yearning上执行下面的语句的时候爆出了错误。
`SELECT * FROM table_0000 ORDER BY id DESC limit 1;`

就像我上面说的，我们的库是个只读的replica库，我即便在Yearning的设定画面中设定了limit值，保存不爆粗，但是也反应到书Yearning 
这个库中的`core_global_confiaration`这个表。

**Comment by zhiqiang-xu** [comment]
@cookieY 
对于项目的问题，我现在经过调查之后。又有了新的发现

1： 我们安装Yearning的服务器上，同时安装了一个本地Mysql服务，我发现yearning上的所有配置都写入了这个本地的Mysql中
2： 我们在Yearning中配置的另一个云端的RDS的只读replica，然后执行`SELECT * FROM table_0000 ORDER BY id DESC limit 1;`的时候报错

**Comment by zhiqiang-xu** [comment]
@cookieY 
从 这个报错`rpc error code=unknow desc=limit数大于全局最大数，请缩小查询范围` 来看是不是我们取不到`全局最大数`这个值
这个值是在哪里设定的呢

**Comment by zhiqiang-xu** [comment]
![image](https://user-images.githubusercontent.com/10258454/233934453-7d7b2685-1805-4f2d-b437-509173d26900.png)

**Comment by cookieY** [comment]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/22343354/233934817-f9b3a84e-29e1-4c87-83fc-0c217c950df1.png">
https://next.yearning.io/dev/callback.html

**Comment by zhiqiang-xu** [comment]
@cookieY 
谢谢，我刚才解决了这个问题，非常感谢！！！
