### ISSUE TITLE
3.1.4版本审批执行按钮样式异常

### ISSUE THREAD

**Issue by Horus-K** [cookieY/Yearning#802]
**Describe** **描述**
3.1.4版本
审批执行按钮样式异常
![image](https://user-images.githubusercontent.com/48319268/234261537-d99be2bf-85f8-407d-aeaa-f341a3f71b2b.png)

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
<img width="255" alt="image" src="https://user-images.githubusercontent.com/22343354/234481388-564b3848-f1bd-4d81-b94c-e394151ce069.png">
请告知你的浏览器版本

**Comment by Horus-K** [comment]
chrome 版本 112.0.5615.138（正式版本） （64 位）  昨天更新后出现的，现在重新升级后可以了，应该是浏览器缓存？

**Comment by Horus-K** [comment]
![image](https://github.com/cookieY/Yearning/assets/48319268/a89cc6b0-8d9b-4747-a151-0e745a5d7eca)
确认了下，当审批工单比较多时，翻到页面中间的工单就会出现这个问题

**Comment by Horus-K** [comment]
并且部分工单执行后会跳到我的工单页面

**Comment by solomon-cc** [comment]
3.1.4使用google浏览器也是有这个问题，不是必现。网页缩放比例放小，再放大就正常了。
chrome版本 113.0.5672.93（正式版本） （64 位）

**Comment by cookieY** [comment]
v3.1.5 已修复这个问题
