### ISSUE TITLE
秘钥解析失败,无法解密当前密码！

### ISSUE THREAD

**Issue by qianghong000** [cookieY/Yearning#805]
**秘钥解析失败,无法解密当前密码！**

 [Error] 2023-04-26 17:56:16 (/Users/henryyee/PersonalProjects/Yearning-go/src/lib/encrypt.go:108) 秘钥解析失败,无法解密当前密码！

**To Reproduce** **如何复现**

我使用的外部数据库

**Expected behavior** **期望的结果**

问题解决

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**
OS: [Ubuntu]

**Additional context** **其他**

**Comment by cookieY** [comment]
https://next.yearning.io/guide/install.html#%E5%85%B3%E4%BA%8E-secretkey

**Comment by qianghong000** [comment]
不行啊。我是使用的外部数据库

**Comment by qianghong000** [comment]
这个安装教程很简单， SecretKey = "dbcjqheupqjsuwsm"  这一行我只改了两个字母，启动后点击个人信息页面就报错

**Comment by cookieY** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/22343354/236716422-a0cacfd1-14f1-4402-a0c8-f0640ee94094.png">

**Comment by qianghong000** [comment]
是在运行./Yearning install 命令之前修改的，数据库都清空好几次了

**Comment by qianghong000** [comment]
初次安装不就是 ./Yearning install 吗

**Comment by cookieY** [comment]
秘钥必须16位

**Comment by qianghong000** [comment]
是16位数，我的conf.toml内容如下：
[Mysql]
Db = "yearning_prod"
Host = "192.168.0.111"
Port = "3306"
Password = "Ops2023"
User = "ops"

[General]
SecretKey = "fcyxqheuxxxsuwxx"

**Comment by teaGod-s** [comment]
最后解决了没，怎么解决的？
