### ISSUE TITLE
后端为mycat时，执行insert语句报错找不到表

### ISSUE THREAD

**Issue by degary** [cookieY/Yearning#809]
**Describe** **描述**
后端为mycat语句时，执行insert语句报错 表名'db_name.table_name' 不存在.
在mycat上可以看到报错
executeSql= SHOW FULL FIELDS FROM `db_name`.`table_name`]No dataNode found ,please check tables defined in schema

直接在mycat上执行insert语句是没问题的。请问这种情况如何解决

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
暂时还没有适配mycat

**Comment by XDongo** [comment]
> 

可以考虑支持吗，我们也遇到了这个问题

**Comment by cookieY** [comment]
执行走的都是标准SQL 并不会对你的SQL进行处理，这个还是要看mycat这边的逻辑到底是怎么样的
