### ISSUE TITLE
优化建议：单表多条DDL合并最好能自动生成

### ISSUE THREAD

**Issue by sh-hanson** [cookieY/Yearning#81]
![image](https://user-images.githubusercontent.com/41986080/49776875-efebbd00-fd38-11e8-9b79-010a7ee471b4.png)
![image](https://user-images.githubusercontent.com/41986080/49776881-f7ab6180-fd38-11e8-8c54-011cdc9f33af.png)

同一个表多个ddl语句，提示要合并。但是在新建的窗口感觉不好合并提交。
最好能在提交窗口中直接生成。手动模式，一般开发都不会直接写语句，会写的可能也不会考虑合并
![image](https://user-images.githubusercontent.com/41986080/49778227-0e54b700-fd3f-11e8-9d51-a61ad70f7ac7.png)

**Comment by cookieY** [comment]
@sh-hanson 请详细查看inception文档对应参数
