### ISSUE TITLE
首页统计信息时间异常

### ISSUE THREAD

**Issue by h31105** [cookieY/Yearning#810]
**Describe** **描述**
3.1.4版本
首页统计信息时间异常
正常应该统计的是最近9天？的数据
但实际显示的时间是未来9天的跨度

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**
![image](https://github.com/cookieY/Yearning/assets/38588395/e8d3e26d-80a8-401d-a8b0-6f1a5fc12deb)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by cookieY** [comment]
其实 这个图表内的数值一直都是没有意义的 - - 后面会优化一下
