### ISSUE TITLE
查询的历史记录可以长期保存吗

### ISSUE THREAD

**Issue by helopng** [cookieY/Yearning#811]
**Describe** **描述**
现在的查询历史只有在浏览器开着时可用, 关闭浏览器就没了. 有一些查询数据的SQL基本是不变的, 这里历史查询是否能长期保存吗

**To Reproduce** **如何复现**
关闭浏览器

**Expected behavior** **期望的结果**
历史查询长期保存

**Desktop (please complete the following information):** **环境**
 - OS:  Windows11
 - Browser: Chrome
 - Version [113.0.5672.93]

**Comment by cookieY** [comment]
如果是需要长期使用的 应该保存在剪贴板中

**Comment by helopng** [comment]
好的, 是我疏忽了, 提完才看到剪贴板确实可以满足使用
