### ISSUE TITLE
审核通过，但执行阶段失败，失败原因：ERROR 1075 (42000): Incorrect table definition; there can be only one auto column and it must be defined as a key

### ISSUE THREAD

**Issue by corama** [cookieY/Yearning#817]
**Describe** **描述**
正常提单流程中对于定义了 auto_increment 字段、但未定义 key 的DDL， 审核可以通过，但执行阶段报错，报错信息如下：
ERROR 1075 (42000): Incorrect table definition; there can be only one auto column and it must be defined as a key

**To Reproduce** **如何复现**
审核以下SQL：
CREATE TABLE `t`(
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` BIGINT(12) NOT NULL,
  `create_time` DATETIME DEFAULT NULL,
  KEY `idx_uid` (`uid`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='test';

**Expected behavior** **期望的结果**
审核阶段不允许通过

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**
 - OS: [e.g. iOS] Centos 7
 - Browser [e.g. chrome, safari] chrome
 yearning版本 V3.1.1

**Additional context** **其他**

**Comment by cookieY** [comment]
<img width="1068" alt="image" src="https://github.com/cookieY/Yearning/assets/22343354/3e1aea77-da19-4441-8126-5e63d89d9687">


或者试一下 v.3.1.4 ?
