### ISSUE TITLE
执行建表语句时提示表名长度超过10

### ISSUE THREAD

**Issue by zzyork** [cookieY/Yearning#818]
**Describe** **描述**
今天执行一个建表语句时，右击审核提示错误信息表xxxxx名称长度11超过最大长度10，请问这个最大长度能在配置文件里修改嘛？还是说软件就是这样设置的？

**Screenshots** **截图**
![image](https://github.com/cookieY/Yearning/assets/45233837/c98ec080-10f4-4f73-a4ff-8a10a491831b)

**Comment by zzyork** [comment]
找到在哪儿设置了

**Comment by zzyork** [comment]
找到为设置位置了

**Comment by songlongkuan** [comment]
在哪设置啊
