### ISSUE TITLE
移动端打开审核界面，部分按钮显示不出来

### ISSUE THREAD

**Issue by unslur** [cookieY/Yearning#819]
**Describe** **描述**
我的是小米9手机，chrome浏览器，在进行审核时，经过检查后，点击通过按钮时，二次确定弹窗的位置，会在移动端显示不出来

**Expected behavior** **期望的结果**

二次弹窗位置是否可以局中，当然审核检测的时候，能不打开手机的输入框就更好了。

**Screenshots** **截图**

![image](https://github.com/cookieY/Yearning/assets/15623689/a2201243-e091-4773-80c4-e464ad7301b8)

**Comment by cookieY** [comment]
社区版暂未适配移动端
