### ISSUE TITLE
添加字段时不能设置字段排序位置

### ISSUE THREAD

**Issue by sh-hanson** [cookieY/Yearning#82]
![image](https://user-images.githubusercontent.com/41986080/49778278-64c1f580-fd3f-11e8-99a7-24d43c3066e2.png)
如图，我要添加tcode字段，想加到tname后面，就不好直接生成。最好后面有调整字段排序位置的按钮

**Comment by cookieY** [comment]
@sh-hanson 抱歉 暂时没有这样的计划
