### ISSUE TITLE
工单不能提交回滚语句

### ISSUE THREAD

**Issue by Gedatang** [cookieY/Yearning#820]
**Describe** **描述**

1.提交工单执行了DML语句，是否回滚选项选择了“是”，update修改一行数据
2.工单执行成功，执行结果显示：“执行&备份 成功”
3.发现数据修改错了，想回滚工单的操作，执行“提交回滚语句”，显示“回滚语句提交不得为空”

**To Reproduce** **如何复现**
模拟提交一条DML语句然后回滚

**Expected behavior** **期望的结果**

**Screenshots** **截图**

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by Gedatang** [comment]
Desktop (please complete the following information): 环境

OS: mac 12.3.1
Browser [chrome, safari]
Version [3.1.3]

DML UPDATE没有生成回滚语句

**Comment by cookieY** [comment]
https://next.yearning.io/feeback.html#%E5%9B%9E%E6%BB%9A%E8%AF%AD%E5%8F%A5
