### ISSUE TITLE
给用户去掉审批权限后，用户只要不重新登录，就还可以审批工单

### ISSUE THREAD

**Issue by punmin** [cookieY/Yearning#822]
**Describe** **描述**
给用户去掉审批权限后，用户只要不重新登录，就还可以审批工单，重新登陆后，就无法审批了

**To Reproduce** **如何复现**
1. 管理员给用户A添加审批权限
2. 用户A登录到yearning
3. 管理员去掉用户A的审批权限
4. 用户B提查询工单
5. 用户A审批用户B的查询工单
6. 查看用户B的工单状态，并且通过工单查询数据

**Expected behavior** **期望的结果**
在第3步去掉用户A的审批权限后，第5步应该审批失败才对

**Desktop (please complete the following information):** **环境**
 - Version [chaiyd/yearning:v3.0.8]

**Comment by cookieY** [comment]
目前审批工单的审批流程是在提交工单时生成，当提交工单后再对节点中的审核人进行修改时是不会同步到已提交的工单流程中

**Comment by punmin** [comment]
先执行的第三步管理员去掉用户A的审批权限，再执行的用户B提交查询工单

**Comment by punmin** [comment]
> 目前审批工单的审批流程是在提交工单时生成，当提交工单后再对节点中的审核人进行修改时是不会同步到已提交的工单流程中

先执行的第三步管理员去掉用户A的审批权限，再执行的用户B提交查询工单，意味着工单是在修改审批权限后，提交的新工单

**Comment by cookieY** [comment]
查询工单，走的是数据源负责人的流程  SQL工单走的是流程 这是两套不一样的体系

**Comment by punmin** [comment]
> 查询工单，走的是数据源负责人的流程 SQL工单走的是流程 这是两套不一样的体系

但是用户重新登录后，就无法再审批新工单了，说明这个权限变更是有效的

**Comment by punmin** [comment]
重点在于不重新登录，还能审批新工单，重新登录就不能审批新工单了

**Comment by cookieY** [comment]
负责人角色目前是将信息加密保存在了token里面所以才会出现你所说的情况，3.1.5会优化这个问题
