### ISSUE TITLE
执行dml，新增默认时间字段出错

### ISSUE THREAD

**Issue by reacar** [cookieY/Yearning#823]
SQL语句：
ALTER TABLE paper_manage.paper ADD jcr_partition_time DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL COMMENT 'jcr分区年份';
ALTER TABLE paper_manage.paper ADD cas_partition_time DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL COMMENT 'cas分区年份';

Yearning版本：3.1.2 

![image](https://github.com/cookieY/Yearning/assets/74039707/a8136be5-f580-480e-a6c9-a5c1a3f88468)

**Comment by Gedatang** [comment]
我也遇到了这个问题，默认值全为0，审核不通过

**Comment by cookieY** [comment]
v3.1.5 已修复这个问题
