### ISSUE TITLE
优化,工单审批排在后面的审批数据审批时存在审批确定按钮被遮挡

### ISSUE THREAD

**Issue by FelixLiuSheng** [cookieY/Yearning#825]
**Describe** **描述**
![image](https://github.com/cookieY/Yearning/assets/18569549/f3f6b773-601e-49b6-bf32-6102e0036c9c)
如图,该审批不在第一条，可能在分页里面的最后一条，点击审批同意时，出现上图,确定按钮被遮挡

**To Reproduce** **如何复现**

进入审核工单,下来审批工单到第一页的最后一条或者最后几条(注意第一条是可以的,排序在后面的就不可以了),点击审批会出现上面情况

**Expected behavior** **期望的结果**

希望确定按钮可以正常显示

**Screenshots** **截图**
![image](https://github.com/cookieY/Yearning/assets/18569549/3e5841e0-6542-41fb-b71d-766126e7ea20)

**Desktop (please complete the following information):** **环境**
 - OS: MAC、WIN的谷歌浏览器都一样
 - Browser chrome、safari
 - Version ：3.1.4

**Additional context** **其他**

**Comment by cookieY** [comment]
v3.1.5 已修复这个问题
