### ISSUE TITLE
3.1.4版本审批执行按钮样式异常

### ISSUE THREAD

**Issue by chow-q** [cookieY/Yearning#829]
**Describe** **描述**

有多个待审批的工单的时候，点击同意后，确认按钮被隐藏，根本点不到，崩溃啊。
![65bb95054a06f61cf3a6ca7ae490f206](https://github.com/cookieY/Yearning/assets/73530205/fdce532a-0dfc-42fc-8aeb-305bfec516f6)

**To Reproduce** **如何复现**

多个待处理工单

**Expected behavior** **期望的结果**

能正常显示，现在是点不了。

**Desktop (please complete the following information):** **环境**
 - OS: win 和苹果都有
 - Browser 360和Google浏览器都不行
 - Version 3.1.4

**Additional context** **其他**

**Comment by FelixLiuSheng** [comment]
我在#825 提过该问题了，希望可以改改，每天都使用js脚本执行改变界面来审核

**Comment by Horus-K** [comment]
@FelixLiuSheng 大佬可以公开下js脚本吗

**Comment by cookieY** [comment]
v3.1.5 已修复这个问题
