### ISSUE TITLE
针对AWS-RDS实例，DML工单执行失败

### ISSUE THREAD

**Issue by zerostarfro** [cookieY/Yearning#83]
报错信息：Execute: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
网上资料显示，aws无法授予super权限，相应的sql优化，网上建议如下https://stackoverflow.com/questions/31315660/1227-access-denied-you-need-at-least-one-of-the-super-privileges-for-thi
望参考，谢谢！

**Comment by YoloByg** [comment]
或者有其它的解决办法也请告知

**Comment by cookieY** [comment]
@zerostarfro 请将rds 设置为binlog row模式

**Comment by zerostarfro** [comment]
已设置，之前的问题没有了，产生了一个新的问题，ddl可以执行成功，查看回滚语句为空，查看备份库，备份表已建立，然数据为空，aws上binlog可以查看到执行记录，这个可能是哪里出了问题呢？
附rds binlog相关参数：
log-bin=/rdsdbdata/log/binlog/mysql-bin-changelog
binlog_format=ROW
log_statements_unsafe_for_binlog=0
sync_binlog=1
