### ISSUE TITLE
3.1.4版本用户查询工单被审批后没有邮件回复

### ISSUE THREAD

**Issue by xudelong07** [cookieY/Yearning#833]
yearning3.1.4
1. 用户提交查询工单, 审批通过后没有通知提交人, 这个很不方便, 希望可以恢复通知提交人的功能
2. 期望可以支持存储过程和自定义变量的工单审核

我的邮箱: xudelong@virtaitech.com

**Comment by xudelong07** [comment]
目前 sqle 审核平台正在追赶yearning, 对 存储过程和自定义变量的工单审核 支持的很好, 但是查询功能不如yearning, yearning加油!

**Comment by cookieY** [comment]
当前测试审批后会发送邮件给申请人告知结果 请查看后台日志是否存在邮箱配置问题

**Comment by Huangzsnone** [comment]
存储过程执行什么时候支持啊
