### ISSUE TITLE
update检测2000多行

### ISSUE THREAD

**Issue by grandwill** [cookieY/Yearning#846]
**Describe** **描述**
整张表都没有2000多行啊

**To Reproduce** **如何复现**

一旦 where 是 mer_order_no = 就会出现

**Expected behavior** **期望的结果**

应该就是一行的。。

**Screenshots** **截图**
![图片](https://github.com/cookieY/Yearning/assets/141031825/1e2c6d70-59cc-4828-9308-445f48ff615f)

**Desktop (please complete the following information):** **环境**
 
 aliyun rds 5.7 主库

**Comment by cookieY** [comment]
https://next.yearning.io/feeback.html#%E5%BD%B1%E5%93%8D%E8%A1%8C%E6%95%B0

**Comment by grandwill** [comment]
谢谢大佬
