### ISSUE TITLE
表结构里面显示可以为空 但是sql 审核平台检测出来不能为空

### ISSUE THREAD

**Issue by rookiesince** [cookieY/Yearning#847]
**Describe** **描述**

表结构里面显示可以为空 但是sql 审核平台检测出来不能为空

**To Reproduce** **如何复现**

**Expected behavior** **期望的结果**

**Screenshots** **截图**

![image](https://github.com/cookieY/Yearning/assets/51947244/ae34000b-18a8-433c-a918-a6e471dcac17)
![image](https://github.com/cookieY/Yearning/assets/51947244/7584e232-8d53-4cec-a058-7a79f728021b)

**Desktop (please complete the following information):** **环境**
Yearning © 2018-2023 Created by HenryYee ver.3.1.4

**Additional context** **其他**

**Comment by cookieY** [comment]
查看审核规则是否设置为不允许为null
