### ISSUE TITLE
请问Yearning使用两个端口，如何设置nginx

### ISSUE THREAD

**Issue by veryrich** [cookieY/Yearning#85]
作者您好，最近想在公司使用Yearning，但是我发现yearning同时使用了两个端口，一个是8000一个是8080，
我觉着这样很麻烦，比如我想前面加一台nginx或者haproxy， 就不知道要怎么设置，如果所有流量都转发到8080，那么就会导致8000无法访问🤔
不知道在这种需要nginx转发一次的需求下，有什么好的解决方能嘛？ 打扰您了，希望您能回复😀🌹

**Comment by cookieY** [comment]
@veryrich 因为是动静分离的架构 所以会有两个端口 这个是无法改变的 8000是必须开放的且不可变 8080你可以随便改

**Comment by veryrich** [comment]
谢谢@cookieY回复，最终通过修改yearning的默认url ，+ haproxy 解决了这个需求……
    	
    	

    	
    
  




On Fri, Dec 14, 2018 at 9:49 AM +0800, "cookieY" <notifications@github.com> wrote:












@veryrich 因为是动静分离的架构 所以会有两个端口 这个是无法改变的 8000是必须开放的且不可变 8080你可以随便改
