### ISSUE TITLE
如下图，数据查询报错，执行任何sql都报错。

### ISSUE THREAD

**Issue by guofushan** [cookieY/Yearning#854]
**
![image](https://github.com/cookieY/Yearning/assets/48540932/fc434855-dc13-4f97-aea5-db25a708ad26)
**

**Comment by cookieY** [comment]
如采用反向代理的方式访问Yearning请在代理层对websocket协议进行代理支持。

例如: nginx 需要配置 proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade";

**Comment by guofushan** [comment]
hi，没有用到反向代理。

**Comment by cookieY** [comment]
你需要提供浏览器控制台关于websocket的错误信息，当前截图无法定位问题

**Comment by cookieY** [comment]
我们似乎定位到了问题 将会在不久紧急更新

**Comment by cookieY** [comment]
已修复至3.1.6.1

**Comment by guofushan** [comment]
hi，
查询页面执行了个delete语句后，页面卡死无法退出。最新版的








&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cookieY/Yearning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月10日(星期四) 下午4:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cookieY/Yearning] 如下图，数据查询报错，执行任何sql都报错。 (Issue #854)





 
我们似乎定位到了问题 将会在不久紧急更新
