### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by feifeigege** [cookieY/Yearning#855]
**描述问题**
  清晰而简洁地描述你遇到的问题
  
**复现**
重现该行为的步骤:
  1. 开启在线表变更工具
  2. OSCExpr  使用了绝对路径执行 gh-ost
  /usr/bin/gh-ost \
  --aliyun-rds \
  --assume-rbr \
  --allow-on-master \
  --host=$ADDR \
  --assume-master-host=$ADDR \
  --port=$PORT \
  --user=$USER \
  --password=$PASSWORD \
  --database=$SCHEMA \
  --table=$TABLE \
  --alter=$SQL \
  --max-load=Threads_running=150 \
  --critical-load=Threads_running=1000 \
  --chunk-size=5000 \
  --cut-over=default \
  --verbose \
  --execute
  4. 执行失败
exec: "pt-online-schema-change": executable file not found in $PATH
5.尝试了各种方法，增加环境变量，/usr/local/sbin/gh-ost  /usr/bin/gh-ost /opt/ghost/gh-ost 都复制了一份，也都再$PATH里，服务器、服务器都重启过了，仍然提示executable file not found in $PATH，版本由3.1.0将为3.5.0还是不行。
  
**期望的结果**
gh-ost可以正常执行
  
**截图**
  
![image](https://github.com/cookieY/Yearning/assets/22868778/443cd169-ff01-45c4-a2d7-2a2b14660569)

  
**部署方式**

- [ ] Manual
  
**环境 (请填写环境信息):**
- 操作系统: CentOS Linux release 7.9.2009 (Core)

- 浏览器 [Chrom]
- 版本号 [Version: 3.0.5 Uranus]
  
**额外的日志信息**
在这里添加有关该问题的所有日志。

**Comment by cookieY** [comment]
确认是否使用了已编译的包还是自己编译 使用juno的呢

**Comment by feifeigege** [comment]
wget https://github.com/cookieY/Yearning/releases/download/v3.1.4/Yearning-v3.1.4-linux-amd64.zip
下载开箱即用的

**Comment by feifeigege** [comment]
在服务器上手动执行gh-ost命令并传参，是可以成功执行的，现象来说是yearning找不到gh-ost的路径

**Comment by cookieY** [comment]
可以提供以下后端的日志信息

**Comment by feifeigege** [comment]
![image](https://github.com/cookieY/Yearning/assets/22868778/df000dfc-4c28-470d-b427-88d75d4fd5cc)

**Comment by cookieY** [comment]
似乎这是个老版本的bug 尝试使用3.1.5

**Comment by feifeigege** [comment]
升级3.1.5，问题解决了，感谢
