### ISSUE TITLE
[Question] [PANIC RECOVER] runtime error: index out of range

### ISSUE THREAD

**Issue by wang-xiaowu** [cookieY/Yearning#883]
**Describe the question**
A clear and concise description of what the question is.

**To Reproduce**
1. 审核-》工单-》详情
2. 点击详情按钮
3. 提示：状态码:500

**Expected behavior**

**Screenshots**
![image](https://github.com/cookieY/Yearning/assets/44340137/84fc5ac2-f992-4786-b5d1-d62475ca0226)

**Deployment**
- [x] Docker
- [ ] Manual

**Env (please complete the following information):**
- Browser [e.g. chrome, safari]：chrome
- Version [e.g. 22]：latest

**Additional Logs**
执行类似sql
```sql
UPDATE xxx
SET xxx = 3999 
WHERE
        xxx IN (
                3468389621786481152,
                3468336257435652608,
                3468328850666820096,
                3468322593466962432,
        3382914393732876800,
        3375173243680918784)
```

```
 [Critical] 2023-08-14 15:08:50 (github.com/cookieY/yee@v0.3.9/middleware/recovery.go:33) [PANIC RECOVER] runtime error: index out of range [4] with length 4 Traceback:
	runtime/panic.go:113
	Yearning-go/src/handler/fetch/fetch.go:130
	Yearning-go/src/apis/fetch.go:23
	github.com/cookieY/yee@v0.3.9/context.go:128
	github.com/cookieY/yee@v0.3.9/middleware/gzip.go:66
	github.com/cookieY/yee@v0.3.9/context.go:128
	github.com/cookieY/yee@v0.3.9/middleware/recovery.go:38
	github.com/cookieY/yee@v0.3.9/context.go:128
	github.com/cookieY/yee@v0.3.9/middleware/logger.go:58
	github.com/cookieY/yee@v0.3.9/context.go:128
	github.com/cookieY/yee@v0.3.9/middleware/cors.go:96
	github.com/cookieY/yee@v0.3.9/context.go:128
	github.com/cookieY/yee@v0.3.9/yee.go:207
	github.com/cookieY/yee@v0.3.9/yee.go:133
	net/http/server.go:2937
	net/http/server.go:1996
	runtime/asm_amd64.s:1599
```

**Comment by cookieY** [comment]
似乎是在流程节点判断中出现了数组越界的问题，你确定对同一个数据源的再次提交是否可以复现

**Comment by wang-xiaowu** [comment]
> 似乎是在流程节点判断中出现了数组越界的问题，你确定对同一个数据源的再次提交是否可以复现

嗯 复现了，`update xxx set xxx= 'xxx' where xxx = 'xxxx';`

**Comment by cookieY** [comment]
方便提供该数据源绑定的流程 的详细信息么

**Comment by wang-xiaowu** [comment]
- 流程
![image](https://github.com/cookieY/Yearning/assets/44340137/ae6a3259-83fa-40f4-884a-ca10c03bf409)

- 提交工单
![image](https://github.com/cookieY/Yearning/assets/44340137/043c7e60-9246-45cc-b865-3371582d7b05)

**Comment by cookieY** [comment]
目前定位为 流程节点越界问题，但是为什么会越界根据目前提供的信息还无法定位
当前怀疑是由于 工单创建后 减少了该工单数据源所在的流程节点从而导致了数据越界的问题

**Comment by wang-xiaowu** [comment]
有什么解决办法吗？
我是从3.1.3升到目前最新的一个版本的，没看到release note有提到需要做兼容之类的部分
那我先回滚吗？

**Comment by cookieY** [comment]
> 有什么解决办法吗？ 我是从3.1.3升到目前最新的一个版本的，没看到release note有提到需要做兼容之类的部分 那我先回滚吗？

在流程节点变动前请先确保该流程所在的数据源对应工单都处于非审核中状态，对于现在的情况 将该工单作废后重新提交一个新的应该就不会有这个问题了

**Comment by wang-xiaowu** [comment]
可是我点进详情，就500了
![image](https://github.com/cookieY/Yearning/assets/44340137/cbddcfb1-c7b3-4214-988b-c69144318642)

**Comment by cookieY** [comment]
我说了 这个单子作废 重新提交个新的单子

**Comment by wang-xiaowu** [comment]
嗯嗯
还有就是，这是升级以来第二个出现这个问题的工单，应该不是偶现问题

**Comment by cookieY** [comment]
我上面已经说了 这个情况只有在工单创建后减少了该工单数据源所在的流程节点才会导致，需要注意这样的操作

**Comment by wang-xiaowu** [comment]
> 我上面已经说了 这个情况只有在工单创建后减少了该工单数据源所在的流程节点才会导致，需要注意这样的操作

我可以确定并没有你说的这个操作

**Comment by cookieY** [comment]
复现的情况是这样的问题 可以根据代码寻找到对应的代码段

```
	model.DB().Where("work_id = ?", workId).Find(&s)
	var steps []StepInfo
	for _, v := range whoIsAuditor {
		steps = append(steps, StepInfo{Tpl: v})
	}
	for i, v := range s {
		steps[i].CoreWorkflowDetail = v
	}
```

问题出在这里了，由于3.1.6版本将进行时的步骤详细信息与全部步骤信息做了融合，由于流程信息是实时去计算的。

打个比方:

该工单原本流程节点为3个

当进行到第2个节点时，已经生成了2条步骤信息 

这时将流程节点从3个变成1个 

此时当工单点击继续后，就会出现这样的情况

本质上是数据的问题

**Comment by wang-xiaowu** [comment]
嗯
我再观察下

**Comment by cookieY** [comment]
目前在下个小版本中将会限制流程编辑，只有当流程对应的工单都已处于结束状态时才允许变更流程信息

**Comment by wu1663307760** [comment]
我也遇到了这个错误，并且经常出现；
发生版本： Yearning © 2018-2024 Created by HenryYee ver.3.1.9
部署： k8s 1.26
刚开始sql工单里有sql语句， 刷新几下，sql语句没了， 报500
![image](https://github.com/user-attachments/assets/88943921-08c3-48a5-930b-0c6346a9c60a)

![image](https://github.com/user-attachments/assets/aaeb6f01-4040-4c54-bcee-79249075d333)
![image](https://github.com/user-attachments/assets/0d0d4d66-89c0-4f33-8db5-8d24e5efd236)


经过一段时间研究，发现了原因， 审核人审核时候点击2次同意就会出现这种情况；
怪不得研发团队经常遇到这种情况， 没有做多点击处理；

![image](https://github.com/user-attachments/assets/a4fcdccb-82d9-4b1c-b094-7fd18ff897fa)
