### ISSUE TITLE
[Question] osc执行失败

### ISSUE THREAD

**Issue by feifeigege** [cookieY/Yearning#886]
**描述问题**
osc执行失败 请检查相关设置是否正确/该表之前如进行过osc kill操作 请清除该表相关触发器及临时表等遗留数据
  
**复现**
重现该行为的步骤:
1.ocs失败后清理遗漏表，再次执行还是这个提示
2.确实是把遗留表都删除了，检查了没有触发器
3.而且将表重命名（eg: tablex改名tablex1）可以执行成功
  
**期望的结果**
  清晰而简洁地描述你希望得到的结果
  
**截图**
  

![image](https://github.com/cookieY/Yearning/assets/22868778/7bf2aa76-b396-4b43-b9cf-bcb7a5af888f)
![image](https://github.com/cookieY/Yearning/assets/22868778/85a37ed0-eabd-4b45-a415-80145d3f93b4)
![image](https://github.com/cookieY/Yearning/assets/22868778/dfd95a44-4031-4c9c-85d3-6090387d6ee8)

  
**部署方式**

- [ ] Manual
  
**环境 (请填写环境信息):**
- 操作系统: [CentOS Linux release 7.9.2009]
- 浏览器 [Chrom]
- 版本号 [3.1.5]
  
**额外的日志信息**
level=error msg="osc执行失败 请检查相关设置是否正确/该表之前如进行过osc kill操作 请清除该表相关触发器及临时表等遗留数据"

**Comment by cookieY** [comment]
你可以在本地使用pt-osc 执行看看是否会报错

**Comment by feifeigege** [comment]
两个要注意的地方：
1.ghost要加参数--initially-drop-ghost-table
2.失败后默认/tmp/gh-ost.dbname.tablename.sock,一直存在，要手动清理

**Comment by feifeigege** [comment]
两个要注意的地方：
1.ghost要加参数--initially-drop-ghost-table
2.失败后默认/tmp/gh-ost.dbname.tablename.sock,一直存在，要手动清理

**Comment by feifeigege** [comment]
多谢指导
