### ISSUE TITLE
针对RDS的DML操作查看备份数据为空

### ISSUE THREAD

**Issue by zerostarfro** [cookieY/Yearning#89]
关联ISSUE: 针对AWS-RDS实例，DML工单执行失败 #83
已设置，之前的问题没有了，产生了一个新的问题，ddl可以执行成功，查看回滚语句为空，查看备份库，备份表已建立，然数据为空，aws上binlog可以查看到执行记录，这个可能是哪里出了问题呢？（可以确定是只有RDS有这个问题，本地库DML可以回滚成功）

附rds binlog相关参数：
log-bin=/rdsdbdata/log/binlog/mysql-bin-changelog
binlog_format=ROW
log_statements_unsafe_for_binlog=0
sync_binlog=1

_Originally posted by @zerostarfro in https://github.com/cookieY/Yearning/issues/83#issuecomment-447786098_

**Comment by cookieY** [comment]
@zerostarfro 请检查该表是否拥有主键

**Comment by zerostarfro** [comment]
嗯，已解决，就是主键的问题，谢谢~
