### ISSUE TITLE
[Question] yearning进程异常退出

### ISSUE THREAD

**Issue by feifeigege** [cookieY/Yearning#892]
**描述问题**
在点审核  同意按钮时，yearning进程异常退出

后端日志报错信息
Aug 23 15:16:57 yearning.tesong.net bash[24905]: time="2023-08-23T15:16:57+08:00" level=error msg="Error 1040: Too many connections" file="gitee.com/cookieYe/enginex@v0.0.0-00010101000000-000000000000/parse/parse.go:232"
Aug 23 15:16:57 yearning.tesong.net bash[24905]: panic: runtime error: invalid memory address or nil pointer dereference

  
**复现**
重现该行为的步骤:
1.目标数据库配置较低，iops使用率较高，Too many connections就是数据库返回报错
2.但是这个是yearning进程异常退出的原因吗，如果是的话，这不可被接受。
  
**期望的结果**
  DDL正常执行，异常时输出报错信息，但yearning进程不能退出。
  
**截图**
  
![image](https://github.com/cookieY/Yearning/assets/22868778/6a2500dc-43b4-4d50-a892-72e890c6adb0)
![image](https://github.com/cookieY/Yearning/assets/22868778/b74a51e6-9513-4658-9e53-c035bf2982bf)

  
**部署方式**

- [ ] Manual
  
**环境 (请填写环境信息):**
- 操作系统: [CentOS Linux release 7.9.2009]
- 浏览器 [Chrom]
- 版本号 [3.1.5]
  
**额外的日志信息**

**Comment by feifeigege** [comment]
不是必现，但最近发生概率很高

**Comment by cookieY** [comment]
由于服务端连接过多，无法让Yearning建立有效连接，导致审核结束后关闭连接异常(因为根本没有建立连接)，当前对close方法已做nil 判断，但不清楚为什么这里没有生效。在下个版本中升级orm库看下是否能解决这个问题，感谢反馈

**Comment by cookieY** [comment]
也许在3.1.6.3中修复了？

**Comment by ghostg00** [comment]
我也出现了 panic: runtime error: invalid memory address or nil pointer dereference ，可以报错，但是进程别退出啊
