### ISSUE TITLE
[Question]  DDL审核报错

### ISSUE THREAD

**Issue by solomon-cc** [cookieY/Yearning#894]
**Describe the question**
DDL 语句，审核报错  %!(EXTRA string=uc_growthintegralrecord.businessSource)	
**To Reproduce**
1.检查过审核规则，没有发现有什么问题

**Expected behavior**
审核通过
**Screenshots**
![image](https://github.com/cookieY/Yearning/assets/25998534/dc8c99bf-d1d7-429b-99e1-91fef9292c77)

**Deployment**
- [x] Docker

**Env (please complete the following information):**
- OS: windows
- Browser chrome
- Version 版本 116.0.5845.110（正式版本） （64 位）

**Additional Logs**
level=error msg="%!(EXTRA string=bdp_data_executor_service.task_info)" file="/Users/henryyee/go/pkg/mod/git.henrylabs.app/root/engine!x@v0.0.2/parse/common.go:71"

**Comment by no-serve-people** [comment]
框架换成gin 别用yee

**Comment by solomon-cc** [comment]
yeelabs/juno:v3.1.6更换了juno镜像
