### ISSUE TITLE
脱敏字段大小写没匹配上不生效

### ISSUE THREAD

**Issue by wuyuanyong** [cookieY/Yearning#90]
1、脱敏字段：phone

2、查询语句
     select phone from xxxx where id=xxxx    //脱敏生效
     select Phone from xxxx where id=xxxx   //脱敏不生效
     select PHONE from xxxx where id=xxxx //脱敏不生效

**Comment by cookieY** [comment]
什么版本

**Comment by wuyuanyong** [comment]
1、
非常感谢你的回答，yearning非常好用。 你说的这种方法，我在测试过程中也试过，确实能实现。但这种方法，一个字段需要脱敏的话，在脱敏设置里面需要设置N多种情况才能满足脱敏某个字段的要求而且通过这种方法来解决大小脱敏的问题，很容易就可以绕过脱敏字段设置。

例如：脱敏设置  phone,Phone,pHone,phOne,phoNe,phonE。

假设我当时在设置 脱敏字段时，没有想到下面两种组合(PHone,PHOne)：
select PHone from xxxx where id=xxxx
select PHOne from xxxx where id =xxxx
那么查询数据的人要是想到这两种规则，就可以绕过脱敏字段了。


 
2、
yearning代码中能否解决这个问题？例如我脱敏字段设置为phone
不管是
select phone
select Phone
select PHone
select PHONE
.......
都能与脱敏字段phone匹配上。 

3、我个人的想法
代码对查询语句进行脱敏字段匹配时，对查询的列做下转换，例如全部转大写或小写，这样脱敏字段设置为PHONE或phone。则查询phone字段时通过大小写形式不管怎么组合，脱敏字段设置都能生效。

**Comment by wuyuanyong** [comment]
1、
你担心的是如果是select PHone这样怎么办？
-----------------------------------------------
是的,担心类似的大小写组合出现绕过脱敏设置。

2、
实际上yearning 会对你输入的SQL语句强制全部小写化 所以 如果你指定了查询Phone这个字段 那不管他是怎么样 最后实际上都是phone
--------------------------------------------------------------
虽然转换成小写，但目前的脱敏匹配规则，必须完全一致才能生效。
例如脱敏字段设置为PHone，则查询的时候必须写成select PHone脱敏才会生效。查询语句写成select phone/select PHONE脱敏是不生效的。

3、
你的想法非常不错 确实可以规避所有的问题但会存在一个性能上的丢失，因为我需要把每一条记录的所有的字段全部遍历并检查修改 这样在大批量数据查询的时候就会造成严重的性能损失。
-----------------------------------------------------------------------------------------------
确实有性能的损耗。不知道能否在安全和性能中找到一个折中的方法。
在实际中，给开发提供查询后，大批量查询的需求还是不多。

4、文字描述有可能存在理解上的偏差，我截个图给你看下
4.1、脱敏字段设置
![default](https://user-images.githubusercontent.com/23651890/50198285-e2ac7f00-0385-11e9-898f-4da169d4168d.png)

4.2、表字段
![default](https://user-images.githubusercontent.com/23651890/50198349-2f905580-0386-11e9-8dfe-3808cb5f568e.png)

4.3、脱敏要询结果
![default](https://user-images.githubusercontent.com/23651890/50198702-a843e180-0387-11e9-8e52-caf5014eff70.png)

**Comment by wuyuanyong** [comment]
非常抱歉，这几天没注意到你们的版本更新。我12月初git clone下来的，版本是1.3.4。我升级到1.3.5看看，非常感谢！

**Comment by cookieY** [comment]
@wuyuanyong 可以稍晚在更新 1.3.5还有点小bug 我在修复

**Comment by wuyuanyong** [comment]
好的，升级到1.3.5 脱敏大小写问题已解决。但在1.3.5里面as语句还是可以逃避脱敏规则（as自定义列别名还是可以逃避脱敏规则），具体如下：

![1 3 5](https://user-images.githubusercontent.com/23651890/50203645-28c10d00-039d-11e9-9d65-ea2d2099daff.png)

麻烦看下能不能一起修复这个问题，谢谢！

**Comment by cookieY** [comment]
@wuyuanyong 已将修复好的 1.3.5 上传镜像了。 这个功能已经在1.3.5上线

**Comment by wuyuanyong** [comment]
修复效率真高^^，我升级到1.3.5看看，谢谢！
