### ISSUE TITLE
[Question] 查询页面卡死，无法退出

### ISSUE THREAD

**Issue by guofushan** [cookieY/Yearning#901]
**描述问题**
当sql有错误会导致查询页面无法退出卡死
  
**复现**
重现该行为的步骤:
  1.select一张不存在的表名或者执行一个dml都会让查询页面卡死无法退出
  

**截图**
  
![EYXVCBP{XAVFO`4AP@LZUID](https://github.com/cookieY/Yearning/assets/48540932/65fe7ada-eda9-46c2-b5a8-553ac9bbd712)

  
**部署方式**
版本3.1.6.2

**Comment by guofushan** [comment]
这因该是个bug

**Comment by cookieY** [comment]
![image](https://github.com/cookieY/Yearning/assets/22343354/5d47a939-05d0-48fd-9542-64ad8d34f1c9)

**Comment by guofushan** [comment]
hi,
没用到反向代理查询。当前版本3.1.6.2，存在查询页面sql报错后，页面卡死。确定是bug





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cookieY/Yearning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月3日(星期天) 晚上8:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cookieY/Yearning] [Question] 查询页面卡死，无法退出 (Issue #901)

**Comment by cookieY** [comment]
<img width="1282" alt="image" src="https://github.com/cookieY/Yearning/assets/22343354/07154980-b72c-4cae-84d5-5b67b4922c14">
我无法复现你的问题，

请提供相关的浏览器控制台console 信息, ws连接信息等  截图中无有效关键信息

**Comment by guofushan** [comment]
hi，
关于复现：
1，在3.1.6.2版本下
2，执行select * from aabbcc;   (aabbcc表不存在，目的是使sql报错)
3，查询页面报错无法退出

**Comment by cookieY** [comment]
> hi， 关于复现： 1，在3.1.6.2版本下 2，执行select * from aabbcc; (aabbcc表不存在，目的是使sql报错) 3，查询页面报错无法退出

已发现该问题，感谢反馈 会在近期的版本中修复

**Comment by guofushan** [comment]
大佬  下个版本啥时候发啊？

**Comment by aabbccccdd** [comment]
这bug太难受了啊，太影响查询体验感了，还是尽快修复吧

**Comment by guofushan** [comment]
这bug真影响体验啊     期待下一个release

**Comment by cookieY** [comment]
v3.1.6.3
