### ISSUE TITLE
审核页面会报错500如何解决

### ISSUE THREAD

**Issue by kuzuozhou** [cookieY/Yearning#904]
Please provide titles that are straightforward and concise. exp: [Question] How to use or [Feature] Add new feature

      请提供简单明了的标题。例如 [Question] 如何使用 or [Feature] 添加新功能

**Comment by JackloveJam** [comment]
更新至3.1.7

**Comment by kuzuozhou** [comment]
没看到官网上有这个版本




任松
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cookieY/Yearning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月7日(星期五) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cookieY/Yearning] 审核页面会报错500如何解决 (Issue #904)





 
更新至3.1.7

**Comment by JackloveJam** [comment]
> 没看到官网上有这个版本 任松 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cookieY/Yearning" ***@***.***&gt;; 发送时间:&nbsp;2024年6月7日(星期五) 上午10:38 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [cookieY/Yearning] 审核页面会报错500如何解决 (Issue #904) 更新至3.1.7 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

官网更新的不及时，直接在仓库里下载最新的替换更新即可。
