### ISSUE TITLE
[Question] dml无法生成回滚sql

### ISSUE THREAD

**Issue by guofushan** [cookieY/Yearning#915]
**描述问题**
3.1.6.3版本，dml工单无法生成回滚sql  

**复现**
重现该行为的步骤:
  1. dml工单，测试了insert、delete sql语句都无法生成回滚sql
  

**截图**
  
![image](https://github.com/cookieY/Yearning/assets/48540932/feb6f23d-19ab-44b2-8f7b-301fc6bef771)

  
**部署方式**
版本3.1.6.3

**Comment by guofushan** [comment]
抱歉：是没有slave权限，授权后ok了

**Comment by liucx1201** [comment]
> slave权限

怎么怎么授权？
