### ISSUE TITLE
v1.3.5 osc进度条仍然无法展示的问题

### ISSUE THREAD

**Issue by wasonchung** [cookieY/Yearning#92]
使用了最新registry.cn-hangzhou.aliyuncs.com/cookie/yearning:v1.3.5镜像，osc进度条仍然无法展示。SHA1值下拉框，没有任何东西可以选择。直接在inception上运行命令inception get osc_percent '*6447AAE92414DE641D69450EA0FEA9F8829D54C2'\G 是有数据返回的。

**Comment by cookieY** [comment]
选择后延迟5s才会显示

**Comment by wasonchung** [comment]
SHA1值下拉框是空的，不能选择SHA1值。但审核时，是有返回SHA1值。
![image](https://user-images.githubusercontent.com/37434329/50211899-b825ea80-03b4-11e9-9861-a5410385be59.png)

**Comment by cookieY** [comment]
@wasonchung 检查版本 更换浏览器

**Comment by wasonchung** [comment]
试了三个浏览器，情况均一样，各浏览器版本及客户端MAC版本如下：
![image](https://user-images.githubusercontent.com/37434329/50257667-2e6b3100-0437-11e9-9dd8-c5e887f6ed07.png)
![image](https://user-images.githubusercontent.com/37434329/50257673-3a56f300-0437-11e9-9de1-f74400402a2b.png)
![image](https://user-images.githubusercontent.com/37434329/50257684-48a50f00-0437-11e9-9b17-89e60f753f2f.png)
![image](https://user-images.githubusercontent.com/37434329/50257695-50fd4a00-0437-11e9-84a9-a9769ccca1d1.png)
SHA1值下拉框是空的，不能选择SHA1值。但审核时，是有返回SHA1值。
![image](https://user-images.githubusercontent.com/37434329/50257712-696d6480-0437-11e9-8fac-fd60bd188fb8.png)
![image](https://user-images.githubusercontent.com/37434329/50257715-6d998200-0437-11e9-8866-e56e98cefefe.png)
是否方便提供您的浏览器版本？

**Comment by wasonchung** [comment]
补充一个GOOGLE浏览器的版本
![image](https://user-images.githubusercontent.com/37434329/50257753-9c175d00-0437-11e9-85fb-2226ef236151.png)

**Comment by cookieY** [comment]
@wasonchung 是开启多级审核之后出现的情况吧

**Comment by wasonchung** [comment]
是的，开启了多级审核。
![image](https://user-images.githubusercontent.com/37434329/50258659-9d4a8900-043b-11e9-990d-335cdac81d82.png)

**Comment by wuyuanyong** [comment]
不开多级审核也存在同样的问题。

**Comment by cookieY** [comment]
@wasonchung 不开多级是没问题的 亲测  开了多级会有问题

**Comment by wasonchung** [comment]
业务上需要开多级审核。这个问题能在下一版本修复吗？

**Comment by cookieY** [comment]
@wasonchung 嗯

**Comment by wasonchung** [comment]
不好意思，我想问一个题外话。yearning:v1.3.5 docker容器内好像只有nginx的日志。有没有yearning程序的运行和错误日志？有的话，路径在那里？我想把这日志外挂到宿主机上。这样有问题时，也好查一下日志是那里的问题。

**Comment by wuyuanyong** [comment]
![123](https://user-images.githubusercontent.com/23651890/50278778-f25dbd80-0482-11e9-823a-f592b15be37d.png)

@cookieY 我没开多级审核还是不行的，版本1.3.5。inception针对pt-osc的设置，能不能提供下？我怀疑我的pt-osc设置的有问题。

**Comment by wuyuanyong** [comment]
1、
@cookieY  版本1.3.5 没有开启多级审核，osc进度条时好时怀。我跟踪了下，发现yearning在实时展示OSC进度时，yearning每秒就会调用一次inception get osc_percent命令查看OSC的执行进度。
频繁的查询或者多个DDL同时执行inception客户端会没有响应(连入到inception客户端执行任何命令都卡住不动)。然后等一会，inception进程会异常退出，inception异常退出时会报Segmentation fault(Core Dump)的错误。


3、
  yearning展示osc进度时，调用inception get osc_percent 频率是否可以调低？这样可以降低inception的压力，个人觉的没必要每秒种就调用一次。


4、yearning osc进度条
![1545382517 1](https://user-images.githubusercontent.com/23651890/50333749-4202be80-0541-11e9-8110-9076d923d8b1.png)

5、yearning osc进度条调用 inception get osc_percent频率
# 截了部份日志
![1545382600 1](https://user-images.githubusercontent.com/23651890/50333844-842c0000-0541-11e9-8d19-edce542cd108.png)

6、yearing给pt-osc传的是明文密码
# 执行DDL语句的用户，权限一般都比较高的，直接明文传给pt-osc容易造成密码泄露。能否做下处理？
![image](https://user-images.githubusercontent.com/23651890/50333884-9e65de00-0541-11e9-8f71-81c15dee8173.png)

**Comment by wasonchung** [comment]
@wuyuanyong 日志路径在那里？你是用DOCKER容器的吗？

**Comment by wuyuanyong** [comment]
1、
@cookieY 是的docker容器 版本1.3.5 全新部署(非升级没有使用外部MySQL)

2、
你说的日志路径是第5步中的日志路径吗？
第5步中的日志是inception的日志，不是yearning容器的日志
日志路径如下：
/usr/local/inception/data/inception.log

3、
你是想找自己的inception日志路径吗，inception日志路径可以inception配置文件inc.cnf

4、这是我的inception 日志路径设置
![image](https://user-images.githubusercontent.com/23651890/50338122-58634700-054e-11e9-9f5c-8c9b9bbcedd9.png)

**Comment by cookieY** [comment]
@wuyuanyong 

1.调用频率我会降低至5秒一次 但是多个ddl 依然会导致inception卡死（inception本身就非常容易挂）
2.明文传输这个是inception的问题不是yearning能够解决

**Comment by wuyuanyong** [comment]
@cookieY 谢谢你的建议。inception调用PT-OSC问题确实是比较多的。
