### ISSUE TITLE
[Question] 不能上网得服务器是不是无法显示登录页面，考虑所有东西本地化吗

### ISSUE THREAD

**Issue by zz950115** [cookieY/Yearning#927]
**描述问题**
  清晰而简洁地描述你遇到的问题
  
**复现**
重现该行为的步骤:
  
**期望的结果**
  清晰而简洁地描述你希望得到的结果
  
**截图**
  
  
**部署方式**
- [ ] Docker
- [ ] Manual
  
**环境 (请填写环境信息):**
- 操作系统: [e.g. iOS]
- 浏览器 [e.g. chrome, safari]
- 版本号 [e.g. 22]
  
**额外的日志信息**
在这里添加有关该问题的所有日志。

**Comment by cookieY** [comment]
目前用到的静态资源均存在于本地，但不排除引用的css中存在url关联
