### ISSUE TITLE
[Question] 审核SQL语句再次审核页面弹出500，控制台日志也有index out of range错误

### ISSUE THREAD

**Issue by big-dollar** [cookieY/Yearning#930]
**描述问题**
  - 版本：3.1.6.3
  - SQL：update author_info set phone_account='151XXXX937' where id='319024';
  - 报错：第一次审核通过后，同一个审核人第二次审核 弹出 状态码500，SQL窗口是空的
  - 解决：在core_workflow_details中查word_id有四行，删除最后一个重复行后在页面恢复正常，怀疑是在SQL窗口检测后点击【同意】，页面没有变化又多次当前页面检测语法点击【同意】导致的。

  
**截图**
  
![image](https://github.com/cookieY/Yearning/assets/50395663/a2f96b0d-208d-4047-b97f-80eec0b57230)
![image](https://github.com/cookieY/Yearning/assets/50395663/61793ded-ac27-4464-965c-97fcad588a34)
![image](https://github.com/cookieY/Yearning/assets/50395663/587e623b-197f-4a8f-86cc-99df2133c53f)
![image](https://github.com/cookieY/Yearning/assets/50395663/80d17400-8695-4260-ad18-2dc1425946d1)

  
**部署方式**
- [ ] Manual
  
**环境 (请填写环境信息):**
- 操作系统: CentOS Linux release 8.5.2111
- 浏览器 Edge 版本 117.0.2045.36 (正式版本) (64 位)
- 版本号 3.1.6.3
  
**额外的日志信息**
 [Critical] 2023-09-22 11:30:59 (github.com/cookieY/yee@v0.3.9/middleware/recovery.go:33) [PANIC RECOVER] runtime error: index out of range [3] with length 3 Traceback:
        runtime/panic.go:113
        Yearning-go/src/handler/fetch/fetch.go:130
        Yearning-go/src/apis/fetch.go:23
        github.com/cookieY/yee@v0.3.9/context.go:128
        github.com/cookieY/yee@v0.3.9/middleware/gzip.go:66
        github.com/cookieY/yee@v0.3.9/context.go:128
        github.com/cookieY/yee@v0.3.9/middleware/recovery.go:38
        github.com/cookieY/yee@v0.3.9/context.go:128
        github.com/cookieY/yee@v0.3.9/middleware/logger.go:58
        github.com/cookieY/yee@v0.3.9/context.go:128
        github.com/cookieY/yee@v0.3.9/middleware/cors.go:96
        github.com/cookieY/yee@v0.3.9/context.go:128
        github.com/cookieY/yee@v0.3.9/yee.go:207
        github.com/cookieY/yee@v0.3.9/yee.go:133
        net/http/server.go:2937
        net/http/server.go:1996
        runtime/asm_amd64.s:1599

 [Error] 2023-09-22 11:30:59 (github.com/cookieY/yee@v0.3.9/context.go:149) /api/v2/fetch/timeline?source_id=652399a4-153b-4a95-9991-593eb8c4d1ed&work_id=2023092210560579 Internal Server Error
 [Warn] 2023-09-22 11:30:59 "url":"/api/v2/fetch/timeline" "method":"GET" "status":500 "protocol":"HTTP/1.1" "remote_ip":"127.0.0.1" "bytes_in": "0 bytes" "bytes_out": "21 bytes"

**Comment by butp** [comment]
同遇到此问题：审核的提交接口非幂等，重复提交后 再打开工单详情时接口（/api/v2/fetch/timeline?source_id=?&work_id=?）报错。
此工具简洁易用，希望有开发者能修复下~

**Comment by solomon-cc** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> **Title:** [Question] When auditing the SQL statement and auditing the page again, a 500 error message pops up, and there is also an index out of range error in the console log.



> 同遇到此问题：审核的提交接口非幂等，重复提交后 再打开工单详情时接口（/api/v2/fetch/timeline?source_id=?&work_id=?）报错。 此工具简洁易用，希望有开发者能修复下~

这个问题我也遇到过，直接给表core_workflow_details ,work_id、action添加唯一索引，避免了重复插入
