### ISSUE TITLE
[Question] 大表执行create index时没触发在线表变更工具gh-ost

### ISSUE THREAD

**Issue by feifeigege** [cookieY/Yearning#934]
**描述问题**
同一个表，先执行增加字段sql，触发了在线表变更工具gh-ost，在创建索引时没有触发gh-ost
  
**复现**
重现该行为的步骤:
1.增加字段sql
ALTER TABLE `tt`.`tt_transport_orders`
    ADD COLUMN `technical_service_no` varchar(20)  DEFAULT ''  COMMENT '服务费单号' AFTER `pay_order_no`
触发gh-ost
2.增加索引sql
create index idx_transport_order_pay_end_time
    on tt.tt_transport_orders (pay_end_time);
没触发gh-ost
  
**期望的结果**
希望在表体积大于该值后触发在线表变更同步，单位:M : 20M
  
**截图**
  
![image](https://github.com/cookieY/Yearning/assets/22868778/10e9fcca-ca01-4a5f-86b1-a8c7714b196a)

  
**部署方式**
- [ ] Manual
  
**环境 (请填写环境信息):**
操作系统: [CentOS Linux release 7.9.2009]
浏览器 [Chrom]
版本号 [3.1.5]
  
**额外的日志信息**
为什么在添加索引时没触发gh-ost

**Comment by Horus-K** [comment]
今天用也发现了，没法开启gh-ost，这个是需要单独安装才行吗

**Comment by cookieY** [comment]
gh-ost 是需要单独安装的 然后在OSCExpr 里面填写对应的执行命令 https://next.yearning.io/guide/config/rule.html

**Comment by cy724** [comment]
> gh-ost 是需要单独安装的 然后在OSCExpr 里面填写对应的执行命令 https://next.yearning.io/guide/config/rule.html

你好，这个链接打不开，404了
