### ISSUE TITLE
[Question] 严重的bug-数据源无法添加

### ISSUE THREAD

**Issue by 123tim123** [cookieY/Yearning#939]
**描述问题**
  无法添加数据源，添加数据源的ip都是使用第一个数据源的ip
  
**复现**
重现该行为的步骤:
  
**期望的结果**
  清晰而简洁地描述你希望得到的结果
  
**截图**
  
![image](https://github.com/cookieY/Yearning/assets/18544182/6e18a408-c184-43e9-af90-d920fad17031)
![image](https://github.com/cookieY/Yearning/assets/18544182/1f1691e5-d704-433c-b3dd-80a8f4a639ef)

  
**部署方式**
- [ ] Docker
- [ ] Manual
  
**环境 (请填写环境信息):**
- 操作系统: [e.g. iOS]
- 浏览器 [e.g. chrome, safari]
- 版本号 [e.g. 22]
  
**额外的日志信息**
在这里添加有关该问题的所有日志。

**Comment by cookieY** [comment]
请检查数据库连接信息是否正确
