### ISSUE TITLE
生成数据字典报Network Error

### ISSUE THREAD

**Issue by sh-hanson** [cookieY/Yearning#94]
现在一个库里有250张表，生成数据字典时，报“Network Error”，然后查询数据字典，只生成了216张。删掉重来一遍，还是报错。
![image](https://user-images.githubusercontent.com/41986080/50415347-73d39800-0855-11e9-9f7f-e15324f10b3b.png)

**Comment by sh-hanson** [comment]
有几个库是100张表以下的，生成数据字典没问题，就是这个超过200张表的库出问题

**Comment by cookieY** [comment]
更改 gunicorn timeout

**Comment by sh-hanson** [comment]
gunicorn timeout值加大，没出现报错了，解决了，多谢
