### ISSUE TITLE
添加组合索引报错

### ISSUE THREAD

**Issue by sh-hanson** [cookieY/Yearning#95]
![image](https://user-images.githubusercontent.com/41986080/50443769-c7221500-093f-11e9-948d-5b192b7cca93.png)
如图，我添加一个组合索引（id,tname），然后提交工单后就变成下图这样：
![image](https://user-images.githubusercontent.com/41986080/50443804-e6b93d80-093f-11e9-84ef-f9514c4f9bc3.png)
两个字段被符号（`）括起来变成一个字段了

**Comment by cookieY** [comment]
@sh-hanson 后面生成功能会移除 ddl dml全部采用手动模式
