### ISSUE TITLE
[Question]  查询时间已经过期或已被审核人提前结束，请重新进入查询系统 

### ISSUE THREAD

**Issue by inlooklook** [cookieY/Yearning#960]
**描述问题**
每次查询停了一两秒就会提示： 查询时间已经过期或已被审核人提前结束，请重新进入查询系统 

**复现**
重现该行为的步骤:
  1. 工单申请>查询>进入
  
**期望的结果**
  可以设置时间查询时限或者 不要关闭sql页面，这样写的sql不会丢失
  
**截图**
  ![img_v3_025f_6421de5a-f719-4d75-a3c0-f9ac9a88c2hu](https://github.com/cookieY/Yearning/assets/151817004/93b43ad1-698b-44bb-bd18-48c9fb9ba895)
  
**部署方式**
- Manual
  
**环境 (请填写环境信息):**
- 操作系统: [centos]
- 浏览器 [chrome]
- 版本号 [Version: 3.1.6 Uranus COMMON]
  
**额外的日志信息**
在这里添加有关该问题的所有日志。

**Comment by cookieY** [comment]
在设置页面中 可以设置查询时限 
<img width="366" alt="image" src="https://github.com/cookieY/Yearning/assets/22343354/96985c70-86b6-4abd-a0e2-f1393ce00705">

**Comment by Himer** [comment]
同样遇到 “查询时间已经过期或已被审核人提前结束，请重新进入查询系统” 情况， 时限已经设置成100分，但是提交查询秒出错误“查询时间已经过期或已被审核人提前结束，请重新进入查询系统” ， 有没有啥思路？  @cookieY
