### ISSUE TITLE
[Question] 用户界面看不到角色的设置

### ISSUE THREAD

**Issue by lizhong12** [cookieY/Yearning#968]
**描述问题**
 用户界面看不到角色的设置
  
**复现**
重现该行为的步骤:
  
**期望的结果**
可以设置用户角色  
**截图**
  
![image](https://github.com/cookieY/Yearning/assets/23659890/0101739a-fc4d-43b2-a967-b0fbad8cbdf4)

  
**部署方式**
- [ ] Docker
- [x] Manual
  
**环境 (请填写环境信息):**
- 操作系统: [e.g. iOS]
- 浏览器 [e.g. chrome, safari]
- 版本号 [e.g. 22]
  
**额外的日志信息**
在这里添加有关该问题的所有日志。

**Comment by cookieY** [comment]
3.x 已经没有角色的概念了 https://next.yearning.io/guide/getting-started.html
