### ISSUE TITLE
DDL点击执行后，状态一直不变，SQL实际没在生产库上执行

### ISSUE THREAD

**Issue by nhlzh8708** [cookieY/Yearning#97]
DDL点击执行后，卡着一直不动。检查inception日志，没触发执行DDL的信息。
问题已定位：
当提交DDL的时候，如果延迟执行字段设置为空(core_sqlorder.delay=null)，工单能正常提交。
但当管理员"执行"时，后台的(core_sqlorder.status=3)，一直都不变。实际SQL也没在生产库上执行

**Comment by cookieY** [comment]
@nhlzh8708 什么场景下 导致的delay 变成了null ?

**Comment by nhlzh8708** [comment]
@cookieY 我估计是人为误点删除的。我重现了一下，确实如果人为删除掉，还是能正常提交的。虽然这个出现的概率非常低
