### ISSUE TITLE
[Question]  [SQL查询]功能，在查询出来的数据单列太大的情况下无法折叠，导致展示界面异常，无法正常查看

### ISSUE THREAD

**Issue by daihanyang** [cookieY/Yearning#971]
**描述问题**
 [SQL查询]功能，在查询出来的数据单列太大的情况下无法折叠，导致展示界面异常，无法正常查看
  
**问题现场**
![image](https://github.com/cookieY/Yearning/assets/89181622/d61cb30d-d668-4f2f-ae93-7abe7a7e3a9c)

**问题复现**
在表里面声明一个列，insert 时往列中插入大量数据

**Comment by cookieY** [comment]
3.x版本支持查询结果表格伸缩
