### ISSUE TITLE
[Question] 个人详情页无法显示部门和真实姓名

### ISSUE THREAD

**Issue by igangz** [cookieY/Yearning#974]
**描述问题**
  个人详情页无法显示已经设置的部门和真实姓名
  
**截图**
  
<img width="581" alt="image" src="https://github.com/cookieY/Yearning/assets/18605969/48e1f8df-76ed-4f16-841e-86cabe2ea5e6">

环境 (请填写环境信息):

操作系统: [macos]
浏览器 [edge]
版本号 [v3.1.6.3]

**Comment by cookieY** [comment]
请查看后台日志是否存在报错

**Comment by igangz** [comment]
> 请查看后台日志是否存在报错

仅有这个报错，但是这个报错完全无法消除，使用仓库里的docker-compose.yml脚本启动，照样有这个报错，也同样有个人详情页的显示问题：
`[Error] 2023-12-26 16:54:11 (Yearning-go/src/lib/encrypt.go:109) 秘钥解析失败,无法解密当前密码！`
