### ISSUE TITLE
[Question] 开启审计人权限的用户无法看到审计菜单

### ISSUE THREAD

**Issue by KolorYan** [cookieY/Yearning#975]
**描述问题**
 开启审计人权限的用户无法看到审计菜单
    
**截图**
  
![image](https://github.com/cookieY/Yearning/assets/54943795/3ceac8a8-b29a-4a89-9d11-9f49ea64e706)

  
  
**环境 (请填写环境信息):**
- 操作系统: [win/mac]
- 浏览器 [edge/chrome]
- 版本号 [.3.1.6]

**Comment by cookieY** [comment]
需重新登录后才会显示

**Comment by KolorYan** [comment]
> 需重新登录后才会显示

重新登录后也没有
