### ISSUE TITLE
[Feature] 查询的时候，希望可以按照每个用户的查询语句保存web 上。

### ISSUE THREAD

**Issue by adgers** [cookieY/Yearning#980]
**描述需求**
查询的时候，右键菜单栏，希望能有一个自定义保存sql 名称的功能。
很多时候。 开发或者dba的都需要保存历史的sql 语句。

**你的思路**
1、右键弹出查询的时候，添加一个SQL 保存 功能， 弹出一个保存框保存sql名称， 
2、历史保存的点击库名称进行查看
3、点击保存的历史sql 就进行打开sql查询会话

**截图**
![image](https://github.com/cookieY/Yearning/assets/52065423/d5d014e9-9880-4bea-898d-a0551b099775)

**Comment by cookieY** [comment]
https://next.yearning.io/guide/get/query.html#%E5%89%AA%E8%B4%B4%E6%9D%BF%E5%8A%9F%E8%83%BD
