### ISSUE TITLE
[Question] 版本3.1.7，如何切换为中文界面？

### ISSUE THREAD

**Issue by alon27** [cookieY/Yearning#987]
搭建了3.1.7版本的yearning，界面是英文界面，如何切换为中文界面。
之前版本2.1.7的界面是中文的
  
  
**部署方式**
- [ ] Docker
  
**环境 (请填写环境信息):**
- 操作系统: centos7.9
- 浏览器 edge
- 版本号 120
  
**额外的日志信息**
在这里添加有关该问题的所有日志。

**Comment by cookieY** [comment]
<img width="1173" alt="image" src="https://github.com/cookieY/Yearning/assets/22343354/dd75b9c9-8f9e-40be-a2fd-c43cb7cf18ca">

**Comment by xiao-sun** [comment]
请问使用k8s部署的3.1.8版本，中文界面如何切换

**Comment by cookieY** [comment]
添加环境变量 Y_LANG = zh_CN

**Comment by xiao-sun** [comment]
@cookieY 成功了，谢谢。

**Comment by Eileen2014** [comment]
> <img alt="图像" width="1173" src="https://private-user-images.githubusercontent.com/22343354/297007987-dd75b9c9-8f9e-40be-a2fd-c43cb7cf18ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5Njk2NTYsIm5iZiI6MTczMDk2OTM1NiwicGF0aCI6Ii8yMjM0MzM1NC8yOTcwMDc5ODctZGQ3NWI5YzktOGY5ZS00MGJlLWEyZmQtYzQzY2I3Y2YxOGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA4NDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMWIzYjZlNjkyZWI3ZmM1YzQwNzMwMDZmZjUyOTU1NTZiOThjNjI3ZGM3YzFkMWY2MzYyMWY0ZmQxYzQ1MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V4DkEUBjVTN9S5iPY1Pl7BlMcWv7XAHyiC3IMSoGdeU">

我是用了3.19版本，按照这个修改了文件，重新run了之后还是没有把界面从英文改成中文，添加环境变量 Y_LANG = zh_CN这个是在哪里更改
